// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The MAGE class ladder — 25 magic SPELLS, unlocked one per 10 points of
// effective INTELLIGENCE (10, 20, … 250). Surfaced only to an INT-dominant hero
// (see `dominantSpellStat`). Schools interleave attack → aoe → defense; the
// capstone (INT 250) is ARMAGEDDON, the mage's screen-shaping payoff. See
// ../spells.ts for the shared types and the class helpers.

import type { SpellDef } from "../spells.ts";

export const MAGIC_SPELLS: SpellDef[] = [
  {
    id: "arc_bolt",
    name: "ARC BOLT",
    stat: "intelligence",
    category: "attack",
    element: "storm",
    minStat: 10,
    manaCost: 8,
    cooldownMs: 1600,
    effect: { kind: "bolt", damage: 26, range: 200 },
    icon: "spell_arc_bolt",
    blurb: "A crackling dart of static leaps to the nearest foe.",
  },
  {
    id: "ember_burst",
    name: "EMBER BURST",
    stat: "intelligence",
    category: "aoe",
    element: "fire",
    minStat: 20,
    manaCost: 11,
    cooldownMs: 3000,
    effect: { kind: "nova", damage: 18, radius: 66 },
    icon: "spell_ember_burst",
    blurb: "A ring of cinders erupts outward around you.",
  },
  {
    id: "mana_ward",
    name: "MANA WARD",
    stat: "intelligence",
    category: "defense",
    element: "holy",
    minStat: 30,
    manaCost: 14,
    cooldownMs: 8000,
    effect: { kind: "shield", absorbPct: 0.18, durationMs: 7000 },
    icon: "spell_mana_ward",
    blurb: "A shimmering ward drinks the blows meant for you.",
  },
  {
    id: "frost_lance",
    name: "FROST LANCE",
    stat: "intelligence",
    category: "attack",
    element: "frost",
    minStat: 40,
    manaCost: 13,
    cooldownMs: 1800,
    effect: { kind: "bolt", damage: 40, range: 214 },
    icon: "spell_frost_lance",
    blurb: "A spear of ice punches clean through a single foe.",
  },
  {
    id: "gravitic_pulse",
    name: "GRAVITIC PULSE",
    stat: "intelligence",
    category: "aoe",
    element: "void",
    minStat: 50,
    manaCost: 17,
    cooldownMs: 3600,
    effect: { kind: "nova", damage: 27, radius: 80 },
    icon: "spell_gravitic_pulse",
    blurb: "Space buckles outward, throwing the crowd off its feet.",
  },
  {
    id: "mending_light",
    name: "MENDING LIGHT",
    stat: "intelligence",
    category: "defense",
    element: "holy",
    minStat: 60,
    manaCost: 18,
    cooldownMs: 9000,
    effect: { kind: "heal", healPct: 0.3 },
    icon: "spell_mending_light",
    blurb: "Warm light knits your wounds back together.",
  },
  {
    id: "chain_spark",
    name: "CHAIN SPARK",
    stat: "intelligence",
    category: "attack",
    element: "storm",
    minStat: 70,
    manaCost: 16,
    cooldownMs: 2200,
    effect: { kind: "bolt", damage: 34, range: 204, chain: 2 },
    icon: "spell_chain_spark",
    blurb: "Lightning arcs from one foe to the next.",
  },
  {
    id: "inferno",
    name: "INFERNO",
    stat: "intelligence",
    category: "aoe",
    element: "fire",
    minStat: 80,
    manaCost: 22,
    cooldownMs: 4200,
    effect: { kind: "nova", damage: 37, radius: 88 },
    icon: "spell_inferno",
    blurb: "A blossom of flame engulfs everything near you.",
  },
  {
    id: "frost_nova",
    name: "FROST NOVA",
    stat: "intelligence",
    category: "defense",
    element: "frost",
    minStat: 90,
    manaCost: 20,
    cooldownMs: 7000,
    effect: { kind: "slow", radius: 98, factor: 0.35, durationMs: 3500 },
    icon: "spell_frost_nova",
    blurb: "A freezing ring locks the horde in a slow crawl.",
  },
  {
    id: "void_lance",
    name: "VOID LANCE",
    stat: "intelligence",
    category: "attack",
    element: "void",
    minStat: 100,
    manaCost: 24,
    cooldownMs: 2400,
    effect: { kind: "bolt", damage: 58, range: 230 },
    icon: "spell_void_lance",
    blurb: "A lance of pure nothing unmakes a single target.",
  },
  {
    id: "tempest",
    name: "TEMPEST",
    stat: "intelligence",
    category: "aoe",
    element: "storm",
    minStat: 110,
    manaCost: 26,
    cooldownMs: 4200,
    effect: { kind: "nova", damage: 44, radius: 94 },
    icon: "spell_tempest",
    blurb: "A whirl of storm shreds the ranks around you.",
  },
  {
    id: "arcane_aegis",
    name: "ARCANE AEGIS",
    stat: "intelligence",
    category: "defense",
    element: "arcane",
    minStat: 120,
    manaCost: 28,
    cooldownMs: 10000,
    effect: { kind: "shield", absorbPct: 0.3, durationMs: 8000 },
    icon: "spell_arcane_aegis",
    blurb: "A stronger ward, longer lived, wraps you whole.",
  },
  {
    id: "disintegrate",
    name: "DISINTEGRATE",
    stat: "intelligence",
    category: "attack",
    element: "blood",
    minStat: 130,
    manaCost: 30,
    cooldownMs: 2600,
    effect: { kind: "bolt", damage: 74, range: 230 },
    icon: "spell_disintegrate",
    blurb: "A searing beam boils a foe away where it stands.",
  },
  {
    id: "meteor",
    name: "METEOR",
    stat: "intelligence",
    category: "aoe",
    element: "fire",
    minStat: 140,
    manaCost: 34,
    cooldownMs: 5200,
    effect: { kind: "nova", damage: 58, radius: 106 },
    icon: "spell_meteor",
    blurb: "A falling star cracks the ground wide open.",
  },
  {
    id: "renewal",
    name: "RENEWAL",
    stat: "intelligence",
    category: "defense",
    element: "holy",
    minStat: 150,
    manaCost: 34,
    cooldownMs: 9000,
    effect: { kind: "heal", healPct: 0.45 },
    icon: "spell_renewal",
    blurb: "A surge of vitality floods back into your body.",
  },
  {
    id: "thunderspear",
    name: "THUNDERSPEAR",
    stat: "intelligence",
    category: "attack",
    element: "storm",
    minStat: 160,
    manaCost: 34,
    cooldownMs: 2600,
    effect: { kind: "bolt", damage: 66, range: 234, chain: 3 },
    icon: "spell_thunderspear",
    blurb: "A hurled bolt forks through a whole file of foes.",
  },
  {
    id: "supernova",
    name: "SUPERNOVA",
    stat: "intelligence",
    category: "aoe",
    element: "void",
    minStat: 170,
    manaCost: 40,
    cooldownMs: 5600,
    effect: { kind: "nova", damage: 70, radius: 112 },
    icon: "spell_supernova",
    blurb: "A dying star's shockwave flattens the field.",
  },
  {
    id: "time_dilation",
    name: "TIME DILATION",
    stat: "intelligence",
    category: "defense",
    element: "arcane",
    minStat: 180,
    manaCost: 38,
    cooldownMs: 8000,
    effect: { kind: "slow", radius: 122, factor: 0.3, durationMs: 4500 },
    icon: "spell_time_dilation",
    blurb: "Time itself crawls for everything hunting you.",
  },
  {
    id: "annihilate",
    name: "ANNIHILATE",
    stat: "intelligence",
    category: "attack",
    element: "blood",
    minStat: 190,
    manaCost: 42,
    cooldownMs: 2800,
    effect: { kind: "bolt", damage: 96, range: 240 },
    icon: "spell_annihilate",
    blurb: "Raw force erases a target from existence.",
  },
  {
    id: "cataclysm",
    name: "CATACLYSM",
    stat: "intelligence",
    category: "aoe",
    element: "fire",
    minStat: 200,
    manaCost: 46,
    cooldownMs: 6000,
    effect: { kind: "nova", damage: 84, radius: 122 },
    icon: "spell_cataclysm",
    blurb: "A firestorm consumes everything in a wide ring.",
  },
  {
    id: "sanctuary",
    name: "SANCTUARY",
    stat: "intelligence",
    category: "defense",
    element: "holy",
    minStat: 210,
    manaCost: 46,
    cooldownMs: 11000,
    effect: { kind: "shield", absorbPct: 0.42, durationMs: 9000 },
    icon: "spell_sanctuary",
    blurb: "Hallowed light stands between you and every blow.",
  },
  {
    id: "chain_lightning",
    name: "CHAIN LIGHTNING",
    stat: "intelligence",
    category: "attack",
    element: "storm",
    minStat: 220,
    manaCost: 46,
    cooldownMs: 2800,
    effect: { kind: "bolt", damage: 88, range: 240, chain: 4 },
    icon: "spell_chain_lightning",
    blurb: "A living arc that jumps from body to body to body.",
  },
  {
    id: "annulment",
    name: "ANNULMENT",
    stat: "intelligence",
    category: "aoe",
    element: "void",
    minStat: 230,
    manaCost: 50,
    cooldownMs: 6400,
    effect: { kind: "nova", damage: 100, radius: 128 },
    icon: "spell_annulment",
    blurb: "A collapsing void erases the crowd around you.",
  },
  {
    id: "divine_mending",
    name: "DIVINE MENDING",
    stat: "intelligence",
    category: "defense",
    element: "holy",
    minStat: 240,
    manaCost: 52,
    cooldownMs: 10000,
    effect: { kind: "heal", healPct: 0.6 },
    icon: "spell_divine_mending",
    blurb: "A miracle pours you back to fighting shape.",
  },
  {
    id: "armageddon",
    name: "ARMAGEDDON",
    stat: "intelligence",
    category: "aoe",
    element: "fire",
    minStat: 250,
    manaCost: 58,
    cooldownMs: 8000,
    effect: { kind: "nova", damage: 140, radius: 152 },
    icon: "spell_armageddon",
    blurb: "The sky falls. Nothing near you is left standing.",
  },
];
