// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The WARRIOR class ladder — 25 melee ARTS, unlocked one per 10 points of
// effective STRENGTH (10, 20, … 250). Surfaced only to a STR-dominant hero (see
// `dominantSpellStat`). The martial mirror of the mage's spellbook: ATTACK arts
// are short-reach lunges (a `bolt` at melee range), AOE arts are hero-centered
// cleaves/slams (`nova`), and DEFENSE arts mix wards, second winds, shouts, and
// the class signature — a self-`buff` war cry that pumps the hero's own weapon.
// Every art costs MANA like a spell (INT sizes the pool; a warrior fuels arts
// off the base pool + SPIRIT regen, or buys a deeper reservoir with some INT).
// The capstone (STR 250) is EARTHSHATTER. See ../spells.ts for shared types.

import type { SpellDef } from "../spells.ts";

export const MELEE_SPELLS: SpellDef[] = [
  {
    id: "rending_strike",
    name: "RENDING STRIKE",
    stat: "strength",
    category: "attack",
    element: "steel",
    minStat: 10,
    manaCost: 8,
    cooldownMs: 1600,
    effect: { kind: "bolt", damage: 26, range: 84 },
    icon: "spell_rending_strike",
    blurb: "A brutal chop that opens the nearest foe wide.",
  },
  {
    id: "cleave",
    name: "CLEAVE",
    stat: "strength",
    category: "aoe",
    element: "steel",
    minStat: 20,
    manaCost: 11,
    cooldownMs: 3000,
    effect: { kind: "nova", damage: 18, radius: 66 },
    icon: "spell_cleave",
    blurb: "One wide swing bites every foe within arm's reach.",
  },
  {
    id: "war_cry",
    name: "WAR CRY",
    stat: "strength",
    category: "defense",
    element: "blood",
    minStat: 30,
    manaCost: 14,
    cooldownMs: 9000,
    effect: { kind: "buff", damageMult: 1.25, durationMs: 6000 },
    icon: "spell_war_cry",
    blurb: "A roar that lends your blows crushing force.",
  },
  {
    id: "sunder",
    name: "SUNDER",
    stat: "strength",
    category: "attack",
    element: "steel",
    minStat: 40,
    manaCost: 13,
    cooldownMs: 1800,
    effect: { kind: "bolt", damage: 40, range: 90 },
    icon: "spell_sunder",
    blurb: "A splitting blow that shatters guard and bone alike.",
  },
  {
    id: "whirlwind",
    name: "WHIRLWIND",
    stat: "strength",
    category: "aoe",
    element: "steel",
    minStat: 50,
    manaCost: 17,
    cooldownMs: 3600,
    effect: { kind: "nova", damage: 27, radius: 80 },
    icon: "spell_whirlwind",
    blurb: "You spin in place, blade carving a full circle.",
  },
  {
    id: "second_wind",
    name: "SECOND WIND",
    stat: "strength",
    category: "defense",
    element: "holy",
    minStat: 60,
    manaCost: 18,
    cooldownMs: 9000,
    effect: { kind: "heal", healPct: 0.3 },
    icon: "spell_second_wind",
    blurb: "You dig deep and shrug off half your wounds.",
  },
  {
    id: "crushing_blow",
    name: "CRUSHING BLOW",
    stat: "strength",
    category: "attack",
    element: "earth",
    minStat: 70,
    manaCost: 16,
    cooldownMs: 2200,
    effect: { kind: "bolt", damage: 34, range: 92 },
    icon: "spell_crushing_blow",
    blurb: "An overhead smash that drives a foe into the dirt.",
  },
  {
    id: "ground_slam",
    name: "GROUND SLAM",
    stat: "strength",
    category: "aoe",
    element: "earth",
    minStat: 80,
    manaCost: 22,
    cooldownMs: 4200,
    effect: { kind: "nova", damage: 37, radius: 88 },
    icon: "spell_ground_slam",
    blurb: "You pound the earth and the shockwave fans out.",
  },
  {
    id: "crushing_shout",
    name: "CRUSHING SHOUT",
    stat: "strength",
    category: "defense",
    element: "earth",
    minStat: 90,
    manaCost: 20,
    cooldownMs: 7000,
    effect: { kind: "slow", radius: 98, factor: 0.35, durationMs: 3500 },
    icon: "spell_crushing_shout",
    blurb: "A bellow that staggers the horde to a crawl.",
  },
  {
    id: "execute",
    name: "EXECUTE",
    stat: "strength",
    category: "attack",
    element: "blood",
    minStat: 100,
    manaCost: 24,
    cooldownMs: 2400,
    effect: { kind: "bolt", damage: 58, range: 96 },
    icon: "spell_execute",
    blurb: "A finishing stroke aimed straight for the throat.",
  },
  {
    id: "blade_storm",
    name: "BLADE STORM",
    stat: "strength",
    category: "aoe",
    element: "steel",
    minStat: 110,
    manaCost: 26,
    cooldownMs: 4200,
    effect: { kind: "nova", damage: 44, radius: 94 },
    icon: "spell_blade_storm",
    blurb: "A cyclone of steel shreds everyone around you.",
  },
  {
    id: "iron_skin",
    name: "IRON SKIN",
    stat: "strength",
    category: "defense",
    element: "steel",
    minStat: 120,
    manaCost: 28,
    cooldownMs: 10000,
    effect: { kind: "shield", absorbPct: 0.3, durationMs: 8000 },
    icon: "spell_iron_skin",
    blurb: "Your hide turns to iron and the blows glance off.",
  },
  {
    id: "mortal_strike",
    name: "MORTAL STRIKE",
    stat: "strength",
    category: "attack",
    element: "blood",
    minStat: 130,
    manaCost: 30,
    cooldownMs: 2600,
    effect: { kind: "bolt", damage: 74, range: 100 },
    icon: "spell_mortal_strike",
    blurb: "A wound so deep it will not close.",
  },
  {
    id: "seismic_slam",
    name: "SEISMIC SLAM",
    stat: "strength",
    category: "aoe",
    element: "earth",
    minStat: 140,
    manaCost: 34,
    cooldownMs: 5200,
    effect: { kind: "nova", damage: 58, radius: 106 },
    icon: "spell_seismic_slam",
    blurb: "The ground bucks and splits in a widening ring.",
  },
  {
    id: "berserk",
    name: "BERSERK",
    stat: "strength",
    category: "defense",
    element: "blood",
    minStat: 150,
    manaCost: 34,
    cooldownMs: 12000,
    effect: {
      kind: "buff",
      damageMult: 1.4,
      hasteMult: 1.25,
      durationMs: 6000,
    },
    icon: "spell_berserk",
    blurb: "Blood-rage: you hit harder and faster than sense.",
  },
  {
    id: "decapitate",
    name: "DECAPITATE",
    stat: "strength",
    category: "attack",
    element: "steel",
    minStat: 160,
    manaCost: 34,
    cooldownMs: 2600,
    effect: { kind: "bolt", damage: 66, range: 100 },
    icon: "spell_decapitate",
    blurb: "One clean arc and a head rolls free.",
  },
  {
    id: "onslaught",
    name: "ONSLAUGHT",
    stat: "strength",
    category: "aoe",
    element: "fire",
    minStat: 170,
    manaCost: 40,
    cooldownMs: 5600,
    effect: { kind: "nova", damage: 70, radius: 112 },
    icon: "spell_onslaught",
    blurb: "A blazing flurry that engulfs the whole press.",
  },
  {
    id: "war_stomp",
    name: "WAR STOMP",
    stat: "strength",
    category: "defense",
    element: "earth",
    minStat: 180,
    manaCost: 38,
    cooldownMs: 8000,
    effect: { kind: "slow", radius: 122, factor: 0.3, durationMs: 4500 },
    icon: "spell_war_stomp",
    blurb: "A thunderous stamp roots the horde where it stands.",
  },
  {
    id: "obliterate",
    name: "OBLITERATE",
    stat: "strength",
    category: "attack",
    element: "blood",
    minStat: 190,
    manaCost: 42,
    cooldownMs: 2800,
    effect: { kind: "bolt", damage: 96, range: 104 },
    icon: "spell_obliterate",
    blurb: "You put your whole weight behind one killing blow.",
  },
  {
    id: "ruination",
    name: "RUINATION",
    stat: "strength",
    category: "aoe",
    element: "fire",
    minStat: 200,
    manaCost: 46,
    cooldownMs: 6000,
    effect: { kind: "nova", damage: 84, radius: 122 },
    icon: "spell_ruination",
    blurb: "A ruinous sweep that levels everything nearby.",
  },
  {
    id: "bulwark",
    name: "BULWARK",
    stat: "strength",
    category: "defense",
    element: "steel",
    minStat: 210,
    manaCost: 46,
    cooldownMs: 11000,
    effect: { kind: "shield", absorbPct: 0.42, durationMs: 9000 },
    icon: "spell_bulwark",
    blurb: "An unbreakable guard stands between you and death.",
  },
  {
    id: "deathblow",
    name: "DEATHBLOW",
    stat: "strength",
    category: "attack",
    element: "blood",
    minStat: 220,
    manaCost: 46,
    cooldownMs: 2800,
    effect: { kind: "bolt", damage: 88, range: 104 },
    icon: "spell_deathblow",
    blurb: "The strike everything before it was leading to.",
  },
  {
    id: "rampage",
    name: "RAMPAGE",
    stat: "strength",
    category: "aoe",
    element: "storm",
    minStat: 230,
    manaCost: 50,
    cooldownMs: 6400,
    effect: { kind: "nova", damage: 100, radius: 128 },
    icon: "spell_rampage",
    blurb: "You go berserk, cutting down all in a wide sweep.",
  },
  {
    id: "last_stand",
    name: "LAST STAND",
    stat: "strength",
    category: "defense",
    element: "holy",
    minStat: 240,
    manaCost: 52,
    cooldownMs: 10000,
    effect: { kind: "heal", healPct: 0.6 },
    icon: "spell_last_stand",
    blurb: "Refuse to fall — your body answers and mends.",
  },
  {
    id: "earthshatter",
    name: "EARTHSHATTER",
    stat: "strength",
    category: "aoe",
    element: "earth",
    minStat: 250,
    manaCost: 58,
    cooldownMs: 8000,
    effect: { kind: "nova", damage: 140, radius: 152 },
    icon: "spell_earthshatter",
    blurb: "You split the world open. Nothing near you survives.",
  },
];
