// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The RANGER class ladder — 25 ranged TECHNIQUES, unlocked one per 10 points of
// effective DEXTERITY (10, 20, … 250). Surfaced only to a DEX-dominant hero (see
// `dominantSpellStat`). The ranged mirror of the spellbook: ATTACK techniques
// are long shots (a `bolt`, some ricocheting via `chain`), AOE techniques are
// volleys that land a burst on a distant cluster (`rain`), and DEFENSE
// techniques mix field dressings, traps, smoke, and the class signature — a
// self-`buff` (TAKE AIM's precision, RAPID FIRE's cadence). Every technique
// costs MANA like a spell. The capstone (DEX 250) is DEATH FROM ABOVE. See
// ../spells.ts for shared types.

import type { SpellDef } from "../spells.ts";

export const RANGED_SPELLS: SpellDef[] = [
  {
    id: "quick_shot",
    name: "QUICK SHOT",
    stat: "dexterity",
    category: "attack",
    element: "wind",
    minStat: 10,
    manaCost: 8,
    cooldownMs: 1600,
    effect: { kind: "bolt", damage: 26, range: 200 },
    icon: "spell_quick_shot",
    blurb: "A snap shot loosed at the nearest foe.",
  },
  {
    id: "scatter_shot",
    name: "SCATTER SHOT",
    stat: "dexterity",
    category: "aoe",
    element: "wind",
    minStat: 20,
    manaCost: 11,
    cooldownMs: 3000,
    effect: { kind: "rain", damage: 18, radius: 66, castRange: 180 },
    icon: "spell_scatter_shot",
    blurb: "A spray of shot peppers a knot of foes.",
  },
  {
    id: "take_aim",
    name: "TAKE AIM",
    stat: "dexterity",
    category: "defense",
    element: "holy",
    minStat: 30,
    manaCost: 14,
    cooldownMs: 9000,
    effect: { kind: "buff", damageMult: 1.25, durationMs: 6000 },
    icon: "spell_take_aim",
    blurb: "You steady your aim; every shot bites deeper.",
  },
  {
    id: "piercing_shot",
    name: "PIERCING SHOT",
    stat: "dexterity",
    category: "attack",
    element: "wind",
    minStat: 40,
    manaCost: 13,
    cooldownMs: 1800,
    effect: { kind: "bolt", damage: 40, range: 214 },
    icon: "spell_piercing_shot",
    blurb: "A shot that drives clean through its mark.",
  },
  {
    id: "arrow_volley",
    name: "ARROW VOLLEY",
    stat: "dexterity",
    category: "aoe",
    element: "wind",
    minStat: 50,
    manaCost: 17,
    cooldownMs: 3600,
    effect: { kind: "rain", damage: 27, radius: 80, castRange: 200 },
    icon: "spell_arrow_volley",
    blurb: "A volley arcs up and rains down on the crowd.",
  },
  {
    id: "field_dressing",
    name: "FIELD DRESSING",
    stat: "dexterity",
    category: "defense",
    element: "holy",
    minStat: 60,
    manaCost: 18,
    cooldownMs: 9000,
    effect: { kind: "heal", healPct: 0.3 },
    icon: "spell_field_dressing",
    blurb: "A quick patch job staunches your wounds.",
  },
  {
    id: "ricochet",
    name: "RICOCHET",
    stat: "dexterity",
    category: "attack",
    element: "storm",
    minStat: 70,
    manaCost: 16,
    cooldownMs: 2200,
    effect: { kind: "bolt", damage: 34, range: 204, chain: 2 },
    icon: "spell_ricochet",
    blurb: "A round that skips from body to body.",
  },
  {
    id: "incendiary_shot",
    name: "INCENDIARY SHOT",
    stat: "dexterity",
    category: "aoe",
    element: "fire",
    minStat: 80,
    manaCost: 22,
    cooldownMs: 4200,
    effect: { kind: "rain", damage: 37, radius: 88, castRange: 210 },
    icon: "spell_incendiary_shot",
    blurb: "A fire round bursts into a pool of flame.",
  },
  {
    id: "caltrops",
    name: "CALTROPS",
    stat: "dexterity",
    category: "defense",
    element: "steel",
    minStat: 90,
    manaCost: 20,
    cooldownMs: 7000,
    effect: { kind: "slow", radius: 98, factor: 0.35, durationMs: 3500 },
    icon: "spell_caltrops",
    blurb: "Spiked iron scatters the ground and hobbles the horde.",
  },
  {
    id: "snipe",
    name: "SNIPE",
    stat: "dexterity",
    category: "attack",
    element: "wind",
    minStat: 100,
    manaCost: 24,
    cooldownMs: 2400,
    effect: { kind: "bolt", damage: 58, range: 240 },
    icon: "spell_snipe",
    blurb: "One patient shot from clear across the field.",
  },
  {
    id: "hail_of_arrows",
    name: "HAIL OF ARROWS",
    stat: "dexterity",
    category: "aoe",
    element: "wind",
    minStat: 110,
    manaCost: 26,
    cooldownMs: 4200,
    effect: { kind: "rain", damage: 44, radius: 94, castRange: 220 },
    icon: "spell_hail_of_arrows",
    blurb: "The sky darkens, then falls on them in a storm.",
  },
  {
    id: "rapid_fire",
    name: "RAPID FIRE",
    stat: "dexterity",
    category: "defense",
    element: "storm",
    minStat: 120,
    manaCost: 28,
    cooldownMs: 10000,
    effect: { kind: "buff", hasteMult: 1.5, durationMs: 5000 },
    icon: "spell_rapid_fire",
    blurb: "You fire in a blur, loosing shots twice as fast.",
  },
  {
    id: "venom_shot",
    name: "VENOM SHOT",
    stat: "dexterity",
    category: "attack",
    element: "venom",
    minStat: 130,
    manaCost: 30,
    cooldownMs: 2600,
    effect: { kind: "bolt", damage: 74, range: 230 },
    icon: "spell_venom_shot",
    blurb: "A toxin-slick round that rots a foe from within.",
  },
  {
    id: "frag_shot",
    name: "FRAG SHOT",
    stat: "dexterity",
    category: "aoe",
    element: "fire",
    minStat: 140,
    manaCost: 34,
    cooldownMs: 5200,
    effect: { kind: "rain", damage: 58, radius: 106, castRange: 230 },
    icon: "spell_frag_shot",
    blurb: "A bursting shell throws shrapnel through the pack.",
  },
  {
    id: "triage",
    name: "TRIAGE",
    stat: "dexterity",
    category: "defense",
    element: "holy",
    minStat: 150,
    manaCost: 34,
    cooldownMs: 9000,
    effect: { kind: "heal", healPct: 0.45 },
    icon: "spell_triage",
    blurb: "A field kit closes even the deep ones fast.",
  },
  {
    id: "piercing_bolt",
    name: "PIERCING BOLT",
    stat: "dexterity",
    category: "attack",
    element: "wind",
    minStat: 160,
    manaCost: 34,
    cooldownMs: 2600,
    effect: { kind: "bolt", damage: 66, range: 234, chain: 3 },
    icon: "spell_piercing_bolt",
    blurb: "A bolt that skewers a whole rank in a line.",
  },
  {
    id: "arrow_storm",
    name: "ARROW STORM",
    stat: "dexterity",
    category: "aoe",
    element: "wind",
    minStat: 170,
    manaCost: 40,
    cooldownMs: 5600,
    effect: { kind: "rain", damage: 70, radius: 112, castRange: 240 },
    icon: "spell_arrow_storm",
    blurb: "An unrelenting downpour of shafts.",
  },
  {
    id: "tar_trap",
    name: "TAR TRAP",
    stat: "dexterity",
    category: "defense",
    element: "venom",
    minStat: 180,
    manaCost: 38,
    cooldownMs: 8000,
    effect: { kind: "slow", radius: 122, factor: 0.3, durationMs: 4500 },
    icon: "spell_tar_trap",
    blurb: "A slick of tar mires everything that hunts you.",
  },
  {
    id: "deadeye",
    name: "DEADEYE",
    stat: "dexterity",
    category: "attack",
    element: "void",
    minStat: 190,
    manaCost: 42,
    cooldownMs: 2800,
    effect: { kind: "bolt", damage: 96, range: 240 },
    icon: "spell_deadeye",
    blurb: "A killing shot that never, ever misses.",
  },
  {
    id: "barrage",
    name: "BARRAGE",
    stat: "dexterity",
    category: "aoe",
    element: "fire",
    minStat: 200,
    manaCost: 46,
    cooldownMs: 6000,
    effect: { kind: "rain", damage: 84, radius: 122, castRange: 250 },
    icon: "spell_barrage",
    blurb: "Saturating fire walks a wall of blasts over them.",
  },
  {
    id: "smoke_screen",
    name: "SMOKE SCREEN",
    stat: "dexterity",
    category: "defense",
    element: "wind",
    minStat: 210,
    manaCost: 46,
    cooldownMs: 11000,
    effect: { kind: "shield", absorbPct: 0.42, durationMs: 9000 },
    icon: "spell_smoke_screen",
    blurb: "A cloud swallows you; their shots find only smoke.",
  },
  {
    id: "split_arrow",
    name: "SPLIT ARROW",
    stat: "dexterity",
    category: "attack",
    element: "storm",
    minStat: 220,
    manaCost: 46,
    cooldownMs: 2800,
    effect: { kind: "bolt", damage: 88, range: 240, chain: 4 },
    icon: "spell_split_arrow",
    blurb: "One shot splits again and again down the line.",
  },
  {
    id: "death_blossom",
    name: "DEATH BLOSSOM",
    stat: "dexterity",
    category: "aoe",
    element: "void",
    minStat: 230,
    manaCost: 50,
    cooldownMs: 6400,
    effect: { kind: "rain", damage: 100, radius: 128, castRange: 255 },
    icon: "spell_death_blossom",
    blurb: "You loose in every direction at once — a lethal bloom.",
  },
  {
    id: "combat_medic",
    name: "COMBAT MEDIC",
    stat: "dexterity",
    category: "defense",
    element: "holy",
    minStat: 240,
    manaCost: 52,
    cooldownMs: 10000,
    effect: { kind: "heal", healPct: 0.6 },
    icon: "spell_combat_medic",
    blurb: "A full trauma kit puts you back in the fight.",
  },
  {
    id: "death_from_above",
    name: "DEATH FROM ABOVE",
    stat: "dexterity",
    category: "aoe",
    element: "void",
    minStat: 250,
    manaCost: 58,
    cooldownMs: 8000,
    effect: { kind: "rain", damage: 140, radius: 152, castRange: 280 },
    icon: "spell_death_from_above",
    blurb: "You call down an annihilating rain from the dark.",
  },
];
