#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The enemy pipeline (see the `enemy-design` skill). Compiles the YAML enemy
// tree (`website/scripts/enemies/<biome>/<id>.yaml`) into the engine's EnemyDef
// catalog — the roster equivalent of the level/sprite pipelines. It:
//   1. harvests the live def-id catalogs an EnemyDef points AT (companions,
//      uniques, story items, weapons+gear) for cross-ref checks,
//   2. loads + schema-validates every YAML enemy (a bad field/id fails the
//      build),
//   3. writes src/generated/enemies.ts — GENERATED_ENEMIES, the flat catalog
//      src/game/defs/enemies/index.ts reads.
// The output is gitignored and regenerated on every build (like levels.ts), so
// the YAML is the single source of truth.
//
// MUST run BEFORE generate-levels.mjs: the level generator imports
// enemies/index.ts (which now reads this file) to cross-ref its spawn ids.
// The cross-ref catalogs below are imported DIRECTLY (never @game/core, and
// never the enemy index) so nothing pulls the file we are about to write —
// mirroring the bootstrap-cycle note in generate-levels.mjs.

import { mkdirSync, writeFileSync } from "node:fs";
import { register } from "node:module";
import { fileURLToPath } from "node:url";

// Engine modules under src/lib use the @game/lib alias at runtime — map it so
// the def catalogs import cleanly under plain node.
register("../../scripts/game-alias-loader.mjs", import.meta.url);

import { validateEnemy } from "./asset-tools/enemy-schema.mjs";
import { loadEnemies } from "./enemy-data/load-yaml.mjs";

const engine = (p) => fileURLToPath(new URL(`../../${p}`, import.meta.url));

const { COMPANION_DEFS } = await import(engine("src/game/defs/companions.ts"));
const { UNIQUE_DEFS } = await import(engine("src/game/defs/uniques.ts"));
const { STORY_ITEM_DEFS } = await import(engine("src/game/defs/story.ts"));
const { WEAPON_DEFS } = await import(engine("src/game/defs/equipment.ts"));
const { GEAR_DEFS } = await import(engine("src/game/defs/gear.ts"));

const { enemies, entries } = loadEnemies();

const refs = {
  enemies: new Set(Object.keys(enemies)),
  companions: new Set(Object.keys(COMPANION_DEFS)),
  uniques: new Set(Object.keys(UNIQUE_DEFS)),
  storyItems: new Set(Object.keys(STORY_ITEM_DEFS)),
  items: new Set([...Object.keys(WEAPON_DEFS), ...Object.keys(GEAR_DEFS)]),
};

const errors = [];
const warnings = [];
for (const { def } of entries) {
  const res = validateEnemy(def, refs);
  errors.push(...res.errors);
  warnings.push(...res.warnings);
}
for (const w of warnings) console.warn(`! ${w}`);
if (errors.length > 0) {
  console.error(
    `${errors.length} enemy schema error(s):\n  ${errors.join("\n  ")}`,
  );
  process.exit(1);
}

const banner = `// @generated by website/scripts/generate-enemies.mjs — DO NOT EDIT.
// Source of truth: website/scripts/enemies/<biome>/<id>.yaml. Regenerate with
// \`npm run levels\` (also runs inside \`npm run assets\` / \`make assets\`).
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0`;

const out = `${banner}
import type { EnemyDef } from "../game/defs/enemies/types.ts";

export const GENERATED_ENEMIES: Record<string, EnemyDef> = ${JSON.stringify(
  enemies,
  null,
  2,
)} as unknown as Record<string, EnemyDef>;
`;

const destDir = engine("src/generated");
mkdirSync(destDir, { recursive: true });
writeFileSync(`${destDir}/enemies.ts`, out);
console.log(
  `wrote src/generated/enemies.ts — ${Object.keys(enemies).length} enemies`,
);
