// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Source of truth for every in-game pixel sprite (see the `pixel-assets`
// skill). One string per pixel row, one character per pixel; `.` is
// transparent and every other character must exist in PALETTE. Edit these
// grids, then run generate-assets.mjs and LOOK at the previews.
//
// Colors are organized as ramps (asset-tools/palette.mjs): each subject has
// a base color and derives its shade/highlight programmatically, so a whole
// character or biome can be re-themed by changing one base value — and
// palette variants (elite enemies, new level biomes) are a `swapPalette`
// call away instead of a redraw.

import {
  buildPalette,
  ramp,
  shade,
  swapPalette,
  tint,
} from "./asset-tools/palette.mjs";

// ---- Subjects -------------------------------------------------------------

const OUTLINE = [26, 28, 44]; // dark navy, not pure black; also eyes/mouths

/** The astronaut hero: white EVA suit, gold visor. */
const ASTRO = {
  suit: ramp([214, 220, 228], { shadeBy: 0.34 }),
  visor: [255, 176, 46], // shares the bolt gold
};

/**
 * The moon's haunting, one translucency-baked ramp per tier (4th channel =
 * alpha). Wisps are faint, ghosts solid, wraiths violet with hot red eyes,
 * and ARMSTRONG — the boss — a pale green revenant.
 */
const WISP = { base: [205, 232, 240, 185], dark: [148, 188, 199, 185] };
const GHOST = {
  base: [140, 205, 215, 225],
  dark: [91, 133, 140, 225],
  light: [197, 230, 235, 225],
};
const WRAITH = {
  base: [165, 125, 225, 230],
  dark: [100, 70, 150, 230],
  eyes: [255, 82, 82],
};
const BOSS = { base: [185, 230, 205, 240], dark: [115, 160, 135, 240] };

const SLIME = ramp([176, 92, 220], { shadeBy: 0.35, tintBy: 0.45 });

const MEDKIT_COLORS = { white: [244, 244, 244], red: [216, 58, 58] };

/** The moon biome floor — retheme the whole moonscape from this base. */
const MOON = ramp([136, 138, 150], { shadeBy: 0.24, tintBy: 0.22 });
const MOON_PIT = shade([136, 138, 150], 0.43); // crater floors

/** Landmark accents: the flag's canton and the lander's gold foil. */
const FLAG_BLUE = [64, 84, 188];
const LANDER_GOLD = ramp([214, 168, 66], { shadeBy: 0.3 });

const WOOD = [52, 44, 38]; // wand handles and other grips

/** The (future) earth biome ground. */
const GRASS = ramp([74, 122, 62], { shadeBy: 0.18, tintBy: 0.16 });
const DIRT = [104, 84, 56];

/** SpaceZ HQ (level 1): the lab floor and its steel architecture. */
const LAB = ramp([170, 176, 190], { shadeBy: 0.24, tintBy: 0.26 });
const STEEL = ramp([96, 104, 126], { shadeBy: 0.34, tintBy: 0.3 });

/** The night shift: one skin tone; uniforms reuse existing ramps. */
const SKIN = [222, 170, 134];
const HAZMAT_SUIT = ramp([226, 198, 64], { shadeBy: 0.3 });
const GUARD_NAVY = shade(FLAG_BLUE, 0.3);

/** MUSKRAT (and the prelude couch): matted brown fur. */
const RAT = ramp([146, 100, 62], { shadeBy: 0.36, tintBy: 0.3 });

/** Shared palette: char → RGBA. Light source is top-left. */
export const PALETTE = buildPalette(
  { O: OUTLINE },
  { a: ASTRO.suit.base, A: ASTRO.suit.dark },
  { y: ASTRO.visor, Y: tint(ASTRO.visor, 0.65) },
  { u: WISP.base, U: WISP.dark },
  { c: GHOST.base, C: GHOST.dark, x: GHOST.light },
  { m: WRAITH.base, M: WRAITH.dark, R: WRAITH.eyes },
  { n: BOSS.base, N: BOSS.dark },
  { P: SLIME.base, Q: SLIME.dark, L: SLIME.light },
  {
    W: MEDKIT_COLORS.white,
    w: shade(MEDKIT_COLORS.white, 0.19),
    r: MEDKIT_COLORS.red,
  },
  { f: MOON.base, F: MOON.light, d: MOON.dark, e: MOON_PIT },
  { j: FLAG_BLUE },
  { o: LANDER_GOLD.base, q: LANDER_GOLD.dark },
  { k: WOOD },
  { z: [12, 14, 22, 110] }, // soft jump shadow
  { G: GRASS.base, g: GRASS.dark, l: GRASS.light, D: DIRT },
  { t: LAB.base, T: LAB.light, s: LAB.dark },
  { v: STEEL.base, V: STEEL.light, b: STEEL.dark },
  { p: SKIN },
  { h: HAZMAT_SUIT.base, H: HAZMAT_SUIT.dark },
  { J: GUARD_NAVY },
  { B: RAT.base, E: RAT.dark, S: RAT.light },
);

// ---- Animations -----------------------------------------------------------

/** Frame sequences the generator turns into film strips + animated previews. */
export const ANIMATIONS = {
  player_walk: { frames: ["player_0", "player_1"], delayMs: 160 },
  wisp_float: { frames: ["wisp_0", "wisp_1"], delayMs: 340 },
  ghost_float: { frames: ["ghost_0", "ghost_1"], delayMs: 300 },
  wraith_float: { frames: ["wraith_0", "wraith_1"], delayMs: 240 },
  armstrong_loom: { frames: ["armstrong_0", "armstrong_1"], delayMs: 420 },
  slime_bounce: { frames: ["slime_0", "slime_1"], delayMs: 280 },
  intern_walk: { frames: ["intern_0", "intern_1"], delayMs: 300 },
  scientist_walk: { frames: ["scientist_0", "scientist_1"], delayMs: 300 },
  engineer_walk: { frames: ["engineer_0", "engineer_1"], delayMs: 280 },
  guard_walk: { frames: ["guard_0", "guard_1"], delayMs: 220 },
  hazmat_walk: { frames: ["hazmat_0", "hazmat_1"], delayMs: 380 },
  muskrat_loom: { frames: ["muskrat_0", "muskrat_1"], delayMs: 400 },
  ada_walk: { frames: ["ada_0", "ada_1"], delayMs: 220 },
  hero_couch_idle: { frames: ["hero_couch_0", "hero_couch_1"], delayMs: 600 },
};

// The GOLDEN STAPLER icon is the stapler re-skinned in trophy gold — a
// swapPalette call, never a redraw.
const STAPLER_ICON = [
  "............",
  "..OOOOOO....",
  ".OrrrrrrO...",
  ".OrrrrrrOO..",
  "..OOOOOrrO..",
  ".OaaaaaaaO..",
  ".OAAAAAAAO..",
  "..OOOOOOO...",
  "............",
  "............",
  "............",
  "............",
];

// ---- Sprites --------------------------------------------------------------

/**
 * Sprite grids. Animation frames are separate entries named `<sprite>_<n>`.
 * Sizes: characters/enemies 16×16 (the boss 48×48), projectiles 8×8, icons
 * 12×12, medkit 12×12, tiles 16×16, lander 32×32, flag 16×24.
 */
export const SPRITES = {
  // The hero: an astronaut in a white EVA suit, 3/4 top-down.
  // Frames 0/1 alternate the leg stride; player_jump tucks the legs.
  player_0: [
    "................",
    ".....OOOOOO.....",
    "....OaaaaaaO....",
    "...OaaaaaaaaO...",
    "...OaOYyyyOaO...",
    "...OaOyyyyOaO...",
    "....OaaaaaaO....",
    "...OOaaaaaaOO...",
    "..OaaaaaaaaaaO..",
    "..OAaaarraaaAO..",
    "..OWOaaaaaaOWO..",
    "...OAAAAAAAAO...",
    "...OaaO..OaaO...",
    "...OAAO..OAAO...",
    "...OOOO..OOOO...",
    "................",
  ],
  player_1: [
    "................",
    ".....OOOOOO.....",
    "....OaaaaaaO....",
    "...OaaaaaaaaO...",
    "...OaOYyyyOaO...",
    "...OaOyyyyOaO...",
    "....OaaaaaaO....",
    "...OOaaaaaaOO...",
    "..OaaaaaaaaaaO..",
    "..OAaaarraaaAO..",
    "..OWOaaaaaaOWO..",
    "...OAAAAAAAAO...",
    "..OaaO....OaaO..",
    "..OAAO....OAAO..",
    "..OOOO....OOOO..",
    "................",
  ],
  player_jump: [
    "................",
    ".....OOOOOO.....",
    "....OaaaaaaO....",
    "...OaaaaaaaaO...",
    "...OaOYyyyOaO...",
    "...OaOyyyyOaO...",
    "....OaaaaaaO....",
    "...OOaaaaaaOO...",
    "..OaaaaaaaaaaO..",
    "..OAaaarraaaAO..",
    "..OWOaaaaaaOWO..",
    "...OAAAAAAAAO...",
    "...OaaO..OaaO...",
    "...OOOO..OOOO...",
    "................",
    "................",
  ],
  // WISP — the faintest haunting, found near the landing site.
  wisp_0: [
    "................",
    "................",
    "......OOOO......",
    ".....OuuuuO.....",
    "....OuuuuuuO....",
    "....OuOuuOuO....",
    "....OuuuuuuO....",
    "....OUuuuuUO....",
    ".....OuuuUO.....",
    "......OuUO......",
    ".......OO.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  wisp_1: [
    "................",
    "................",
    "................",
    "......OOOO......",
    ".....OuuuuO.....",
    "....OuOuuOuO....",
    "....OuuuuuuO....",
    "....OUuuuuUO....",
    ".....OUuuuO.....",
    "......OUuO......",
    ".......OO.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  // MOON GHOST — the classic sheet, mid-difficulty band.
  ghost_0: [
    "................",
    ".....OOOOOO.....",
    "....OxxccccO....",
    "...OxcccccccO...",
    "...OcOccccOcO...",
    "...OccccccccO...",
    "..OccccOOccccO..",
    "..OccccccccccO..",
    "..OccccccccccO..",
    "..OCccccccccCO..",
    "..OCcOccccOcCO..",
    "...OCO.OO.OCO...",
    "................",
    "................",
    "................",
    "................",
  ],
  ghost_1: [
    "................",
    "................",
    ".....OOOOOO.....",
    "....OxxccccO....",
    "...OxcccccccO...",
    "...OcOccccOcO...",
    "...OccccccccO...",
    "..OccccOOccccO..",
    "..OccccccccccO..",
    "..OccccccccccO..",
    "..OCccccccccCO..",
    "..OCcOccccOcCO..",
    "...OCO.OO.OCO...",
    "................",
    "................",
    "................",
  ],
  // WRAITH — fast, hooded, red-eyed; prowls the far side.
  wraith_0: [
    "......OOOO......",
    ".....OmmmmO.....",
    "....OmmmmmmO....",
    "....OmRmmRmO....",
    "....OmmmmmmO....",
    "...OmmmMMmmmO...",
    "...OmmmmmmmmO...",
    "..OmmMmmmmMmmO..",
    "..OmmmmmmmmmmO..",
    "..OMmmmmmmmmMO..",
    "..OMmMmmmmMmMO..",
    "...OMOMmmMOMO...",
    "....O.OMMO.O....",
    ".......OO.......",
    "................",
    "................",
  ],
  wraith_1: [
    "......OOOO......",
    ".....OmmmmO.....",
    "....OmmmmmmO....",
    "....OmRmmRmO....",
    "....OmmmmmmO....",
    "...OmmMMmmmmO...",
    "...OmmmmmmmmO...",
    "..OmmMmmmmMmmO..",
    "..OmmmmmmmmmmO..",
    "..OMmmmmmmmmMO..",
    "..OMmMmmmmMmMO..",
    "...OMOMmmMOMO...",
    "....O..OMMO.O...",
    "........OO......",
    "................",
    "................",
  ],
  // ARMSTRONG — the boss: a giant astronaut ghost with ENORMOUS arms,
  // haunting the flag he planted. 48×48, generated-then-tuned by hand.
  armstrong_0: [
    "................................................",
    "................................................",
    "....................OOOOOOOO....................",
    "..................OOnnnnnnnnOO..................",
    ".................OWWWWnnnnnnnnO.................",
    "................OnnnnnnOOnnnnnnO................",
    "...............OnnnOOOOOOOOOOnnnO...............",
    "..............OnnnOOOOOOOOOOOOnnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "...............OnnOOOOOOOOOOOOnnO...............",
    "................OnnOOOOOOOOOOnnO................",
    "...........OOOOOnnnnnnnOOnnnnnnnOOOOO...........",
    "........OOOnnnnnnnnnnnnnnnnnnnnnnnnnnOOO........",
    "......OOnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnOO......",
    ".....OnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnO.....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnNnnnnnnnnnnnnnnnnnnNnnNnnnnnnnO...",
    "...OnnnnnnnNOnNnnnnnnnnnnnnnnnnnnNnONnnnnnnnO...",
    "...OnnnnnnnO.ONNnnnnnnnnnnnnnnnnNNO.OnnnnnnnO...",
    "...OnnnnnnnO.ONNNnnnnnnnnnnnnnnNNNO.OnnnnnnnO...",
    "...OnnnnnnnO..ONNNnnnnnnnnnnnnNNNO..OnnnnnnnO...",
    "..OnnnnnnnnnO.OnnnnnnnnnnnnnnnnnnO.OnnnnnnnnnO..",
    "..OnnnnnnnnnO..OnnnnnnnnnnnnnnnnO..OnnnnnnnnnO..",
    ".OnnnnnnnnnnnO..OnnnnnnnnnnnnnnO..OnnnnnnnnnnnO.",
    "..OnnnnnnnnnO...OnnnnnnnnnnnnnnO...OnnnnnnnnnO..",
    "..OnNNNNNNnnO..OnnnnnnnnnnnnnnnnO..OnNNNNNNnnO..",
    "...OnnnnnnnO....OnnnnnnnnnnnnnnO....OnnnnnnnO...",
    "...OOnnnnnOO....OnnnnnnnnnnnnnnO....OOnnnnnOO...",
    ".....OOOOO.......OnnnnnnnnnnnnO.......OOOOO.....",
    "...............OOnnnnnnnnnnnnnnOO...............",
    "..............OnnnnOOOnnnOOOOnnnnO..............",
    "..............OnnnO...OnO....OnnnO..............",
    "..............OnnnO..OnnnO...OnnnO..............",
    "...............OOO...OnnnO....OOO...............",
    ".....................OnnnO......................",
    "......................OOO.......................",
  ],
  armstrong_1: [
    "................................................",
    "................................................",
    "....................OOOOOOOO....................",
    "..................OOnnnnnnnnOO..................",
    ".................OWWWWnnnnnnnnO.................",
    "................OnnnnnnOOnnnnnnO................",
    "...............OnnnOOOOOOOOOOnnnO...............",
    "..............OnnnOOOOOOOOOOOOnnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "...............OnnOOOOOOOOOOOOnnO...............",
    "................OnnOOOOOOOOOOnnO................",
    "...........OOOOOnnnnnnnOOnnnnnnnOOOOO...........",
    "......OOOOOnnnnnnnnnnnnnnnnnnnnnnnnnnOOOOO......",
    ".....OnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnO.....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnNnnnnnnnnnnnnnnnnnnNnnNnnnnnnnO...",
    "...OnnnnnnnNOnNnnnnnnnnnnnnnnnnnnNnONnnnnnnnO...",
    "...OnnnnnnnO.ONNnnnnnnnnnnnnnnnnNNO.OnnnnnnnO...",
    "..OnnnnnnnnnOONNNnnnnnnnnnnnnnnNNNOOnnnnnnnnnO..",
    "..OnnnnnnnnnO.ONNNnnnnnnnnnnnnNNNO.OnnnnnnnnnO..",
    ".OnnnnnnnnnnnOOnnnnnnnnnnnnnnnnnnOOnnnnnnnnnnnO.",
    "..OnnnnnnnnnO..OnnnnnnnnnnnnnnnnO..OnnnnnnnnnO..",
    "..OnNNNNNNnnO...OnnnnnnnnnnnnnnO...OnNNNNNNnnO..",
    "...OnnnnnnnO....OnnnnnnnnnnnnnnO....OnnnnnnnO...",
    "...OOnnnnnOO...OnnnnnnnnnnnnnnnnO...OOnnnnnOO...",
    ".....OOOOO......OnnnnnnnnnnnnnnO......OOOOO.....",
    "................OnnnnnnnnnnnnnnO................",
    ".................OnnnnnnnnnnnnO.................",
    "...............OOnnnnnnnnnnnnnnOO...............",
    "..............OnnnnOOOOnnnOOOnnnnO..............",
    "..............OnnnO....OnO...OnnnO..............",
    "..............OnnnO...OnnnO..OnnnO..............",
    "...............OOO....OnnnO...OOO...............",
    "......................OnnnO.....................",
    ".......................OOO......................",
  ],
  // Landmarks: the ship at the landing site and the old flag.
  lander: [
    "................................",
    "..................AA............",
    "..................A.............",
    "............OOOOOOOO............",
    "............OaaaaaaO............",
    "............OaaaaaaO............",
    "..........OOaaaaaaaaOO..........",
    "..........OaaOOOaaaaAO..........",
    "..........OaaOOOaAAAAO..........",
    "..........OaaOOOaAAAAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    ".......OOOooooooooooooOOO.......",
    ".......OooooooooooooooqqO.......",
    ".......OqooqooqooqooqoqqO.......",
    ".......OooooooooooooooqqO.......",
    ".......OoqooqooqooqooqqqO.......",
    ".......OooooooooooooooqqO.......",
    ".......OooooooooooooooqqO.......",
    ".......OqqqqqqqqqqqqqqqqO.......",
    ".......OOOOOOOqqqqOOOOOOO.......",
    "......OO......OAAO......OO......",
    ".....OO.......OAAO.......OO.....",
    "....OO.......OOOOOO.......OO....",
    "...OO......................OO...",
    ".OOOOO....................OOOOO.",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  flag: [
    "................",
    "...OO...........",
    "...OAOOOOOOOOOO.",
    "...OAOjjjjjrrrO.",
    "...OAOjWjjjrrrO.",
    "...OAOjjjjjWWWO.",
    "...OAOjjjjjWWWO.",
    "...OAOrrrrrrrrO.",
    "...OAOWWWWWWWWO.",
    "...OAOrrrrrrrrO.",
    "...OAOOOOOOOOOO.",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "..OOAOO.........",
    "................",
  ],
  // Moonscape decor: craters and strewn rocks (no collision).
  crater_big: [
    "................................",
    "................................",
    "................................",
    "................................",
    "..............dddd..............",
    "..........FFdddddddddd..........",
    ".......FFFFdddddddddddddd.......",
    "......FFFFd.eeeeeeee.ddddd......",
    ".....FFFFeeeeeeeeeeeeeedddd.....",
    "....FFF.eeeeee....eeeeee.ddd....",
    "...FFFeeeee..........eeeeeddd...",
    "..FFFFeee..............eeedddd..",
    "..FFFeeee..............eeeeddd..",
    ".FFFeeee................eeeeddd.",
    ".FFdeee..................eeeddd.",
    ".Fddeee..................eeeddd.",
    ".dddeee..................eeeddd.",
    ".dddeee..................eeeddd.",
    ".dddeeee................eeeeddd.",
    "..dddeeee..............eeeeddd..",
    "..ddddeee..............eeedddd..",
    "...dddeeeee..........eeeeeddd...",
    "....ddd.eeeeee....eeeeee.ddd....",
    ".....ddddeeeeeeeeeeeeeedddd.....",
    "......ddddd.eeeeeeee.ddddd......",
    ".......dddddddddddddddddd.......",
    "..........dddddddddddd..........",
    "..............dddd..............",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  crater_small: [
    "................",
    "................",
    "......Fddd......",
    "...FFFddddddd...",
    "..FFF.eeee.ddd..",
    ".FF.eeeeeeee.dd.",
    ".FFee......eedd.",
    ".F.ee......ee.d.",
    ".d.ee......ee.d.",
    ".ddee......eedd.",
    ".dd.eeeeeeee.dd.",
    "..ddd.eeee.ddd..",
    "...dddddddddd...",
    "......dddd......",
    "................",
    "................",
  ],
  rocks: [
    "................",
    "................",
    "................",
    "...eeee.........",
    "..edddde........",
    "...eeee.........",
    "..........eeee..",
    "..........edde..",
    "..........eeee..",
    "................",
    "................",
    ".....eee........",
    ".....eee........",
    "................",
    "................",
    "................",
  ],
  // Solid obstacles (collision in the engine): the tall boulder blocks
  // everything; the low rock can be jumped over (never by monsters).
  boulder: [
    "............OOOOO...........",
    "..........OOFFFFOOO.........",
    ".........OFFFFFFFFFOO.......",
    "........OFFFFFFFffffOO......",
    ".......OFFFFFdFFffffffO.....",
    "......OFFFFFdffffffffffO....",
    ".....OFFFFFdfffffffffffO....",
    "....OFFFFFdffffffffffffdO...",
    "...OFFFFFdffffffffffffddO...",
    "..OFFFFFdfffffffdfffffddO...",
    "..OFFFFdffffffffdffffdddO...",
    ".OFFFFdfffffffffdfffddddO...",
    ".OFFFdffffffffffdffdddddO...",
    ".OFFfffffffffffdddddddddO...",
    ".OFffffffffffffdeeddddddOO..",
    "OFffffffffffffdeeedddddddO..",
    "OffffffffffffdeeeddddddddO..",
    "OfffffffdddddeeedddddddeeO..",
    "OffffdddddddeeeddddddeeeeO..",
    ".OdddddddddeeedddddeeeeeO...",
    ".OOddddddddeedddddeeeeeOO...",
    "...OOOOOOOOOOOOOOOOOOOO.....",
  ],
  rock: [
    "..................",
    ".....OOOOOOOO.....",
    "...OOFFFfffffOO...",
    "..OFFFFffffffffO..",
    ".OFFFfddffffffddO.",
    ".OFFfffffffffdddO.",
    ".OfffffffffdddddO.",
    ".OfffdfffdddeddeO.",
    "..OfffffddddddeO..",
    "...OOfddddddeOO...",
    ".....OOOOOOOO.....",
    "..................",
  ],
  // Ground tiles. Keep edges featureless so they tile without seams;
  // moon_1 carries a small pock, gravel_* are the scree patches.
  moon_0: [
    "ffffffffffffffff",
    "fffffffffffffdff",
    "ffFfffffffffFfff",
    "fffffffffffdffff",
    "ffffffffffffffff",
    "ffffffffffFfffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
    "fffffdffffffffff",
    "ffffffffffffffff",
    "fffffffffffddfff",
    "ffffffffffdfffff",
    "fffFffffffffffff",
    "fffffffffffffdff",
    "ffffffffffffffff",
    "ffffffffffffffff",
  ],
  moon_1: [
    "ffffffffffffffff",
    "fdFfffffffffffff",
    "ffffffffffffdfff",
    "fffffffFffffffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
    "fffffffddfffffff",
    "ffffffdeedffffff",
    "ffffffdeedffffdf",
    "fffffffddfffffff",
    "ffffFfffffffffff",
    "fffdffffffffffff",
    "ffffffffffffffff",
    "ffffffffdfffffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
  ],
  gravel_0: [
    "ffffffffffffffff",
    "ffffffffFfffffff",
    "fffffFffffffffff",
    "fffffddFffffffff",
    "fffffdFfdfffffff",
    "ffFffffddfffffff",
    "ffddffffffffffff",
    "ffddffffffffffff",
    "ffffffffffedfeff",
    "fffffffffffffddf",
    "ffffffFffffffFff",
    "ffedffddffFfffff",
    "ffddffdfffffffff",
    "fffffedfddfFffff",
    "fFffffffdfffffff",
    "ffffffffffffffff",
  ],
  gravel_1: [
    "ffffffffffffffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
    "ffffffFffffFffff",
    "ffffffddfffedfff",
    "fffffffFffFdffff",
    "ffffffffffeeffff",
    "ffffffffffFddfff",
    "fffffffffFfddfff",
    "ffffffffffffedff",
    "ffffffffffFfddff",
    "ffffffffffffFfff",
    "ffffffFffffffFff",
    "fffffffdffffffdf",
    "ffffffddffffffdf",
    "ffffffffffffffff",
  ],
  // Projectiles: the blaster bolt and the wand spark.
  bolt: [
    "........",
    "...OO...",
    "..OyyO..",
    ".OyYYyO.",
    ".OyYYyO.",
    "..OyyO..",
    "...OO...",
    "........",
  ],
  spark: [
    "........",
    "...OO...",
    "..OLLO..",
    ".OLPPLO.",
    ".OLPPLO.",
    "..OLLO..",
    "...OO...",
    "........",
  ],
  // The FIRE ORBS ability's orbiting fireball: red rim, white-hot core.
  fireball: [
    "........",
    "...OO...",
    "..OrrO..",
    ".OrYYrO.",
    ".OrYYrO.",
    "..OrrO..",
    "...OO...",
    "........",
  ],
  // The medkit consumable.
  medkit: [
    "............",
    ".OOOOOOOOOO.",
    ".OWWWWWWWWO.",
    ".OWWWrrWWWO.",
    ".OWWWrrWWWO.",
    ".OWrrrrrrWO.",
    ".OWrrrrrrWO.",
    ".OWWWrrWWWO.",
    ".OWWWrrWWWO.",
    ".OwwwwwwwwO.",
    ".OOOOOOOOOO.",
    "............",
  ],
  // The repair kit: a grey toolbox with a gold latch.
  repair: [
    "....OOOO....",
    "...OO..OO...",
    ".OOOOOOOOOO.",
    ".OaaaaaaaaO.",
    ".OaaayyaaaO.",
    ".OAAAyYAAAO.",
    ".OAAAAAAAAO.",
    ".OAAAAAAAAO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
    "............",
  ],
  // ARMSTRONG's Apollo survival-kit machete: broad steel blade, wood grip.
  icon_machete: [
    "............",
    ".......OOO..",
    "......OaaO..",
    ".....OaaAO..",
    "....OaaAO...",
    "...OaaAO....",
    "..OaaAO.....",
    ".OaaAO......",
    ".OaAO.......",
    "OkkO........",
    "OkkO........",
    ".OO.........",
  ],
  // The MOON'S BLADE trophy: a pale spectral blade, ghost-lit.
  icon_moons_blade: [
    "............",
    ".......OOO..",
    "......OxxO..",
    ".....OxxcO..",
    "....OxxcO...",
    "...OxxcO....",
    "..OxxcO.....",
    ".OxxcO......",
    ".OxcO.......",
    "OkkO........",
    "OkkO........",
    ".OO.........",
  ],
  // The weapon-upgrade pickup: a golden up arrow.
  upgrade: [
    "............",
    ".....OO.....",
    "....OyyO....",
    "...OyYyyO...",
    "..OyYyyyyO..",
    ".OyYyyyyyyO.",
    ".OOOOyyOOOO.",
    "....OyyO....",
    "....OyyO....",
    "....OyyO....",
    "....OOOO....",
    "............",
  ],
  // Soft blob shadow under the player while jumping.
  shadow: ["...zzzzzz...", ".zzzzzzzzzz.", ".zzzzzzzzzz.", "...zzzzzz..."],
  // Inventory icons, 12×12.
  icon_blaster: [
    "............",
    "............",
    ".OOOOOOOOO..",
    ".OAAAAAAAyO.",
    ".OAAAAAAAyO.",
    ".OOOOAAOOO..",
    "....OAAO....",
    "....OAAO....",
    "....OOOO....",
    "............",
    "............",
    "............",
  ],
  icon_wand: [
    "............",
    "........OO..",
    ".......OLLO.",
    "......OLPPO.",
    "......OPPO..",
    ".....OkkO...",
    "....OkkO....",
    "...OkkO.....",
    "..OkkO......",
    "..OkO.......",
    "...O........",
    "............",
  ],
  icon_wrench: [
    "............",
    ".OO....OO...",
    ".OAO..OAO...",
    ".OAAOOAAO...",
    "..OAAAAO....",
    "...OAAO.....",
    "....OAAO....",
    ".....OAAO...",
    "......OAAO..",
    ".......OAO..",
    "........O...",
    "............",
  ],
  icon_suit: [
    "............",
    "..OOOOOOOO..",
    ".OaaaaaaaaO.",
    ".OaaOrrOaaO.",
    ".OaaaaaaaaO.",
    ".OAaaaaaaAO.",
    ".OAaaaaaaAO.",
    "..OaaaaaaO..",
    "..OAAAAAAO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  icon_charm: [
    "............",
    "....OOOO....",
    "...OFFFFO...",
    "..OFFOOOO...",
    "..OFO.......",
    "..OFO.......",
    "..OFO.......",
    "..OFFOOOO...",
    "...OFFFFO...",
    "....OOOO....",
    "............",
    "............",
  ],
  // The simple base-type weapons (Diablo-style unnamed drops).
  // A length of scavenged conduit: dull steel, flanged ends.
  icon_pipe: [
    "............",
    "........OO..",
    ".......OaaO.",
    "......OaaAO.",
    ".....OaaAO..",
    "....OaaAO...",
    "...OaaAO....",
    "..OaaAO.....",
    ".OaaAO......",
    ".OaAO.......",
    "..OO........",
    "............",
  ],
  // A geologist's sledge: heavy steel head, wooden haft.
  icon_hammer: [
    "............",
    "..OOOOOOO...",
    ".OaaaaaaAO..",
    ".OaaaaaaAO..",
    ".OAAAAAAAO..",
    "..OOOkOOO...",
    ".....OkO....",
    ".....OkO....",
    ".....OkO....",
    ".....OkO....",
    "......O.....",
    "............",
  ],
  // A compact sidearm: shorter and duller than the hero's blaster.
  icon_pistol: [
    "............",
    "............",
    "..OOOOOO....",
    "..OaaaaAO...",
    "..OOOaaO....",
    "....OaAO....",
    "....OaAO....",
    "....OOO.....",
    "............",
    "............",
    "............",
    "............",
  ],
  // A long-barreled rifle with a wooden stock.
  icon_rifle: [
    "............",
    ".........OO.",
    "........OaO.",
    ".......OaO..",
    "......OaO...",
    ".....OaO....",
    "....OaO.....",
    "...OkkO.....",
    "..OkkO......",
    "..OkO.......",
    "...O........",
    "............",
  ],
  // A wand crowned with a golden star.
  icon_star_wand: [
    "............",
    ".....OyO....",
    "....OyYyO...",
    ".....OyO....",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    ".OO.........",
    "............",
    "............",
  ],
  // A wand bearing a violet void orb.
  icon_void_wand: [
    "............",
    ".....OO.....",
    "....OmmO....",
    "....OmMO....",
    ".....OO.....",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    "..O.........",
    "............",
  ],
  // Ability pickups: time-limited powers.
  // FIRE ORBS: three fireballs mid-orbit.
  icon_fire_orbs: [
    "............",
    "....OO......",
    "...OrYO.....",
    "....OO......",
    "............",
    ".OO.....OO..",
    "OrYO...OrYO.",
    ".OO.....OO..",
    "............",
    "............",
    "............",
    "............",
  ],
  // STORM CELL: a jagged golden bolt.
  icon_storm: [
    "............",
    "......OOO...",
    ".....OyyO...",
    "....OyyO....",
    "...OyyOO....",
    "..OyyyyO....",
    "...OOyyO....",
    "....OyyO....",
    "...OyyO.....",
    "...OyO......",
    "...OO.......",
    "............",
  ],
  // STASIS FIELD: a pale ring holding still around a speck of astronaut.
  icon_stasis: [
    "............",
    "....xxxx....",
    "..xx....xx..",
    ".x........x.",
    ".x........x.",
    "x....aa....x",
    "x....aa....x",
    ".x........x.",
    ".x........x.",
    "..xx....xx..",
    "....xxxx....",
    "............",
  ],
  // SCREEN NUKE: a squat bomb, fuse lit.
  icon_nuke: [
    "........yy..",
    "....OO..y...",
    "...OkkOy....",
    "..OOkkOO....",
    ".OaaAAAAO...",
    "OaaAAAAAAO..",
    "OaAAAAAAAO..",
    "OaAAAAAAAO..",
    "OAAAAAAAAO..",
    ".OAAAAAAO...",
    "..OOOOOO....",
    "............",
  ],
  // ITEM MAGNET: the classic red horseshoe, poles down.
  icon_magnet: [
    "............",
    "...rrrrrr...",
    "..rrrrrrrr..",
    ".rrr....rrr.",
    ".rr......rr.",
    ".rr......rr.",
    ".rr......rr.",
    ".rr......rr.",
    ".WW......WW.",
    ".WW......WW.",
    "............",
    "............",
  ],
  // Earth biome tiles + the slime, parked for level 1 (the NASA heist).
  grass_0: [
    "GGGGGGGGGGGGGGGG",
    "GGlGGGGGGGGGgGGG",
    "GGlGGGGgGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GgGGGGGGGGlGGGGG",
    "GGGGGGGGGGlGGGGG",
    "GGGGlGGGGGGGgGGG",
    "GGGGlGGGGgGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GlGGGGGGGGGGGDGG",
    "GlGGGGgGGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GGGGGGGGGGlGGGGG",
    "GGgGGGGGGGlGGGGG",
    "GGGGGGGDGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
  ],
  grass_1: [
    "GGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGlGGGG",
    "GGgGGGGGGGGlGGGG",
    "GGGGGGGGGGGGGGGG",
    "GGGGGGlGGGGGGgGG",
    "GGGGGGlGGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GDGGGGGGGgGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GGGGGgGGGGGGlGGG",
    "GGGGGGGGGGGGlGGG",
    "GWyWGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GGGGGGGGgGGGGGGG",
    "GGGGGGGGGGGGGgGG",
    "GGGGGGGGGGGGGGGG",
  ],
  slime_0: [
    "................",
    "................",
    "................",
    "................",
    ".....OOOOOO.....",
    "....OLLPPPPO....",
    "...OLPPPPPPPO...",
    "..OLPPPPPPPPPO..",
    "..OPPOPPPPOPPO..",
    "..OPPOPPPPOPPO..",
    "..OPPPPOOPPPPO..",
    "..OQPPPPPPPPQO..",
    "..OQQPPPPPPQQO..",
    "...OQQQQQQQQO...",
    "....OOOOOOOO....",
    "................",
  ],
  slime_1: [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....OOOOOOOO....",
    "..OOLLPPPPPPOO..",
    ".OLPPPPPPPPPPPO.",
    ".OPPOPPPPPPOPPO.",
    ".OPPPPOOOOPPPPO.",
    ".OQPPPPPPPPPPQO.",
    ".OQQQPPPPPPQQQO.",
    "..OQQQQQQQQQQO..",
    "...OOOOOOOOOO...",
    "................",
  ],
  // ---- SpaceZ HQ (level 1) --------------------------------------------------
  // The night shift. All five staff share one 12px-wide figure (head rows
  // 1-4, torso 5-9, legs 10-12) so the crowd reads as coworkers; frames
  // alternate the leg stride exactly like the player's.
  // INTERN — gray hoodie, jeans, perpetually underslept.
  intern_0: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OvVvvvvvvO...",
    "..OvvVvvvvvvvO..",
    "..OvvVvvvvVvvO..",
    "..OpOvvvvvvOpO..",
    "...OvvvvvvvvO...",
    "...OjjO..OjjO...",
    "...OjjO..OjjO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  intern_1: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OvVvvvvvvO...",
    "..OvvVvvvvvvvO..",
    "..OvvVvvvvVvvO..",
    "..OpOvvvvvvOpO..",
    "...OvvvvvvvvO...",
    "..OjjO....OjjO..",
    "..OjjO....OjjO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // LAB SCIENTIST — white coat, gray hair, glasses.
  scientist_0: [
    "................",
    ".....OOOOO......",
    "....OWWWWWWO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OWWWjjWWWO...",
    "..OWWWWjjWWWWO..",
    "..OWWwWWWWwWWO..",
    "..OpOWWWWWWOpO..",
    "...OWwWWWWwWO...",
    "...ObbO..ObbO...",
    "...ObbO..ObbO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  scientist_1: [
    "................",
    ".....OOOOO......",
    "....OWWWWWWO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OWWWjjWWWO...",
    "..OWWWWjjWWWWO..",
    "..OWWwWWWWwWWO..",
    "..OpOWWWWWWOpO..",
    "...OWwWWWWwWO...",
    "..ObbO....ObbO..",
    "..ObbO....ObbO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // PROPULSION ENGINEER — gold hard hat, hi-vis vest over gray overalls.
  engineer_0: [
    "................",
    ".....OOOOO......",
    "....OyYyyyyO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OovvvvvvoO...",
    "..OoovvvvvvooO..",
    "..OoovqqqvvooO..",
    "..OpOvvvvvvOpO..",
    "...OvvvqqvvvO...",
    "...ObbO..ObbO...",
    "...ObbO..ObbO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  engineer_1: [
    "................",
    ".....OOOOO......",
    "....OyYyyyyO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OovvvvvvoO...",
    "..OoovvvvvvooO..",
    "..OoovqqqvvooO..",
    "..OpOvvvvvvOpO..",
    "...OvvvqqvvvO...",
    "..ObbO....ObbO..",
    "..ObbO....ObbO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // SECURITY GUARD — navy uniform, cap, gold badge. The fast one.
  guard_0: [
    "................",
    ".....OOOOO......",
    "....OJJJJJJO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OJJjjjjJJO...",
    "..OJJJjjjjJJJO..",
    "..OJJjjyjjjJJO..",
    "..OpOjjjjjjOpO..",
    "...OJJjjjjJJO...",
    "...OJJO..OJJO...",
    "...OJJO..OJJO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  guard_1: [
    "................",
    ".....OOOOO......",
    "....OJJJJJJO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OJJjjjjJJO...",
    "..OJJJjjjjJJJO..",
    "..OJJjjyjjjJJO..",
    "..OpOjjjjjjOpO..",
    "...OJJjjjjJJO...",
    "..OJJO....OJJO..",
    "..OJJO....OJJO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // HAZMAT TECH — sealed yellow suit, cyan visor slit. The slow tank.
  hazmat_0: [
    "................",
    ".....OOOOO......",
    "....OhhhhhhO....",
    "....OhcccchO....",
    "....OhhhhhhO....",
    "...OhhhhhhhhO...",
    "..OhhHhhhhHhhO..",
    "..OhhHhhhhHhhO..",
    "..OhOhhhhhhOhO..",
    "...OhHhhhhHhO...",
    "...OhhO..OhhO...",
    "...OHHO..OHHO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  hazmat_1: [
    "................",
    ".....OOOOO......",
    "....OhhhhhhO....",
    "....OhcccchO....",
    "....OhhhhhhO....",
    "...OhhhhhhhhO...",
    "..OhhHhhhhHhhO..",
    "..OhhHhhhhHhhO..",
    "..OhOhhhhhhOhO..",
    "...OhHhhhhHhO...",
    "..OhhO....OhhO..",
    "..OHHO....OHHO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // ---- SpaceZ HQ weapons & gear icons (12×12) -------------------------------
  icon_stapler: STAPLER_ICON,
  icon_golden_stapler: swapPalette(STAPLER_ICON, { r: "y", a: "o", A: "q" }),
  // A gray slab of keys — the IT department's last stand.
  icon_keyboard: [
    "............",
    "............",
    "............",
    ".OOOOOOOOOO.",
    ".OvvvvvvvvO.",
    ".OvTvTvTvvO.",
    ".OvTvTvTvvO.",
    ".OvvTTTTvvO.",
    ".ObbbbbbbbO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
  ],
  // The janitor's mop: long handle, stringy head.
  icon_mop: [
    "............",
    ".........OO.",
    "........OkO.",
    ".......OkO..",
    "......OkO...",
    ".....OkO....",
    "....OkO.....",
    "..OOkOO.....",
    ".OWWWWWO....",
    ".OWwWwWO....",
    ".OWOWOWO....",
    "............",
  ],
  // Red cylinder, white label, hose nozzle up top.
  icon_extinguisher: [
    "............",
    "....OaO.....",
    "...OOOOO....",
    "..OrrrrrO...",
    "..OrWWrrO...",
    "..OrWWrrO...",
    "..OrrrrrO...",
    "..OrrrrrO...",
    "..OrrrrqO...",
    "...OOOO.....",
    "............",
    "............",
  ],
  // Security-issue taser: yellow body, twin prongs.
  icon_taser: [
    "............",
    "...aa..aa...",
    "...Oa..aO...",
    "..OOOOOOO...",
    "..OhhhhhO...",
    "..OhHhhhO...",
    "..OhhhhhO...",
    "...OhhhO....",
    "...OhhhO....",
    "...OOOOO....",
    "............",
    "............",
  ],
  // A pen light with a hot red dot on the far wall.
  icon_laser_pointer: [
    "............",
    ".rr.........",
    ".rr.........",
    "....OO......",
    "...ObbO.....",
    "....ObbO....",
    ".....ObbO...",
    "......ObbO..",
    ".......ObO..",
    "........O...",
    "............",
    "............",
  ],
  // Something unlabeled from the lab shelf, glowing faintly green.
  icon_beaker: [
    "............",
    "...OxxO.....",
    "....xx......",
    "....xx......",
    "...OxxO.....",
    "..OxxxxO....",
    ".OxnnnnxO...",
    ".OnnnnnnO...",
    ".OnnnnnnO...",
    "..OOOOOO....",
    "............",
    "............",
  ],
  // The guard's baton: dark shaft, wooden grip.
  icon_baton: [
    "............",
    ".........OO.",
    "........ObO.",
    ".......ObO..",
    "......ObO...",
    ".....ObO....",
    "....ObO.....",
    "...OkO......",
    "..OkO.......",
    "..OO........",
    "............",
    "............",
  ],
  // Cleanroom tooling rated for rocket hulls — MUSKRAT's toothpick.
  icon_plasma_cutter: [
    "..........cc",
    ".........cWc",
    "........cWWc",
    ".......cWWc.",
    ".....OvvWc..",
    "....OvvO....",
    "...OvvO.....",
    "..OkkO......",
    ".OkkO.......",
    ".OO.........",
    "............",
    "............",
  ],
  // White coat over a blue shirt — the LAB COAT suit gear.
  icon_lab_coat: [
    "............",
    "..OOOOOOOO..",
    ".OWWWOOWWWO.",
    ".OWWOjjOWWO.",
    ".OWWWWWWWWO.",
    ".OwWWWWWWwO.",
    ".OwWWWWWWwO.",
    "..OWWWWWWO..",
    "..OwwwwwwO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // The ID BADGE charm: photo, smudged name, gold clip.
  icon_badge: [
    "............",
    "....OyO.....",
    "..OOOOOOOO..",
    ".OWWWWWWWWO.",
    ".OWppOwwwWO.",
    ".OWppOwwwWO.",
    ".OWWWWWWWWO.",
    ".OWwwwwWWWO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
    "............",
  ],
  // ---- SpaceZ HQ projectiles (8×8) ------------------------------------------
  // The stapler's staple: a flying silver U.
  staple: [
    "........",
    "........",
    ".OOOOOO.",
    ".OaaaaO.",
    ".OaOOaO.",
    ".OO..OO.",
    "........",
    "........",
  ],
  // The taser's arc: a hot yellow spark.
  zap: [
    "........",
    "....OO..",
    "...OyyO.",
    "..OyyO..",
    "...OyyO.",
    "..OyO...",
    "..OO....",
    "........",
  ],
  // The laser pointer's dot: red rim, white-hot core.
  ray: [
    "........",
    "...OO...",
    "..OrrO..",
    ".OrWWrO.",
    ".OrWWrO.",
    "..OrrO..",
    "...OO...",
    "........",
  ],
  // The thrown beaker, mid-flight, sloshing green.
  vial: [
    "........",
    "...OO...",
    "..OxxO..",
    "..OxxO..",
    ".OxnnxO.",
    ".OnnnnO.",
    "..OOOO..",
    "........",
  ],
  // ---- SpaceZ HQ floor tiles (16×16) ----------------------------------------
  // Polished lab tiles with a seam along the top/left edge — every tile
  // carries the same seam, so the grid pattern is continuous when tiled.
  lab_0: [
    "ssssssssssssssss",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttTtttttt",
    "sttttttttttttttt",
    "stttTttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttstt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "stttttTttttttttt",
    "sttttttttttttttt",
    "stttttttttttTttt",
    "sttttttttttttttt",
    "sttstttttttttttt",
    "sttttttttttttttt",
  ],
  lab_1: [
    "ssssssssssssssss",
    "sttttttttttttttt",
    "stttttttttttTttt",
    "sttttttttttttttt",
    "sttttssttttttttt",
    "stttsstttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttssttt",
    "stttttttttsstttt",
    "sttttttttttttttt",
    "stTttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttTtttt",
    "sttttttttttttttt",
  ],
  // The "gravel" analogs: a floor vent grate and a hazard-striped patch,
  // clustering on the coarse grid exactly like the moon's scree.
  vent_0: [
    "ssssssssssssssss",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "stttOOOOOOOOtttt",
    "stttObbbbbbOtttt",
    "stttOvvvvvvOtttt",
    "stttObbbbbbOtttt",
    "stttOvvvvvvOtttt",
    "stttObbbbbbOtttt",
    "stttOvvvvvvOtttt",
    "stttObbbbbbOtttt",
    "stttOOOOOOOOtttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
  ],
  // The second grate variant: same inset, slats running the other way, so
  // patch clusters read as one field of server-room floor grating.
  vent_1: [
    "ssssssssssssssss",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "stttOOOOOOOOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttOOOOOOOOtttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
  ],
  // ---- SpaceZ HQ obstacles --------------------------------------------------
  // One wall block: chained every 16 px by the engine's wall segments, the
  // shared edge outline reads as steel paneling.
  wall: [
    "OOOOOOOOOOOOOOOO",
    "OVVVVVVVVVVVVVVO",
    "OVvvvvvvvvvvvvVO",
    "OvvvvvvvvvvvvvvO",
    "OvvvvvvvvvvvvvvO",
    "OvbvvvvvvvvvvbvO",
    "OvvvvvvvvvvvvvvO",
    "OvvvvvvvvvvvvvvO",
    "OvvvvvvvvvvvvvvO",
    "OvvvvvvvvvvvvvvO",
    "OvbvvvvvvvvvvbvO",
    "OvvvvvvvvvvvvvvO",
    "OvvvvvvvvvvvvvvO",
    "ObbbbbbbbbbbbbbO",
    "ObbbbbbbbbbbbbbO",
    "OOOOOOOOOOOOOOOO",
  ],
  // A server rack, blinkenlights and all. Blocks outright.
  server: [
    "....OOOOOOOO....",
    "...ObbbbbbbbO...",
    "...ObvvvvvvbO...",
    "...ObcbbbbrbO...",
    "...ObvvvvvvbO...",
    "...ObbbbbbbbO...",
    "...ObvvvvvvbO...",
    "...ObrbbbbcbO...",
    "...ObvvvvvvbO...",
    "...ObbbbbbbbO...",
    "...ObvvvvvvbO...",
    "...ObcbbbbcbO...",
    "...ObvvvvvvbO...",
    "...ObbbbbbbbO...",
    "....OOOOOOOO....",
    "................",
  ],
  // The vending machine Ada never got to. Blocks outright.
  vending: [
    "...OOOOOOOOO....",
    "..OrrrrrrrrrO...",
    "..OrWWWWWWrrO...",
    "..OrWxxxxWrrO...",
    "..OrWxxxxWrrO...",
    "..OrWxxxxWrrO...",
    "..OrWWWWWWrrO...",
    "..OrrrrrrrrrO...",
    "..OrrOOOOrrrO...",
    "..OrrrrrrrrrO...",
    "..ObbbbbbbbbO...",
    "...OOOOOOOOO....",
    "................",
    "................",
    "................",
    "................",
  ],
  // An office desk, monitor still on. Low — hop it.
  desk: [
    "......OOOO..........",
    "......OxxO..........",
    "......ObbO..........",
    ".OOOOOOOOOOOOOOOOOO.",
    ".OTTTTTTTTTTTTTTTTO.",
    ".OttttttttttttttttO.",
    ".OssssssssssssssssO.",
    ".ObbO..........ObbO.",
    ".ObbO..........ObbO.",
    ".OOOO..........OOOO.",
    "....................",
    "....................",
  ],
  // A shipping crate of rocket parts. Low — hop it.
  crate: [
    "..............",
    ".OOOOOOOOOOOO.",
    ".OooooOOooooO.",
    ".OooooqqooooO.",
    ".OqqqqqqqqqqO.",
    ".OooooqqooooO.",
    ".OooooqqooooO.",
    ".OqqqqqqqqqqO.",
    ".OOOOOOOOOOOO.",
    "..............",
    "..............",
    "..............",
  ],
  // ---- SpaceZ HQ landmarks --------------------------------------------------
  // The lobby's glass double door — where the run begins.
  entrance: [
    "................................",
    "....OOOOOOOOOOOOOOOOOOOOOOOO....",
    "...OVVVVVVVVVVVVVVVVVVVVVVVVO...",
    "...OVrrrrVVVVVVVVVVVVrrrrrVVO...",
    "...OVVVVVVVVVVVVVVVVVVVVVVVVO...",
    "...OVOOOOOOOOOOOOOOOOOOOOOOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxOxxOOxxOxxxxxxOVO...",
    "...OVOxxxxxxOxxOOxxOxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVObbbbbbbbbOObbbbbbbbbOVO...",
    "...OVOOOOOOOOOOOOOOOOOOOOOOVO...",
    "...OVVVVVVVVVVVVVVVVVVVVVVVVO...",
    "....OOOOOOOOOOOOOOOOOOOOOOOO....",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  // The prototype rocket MUSKRAT nests under — the reason we're here.
  rocket: [
    "................................",
    "..............OOOO..............",
    ".............OrrrrO.............",
    "............OrrrrrrO............",
    "...........OrrrrrrrrO...........",
    "...........OaaaaaaaaO...........",
    "..........OaaaaaaaaaaO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaOOOOaaAO..........",
    "..........OaaOxxxxOaAO..........",
    "..........OaaOxxxxOaAO..........",
    "..........OaaaOOOOaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaOOOOaaAO..........",
    "..........OaaOxxxxOaAO..........",
    "..........OaaOxxxxOaAO..........",
    "..........OaaaOOOOaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    ".........OraaaaaaaaaArO.........",
    "........OrraaaaaaaaaArrO........",
    ".......OrrraaaaaaaaaArrrO.......",
    "......OrrrraaaaaaaaaArrrrO......",
    "......OrrraaaaaaaaaaArrrO.......",
    "......OrrOaaaaaaaaaaAOrrO.......",
    "......OOO.OAAAAAAAAAO.OOO.......",
    "...........ObbObbO..............",
    "..........ObbO.ObbO.............",
    ".........ObbO...ObbO............",
    "........OOOOO...OOOOO...........",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  // ---- SpaceZ HQ decor (no collision) ---------------------------------------
  // Scattered printouts nobody will ever file again.
  papers: [
    "............",
    "..WWW..W....",
    "..WwW.WWW...",
    "..WWW.WwW...",
    "......WWW...",
    ".WW.........",
    ".WWw........",
    "............",
  ],
  // A cable run taped to the floor.
  cable: [
    "..............",
    ".bb...bbb.....",
    "..bb.bb.bb.bb.",
    "...bbb...bbb..",
    "..............",
  ],
  // Something green leaked out of the lab. It moves if you stare.
  stain: [
    "............",
    "....nn......",
    "...nnnn.nn..",
    "..nnnnnnnn..",
    "...nnnnnn...",
    ".nn..nnn....",
    ".nn...nn....",
    "............",
  ],
  // The obligatory office plant, thriving on neglect.
  plant: [
    "............",
    "...G.GG.G...",
    "...GGllGG...",
    "..GGlGGlGG..",
    "..GgGGGGgG..",
    "...GgGGgG...",
    "....OkkO....",
    "....OkkO....",
    "...OkkkkO...",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // ---- The prelude: living-room props ---------------------------------------
  // The couch our hero holds down for the whole scene.
  couch: [
    "....................................",
    ".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..",
    ".OBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBO..",
    ".OBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBO..",
    ".OBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBO..",
    ".OBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBO..",
    ".OBBSSSSSSSSSSSSSSSSSSSSSSSSSSBBBO..",
    ".OBBOOOOOOOOOOOOOOOOOOOOOOOOOOBBBO..",
    ".OBBOSSSSSSSSSOSSSSSSSSOSSSSSOBBBO..",
    ".OBBOSSSSSSSSSOSSSSSSSSOSSSSSOBBBO..",
    ".OBBOSSSSSSSSSOSSSSSSSSOSSSSSOBBBO..",
    ".OBBOEEEEEEEEEOEEEEEEEEOEEEEEOBBBO..",
    ".OBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBO..",
    ".OEBBBBBBBBBBBBBBBBBBBBBBBBBBBBEEO..",
    ".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...",
    "..OkkO..........................OkkO",
    "..OkkO..........................OkkO",
    "....................................",
    "....................................",
    "....................................",
  ],
  // The TV, mid-movie, lighting the room.
  tv: [
    "........................",
    "..OOOOOOOOOOOOOOOOOOOO..",
    ".ObbbbbbbbbbbbbbbbbbbbO.",
    ".ObOOOOOOOOOOOOOOOOOObO.",
    ".ObOxxxxxxxxxxxxxxxxObO.",
    ".ObOxxxxxxccccxxxxxxObO.",
    ".ObOxxxcccccccccxxxxObO.",
    ".ObOxxxxxcccxxxxxxxxObO.",
    ".ObOxxxxxxxxxxxxxxxxObO.",
    ".ObOOOOOOOOOOOOOOOOOObO.",
    ".ObbbbbbbbbbbbbbbbbbbbO.",
    "..OOOOOOOOOOOOOOOOOOOO..",
    "........ObbbbO..........",
    "......ObbbbbbbbO........",
    "......OOOOOOOOOO........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // The coffee table. Conspicuously chipless. Sodaless too.
  table: [
    "....................",
    "..OOOOOOOOOOOOOOOO..",
    ".OBBBBBBBBBBBBBBBBO.",
    ".OEEEEEEEEEEEEEEEEO.",
    "..OEEO........OEEO..",
    "..OEEO........OEEO..",
    "..OOOO........OOOO..",
    "....................",
    "....................",
    "....................",
  ],
  // A floor lamp doing its best.
  lamp: [
    "..........",
    "...OOOO...",
    "..OyyyyO..",
    ".OyyYyyyO.",
    ".OyyyyyyO.",
    ".OOOOOOOO.",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "...OObO...",
    "..ObbbbO..",
    "..OOOOOO..",
    "..........",
    "..........",
  ],
  // The front door. Last seen closing.
  door: [
    "..................",
    ".OOOOOOOOOOOOOOOO.",
    ".OVVVVVVVVVVVVVVO.",
    ".OVOOOOOOOOOOOOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEBBBByBEBOVO.",
    ".OVOBEBBBByBEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOOOOOOOOOOOOVO.",
    ".OVVVVVVVVVVVVVVO.",
    ".OOOOOOOOOOOOOOOO.",
    "..................",
    "..................",
  ],
  // The window: night outside, and — wait for it — the moon.
  window: [
    "....................",
    ".OOOOOOOOOOOOOOOOOO.",
    ".OVVVVVVVVVVVVVVVVO.",
    ".OVOOOOOOOOOOOOOOVO.",
    ".OVOJJJJJJJJJffJOVO.",
    ".OVOJJJWJJJJffffOVO.",
    ".OVOJJJJJJJJffffOVO.",
    ".OVOJWJJJJJJJffJOVO.",
    ".OVOJJJJJWJJJJJJOVO.",
    ".OVOJJJJJJJJJJJJOVO.",
    ".OVOJJJJJJJJWJJJOVO.",
    ".OVOJJJJJJJJJJJJOVO.",
    ".OVOOOOOOOOOOOOOOVO.",
    ".OVVVVVVVVVVVVVVVVO.",
    ".OOOOOOOOOOOOOOOOOO.",
    "....................",
  ],
  // ---- The prelude: the cast ------------------------------------------------
  // ADA — red jacket (the one with the beacon in it), off to the store.
  ada_0: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OkppppkO....",
    "...OrrrrrrrrO...",
    "..OrrrWWrrrrrO..",
    "..OrrrWWrrrrrO..",
    "..OpOrrrrrrOpO..",
    "...OrrrrrrrrO...",
    "...OjjO..OjjO...",
    "...OjjO..OjjO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  ada_1: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OkppppkO....",
    "...OrrrrrrrrO...",
    "..OrrrWWrrrrrO..",
    "..OrrrWWrrrrrO..",
    "..OpOrrrrrrOpO..",
    "...OrrrrrrrrO...",
    "..OjjO....OjjO..",
    "..OjjO....OjjO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // Our hero, couch mode: white tee, knees up, movie face. Frame 1 blinks
  // with the TV light.
  hero_couch_0: [
    "................",
    "................",
    "......OOOOO.....",
    ".....OkkkkkO....",
    ".....OpOpppO....",
    ".....OppppkO....",
    ".....OWWWWWO....",
    "....OWWWWWWWO...",
    "....OWWWWWWWO...",
    "...OjjjjOWWWO...",
    "..OjjjjjjWWWO...",
    "..OjjOOjjOOO....",
    "..OOO..OOO......",
    "................",
    "................",
    "................",
  ],
  hero_couch_1: [
    "................",
    "................",
    "......OOOOO.....",
    ".....OkkkkkO....",
    ".....OpppppO....",
    ".....OppppkO....",
    ".....OWWWWWO....",
    "....OWWWWWWWO...",
    "....OWWWWWWWO...",
    "...OjjjjOWWWO...",
    "..OjjjjjjWWWO...",
    "..OjjOOjjOOO....",
    "..OOO..OOO......",
    "................",
    "................",
    "................",
  ],
  // MUSKRAT — the boss: a mutant rat the size of a golf cart, nesting
  // under the prototype rocket with the drive ingredient in his belly.
  // 48x48, generated from ellipse primitives then tuned by hand.
  muskrat_0: [
    "................................................",
    "................................................",
    "................................................",
    "...........OOOOO.................OOOOO..........",
    "..........OBBBBBO...............OBBBBBO.........",
    ".........OBBBBBBBO.............OBBBBBBBO........",
    "........OBBBBBBBBBO...........OBBBBBBBBBO.......",
    ".......OBBBBBpBBBBBO.O.......OBBBBBpBBBBBO......",
    ".......OBBBpppppBBBOOSOOOOOO.OBBBpppppBBBO......",
    ".......OBBBpppppBSSSSSSSSSBBOOBBBpppppBBBO......",
    ".......OBBpppppSSSSSSSSSSSSSBBBBpppppppBBO......",
    ".......OBBBpppSSSSSSSBBBBBBBSBBBBpppppBBBO......",
    "........OBBppSSSSSSBBBBBBBBBBBBBBpppppBBO.......",
    ".........OBBBSSSOOBBBBBBBBBBBBOOBBBpBBBO........",
    "..........OBBSSSBBOOBBBBBBBBOOBBBBBBBBO.........",
    "...........OSSSSBRRRRBBBBBBBRRRRBBBOOO..........",
    "............OSSBBRRRRBBBBBBBRRRRBBBBO...........",
    "............OSSBBRRRRBBBBBBBRRRRBBBBO...........",
    "............OSSBBBBBBBBBBBBBBBBBBBBBO...........",
    "............OBSBBBBBBBSSSSSBBBBBBBBBO...........",
    "............OBBBBBBBSSSpppSSSBBBBBBBO...........",
    "............OSSBBBBSSSpppppSSSBBBBBO............",
    "...........OSSSSBBBSSSSpppSSSSBBBBBO............",
    "..........OSSSSSBBBSSSSSSSSSSSBBBBO.......OOO...",
    ".........OSSSSSSSBBSSSSSSSSSSSBBBBBO.....OpppO..",
    "........OSSSSSSBBBBBSSWWOWWSSBBBBBBBO....OpppO..",
    "........OSSSSSBBBBBBBBWWOWWBBBBBBBBBBO...OppppO.",
    "........OSSSSBBBBBBBBBWWOWWBBBBBBBBBBBO...OpppO.",
    ".......OSSSSBBBBBBBBBBWWOWWBBBBBBBBBBBBO..OppppO",
    "........OSSSBBBBBBBBBBBBBBBBBBBBnnnBBBBO...OpppO",
    "........OSSBBBBBBBBBBBBBBBBBBBBnnnnnBBBBO..OpppO",
    "........OSSBBnnnBBBBBBBBBBBBBBBBnnnBBBBBO..OpppO",
    "........OBSBnnnnnBBBBBBBBBBBBBBBBBBBBBBBO.OppppO",
    "........OBBBnnnnnBBBBBBBBBBBBBBBBBBBBBBBO.OpppO.",
    "........OBBBnnnnnBBBBBBBBBEBBBBBBBBBBBBBOOppppO.",
    "........OBBBBnnnBBBEEEEEEEEEEEEEEEBBBBBBOOpppO..",
    "........OBBBBBBBBEEEEEEEEEEEEEEEEEEEBBBBpppppO..",
    ".........OBBBBBEEEEEEEEEEEEnnnEEEEEEEEpppppOO...",
    ".........OBBBBEEEEEEEEEEEEEnnnEEEEEEEEpppppO....",
    "..........OBBBEEEEEEEEEEEEEnnnEEEEEEEEpppOO.....",
    "...........OBEEEEEEEEEEEEEEEEEEEEEEEEEEEO.......",
    "............OBBBBBEEEEEEEEEEEEEBBBBBEEEO........",
    "...........OBBBBBBBEEEEEEEEEEEBBBBBBBEEO........",
    "..........OBBBBBBBBBEEEEEEEEEBBBBBBBBBO.........",
    "...........OBBBBBBBEEEEEEEEEEEBBBBBBBO..........",
    "............OpBpBpOEEEEEEEEEEEEpBpBpO...........",
    ".............OOOOO.OOOOOOOEOOOOOOOOO............",
    "..........................O.....................",
  ],
  muskrat_1: [
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "...........OOOOO.................OOOOO..........",
    "..........OBBBBBO...............OBBBBBO.........",
    ".........OBBBBBBBO.............OBBBBBBBO........",
    "........OBBBBBBBBBO..O........OBBBBBBBBBO.......",
    ".......OBBBBBpBBBBBOOSOOOOOO.OBBBBBpBBBBBO......",
    ".......OBBBpppppBSSSSSSSSSBBOOBBBpppppBBBO......",
    ".......OBBBppppSSSSSSSSSSSSSBBBBBpppppBBBO......",
    ".......OBBppppSSSSSSSBBBBBBBSBBBpppppppBBO......",
    ".......OBBBppSSSSSSBBBBBBBBBBBBBBpppppBBBO......",
    "........OBBppSSSOOBBBBBBBBBBBBOOBBppppBBO.......",
    ".........OBBBSSSBBOOBBBBBBBBOOBBBBBpBBBO........",
    "..........OBSSSSBRRRRBBBBBBBRRRRBBBBBBO.........",
    "...........OOSSBBRRRRBBBBBBBRRRRBBBBOO..........",
    "............OSSBBRRRRBBBBBBBRRRRBBBBO...........",
    "............OSSBBBBBBBBBBBBBBBBBBBBBO...........",
    "............OBSBBBBBBBSSSSSBBBBBBBBBO.....OOO...",
    "............OBBBBBBBSSSpppSSSBBBBBBBO....OpppO..",
    "............OSSBBBBSSSpppppSSSBBBBBO.....OpppOO.",
    "...........OSSSSBBBSSSSpppSSSSBBBBBO.....OpppppO",
    "..........OSSSSSBBBSSSSSSSSSSSBBBBO.......OOpppO",
    ".........OSSSSSSSBBSSSSSSSSSSSBBBBBO.......OpppO",
    "........OSSSSSSBBBBBSSWWOWWSSBBBBBBBO.......Oppp",
    "........OSSSSSBBBBBBBBWWOWWBBBBBBBBBBO......Oppp",
    "........OSSSSBBBBBBBBBWWOWWBBBBBBBBBBBO.....Oppp",
    ".......OSSSSBBBBBBBBBBWWOWWBBBBBBBBBBBBO....Oppp",
    "........OSSSBBBBBBBBBBBBBBBBBBBBnnnBBBBO....Oppp",
    "........OSSBBBBBBBBBBBBBBBBBBBBnnnnnBBBBO...Oppp",
    "........OSSBBnnnBBBBBBBBBBBBBBBBnnnBBBBBO..OpppO",
    "........OBSBnnnnnBBBBBBBBBBBBBBBBBBBBBBBO.OOpppO",
    "........OBBBnnnnnBBBBBBBBBBBBBBBBBBBBBBBOOpppppO",
    "........OBBBnnnnnBBBBBBBBBEBBBBBBBBBBBBBOOpppOO.",
    "........OBBBBnnnBBBEEEEEEEEEEEEEEEBBBBBBpppppO..",
    "........OBBBBBBBBEEEEEEEEEEEEEEEEEEEBBBBpppOO...",
    ".........OBBBBBEEEEEEEEEEEEnnnEEEEEEEEpppppO....",
    ".........OBBBBEEEEEEEEEEEEEnnnEEEEEEEEpppOO.....",
    "..........OBBBEEEEEEEEEEEEEnnnEEEEEEEEpppO......",
    "...........OBEEEEEEEEEEEEEEEEEEEEEEEEEEEO.......",
    "............OBBBBBEEEEEEEEEEEEEBBBBBEEEO........",
    "...........OBBBBBBBEEEEEEEEEEEBBBBBBBEEO........",
    "..........OBBBBBBBBBEEEEEEEEEBBBBBBBBBO.........",
    "...........OBBBBBBBEEEEEEEEEEEBBBBBBBO..........",
    "............OpBpBpOEEEEEEEEEEEEpBpBpO...........",
    ".............OOOOO.OOOOOOOEOOOOOOOOO............",
    "..........................O.....................",
  ],
};
