// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Source of truth for every in-game pixel sprite (see the `pixel-assets`
// skill). One string per pixel row, one character per pixel; `.` is
// transparent and every other character must exist in PALETTE. Edit these
// grids, then run generate-assets.mjs and LOOK at the previews.
//
// Colors are organized as ramps (asset-tools/palette.mjs): each subject has
// a base color and derives its shade/highlight programmatically, so a whole
// character or biome can be re-themed by changing one base value — and
// palette variants (elite enemies, new level biomes) are a `swapPalette`
// call away instead of a redraw.

import { buildPalette, ramp, shade, tint } from "./asset-tools/palette.mjs";

// ---- Subjects -------------------------------------------------------------

const OUTLINE = [26, 28, 44]; // dark navy, not pure black; also eyes/mouths

/** The astronaut hero: white EVA suit, gold visor. */
const ASTRO = {
  suit: ramp([214, 220, 228], { shadeBy: 0.34 }),
  visor: [255, 176, 46], // shares the bolt gold
};

/**
 * The moon's haunting, one translucency-baked ramp per tier (4th channel =
 * alpha). Wisps are faint, ghosts solid, wraiths violet with hot red eyes,
 * and ARMSTRONG — the boss — a pale green revenant.
 */
const WISP = { base: [205, 232, 240, 185], dark: [148, 188, 199, 185] };
const GHOST = {
  base: [140, 205, 215, 225],
  dark: [91, 133, 140, 225],
  light: [197, 230, 235, 225],
};
const WRAITH = {
  base: [165, 125, 225, 230],
  dark: [100, 70, 150, 230],
  eyes: [255, 82, 82],
};
const BOSS = { base: [185, 230, 205, 240], dark: [115, 160, 135, 240] };

const SLIME = ramp([176, 92, 220], { shadeBy: 0.35, tintBy: 0.45 });

const MEDKIT_COLORS = { white: [244, 244, 244], red: [216, 58, 58] };

/** The moon biome floor — retheme the whole moonscape from this base. */
const MOON = ramp([136, 138, 150], { shadeBy: 0.24, tintBy: 0.22 });
const MOON_PIT = shade([136, 138, 150], 0.43); // crater floors

/** Landmark accents: the flag's canton and the lander's gold foil. */
const FLAG_BLUE = [64, 84, 188];
const LANDER_GOLD = ramp([214, 168, 66], { shadeBy: 0.3 });

const WOOD = [52, 44, 38]; // wand handles and other grips

/** The (future) earth biome ground. */
const GRASS = ramp([74, 122, 62], { shadeBy: 0.18, tintBy: 0.16 });
const DIRT = [104, 84, 56];

/** Shared palette: char → RGBA. Light source is top-left. */
export const PALETTE = buildPalette(
  { O: OUTLINE },
  { a: ASTRO.suit.base, A: ASTRO.suit.dark },
  { y: ASTRO.visor, Y: tint(ASTRO.visor, 0.65) },
  { u: WISP.base, U: WISP.dark },
  { c: GHOST.base, C: GHOST.dark, x: GHOST.light },
  { m: WRAITH.base, M: WRAITH.dark, R: WRAITH.eyes },
  { n: BOSS.base, N: BOSS.dark },
  { P: SLIME.base, Q: SLIME.dark, L: SLIME.light },
  {
    W: MEDKIT_COLORS.white,
    w: shade(MEDKIT_COLORS.white, 0.19),
    r: MEDKIT_COLORS.red,
  },
  { f: MOON.base, F: MOON.light, d: MOON.dark, e: MOON_PIT },
  { j: FLAG_BLUE },
  { o: LANDER_GOLD.base, q: LANDER_GOLD.dark },
  { k: WOOD },
  { z: [12, 14, 22, 110] }, // soft jump shadow
  { G: GRASS.base, g: GRASS.dark, l: GRASS.light, D: DIRT },
);

// ---- Animations -----------------------------------------------------------

/** Frame sequences the generator turns into film strips + animated previews. */
export const ANIMATIONS = {
  player_walk: { frames: ["player_0", "player_1"], delayMs: 160 },
  wisp_float: { frames: ["wisp_0", "wisp_1"], delayMs: 340 },
  ghost_float: { frames: ["ghost_0", "ghost_1"], delayMs: 300 },
  wraith_float: { frames: ["wraith_0", "wraith_1"], delayMs: 240 },
  armstrong_loom: { frames: ["armstrong_0", "armstrong_1"], delayMs: 420 },
  slime_bounce: { frames: ["slime_0", "slime_1"], delayMs: 280 },
};

// ---- Sprites --------------------------------------------------------------

/**
 * Sprite grids. Animation frames are separate entries named `<sprite>_<n>`.
 * Sizes: characters/enemies 16×16 (the boss 48×48), projectiles 8×8, icons
 * 12×12, medkit 12×12, tiles 16×16, lander 32×32, flag 16×24.
 */
export const SPRITES = {
  // The hero: an astronaut in a white EVA suit, 3/4 top-down.
  // Frames 0/1 alternate the leg stride; player_jump tucks the legs.
  player_0: [
    "................",
    ".....OOOOOO.....",
    "....OaaaaaaO....",
    "...OaaaaaaaaO...",
    "...OaOYyyyOaO...",
    "...OaOyyyyOaO...",
    "....OaaaaaaO....",
    "...OOaaaaaaOO...",
    "..OaaaaaaaaaaO..",
    "..OAaaarraaaAO..",
    "..OWOaaaaaaOWO..",
    "...OAAAAAAAAO...",
    "...OaaO..OaaO...",
    "...OAAO..OAAO...",
    "...OOOO..OOOO...",
    "................",
  ],
  player_1: [
    "................",
    ".....OOOOOO.....",
    "....OaaaaaaO....",
    "...OaaaaaaaaO...",
    "...OaOYyyyOaO...",
    "...OaOyyyyOaO...",
    "....OaaaaaaO....",
    "...OOaaaaaaOO...",
    "..OaaaaaaaaaaO..",
    "..OAaaarraaaAO..",
    "..OWOaaaaaaOWO..",
    "...OAAAAAAAAO...",
    "..OaaO....OaaO..",
    "..OAAO....OAAO..",
    "..OOOO....OOOO..",
    "................",
  ],
  player_jump: [
    "................",
    ".....OOOOOO.....",
    "....OaaaaaaO....",
    "...OaaaaaaaaO...",
    "...OaOYyyyOaO...",
    "...OaOyyyyOaO...",
    "....OaaaaaaO....",
    "...OOaaaaaaOO...",
    "..OaaaaaaaaaaO..",
    "..OAaaarraaaAO..",
    "..OWOaaaaaaOWO..",
    "...OAAAAAAAAO...",
    "...OaaO..OaaO...",
    "...OOOO..OOOO...",
    "................",
    "................",
  ],
  // WISP — the faintest haunting, found near the landing site.
  wisp_0: [
    "................",
    "................",
    "......OOOO......",
    ".....OuuuuO.....",
    "....OuuuuuuO....",
    "....OuOuuOuO....",
    "....OuuuuuuO....",
    "....OUuuuuUO....",
    ".....OuuuUO.....",
    "......OuUO......",
    ".......OO.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  wisp_1: [
    "................",
    "................",
    "................",
    "......OOOO......",
    ".....OuuuuO.....",
    "....OuOuuOuO....",
    "....OuuuuuuO....",
    "....OUuuuuUO....",
    ".....OUuuuO.....",
    "......OUuO......",
    ".......OO.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  // MOON GHOST — the classic sheet, mid-difficulty band.
  ghost_0: [
    "................",
    ".....OOOOOO.....",
    "....OxxccccO....",
    "...OxcccccccO...",
    "...OcOccccOcO...",
    "...OccccccccO...",
    "..OccccOOccccO..",
    "..OccccccccccO..",
    "..OccccccccccO..",
    "..OCccccccccCO..",
    "..OCcOccccOcCO..",
    "...OCO.OO.OCO...",
    "................",
    "................",
    "................",
    "................",
  ],
  ghost_1: [
    "................",
    "................",
    ".....OOOOOO.....",
    "....OxxccccO....",
    "...OxcccccccO...",
    "...OcOccccOcO...",
    "...OccccccccO...",
    "..OccccOOccccO..",
    "..OccccccccccO..",
    "..OccccccccccO..",
    "..OCccccccccCO..",
    "..OCcOccccOcCO..",
    "...OCO.OO.OCO...",
    "................",
    "................",
    "................",
  ],
  // WRAITH — fast, hooded, red-eyed; prowls the far side.
  wraith_0: [
    "......OOOO......",
    ".....OmmmmO.....",
    "....OmmmmmmO....",
    "....OmRmmRmO....",
    "....OmmmmmmO....",
    "...OmmmMMmmmO...",
    "...OmmmmmmmmO...",
    "..OmmMmmmmMmmO..",
    "..OmmmmmmmmmmO..",
    "..OMmmmmmmmmMO..",
    "..OMmMmmmmMmMO..",
    "...OMOMmmMOMO...",
    "....O.OMMO.O....",
    ".......OO.......",
    "................",
    "................",
  ],
  wraith_1: [
    "......OOOO......",
    ".....OmmmmO.....",
    "....OmmmmmmO....",
    "....OmRmmRmO....",
    "....OmmmmmmO....",
    "...OmmMMmmmmO...",
    "...OmmmmmmmmO...",
    "..OmmMmmmmMmmO..",
    "..OmmmmmmmmmmO..",
    "..OMmmmmmmmmMO..",
    "..OMmMmmmmMmMO..",
    "...OMOMmmMOMO...",
    "....O..OMMO.O...",
    "........OO......",
    "................",
    "................",
  ],
  // ARMSTRONG — the boss: a giant astronaut ghost with ENORMOUS arms,
  // haunting the flag he planted. 48×48, generated-then-tuned by hand.
  armstrong_0: [
    "................................................",
    "................................................",
    "....................OOOOOOOO....................",
    "..................OOnnnnnnnnOO..................",
    ".................OWWWWnnnnnnnnO.................",
    "................OnnnnnnOOnnnnnnO................",
    "...............OnnnOOOOOOOOOOnnnO...............",
    "..............OnnnOOOOOOOOOOOOnnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "...............OnnOOOOOOOOOOOOnnO...............",
    "................OnnOOOOOOOOOOnnO................",
    "...........OOOOOnnnnnnnOOnnnnnnnOOOOO...........",
    "........OOOnnnnnnnnnnnnnnnnnnnnnnnnnnOOO........",
    "......OOnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnOO......",
    ".....OnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnO.....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnNnnnnnnnnnnnnnnnnnnNnnNnnnnnnnO...",
    "...OnnnnnnnNOnNnnnnnnnnnnnnnnnnnnNnONnnnnnnnO...",
    "...OnnnnnnnO.ONNnnnnnnnnnnnnnnnnNNO.OnnnnnnnO...",
    "...OnnnnnnnO.ONNNnnnnnnnnnnnnnnNNNO.OnnnnnnnO...",
    "...OnnnnnnnO..ONNNnnnnnnnnnnnnNNNO..OnnnnnnnO...",
    "..OnnnnnnnnnO.OnnnnnnnnnnnnnnnnnnO.OnnnnnnnnnO..",
    "..OnnnnnnnnnO..OnnnnnnnnnnnnnnnnO..OnnnnnnnnnO..",
    ".OnnnnnnnnnnnO..OnnnnnnnnnnnnnnO..OnnnnnnnnnnnO.",
    "..OnnnnnnnnnO...OnnnnnnnnnnnnnnO...OnnnnnnnnnO..",
    "..OnNNNNNNnnO..OnnnnnnnnnnnnnnnnO..OnNNNNNNnnO..",
    "...OnnnnnnnO....OnnnnnnnnnnnnnnO....OnnnnnnnO...",
    "...OOnnnnnOO....OnnnnnnnnnnnnnnO....OOnnnnnOO...",
    ".....OOOOO.......OnnnnnnnnnnnnO.......OOOOO.....",
    "...............OOnnnnnnnnnnnnnnOO...............",
    "..............OnnnnOOOnnnOOOOnnnnO..............",
    "..............OnnnO...OnO....OnnnO..............",
    "..............OnnnO..OnnnO...OnnnO..............",
    "...............OOO...OnnnO....OOO...............",
    ".....................OnnnO......................",
    "......................OOO.......................",
  ],
  armstrong_1: [
    "................................................",
    "................................................",
    "....................OOOOOOOO....................",
    "..................OOnnnnnnnnOO..................",
    ".................OWWWWnnnnnnnnO.................",
    "................OnnnnnnOOnnnnnnO................",
    "...............OnnnOOOOOOOOOOnnnO...............",
    "..............OnnnOOOOOOOOOOOOnnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "...............OnnOOOOOOOOOOOOnnO...............",
    "................OnnOOOOOOOOOOnnO................",
    "...........OOOOOnnnnnnnOOnnnnnnnOOOOO...........",
    "......OOOOOnnnnnnnnnnnnnnnnnnnnnnnnnnOOOOO......",
    ".....OnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnO.....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnNnnnnnnnnnnnnnnnnnnNnnNnnnnnnnO...",
    "...OnnnnnnnNOnNnnnnnnnnnnnnnnnnnnNnONnnnnnnnO...",
    "...OnnnnnnnO.ONNnnnnnnnnnnnnnnnnNNO.OnnnnnnnO...",
    "..OnnnnnnnnnOONNNnnnnnnnnnnnnnnNNNOOnnnnnnnnnO..",
    "..OnnnnnnnnnO.ONNNnnnnnnnnnnnnNNNO.OnnnnnnnnnO..",
    ".OnnnnnnnnnnnOOnnnnnnnnnnnnnnnnnnOOnnnnnnnnnnnO.",
    "..OnnnnnnnnnO..OnnnnnnnnnnnnnnnnO..OnnnnnnnnnO..",
    "..OnNNNNNNnnO...OnnnnnnnnnnnnnnO...OnNNNNNNnnO..",
    "...OnnnnnnnO....OnnnnnnnnnnnnnnO....OnnnnnnnO...",
    "...OOnnnnnOO...OnnnnnnnnnnnnnnnnO...OOnnnnnOO...",
    ".....OOOOO......OnnnnnnnnnnnnnnO......OOOOO.....",
    "................OnnnnnnnnnnnnnnO................",
    ".................OnnnnnnnnnnnnO.................",
    "...............OOnnnnnnnnnnnnnnOO...............",
    "..............OnnnnOOOOnnnOOOnnnnO..............",
    "..............OnnnO....OnO...OnnnO..............",
    "..............OnnnO...OnnnO..OnnnO..............",
    "...............OOO....OnnnO...OOO...............",
    "......................OnnnO.....................",
    ".......................OOO......................",
  ],
  // Landmarks: the ship at the landing site and the old flag.
  lander: [
    "................................",
    "..................AA............",
    "..................A.............",
    "............OOOOOOOO............",
    "............OaaaaaaO............",
    "............OaaaaaaO............",
    "..........OOaaaaaaaaOO..........",
    "..........OaaOOOaaaaAO..........",
    "..........OaaOOOaAAAAO..........",
    "..........OaaOOOaAAAAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    ".......OOOooooooooooooOOO.......",
    ".......OooooooooooooooqqO.......",
    ".......OqooqooqooqooqoqqO.......",
    ".......OooooooooooooooqqO.......",
    ".......OoqooqooqooqooqqqO.......",
    ".......OooooooooooooooqqO.......",
    ".......OooooooooooooooqqO.......",
    ".......OqqqqqqqqqqqqqqqqO.......",
    ".......OOOOOOOqqqqOOOOOOO.......",
    "......OO......OAAO......OO......",
    ".....OO.......OAAO.......OO.....",
    "....OO.......OOOOOO.......OO....",
    "...OO......................OO...",
    ".OOOOO....................OOOOO.",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  flag: [
    "................",
    "...OO...........",
    "...OAOOOOOOOOOO.",
    "...OAOjjjjjrrrO.",
    "...OAOjWjjjrrrO.",
    "...OAOjjjjjWWWO.",
    "...OAOjjjjjWWWO.",
    "...OAOrrrrrrrrO.",
    "...OAOWWWWWWWWO.",
    "...OAOrrrrrrrrO.",
    "...OAOOOOOOOOOO.",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "..OOAOO.........",
    "................",
  ],
  // Moonscape decor: craters and strewn rocks (no collision).
  crater_big: [
    "................................",
    "................................",
    "................................",
    "................................",
    "..............dddd..............",
    "..........FFdddddddddd..........",
    ".......FFFFdddddddddddddd.......",
    "......FFFFd.eeeeeeee.ddddd......",
    ".....FFFFeeeeeeeeeeeeeedddd.....",
    "....FFF.eeeeee....eeeeee.ddd....",
    "...FFFeeeee..........eeeeeddd...",
    "..FFFFeee..............eeedddd..",
    "..FFFeeee..............eeeeddd..",
    ".FFFeeee................eeeeddd.",
    ".FFdeee..................eeeddd.",
    ".Fddeee..................eeeddd.",
    ".dddeee..................eeeddd.",
    ".dddeee..................eeeddd.",
    ".dddeeee................eeeeddd.",
    "..dddeeee..............eeeeddd..",
    "..ddddeee..............eeedddd..",
    "...dddeeeee..........eeeeeddd...",
    "....ddd.eeeeee....eeeeee.ddd....",
    ".....ddddeeeeeeeeeeeeeedddd.....",
    "......ddddd.eeeeeeee.ddddd......",
    ".......dddddddddddddddddd.......",
    "..........dddddddddddd..........",
    "..............dddd..............",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  crater_small: [
    "................",
    "................",
    "......Fddd......",
    "...FFFddddddd...",
    "..FFF.eeee.ddd..",
    ".FF.eeeeeeee.dd.",
    ".FFee......eedd.",
    ".F.ee......ee.d.",
    ".d.ee......ee.d.",
    ".ddee......eedd.",
    ".dd.eeeeeeee.dd.",
    "..ddd.eeee.ddd..",
    "...dddddddddd...",
    "......dddd......",
    "................",
    "................",
  ],
  rocks: [
    "................",
    "................",
    "................",
    "...eeee.........",
    "..edddde........",
    "...eeee.........",
    "..........eeee..",
    "..........edde..",
    "..........eeee..",
    "................",
    "................",
    ".....eee........",
    ".....eee........",
    "................",
    "................",
    "................",
  ],
  // Ground tiles. Keep edges featureless so they tile without seams;
  // moon_1 carries a small pock, gravel_* are the scree patches.
  moon_0: [
    "ffffffffffffffff",
    "fffffffffffffdff",
    "ffFfffffffffFfff",
    "fffffffffffdffff",
    "ffffffffffffffff",
    "ffffffffffFfffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
    "fffffdffffffffff",
    "ffffffffffffffff",
    "fffffffffffddfff",
    "ffffffffffdfffff",
    "fffFffffffffffff",
    "fffffffffffffdff",
    "ffffffffffffffff",
    "ffffffffffffffff",
  ],
  moon_1: [
    "ffffffffffffffff",
    "fdFfffffffffffff",
    "ffffffffffffdfff",
    "fffffffFffffffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
    "fffffffddfffffff",
    "ffffffdeedffffff",
    "ffffffdeedffffdf",
    "fffffffddfffffff",
    "ffffFfffffffffff",
    "fffdffffffffffff",
    "ffffffffffffffff",
    "ffffffffdfffffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
  ],
  gravel_0: [
    "ffffffffffffffff",
    "ffffffffFfffffff",
    "fffffFffffffffff",
    "fffffddFffffffff",
    "fffffdFfdfffffff",
    "ffFffffddfffffff",
    "ffddffffffffffff",
    "ffddffffffffffff",
    "ffffffffffedfeff",
    "fffffffffffffddf",
    "ffffffFffffffFff",
    "ffedffddffFfffff",
    "ffddffdfffffffff",
    "fffffedfddfFffff",
    "fFffffffdfffffff",
    "ffffffffffffffff",
  ],
  gravel_1: [
    "ffffffffffffffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
    "ffffffFffffFffff",
    "ffffffddfffedfff",
    "fffffffFffFdffff",
    "ffffffffffeeffff",
    "ffffffffffFddfff",
    "fffffffffFfddfff",
    "ffffffffffffedff",
    "ffffffffffFfddff",
    "ffffffffffffFfff",
    "ffffffFffffffFff",
    "fffffffdffffffdf",
    "ffffffddffffffdf",
    "ffffffffffffffff",
  ],
  // Projectiles: the blaster bolt and the wand spark.
  bolt: [
    "........",
    "...OO...",
    "..OyyO..",
    ".OyYYyO.",
    ".OyYYyO.",
    "..OyyO..",
    "...OO...",
    "........",
  ],
  spark: [
    "........",
    "...OO...",
    "..OLLO..",
    ".OLPPLO.",
    ".OLPPLO.",
    "..OLLO..",
    "...OO...",
    "........",
  ],
  // The FIRE ORBS ability's orbiting fireball: red rim, white-hot core.
  fireball: [
    "........",
    "...OO...",
    "..OrrO..",
    ".OrYYrO.",
    ".OrYYrO.",
    "..OrrO..",
    "...OO...",
    "........",
  ],
  // The medkit consumable.
  medkit: [
    "............",
    ".OOOOOOOOOO.",
    ".OWWWWWWWWO.",
    ".OWWWrrWWWO.",
    ".OWWWrrWWWO.",
    ".OWrrrrrrWO.",
    ".OWrrrrrrWO.",
    ".OWWWrrWWWO.",
    ".OWWWrrWWWO.",
    ".OwwwwwwwwO.",
    ".OOOOOOOOOO.",
    "............",
  ],
  // ARMSTRONG's Apollo survival-kit machete: broad steel blade, wood grip.
  icon_machete: [
    "............",
    ".......OOO..",
    "......OaaO..",
    ".....OaaAO..",
    "....OaaAO...",
    "...OaaAO....",
    "..OaaAO.....",
    ".OaaAO......",
    ".OaAO.......",
    "OkkO........",
    "OkkO........",
    ".OO.........",
  ],
  // The MOON'S BLADE trophy: a pale spectral blade, ghost-lit.
  icon_moons_blade: [
    "............",
    ".......OOO..",
    "......OxxO..",
    ".....OxxcO..",
    "....OxxcO...",
    "...OxxcO....",
    "..OxxcO.....",
    ".OxxcO......",
    ".OxcO.......",
    "OkkO........",
    "OkkO........",
    ".OO.........",
  ],
  // The weapon-upgrade pickup: a golden up arrow.
  upgrade: [
    "............",
    ".....OO.....",
    "....OyyO....",
    "...OyYyyO...",
    "..OyYyyyyO..",
    ".OyYyyyyyyO.",
    ".OOOOyyOOOO.",
    "....OyyO....",
    "....OyyO....",
    "....OyyO....",
    "....OOOO....",
    "............",
  ],
  // Soft blob shadow under the player while jumping.
  shadow: ["...zzzzzz...", ".zzzzzzzzzz.", ".zzzzzzzzzz.", "...zzzzzz..."],
  // Inventory icons, 12×12.
  icon_blaster: [
    "............",
    "............",
    ".OOOOOOOOO..",
    ".OAAAAAAAyO.",
    ".OAAAAAAAyO.",
    ".OOOOAAOOO..",
    "....OAAO....",
    "....OAAO....",
    "....OOOO....",
    "............",
    "............",
    "............",
  ],
  icon_wand: [
    "............",
    "........OO..",
    ".......OLLO.",
    "......OLPPO.",
    "......OPPO..",
    ".....OkkO...",
    "....OkkO....",
    "...OkkO.....",
    "..OkkO......",
    "..OkO.......",
    "...O........",
    "............",
  ],
  icon_wrench: [
    "............",
    ".OO....OO...",
    ".OAO..OAO...",
    ".OAAOOAAO...",
    "..OAAAAO....",
    "...OAAO.....",
    "....OAAO....",
    ".....OAAO...",
    "......OAAO..",
    ".......OAO..",
    "........O...",
    "............",
  ],
  icon_suit: [
    "............",
    "..OOOOOOOO..",
    ".OaaaaaaaaO.",
    ".OaaOrrOaaO.",
    ".OaaaaaaaaO.",
    ".OAaaaaaaAO.",
    ".OAaaaaaaAO.",
    "..OaaaaaaO..",
    "..OAAAAAAO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  icon_charm: [
    "............",
    "....OOOO....",
    "...OFFFFO...",
    "..OFFOOOO...",
    "..OFO.......",
    "..OFO.......",
    "..OFO.......",
    "..OFFOOOO...",
    "...OFFFFO...",
    "....OOOO....",
    "............",
    "............",
  ],
  // The simple base-type weapons (Diablo-style unnamed drops).
  // A length of scavenged conduit: dull steel, flanged ends.
  icon_pipe: [
    "............",
    "........OO..",
    ".......OaaO.",
    "......OaaAO.",
    ".....OaaAO..",
    "....OaaAO...",
    "...OaaAO....",
    "..OaaAO.....",
    ".OaaAO......",
    ".OaAO.......",
    "..OO........",
    "............",
  ],
  // A geologist's sledge: heavy steel head, wooden haft.
  icon_hammer: [
    "............",
    "..OOOOOOO...",
    ".OaaaaaaAO..",
    ".OaaaaaaAO..",
    ".OAAAAAAAO..",
    "..OOOkOOO...",
    ".....OkO....",
    ".....OkO....",
    ".....OkO....",
    ".....OkO....",
    "......O.....",
    "............",
  ],
  // A compact sidearm: shorter and duller than the hero's blaster.
  icon_pistol: [
    "............",
    "............",
    "..OOOOOO....",
    "..OaaaaAO...",
    "..OOOaaO....",
    "....OaAO....",
    "....OaAO....",
    "....OOO.....",
    "............",
    "............",
    "............",
    "............",
  ],
  // A long-barreled rifle with a wooden stock.
  icon_rifle: [
    "............",
    ".........OO.",
    "........OaO.",
    ".......OaO..",
    "......OaO...",
    ".....OaO....",
    "....OaO.....",
    "...OkkO.....",
    "..OkkO......",
    "..OkO.......",
    "...O........",
    "............",
  ],
  // A wand crowned with a golden star.
  icon_star_wand: [
    "............",
    ".....OyO....",
    "....OyYyO...",
    ".....OyO....",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    ".OO.........",
    "............",
    "............",
  ],
  // A wand bearing a violet void orb.
  icon_void_wand: [
    "............",
    ".....OO.....",
    "....OmmO....",
    "....OmMO....",
    ".....OO.....",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    "..O.........",
    "............",
  ],
  // Ability pickups: time-limited powers.
  // FIRE ORBS: three fireballs mid-orbit.
  icon_fire_orbs: [
    "............",
    "....OO......",
    "...OrYO.....",
    "....OO......",
    "............",
    ".OO.....OO..",
    "OrYO...OrYO.",
    ".OO.....OO..",
    "............",
    "............",
    "............",
    "............",
  ],
  // STORM CELL: a jagged golden bolt.
  icon_storm: [
    "............",
    "......OOO...",
    ".....OyyO...",
    "....OyyO....",
    "...OyyOO....",
    "..OyyyyO....",
    "...OOyyO....",
    "....OyyO....",
    "...OyyO.....",
    "...OyO......",
    "...OO.......",
    "............",
  ],
  // STASIS FIELD: a pale ring holding still around a speck of astronaut.
  icon_stasis: [
    "............",
    "....xxxx....",
    "..xx....xx..",
    ".x........x.",
    ".x........x.",
    "x....aa....x",
    "x....aa....x",
    ".x........x.",
    ".x........x.",
    "..xx....xx..",
    "....xxxx....",
    "............",
  ],
  // Earth biome tiles + the slime, parked for level 1 (the NASA heist).
  grass_0: [
    "GGGGGGGGGGGGGGGG",
    "GGlGGGGGGGGGgGGG",
    "GGlGGGGgGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GgGGGGGGGGlGGGGG",
    "GGGGGGGGGGlGGGGG",
    "GGGGlGGGGGGGgGGG",
    "GGGGlGGGGgGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GlGGGGGGGGGGGDGG",
    "GlGGGGgGGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GGGGGGGGGGlGGGGG",
    "GGgGGGGGGGlGGGGG",
    "GGGGGGGDGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
  ],
  grass_1: [
    "GGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGlGGGG",
    "GGgGGGGGGGGlGGGG",
    "GGGGGGGGGGGGGGGG",
    "GGGGGGlGGGGGGgGG",
    "GGGGGGlGGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GDGGGGGGGgGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GGGGGgGGGGGGlGGG",
    "GGGGGGGGGGGGlGGG",
    "GWyWGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGG",
    "GGGGGGGGgGGGGGGG",
    "GGGGGGGGGGGGGgGG",
    "GGGGGGGGGGGGGGGG",
  ],
  slime_0: [
    "................",
    "................",
    "................",
    "................",
    ".....OOOOOO.....",
    "....OLLPPPPO....",
    "...OLPPPPPPPO...",
    "..OLPPPPPPPPPO..",
    "..OPPOPPPPOPPO..",
    "..OPPOPPPPOPPO..",
    "..OPPPPOOPPPPO..",
    "..OQPPPPPPPPQO..",
    "..OQQPPPPPPQQO..",
    "...OQQQQQQQQO...",
    "....OOOOOOOO....",
    "................",
  ],
  slime_1: [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....OOOOOOOO....",
    "..OOLLPPPPPPOO..",
    ".OLPPPPPPPPPPPO.",
    ".OPPOPPPPPPOPPO.",
    ".OPPPPOOOOPPPPO.",
    ".OQPPPPPPPPPPQO.",
    ".OQQQPPPPPPQQQO.",
    "..OQQQQQQQQQQO..",
    "...OOOOOOOOOO...",
    "................",
  ],
};
