#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The MAP BLUEPRINT pipeline — the "v2" level format's compile step. Compiles
// the YAML blueprint tree (`content/maps/*.yaml`) into the engine's
// `MapBlueprint` catalog, the recipe half of the GENERATED MAPS feature. It:
//   1. harvests the live catalogs the blueprints cross-reference (enemies, the
//      compiled level ids, the sprite stems, the ladder's ramp names) plus the
//      engine's own compass-region parser, so a typo fails the build here rather
//      than carving a broken map at runtime,
//   2. loads + schema-validates every blueprint, expanding its `ramp` names
//      against `content/ladder.yaml` exactly as the level pipeline does,
//   3. writes src/generated/map-blueprints.ts (GENERATED_MAP_BLUEPRINTS, read by
//      src/game/mapgen/index.ts).
// The output is gitignored and regenerated on every build (like the level
// catalog and the sprite atlas), so the YAML is the single source of truth.
//
// It must run AFTER generate-levels (it cross-refs the compiled level ids) and
// after generate-enemies (it cross-refs the roster).

import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { register } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";

// Engine modules under src/lib use the @game/lib alias at runtime — map it so
// the def catalogs and the mapgen leaf import cleanly under plain node.
register("./game-alias-loader.mjs", import.meta.url);

import { validateMap } from "./asset-tools/map-schema.mjs";
import { loadLadder } from "./level-data/ladder.mjs";
import { loadMaps } from "./map-data/load-yaml.mjs";

const engine = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));

// Import the catalogs DIRECTLY (never @game/core — that pulls the mapgen
// registry, which imports the file we are about to write: a bootstrap cycle).
const { ENEMY_DEFS } = await import(
  pathToFileURL(engine("src/game/defs/enemies/index.ts")).href
);
const { STORY_ITEM_DEFS } = await import(
  pathToFileURL(engine("src/game/defs/story.ts")).href
);
const { GENERATED_LEVELS } = await import(
  pathToFileURL(engine("src/generated/levels.ts")).href
);
// The region grammar comes from the engine itself — one parser, so the gate here
// accepts exactly the names `generate.ts` can resolve. `regions.ts` is a leaf
// with no imports, so this drags nothing along.
const { parseRegion } = await import(
  pathToFileURL(engine("src/game/mapgen/regions.ts")).href
);

// ---- Sprite stems (content/sprites/<family>/<name>.yaml, stem == sprite id;
// underscore-prefixed files are family/core preambles, not sprites). ----------
const spritesDir = engine("content/sprites");
const sprites = new Set();
for (const family of readdirSync(spritesDir, { withFileTypes: true })) {
  if (!family.isDirectory()) continue;
  for (const file of readdirSync(`${spritesDir}/${family.name}`)) {
    if (!file.endsWith(".yaml") || file.startsWith("_")) continue;
    sprites.add(file.slice(0, -".yaml".length));
  }
}

const { ramps } = loadLadder();

const refs = {
  enemies: new Set(Object.keys(ENEMY_DEFS)),
  // A BYSTANDER must actually be a bystander: a mob the blueprint stands on the
  // map as an errand's non-combatant, but which fights back, is a quest that
  // dead-ends the first time the hero swings near it.
  neutrals: new Set(
    Object.entries(ENEMY_DEFS)
      .filter(([, d]) => d.disposition === "neutral")
      .map(([id]) => id),
  ),
  levels: new Set(GENERATED_LEVELS.map((l) => l.id)),
  sprites,
  ramps: new Set(Object.keys(ramps)),
  // Every door a story item is the key to — what a blueprint's `locks` list may
  // name, so a sealed room always has a key somebody carries.
  doorKeys: new Set(
    Object.values(STORY_ITEM_DEFS)
      .map((d) => d.unlocks)
      .filter(Boolean),
  ),
  parseRegion,
};

const { entries } = loadMaps();

const errors = [];
const warnings = [];
for (const { raw, description } of entries) {
  const res = validateMap(raw, refs, description);
  errors.push(...res.errors);
  warnings.push(...res.warnings);
}
for (const w of warnings) console.warn(`! ${w}`);
if (errors.length > 0) {
  console.error(
    `${errors.length} map schema error(s):\n  ${errors.join("\n  ")}`,
  );
  process.exit(1);
}

const blueprints = entries.map((e) => e.blueprint);

const banner = `// @generated by scripts/generate-maps.mjs — DO NOT EDIT.
// Source of truth: content/maps/*.yaml + content/ladder.yaml. Regenerate with
// \`npm run levels\` (also runs inside \`npm run assets\` / \`make assets\`).
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0`;

const out = `${banner}
import type { MapBlueprint } from "../game/mapgen/types.ts";

/** Every mission that ships a GENERATED MAPS blueprint (see src/game/mapgen). */
export const GENERATED_MAP_BLUEPRINTS: MapBlueprint[] = ${JSON.stringify(blueprints, null, 2)} as unknown as MapBlueprint[];
`;

const destDir = engine("src/generated");
mkdirSync(destDir, { recursive: true });
writeFileSync(`${destDir}/map-blueprints.ts`, out);
console.log(
  `wrote src/generated/map-blueprints.ts — ${blueprints.length} map blueprint(s)`,
);
