#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The level pipeline (see the `level-design` skill). Compiles the YAML level
// tree (`scripts/levels/*.yaml`) into the engine's LevelDef catalog —
// the map/atlas equivalent for levels. It:
//   1. harvests the live def-id catalogs from the engine (enemies, weapons,
//      gear, abilities, thoughts, story items, uniques) for cross-ref checks,
//   2. loads + schema-validates every YAML level (a bad id fails the build),
//   3. writes src/generated/levels.ts — GENERATED_LEVELS plus the campaign /
//      secret order arrays that src/game/defs/levels/index.ts reads.
// The output is gitignored and regenerated on every build (like the sprite
// atlas), so the YAML is the single source of truth.

import { mkdirSync, writeFileSync } from "node:fs";
import { register } from "node:module";
import { fileURLToPath } from "node:url";

// Engine modules under src/lib use the @game/lib alias at runtime — map it so
// the def catalogs import cleanly under plain node.
register("./game-alias-loader.mjs", import.meta.url);

import { validateLevel } from "./asset-tools/level-schema.mjs";
import { loadLevels } from "./level-data/load-yaml.mjs";

const engine = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));

// Import the def catalogs DIRECTLY (never @game/core — that pulls the levels
// registry, which imports the file we are about to write: a bootstrap cycle).
const { ENEMY_DEFS } = await import(engine("src/game/defs/enemies/index.ts"));
const { WEAPON_DEFS } = await import(engine("src/game/defs/equipment.ts"));
const { GEAR_DEFS } = await import(engine("src/game/defs/gear.ts"));
const { ABILITY_DEFS } = await import(engine("src/game/defs/abilities.ts"));
const { THOUGHT_DEFS } = await import(engine("src/game/defs/thoughts.ts"));
const { STORY_ITEM_DEFS } = await import(engine("src/game/defs/story.ts"));
const { UNIQUE_DEFS } = await import(engine("src/game/defs/uniques.ts"));
const { WORLD_UNIQUES } = await import(
  engine("src/game/defs/world-uniques.ts")
);

const refs = {
  enemies: new Set(Object.keys(ENEMY_DEFS)),
  // Roles let the pinned-spawn check tell a stationed minion (no authored
  // level/hp — it scales with the map's mob band) from an elite/boss set
  // piece (both required).
  enemyRoles: new Map(
    Object.entries(ENEMY_DEFS).map(([id, d]) => [id, d.role]),
  ),
  weapons: new Set(Object.keys(WEAPON_DEFS)),
  gear: new Set(Object.keys(GEAR_DEFS)),
  abilities: new Set(Object.keys(ABILITY_DEFS)),
  thoughts: new Set(Object.keys(THOUGHT_DEFS)),
  storyItems: new Set(Object.keys(STORY_ITEM_DEFS)),
  uniques: new Set(Object.keys(UNIQUE_DEFS)),
  worldUniques: new Set(WORLD_UNIQUES.map((u) => u.id)),
  doorKeys: new Set(
    Object.values(STORY_ITEM_DEFS)
      .map((s) => s.unlocks)
      .filter(Boolean),
  ),
};

const { entries } = loadLevels();

const errors = [];
const warnings = [];
for (const { def, description } of entries) {
  const res = validateLevel(def, refs, description);
  errors.push(...res.errors);
  warnings.push(...res.warnings);
}
for (const w of warnings) console.warn(`! ${w}`);
if (errors.length > 0) {
  console.error(
    `${errors.length} level schema error(s):\n  ${errors.join("\n  ")}`,
  );
  process.exit(1);
}

// Campaign in story-index order; secret venues after, in file order.
const campaign = entries
  .filter((e) => e.campaign)
  .sort((a, b) => a.def.index - b.def.index);
const secret = entries.filter((e) => e.secret);

const defs = [...campaign, ...secret].map((e) => e.def);
const campaignOrder = campaign.map((e) => e.id);
const secretOrder = secret.map((e) => e.id);

const banner = `// @generated by scripts/generate-levels.mjs — DO NOT EDIT.
// Source of truth: scripts/levels/*.yaml. Regenerate with
// \`npm run levels\` (also runs inside \`npm run assets\` / \`make assets\`).
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0`;

const out = `${banner}
import type { LevelDef } from "../game/defs/levels/types.ts";

export const GENERATED_LEVELS: LevelDef[] = ${JSON.stringify(defs, null, 2)} as unknown as LevelDef[];

export const GENERATED_CAMPAIGN_ORDER: string[] = ${JSON.stringify(campaignOrder)};

export const GENERATED_SECRET_ORDER: string[] = ${JSON.stringify(secretOrder)};
`;

const destDir = engine("src/generated");
mkdirSync(destDir, { recursive: true });
writeFileSync(`${destDir}/levels.ts`, out);
console.log(
  `wrote src/generated/levels.ts — ${defs.length} levels ` +
    `(${campaignOrder.length} campaign, ${secretOrder.length} secret)`,
);
