#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The music pipeline. Compiles `content/music/*.yaml` into the scores the app's
// chiptune player loops, the same way levels, enemies, items and sounds compile.
//
// It emits into `pwa/src/generated/` for the same reason the sounds do: music
// is an APP concern, not an engine one — the engine has no idea a level makes a
// noise, and a score is tens of KB of note data no consumer of `@game/core`
// would ever read.
//
// ONE FILE PER TRACK, not one catalog. A score is a wall of note data and none
// of it is startup: a level's theme is wanted when a run begins, and the title
// theme cannot sound before the player's first gesture unlocks audio. Each
// track therefore keeps its own module, reached through its own `import()` in
// the emitted index — exactly the split the hand-written score files had, which
// is the thing to preserve rather than the files themselves.
//
// Output is gitignored and regenerated on every build, like every other
// compiled catalog — `content/music/` is the source of truth.

import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { validateTrack } from "./asset-tools/music-schema.mjs";
import { cookTrack, loadMusic } from "./music-data/load-yaml.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));

/** The menu's theme. Reserved: a LEVEL may not name it (a run has its own
 * music), and the app asks for it by this id rather than through a level. */
const TITLE_TRACK = "title";

const { entries } = loadMusic();

const errors = [];
const warnings = [];
for (const { doc } of entries) {
  const res = validateTrack(doc);
  errors.push(...res.errors);
  warnings.push(...res.warnings);
}

// The menu's theme is the one id the app names itself, so a build without it
// would fall silent on the title screen with nothing to point at.
if (!entries.some((e) => e.id === TITLE_TRACK)) {
  errors.push(
    `no content/music/${TITLE_TRACK}.yaml — that id is the title screen's ` +
      "theme, and the menu asks for it by name",
  );
}

for (const w of warnings) console.warn(`! ${w}`);
if (errors.length > 0) {
  console.error(
    `${errors.length} music schema error(s):\n  ${errors.join("\n  ")}`,
  );
  process.exit(1);
}

const banner = `// @generated by scripts/generate-music.mjs — DO NOT EDIT.
// Source of truth: content/music/*.yaml. Regenerate with \`npm run levels\`
// (also runs inside \`npm run assets\` / \`make assets\`).
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0`;

const destDir = path.join(root, "pwa", "src", "generated", "music");
mkdirSync(destDir, { recursive: true });
// A retired track would otherwise linger as a stale module the index no longer
// imports — harmless to the build, confusing to everyone reading the tree.
for (const stale of readdirSync(destDir)) {
  rmSync(path.join(destDir, stale));
}

for (const { id, doc } of entries) {
  writeFileSync(
    path.join(destDir, `${id}.ts`),
    `${banner}
import type { ChiptuneTrack } from "../../lib/chiptune.ts";

/** ${doc.name} — its own module, so it is its own chunk. */
export const TRACK: ChiptuneTrack = ${JSON.stringify(cookTrack(doc), null, 2)} as ChiptuneTrack;
`,
  );
}

const loaders = entries
  .map(
    ({ id }) =>
      `  ${JSON.stringify(id)}: () => import("./${id}.ts").then((m) => m.TRACK),`,
  )
  .join("\n");

writeFileSync(
  path.join(destDir, "index.ts"),
  `${banner}
import type { ChiptuneTrack } from "../../lib/chiptune.ts";

/** Every score this build ships, each behind its OWN dynamic import so the
 * browser fetches only the track being asked for. */
export const TRACK_LOADERS: Record<string, () => Promise<ChiptuneTrack>> = {
${loaders}
};

/** The reserved id of the title screen's theme. */
export const TITLE_TRACK = ${JSON.stringify(TITLE_TRACK)};
`,
);

console.log(
  `wrote pwa/src/generated/music/ — ${entries.length} track(s): ` +
    entries
      .map(
        ({ id, doc }) =>
          `${id} (${Object.keys(doc.patterns).length} patterns, ` +
          `${doc.order.length} in order)`,
      )
      .join(", "),
);
