#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The SCRIPT pipeline. Compiles `content/scripts/*.lua` — the authored rules the
// engine hands out to a script instead of keeping in TypeScript — into
// `engine/generated/scripts.ts` (GENERATED_SCRIPTS), which `engine/game/script/host.ts`
// reads as the base catalog under whatever a mod registers on top.
//
// "Compiles" means two different things here, and both matter:
//
//   * the OUTPUT is the source TEXT, not a compiled form. The VM parses at
//     load, once per run, and a chunk is a few hundred nodes; shipping an AST
//     would freeze the interpreter's internal shape into a build artifact for
//     no measurable gain.
//   * the CHECK is a real compile. Every file is parsed and loaded with the
//     game's own VM (`asset-tools/script-schema.mjs`), so a syntax error, a
//     missing `return M`, a typo'd hook name or a hook that is not a function
//     fails `npm run levels` with a file and a line — instead of failing
//     silently at play time, which is what a scripting hook usually does.
//
// It runs FIRST in the chain and imports nothing from the engine except the VM
// and the import-free hook list, so it can never join a bootstrap cycle.
//
//   node scripts/generate-scripts.mjs

import { mkdirSync, writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath } from "node:url";

import {
  validateScript,
  validateScriptCatalog,
} from "./asset-tools/script-schema.mjs";
import { loadScripts } from "./script-data/load-lua.mjs";

const engine = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));

// ---- Load ------------------------------------------------------------------
const { scripts, entries } = loadScripts(engine("content"));

// ---- Validate --------------------------------------------------------------
const errors = [];
const warnings = [];
const implemented = [];
for (const { id, source } of entries) {
  const res = validateScript(id, source, { shipped: true });
  errors.push(...res.errors);
  warnings.push(...res.warnings);
  implemented.push(...res.hooks);
}
{
  const res = validateScriptCatalog(implemented);
  errors.push(...res.errors);
}
for (const w of warnings) console.warn(`! ${w}`);
if (errors.length > 0) {
  console.error(`${errors.length} script error(s):\n  ${errors.join("\n  ")}`);
  process.exit(1);
}

// ---- Emit ------------------------------------------------------------------
const banner = `// @generated by scripts/generate-scripts.mjs — DO NOT EDIT.
// Source of truth: content/scripts/*.lua. Regenerate with
// \`npm run levels\` (also runs inside \`npm run assets\` / \`make assets\`).
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0`;

const out = `${banner}
import type { ScriptSource } from "../game/script/catalog.ts";

/** The shipped rules, by script id. A mod's own \`scripts/<id>.lua\` overrides
 * an entry here for the length of a modded run; \`restoreBaseDefs()\` puts these
 * back. */
export const GENERATED_SCRIPTS: Record<string, ScriptSource> = ${JSON.stringify(
  scripts,
  null,
  2,
)};
`;

const destDir = engine("engine/generated");
mkdirSync(destDir, { recursive: true });
writeFileSync(`${destDir}/scripts.ts`, out);
console.log(
  `wrote engine/generated/scripts.ts — ${entries.length} scripts, ${implemented.length} hooks`,
);
