#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The STORY pipeline. Compiles the three hand-authored catalogs that carry the
// plot — `content/cutscenes/<id>.yaml`, `content/thoughts.yaml` and
// `content/story-items.yaml` — into `engine/generated/cutscenes.ts`,
// `engine/generated/thoughts.ts` and `engine/generated/story-items.ts`, which
// `engine/game/defs/cutscenes.ts`, `defs/thoughts.ts` and `defs/story.ts`
// re-expose as CUTSCENE_DEFS, THOUGHT_DEFS/CAP_THOUGHT_IDS and
// STORY_ITEM_DEFS. It:
//   1. harvests the sprite stems from the content/sprites tree, so a prop,
//      portrait or icon that isn't in the atlas fails the build,
//   2. schema-validates every scene, monologue and plot piece (see
//      asset-tools/story-schema.mjs),
//   3. writes each catalog flat, stamping ids from catalog keys / file stems so
//      the YAML never repeats itself.
// The outputs are gitignored and regenerated on every build (like enemies.ts and
// levels.ts), so the YAML is the single source of truth.
//
//   node scripts/generate-story.mjs
//
// MUST run BEFORE generate-enemies.mjs and generate-levels.mjs: an enemy's
// `loot.storyItems` and a level's `firstKillThoughts` / `prelude` / placed story
// items are cross-referenced against the catalogs this script writes. Like the
// item and powerup pipelines it imports NOTHING from the engine — every ref it
// validates against comes from the content tree — so it can never join a
// bootstrap cycle. (That is also why the difficulty ids a cutscene's `variants:`
// may name are read from `content/ladder.yaml` rather than from
// `defs/difficulties.ts`, which imports the generated level index.)

import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath } from "node:url";

import {
  validateCapRotation,
  validateCutscene,
  validateStoryItem,
  validateThought,
} from "./asset-tools/story-schema.mjs";
import { DIFFICULTY_RUNGS } from "./level-data/ladder.mjs";
import {
  loadCutscenes,
  loadStoryItems,
  loadThoughts,
} from "./story-data/load-yaml.mjs";

const engine = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));

// ---- Sprite stems (content/sprites/<family>/<name>.yaml, stem == sprite id;
// underscore-prefixed files are family/core preambles, not sprites). ----------
const spritesDir = engine("content/sprites");
const sprites = new Set();
for (const family of readdirSync(spritesDir, { withFileTypes: true })) {
  if (!family.isDirectory()) continue;
  for (const file of readdirSync(`${spritesDir}/${family.name}`)) {
    if (!file.endsWith(".yaml") || file.startsWith("_")) continue;
    sprites.add(file.slice(0, -".yaml".length));
  }
}

// ---- Sound ids (content/sounds/<id>.yaml, stem == sound id) — so a `sound`
// beat naming a sound the game does not have fails here rather than playing
// silence in a scene nobody reviews with the volume up. Read from the content
// tree for the same reason the sprite stems are: this generator imports
// nothing from the engine, and must not start.
const soundIds = new Set(
  readdirSync(engine("content/sounds"))
    .filter((f) => f.endsWith(".yaml") && !f.startsWith("_"))
    .map((f) => f.slice(0, -".yaml".length)),
);

const refs = {
  sprites,
  sounds: soundIds,
  difficulties: new Set(DIFFICULTY_RUNGS),
};

// ---- Load ------------------------------------------------------------------
const { cutscenes, entries: sceneEntries } = loadCutscenes(
  engine("content/cutscenes"),
);
const {
  thoughts,
  capRotation,
  entries: thoughtEntries,
} = loadThoughts(engine("content"));
const { storyItems, entries: itemEntries } = loadStoryItems(engine("content"));

// ---- Validate --------------------------------------------------------------
const errors = [];
const warnings = [];
const collect = (res) => {
  errors.push(...res.errors);
  warnings.push(...res.warnings);
};
for (const { doc } of sceneEntries) collect(validateCutscene(doc, refs));
for (const { id, def } of thoughtEntries)
  collect(validateThought(id, def, refs));
for (const { id, def } of itemEntries)
  collect(validateStoryItem(id, def, refs));
collect(validateCapRotation(capRotation, new Set(Object.keys(thoughts))));

for (const w of warnings) console.warn(`! ${w}`);
if (errors.length > 0) {
  console.error(
    `${errors.length} story schema error(s):\n  ${errors.join("\n  ")}`,
  );
  process.exit(1);
}

// ---- Emit ------------------------------------------------------------------
const banner = (
  source,
) => `// @generated by scripts/generate-story.mjs — DO NOT EDIT.
// Source of truth: ${source}. Regenerate with
// \`npm run levels\` (also runs inside \`npm run assets\` / \`make assets\`).
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0`;

const json = (value) => JSON.stringify(value, null, 2);

const destDir = engine("engine/generated");
mkdirSync(destDir, { recursive: true });

writeFileSync(
  `${destDir}/cutscenes.ts`,
  `${banner("content/cutscenes/<id>.yaml")}
import type { CutsceneDef } from "@game/lib/cutscene.ts";

export const GENERATED_CUTSCENES: Record<string, CutsceneDef> = ${json(
    cutscenes,
  )} as unknown as Record<string, CutsceneDef>;
`,
);

writeFileSync(
  `${destDir}/thoughts.ts`,
  `${banner("content/thoughts.yaml")}
import type { ThoughtDef } from "../game/defs/thoughts.ts";

export const GENERATED_THOUGHTS: Record<string, ThoughtDef> = ${json(
    thoughts,
  )} as unknown as Record<string, ThoughtDef>;

/** The cap-farm mutter rotation, in firing order (\`capRotation\`). */
export const GENERATED_CAP_THOUGHTS: readonly string[] = ${json(capRotation)};
`,
);

writeFileSync(
  `${destDir}/story-items.ts`,
  `${banner("content/story-items.yaml")}
import type { StoryItemDef } from "../game/defs/story.ts";

export const GENERATED_STORY_ITEMS: Record<string, StoryItemDef> = ${json(
    storyItems,
  )} as unknown as Record<string, StoryItemDef>;
`,
);

console.log(
  `wrote engine/generated/{cutscenes,thoughts,story-items}.ts — ` +
    `${Object.keys(cutscenes).length} scenes (${sceneEntries.length} authored), ` +
    `${Object.keys(thoughts).length} thoughts, ` +
    `${Object.keys(storyItems).length} story items`,
);
