#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The TALENT pipeline. Compiles `content/talents.yaml` — the hand-authored
// catalog of the three passive trees the hero grows, and the single place their
// balance is tuned — into `engine/generated/talents.ts` (GENERATED_TALENTS), which
// `engine/game/defs/talents/index.ts` re-exposes as TALENT_DEFS. It:
//   1. harvests the sprite stems from the content/sprites tree, so a picker
//      glyph that isn't in the atlas fails the build rather than drawing an
//      unnamed blank card in the one screen the player picks from,
//   2. schema-validates every talent (a missing field, an unknown tree, a slope
//      nothing reads, a proc block with a field no hook looks at — see
//      asset-tools/talent-schema.mjs) plus the one whole-catalog rule (one
//      carrier per proc),
//   3. writes the flat `{ id → TalentDef }` catalog, stamping each def's `id`
//      from its catalog key so the YAML never repeats itself.
// The output is gitignored and regenerated on every build (like powerups.ts and
// levels.ts), so the YAML is the single source of truth.
//
//   node scripts/generate-talents.mjs
//
// Like the item and powerup pipelines it imports NOTHING from the engine except
// the shared rank CEILING (`TALENTS.maxRank` — an import-free config leaf), so
// it can never join a bootstrap cycle. It has no downstream dependents in the
// generator chain: no other catalog cross-references a talent id.

import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  validateTalent,
  validateTalentCatalog,
} from "./asset-tools/talent-schema.mjs";
import { loadTalents } from "./talent-data/load-yaml.mjs";

const engine = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));

// The shared rank ceiling. Imported from the config LEAF directly (never
// @game/core) — it imports nothing, so this stays a leaf-only pipeline.
const { TALENTS } = await import(
  pathToFileURL(engine("engine/game/config/talents.ts")).href
);

// ---- Sprite stems (content/sprites/<family>/<name>.yaml, stem == sprite id;
// underscore-prefixed files are family/core preambles, not sprites). ----------
const spritesDir = engine("content/sprites");
const sprites = new Set();
for (const family of readdirSync(spritesDir, { withFileTypes: true })) {
  if (!family.isDirectory()) continue;
  for (const file of readdirSync(`${spritesDir}/${family.name}`)) {
    if (!file.endsWith(".yaml") || file.startsWith("_")) continue;
    sprites.add(file.slice(0, -".yaml".length));
  }
}

// ---- Load ------------------------------------------------------------------
const { talents, entries } = loadTalents(engine("content"));

// ---- Validate --------------------------------------------------------------
const refs = { sprites, maxRank: TALENTS.maxRank };
const errors = [];
const warnings = [];
for (const { id, def } of entries) {
  const res = validateTalent(id, def, refs);
  errors.push(...res.errors);
  warnings.push(...res.warnings);
}
{
  const res = validateTalentCatalog(talents);
  errors.push(...res.errors);
  warnings.push(...res.warnings);
}
for (const w of warnings) console.warn(`! ${w}`);
if (errors.length > 0) {
  console.error(
    `${errors.length} talent schema error(s):\n  ${errors.join("\n  ")}`,
  );
  process.exit(1);
}

const banner = `// @generated by scripts/generate-talents.mjs — DO NOT EDIT.
// Source of truth: content/talents.yaml. Regenerate with
// \`npm run levels\` (also runs inside \`npm run assets\` / \`make assets\`).
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0`;

const out = `${banner}
import type { TalentDef } from "../game/defs/talents/index.ts";

export const GENERATED_TALENTS: Record<string, TalentDef> = ${JSON.stringify(
  talents,
  null,
  2,
)} as unknown as Record<string, TalentDef>;
`;

const destDir = engine("engine/generated");
mkdirSync(destDir, { recursive: true });
writeFileSync(`${destDir}/talents.ts`, out);
console.log(
  `wrote engine/generated/talents.ts — ${Object.keys(talents).length} talents`,
);
