#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The SET pipeline. Compiles `content/sets.yaml` — the hand-authored kits a
// boss's green armor pieces belong to — into `src/generated/sets.ts`
// (GENERATED_SETS), which `src/game/defs/sets.ts` re-exposes as SET_DEFS. It:
//   1. reads the live UNIQUE catalog, because every check that matters is about
//      the kit holding together: a member that is not `rarity: set`, two head
//      pieces in one kit, a piece claimed by two sets, a piece whose own `setId`
//      points somewhere else,
//   2. schema-validates every set (see asset-tools/set-schema.mjs),
//   3. writes the flat `{ id → SetDef }` catalog, stamping each def's `id` from
//      its catalog key so the YAML never repeats itself.
// The output is gitignored and regenerated on every build (like companions.ts
// and levels.ts), so the YAML is the single source of truth.
//
//   node scripts/generate-sets.mjs
//
// MUST run AFTER generate-items.mjs: the members are uniques, and this reads the
// catalog that script writes.

import { mkdirSync, writeFileSync } from "node:fs";
import { register } from "node:module";
import process from "node:process";
import { fileURLToPath } from "node:url";

// Engine modules under src/lib use the @game/lib alias at runtime — map it so
// the unique catalog imports cleanly under plain node.
register("./game-alias-loader.mjs", import.meta.url);

import { validateSet } from "./asset-tools/set-schema.mjs";
import { loadSets } from "./set-data/load-yaml.mjs";

const engine = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));

// Imported DIRECTLY (never @game/core) so nothing pulls the file we are about
// to write — the same bootstrap rule every other generator follows.
const { UNIQUE_DEFS } = await import(engine("src/game/defs/uniques.ts"));

const { sets, entries } = loadSets(engine("content"));

// The member checks need three fields off each named item; handing the schema a
// Map rather than the catalog keeps it free of the engine's own shapes (a MOD
// compiles with base ∪ mod in the same Map).
const uniques = new Map(
  Object.entries(UNIQUE_DEFS).map(([id, def]) => [
    id,
    { tier: def.tier, slot: def.slot, setId: def.setId },
  ]),
);

const errors = [];
const warnings = [];
for (const { id, def } of entries) {
  const res = validateSet(id, def, { uniques });
  errors.push(...res.errors);
  warnings.push(...res.warnings);
}

// The other direction, which only the SHIPPED build can check: a `rarity: set`
// item that belongs to no kit grants nothing and reads as a bug. (A mod cannot
// be held to this — its set piece may legitimately join a kit the base game
// ships.)
for (const [id, def] of Object.entries(UNIQUE_DEFS)) {
  if (def.tier !== "set") continue;
  if (!entries.some(({ def: set }) => set.members?.includes(id)))
    errors.push(`set item "${id}" belongs to no set in content/sets.yaml`);
}

for (const w of warnings) console.warn(`! ${w}`);
if (errors.length > 0) {
  console.error(
    `${errors.length} set schema error(s):\n  ${errors.join("\n  ")}`,
  );
  process.exit(1);
}

const banner = `// @generated by scripts/generate-sets.mjs — DO NOT EDIT.
// Source of truth: content/sets.yaml. Regenerate with
// \`npm run levels\` (also runs inside \`npm run assets\` / \`make assets\`).
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0`;

const out = `${banner}
import type { SetDef } from "../game/defs/sets.ts";

export const GENERATED_SETS: Record<string, SetDef> = ${JSON.stringify(
  sets,
  null,
  2,
)} as unknown as Record<string, SetDef>;
`;

const destDir = engine("src/generated");
mkdirSync(destDir, { recursive: true });
writeFileSync(`${destDir}/sets.ts`, out);
console.log(`wrote src/generated/sets.ts — ${Object.keys(sets).length} sets`);
