// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The bunker family (see the `pixel-assets` skill): the secret cow level —
// the billionaires' continuity-of-wealth vault. Polished concrete tiles with
// burgundy carpet runs, the torn-open vault gate and the exit blast door,
// the privatized security state (CIA suits, FBI windbreakers, soldiers,
// armed vacuum bots), the six resident ELITES (one per suite — PUTAIN's
// clone is a palette swap of the Eastworld drawing: same man, fresh robe),
// and their personal bodyguards (one drawing, six accent liveries, drawn a
// size up from the crew). One string per pixel row, one character per
// pixel; `.` is transparent and every other char must exist in CORE_PALETTE
// (sprite-data/core.mjs) or this family's local palette.

import { swapPalette } from "../asset-tools/palette.mjs";
import eastworld from "./eastworld.mjs";

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  // The vault floor: polished pale concrete, kept light so the black-suit
  // horde separates. Sheen streaks in near-white.
  z: [186, 188, 198], // floor base
  Z: [156, 158, 172], // floor shade / grout
  u: [216, 218, 228], // floor sheen
  // The money-walk carpet (and DEPARDIEU-grade wine accents).
  X: [150, 60, 70], // carpet burgundy
  D: [96, 40, 48], // carpet dark / aged leather
  // The suits: near-black worsted (matches Eastworld's night-black K by
  // value, so PUTAIN's swapped drawing keeps its shoes and eyes).
  K: [12, 11, 18], // suit black / shades / windows
  N: [58, 56, 70], // suit highlight / gunmetal
  // The military detail's fatigues.
  e: [106, 112, 66], // olive base
  d: [70, 76, 44], // olive dark
  // Accents.
  Q: [92, 210, 255], // scanner cyan: vacuum-bot eye, META livery
  C: [210, 60, 66], // power red: ties, KREMLIN livery, db shards
  U: [120, 235, 140], // aligned green: gpu bolts, ALIGNMENT livery
  t: [238, 152, 88], // DUMP's tan
  s: [234, 210, 186], // SUCKERBERG's screen-lit pale skin
  I: [246, 208, 116], // brass / bullion glint / inlay
};

const SPRITES = {
  // ---- Ground tiles (16×16, edges featureless so they tile) -----------------
  bunker_0: [
    "zzzzzzzzzzzzzzzz",
    "zzzzuzzzzzzzzzzz",
    "zzzzzzzzzzzZzzzz",
    "zzzzzzzzzzzzzzzz",
    "zZzzzzzzzuzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzZzzzzzzuzz",
    "zzzzzzzzzzzzzzzz",
    "zzuzzzzzzzzzzzzz",
    "zzzzzzzzzZzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzZzzzzzzuzzz",
    "zzzzzzzzzzzzzzzz",
    "zuzzzzzzzzzzzzzz",
    "zzzzzzzzzZzzzzzz",
    "zzzzzzzzzzzzzzzz",
  ],
  // The rare tile: a brass inlay medallion — somebody paid for this floor.
  bunker_1: [
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzZZZZzzzzzz",
    "zzzzZZzzzzZZzzzz",
    "zzzZzzzIIzzzZzzz",
    "zzzZzzIIIIzzZzzz",
    "zzZzzIIzzIIzzZzz",
    "zzZzzIzzzzIzzZzz",
    "zzZzzIzzzzIzzZzz",
    "zzZzzIIzzIIzzZzz",
    "zzzZzzIIIIzzZzzz",
    "zzzZzzzIIzzzZzzz",
    "zzzzZZzzzzZZzzzz",
    "zzzzzzZZZZzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
  ],
  // The carpet runs: burgundy pile with a gold thread border.
  carpet_0: [
    "XXXXXXXXXXXXXXXX",
    "XDXXXXXXXXXXXXDX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXDXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXDXXXXXXXXXIXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXDXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXIXXXXXXXXXXXX",
    "XXXXXXXXXXXXDXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXDXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
  ],
  carpet_1: [
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXDXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXIXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXDXX",
    "XXDXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXIXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    "XDXXXXXXXXXXXXXX",
    "XXXXXXXXXXXDXXXX",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
  ],
  // ---- Landmarks ------------------------------------------------------------
  // The torn-open vault gate (also the rift-side portal a used SEVERED HAND
  // summons): a massive steel frame around a black opening, the seam still
  // glowing where the space gave way. Drawn base-anchored.
  bunker_gate: [
    "........................",
    ".......OOOOOOOOOO.......",
    ".....OONNNNNNNNNNOO.....",
    "....ONNNNNNNNNNNNNNO....",
    "...ONNvvvvvvvvvvvvNNO...",
    "...ONvvOOOOOOOOOOvvNO...",
    "...ONvOQKKKKKKKKQOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOQKKKKKKKKQOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOQKKKKKKKKQOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOQKKKKKKKKQOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOQKKKKKKKKQOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOQKKKKKKKKQOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvOQKKKKKKKKQOvNO...",
    "...ONvOKKKKKKKKKKOvNO...",
    "...ONvvOOOOOOOOOOvvNO...",
    "...ONNvvvvvvvvvvvvNNO...",
    "...OONNNNNNNNNNNNNNOO...",
    "....OOOOOOOOOOOOOOOO....",
    "........................",
    "........................",
    "........................",
  ],
  // The service exit: a CLOSED blast door — wheel lock, hazard chevrons,
  // and a brass plaque nobody ever read. The reachExit objective's prop.
  blast_door: [
    "........................",
    ".......OOOOOOOOOO.......",
    ".....OONNNNNNNNNNOO.....",
    "....ONNNNNNNNNNNNNNO....",
    "...ONNvvvvvvvvvvvvNNO...",
    "...ONvVyKyKyKyKyKVvNO...",
    "...ONvVvvvvvvvvvvVvNO...",
    "...ONvVvvvvvvvvvvVvNO...",
    "...ONvVvvvOOOOvvvVvNO...",
    "...ONvVvvOVvvVOvvVvNO...",
    "...ONvVvOVvvvvVOvVvNO...",
    "...ONvVvOvvOOvvOvVvNO...",
    "...ONvVvOvOvvOvOvVvNO...",
    "...ONvVvOvOvvOvOvVvNO...",
    "...ONvVvOvvOOvvOvVvNO...",
    "...ONvVvOVvvvvVOvVvNO...",
    "...ONvVvvOVvvVOvvVvNO...",
    "...ONvVvvvOOOOvvvVvNO...",
    "...ONvVvvvvvvvvvvVvNO...",
    "...ONvVvvIIIIIIvvVvNO...",
    "...ONvVvvIbbbbIvvVvNO...",
    "...ONvVvvIIIIIIvvVvNO...",
    "...ONvVvvvvvvvvvvVvNO...",
    "...ONvVyKyKyKyKyKVvNO...",
    "...ONvvvvvvvvvvvvvvNO...",
    "...ONNbbbbbbbbbbbbNNO...",
    "...OONNNNNNNNNNNNNNOO...",
    "....OOOOOOOOOOOOOOOO....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // ---- Obstacles ------------------------------------------------------------
  // A marble column: solid — sight, shots and blasts stop at it.
  marble_column: [
    "....OOOOOOOO....",
    "...OWWWWWWWWO...",
    "...OWuuuuuuwO...",
    "....OOOOOOOO....",
    ".....OWuuwO.....",
    ".....OWuuwO.....",
    ".....OWuuwO.....",
    ".....OWuuwO.....",
    ".....OWuuwO.....",
    ".....OWuuwO.....",
    ".....OWuuwO.....",
    ".....OWuuwO.....",
    ".....OWuuwO.....",
    ".....OWuuwO.....",
    "....OOOOOOOO....",
    "...OWWWWWWWWO...",
    "...OWuuuuuuwO...",
    "....OOOOOOOO....",
    "................",
    "................",
  ],
  // A pallet of bullion: hoppable — the one fortune nobody carried out.
  gold_pallet: [
    "................",
    "....OOOO.OOOO...",
    "...OIooOOIooO...",
    "..OOOOOOOOOOOO..",
    ".OIooOOIooOOIooO",
    ".OoqoOOoqoOOoqoO",
    ".OOOOOOOOOOOOOO.",
    ".OBBBBOBBOBBBBO.",
    ".OEEEEOEEOEEEEO.",
    "..OOOO.OO.OOOO..",
    "................",
    "................",
  ],
  // ---- Decor ------------------------------------------------------------------
  // Banded stacks of cash, abandoned mid-count. Decor, walk right over it.
  money_pile: [
    "............",
    "...OOOO.....",
    "..OGGGGO....",
    ".OGGWWGGOO..",
    ".OGGGGGGGGO.",
    ".OgGGWWGGgO.",
    ".OggGGGGggO.",
    "..OOOOOOOO..",
  ],
  // ---- Projectiles (8×8) -------------------------------------------------------
  // The soldiers' tracer round.
  rifle_round: [
    "........",
    "........",
    "........",
    "..Oyyw..",
    "........",
    "........",
    "........",
    "........",
  ],
  // ALLISON's shard of weaponized ledger.
  db_shard: [
    "........",
    "...O....",
    "..OCO...",
    ".OCWCO..",
    "..OCO...",
    "...O....",
    "........",
    "........",
  ],
  // HALTMAN's overclocked gpu bolt.
  gpu_bolt: [
    "........",
    "...O....",
    "..OUO...",
    ".OUWUO..",
    "..OUO...",
    "...O....",
    "........",
    "........",
  ],
  // ---- The regular crew (16×16, 2 frames) --------------------------------------
  // CIA AGENT — the fodder rank: black suit, black shades, white collar.
  cia_agent_0: [
    "................",
    ".....OOOO.......",
    "....OKKKKO......",
    "....OppppO......",
    "....OKKKKO......",
    ".....OppO.......",
    "....OKKKKKKO....",
    "...OKKKWWKKKO...",
    "...OKKKCCKKKO...",
    "...OKKKKCKKKO...",
    "...OKKKKKKKKO...",
    "....OKKKKKKO....",
    "....OKK..KKO....",
    "....OKK..KKO....",
    "....OO....OO....",
    "................",
  ],
  cia_agent_1: [
    "................",
    ".....OOOO.......",
    "....OKKKKO......",
    "....OppppO......",
    "....OKKKKO......",
    ".....OppO.......",
    "....OKKKKKKO....",
    "...OKKKWWKKKO...",
    "...OKKKCCKKKO...",
    "...OKKKKCKKKO...",
    "...OKKKKKKKKO...",
    "....OKKKKKKO....",
    "...OKK....KKO...",
    "...OKK....KKO...",
    "...OO......OO...",
    "................",
  ],
  // FBI AGENT — the windbreaker rank: navy jacket, gold chest band, cap.
  fbi_agent_0: [
    "................",
    ".....OOOO.......",
    "....OJJJJO......",
    "....OppppO......",
    "....OpOpOO......",
    ".....OppO.......",
    "....OJJJJJJO....",
    "...OJJJJJJJJO...",
    "...OJyyyyyyJO...",
    "...OJJJJJJJJO...",
    "...OJJJJJJJJO...",
    "....OJJJJJJO....",
    "....OKK..KKO....",
    "....OKK..KKO....",
    "....OO....OO....",
    "................",
  ],
  fbi_agent_1: [
    "................",
    ".....OOOO.......",
    "....OJJJJO......",
    "....OppppO......",
    "....OpOpOO......",
    ".....OppO.......",
    "....OJJJJJJO....",
    "...OJJJJJJJJO...",
    "...OJyyyyyyJO...",
    "...OJJJJJJJJO...",
    "...OJJJJJJJJO...",
    "....OJJJJJJO....",
    "...OKK....KKO...",
    "...OKK....KKO...",
    "...OO......OO...",
    "................",
  ],
  // ICE AGENT — the border detail: black windbreaker, ice-blue chest band,
  // ballcap. Built to detain; faster and grabbier than the suits.
  ice_agent_0: [
    "................",
    ".....OOOO.......",
    "....OKKKKO......",
    "....OppppO......",
    "....OpOpOO......",
    ".....OppO.......",
    "....OKKKKKKO....",
    "...OKKKKKKKKO...",
    "...OKQQQQQQKO...",
    "...OKKKKKKKKO...",
    "...OKKKKKKKKO...",
    "....OKKKKKKO....",
    "....ONN..NNO....",
    "....ONN..NNO....",
    "....OO....OO....",
    "................",
  ],
  ice_agent_1: [
    "................",
    ".....OOOO.......",
    "....OKKKKO......",
    "....OppppO......",
    "....OpOpOO......",
    ".....OppO.......",
    "....OKKKKKKO....",
    "...OKKKKKKKKO...",
    "...OKQQQQQQKO...",
    "...OKKKKKKKKO...",
    "...OKKKKKKKKO...",
    "....OKKKKKKO....",
    "...ONN....NNO...",
    "...ONN....NNO...",
    "...OO......OO...",
    "................",
  ],
  // SOLDIER — the rank-and-file shooter: helmet, camo, a leveled rifle.
  soldier_0: [
    "................",
    ".....OOOO.......",
    "....OeeeeO......",
    "...OeeeeeeO.....",
    "....OppppO......",
    ".....OppO.......",
    "....OeeeeeeO....",
    "...OeedeeedeO...",
    "...OeedeeedeONNy",
    "...OeeddeeddO...",
    "...OeeeeeeeeO...",
    "....OddddddO....",
    "....Oee..eeO....",
    "....Odd..ddO....",
    "....OO....OO....",
    "................",
  ],
  soldier_1: [
    "................",
    ".....OOOO.......",
    "....OeeeeO......",
    "...OeeeeeeO.....",
    "....OppppO......",
    ".....OppO.......",
    "....OeeeeeeO....",
    "...OeedeeedeO...",
    "...OeedeeedeONNy",
    "...OeeddeeddO...",
    "...OeeeeeeeeO...",
    "....OddddddO....",
    "...Oee....eeO...",
    "...Odd....ddO...",
    "...OO......OO...",
    "................",
  ],
  // VACUUM BOT — armed housekeeping: a low steel disc with a cyan scanner
  // eye and stubby wheels. _1 rolls the wheels and blinks the scanner wide.
  vacuum_bot_0: [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......OOOO......",
    "....OOvvvvOO....",
    "...OvvVVVVvvO...",
    "..OvVVVVVVVVvO..",
    "..OQQvvvvvvvvO..",
    "..OvvvvvvvvvvO..",
    "...ObbbbbbbbO...",
    "....OKO..OKO....",
    "................",
    "................",
  ],
  vacuum_bot_1: [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......OOOO......",
    "....OOvvvvOO....",
    "...OvvVVVVvvO...",
    "..OvVVVVVVVVvO..",
    "..OQQQvvvvvvvO..",
    "..OvvvvvvvvvvO..",
    "...ObbbbbbbbO...",
    "...OKO....OKO...",
    "................",
    "................",
  ],
  // ---- The personal detail (20×20, 2 frames) -----------------------------------
  // One drawing, six liveries: the accent char C (tie + lapel pin) is
  // palette-swapped per resident below. Broader and taller than the crew —
  // a wall in a suit.
  bodyguard_0: [
    "....................",
    "........OOOO........",
    ".......OKKKKO.......",
    ".......OppppO.......",
    ".......OKKKKO.......",
    "........OppO........",
    "......OOOOOOOO......",
    "....OKKKKKKKKKKO....",
    "...OKKKKWCCWKKKKO...",
    "...OKKKKWCCWKKKKO...",
    "...OKKKKKCCKKKKKO...",
    "...OKpKKKKKKKKpKO...",
    "...OKKKKKKKKKKKKO...",
    "....OKKKKKKKKKKO....",
    "....OKKK....KKKO....",
    "....OKKK....KKKO....",
    "....OKK......KKO....",
    "....OOO......OOO....",
    "....................",
    "....................",
  ],
  bodyguard_1: [
    "....................",
    "........OOOO........",
    ".......OKKKKO.......",
    ".......OppppO.......",
    ".......OKKKKO.......",
    "........OppO........",
    "......OOOOOOOO......",
    "....OKKKKKKKKKKO....",
    "...OKKKKWCCWKKKKO...",
    "...OKKKKWCCWKKKKO...",
    "...OKKKKKCCKKKKKO...",
    "...OKpKKKKKKKKpKO...",
    "...OKKKKKKKKKKKKO...",
    "....OKKKKKKKKKKO....",
    "...OKKK......KKKO...",
    "...OKKK......KKKO...",
    "...OKK........KKO...",
    "...OOO........OOO...",
    "....................",
    "....................",
  ],
  // ---- The residents (24×24, 2 frames) -----------------------------------------
  // MARK SUCKERBERG — the metaverse landlord: crop cut, screen-lit pale
  // skin, the unblinking stare, gray tee, jeans, white sneakers.
  mark_suckerberg_0: [
    "........................",
    "........................",
    "........................",
    ".........OOOOOO.........",
    "........OKKKKKKO........",
    "........OssssssO........",
    "........OWKssWKO........",
    "........OssssssO........",
    ".........OssssO.........",
    ".......ONNNNNNNNO.......",
    "......ONNNNNNNNNNO......",
    "......OsONNNNNNOsO......",
    "......OsONNNNNNOsO......",
    "......OssONNNNOssO......",
    ".......OONNNNNNOO.......",
    "........ONNNNNNO........",
    "........OjjOOjjO........",
    "........OjjO.OjjO.......",
    "........OjjO.OjjO.......",
    "........OjjO.OjjO.......",
    "........OWWO.OWWO.......",
    "........OOOO.OOOO.......",
    "........................",
    "........................",
  ],
  mark_suckerberg_1: [
    "........................",
    "........................",
    "........................",
    ".........OOOOOO.........",
    "........OKKKKKKO........",
    "........OssssssO........",
    "........OWKssWKO........",
    "........OssssssO........",
    ".........OssssO.........",
    ".......ONNNNNNNNO.......",
    "......ONNNNNNNNNNO......",
    "......OsONNNNNNOsO......",
    "......OsONNNNNNOsO......",
    "......OssONNNNOssO......",
    ".......OONNNNNNOO.......",
    "........ONNNNNNO........",
    "........OjjOOjjO........",
    ".......OjjO...OjjO......",
    ".......OjjO...OjjO......",
    ".......OjjO...OjjO......",
    ".......OWWO...OWWO......",
    ".......OOOO...OOOO......",
    "........................",
    "........................",
  ],
  // JERRY ALLISON — the database emperor: silver crop and beard, black tee
  // under a charcoal blazer, slacks sharp enough to audit.
  jerry_allison_0: [
    "........................",
    "........................",
    "........................",
    "..........OOOO..........",
    ".........OVVVVO.........",
    ".........OppppO.........",
    ".........OpKpKO.........",
    ".........OVppVO.........",
    "..........OVVO..........",
    ".........ONNNNO.........",
    ".......ONNNKKNNNO.......",
    "......ONNNKKKKNNNO......",
    "......ONpONKKNONpO......",
    "......ONpONKKNONpO......",
    "......ONpONKKNONpO......",
    "......OppONNNNOppO......",
    ".......OONNNNNNOO.......",
    "........ONNNNNNO........",
    "........ONNOONNO........",
    "........ONNO.ONNO.......",
    "........ONNO.ONNO.......",
    "........OKKO.OKKO.......",
    "........OOOO.OOOO.......",
    "........................",
  ],
  jerry_allison_1: [
    "........................",
    "........................",
    "........................",
    "..........OOOO..........",
    ".........OVVVVO.........",
    ".........OppppO.........",
    ".........OpKpKO.........",
    ".........OVppVO.........",
    "..........OVVO..........",
    ".........ONNNNO.........",
    ".......ONNNKKNNNO.......",
    "......ONNNKKKKNNNO......",
    "......ONpONKKNONpO......",
    "......ONpONKKNONpO......",
    "......ONpONKKNONpO......",
    "......OppONNNNOppO......",
    ".......OONNNNNNOO.......",
    "........ONNNNNNO........",
    "........ONNOONNO........",
    ".......ONNO...ONNO......",
    ".......ONNO...ONNO......",
    ".......OKKO...OKKO......",
    ".......OOOO...OOOO......",
    "........................",
  ],
  // JEFF BAYWATCH — the delivery emperor, retired to the gym: bald, jacked,
  // shades, a gilet over a tight black tee, arms the size of the fodder.
  jeff_baywatch_0: [
    "........................",
    "........................",
    "........................",
    "..........OOOO..........",
    "........OOppppOO........",
    "........OppppppO........",
    "........OKKKKKKO........",
    "........OppppppO........",
    ".........OppppO.........",
    "......OOOOOOOOOOOO......",
    ".....ONNKKKKKKKKNNO.....",
    "....OppONKKKKKKONppO....",
    "....OppONKKKKKKONppO....",
    "....OppONKKKKKKONppO....",
    "....OppONKKKKKKONppO....",
    ".....OOONNNNNNNNOOO.....",
    "........ONNNNNNO........",
    "........OjjOOjjO........",
    "........OjjO.OjjO.......",
    "........OjjO.OjjO.......",
    "........OjjO.OjjO.......",
    "........OKKO.OKKO.......",
    "........OOOO.OOOO.......",
    "........................",
  ],
  jeff_baywatch_1: [
    "........................",
    "........................",
    "........................",
    "..........OOOO..........",
    "........OOppppOO........",
    "........OppppppO........",
    "........OKKKKKKO........",
    "........OppppppO........",
    ".........OppppO.........",
    "......OOOOOOOOOOOO......",
    ".....ONNKKKKKKKKNNO.....",
    "....OppONKKKKKKONppO....",
    "....OppONKKKKKKONppO....",
    "....OppONKKKKKKONppO....",
    "....OppONKKKKKKONppO....",
    ".....OOONNNNNNNNOOO.....",
    "........ONNNNNNO........",
    "........OjjOOjjO........",
    ".......OjjO...OjjO......",
    ".......OjjO...OjjO......",
    ".......OjjO...OjjO......",
    ".......OKKO...OKKO......",
    ".......OOOO...OOOO......",
    "........................",
  ],
  // SAM HALTMAN — the AGI prepper: soft crop, gray henley, jeans, the
  // expression of a man who has modeled this conversation already.
  sam_haltman_0: [
    "........................",
    "........................",
    "........................",
    "..........OOOO..........",
    ".........ODDDDO.........",
    ".........OppppO.........",
    ".........OpKpKO.........",
    ".........OppppO.........",
    "..........OppO..........",
    ".........OvvvvO.........",
    ".......OvvvvvvvvO.......",
    "......OvvvvvvvvvvO......",
    "......OvpOvvvvOpvO......",
    "......OvpOvvvvOpvO......",
    "......OppOvvvvOppO......",
    ".......OOvvvvvvOO.......",
    "........OvvvvvvO........",
    "........OjjOOjjO........",
    "........OjjO.OjjO.......",
    "........OjjO.OjjO.......",
    "........OjjO.OjjO.......",
    "........OWWO.OWWO.......",
    "........OOOO.OOOO.......",
    "........................",
  ],
  sam_haltman_1: [
    "........................",
    "........................",
    "........................",
    "..........OOOO..........",
    ".........ODDDDO.........",
    ".........OppppO.........",
    ".........OpKpKO.........",
    ".........OppppO.........",
    "..........OppO..........",
    ".........OvvvvO.........",
    ".......OvvvvvvvvO.......",
    "......OvvvvvvvvvvO......",
    "......OvpOvvvvOpvO......",
    "......OvpOvvvvOpvO......",
    "......OppOvvvvOppO......",
    ".......OOvvvvvvOO.......",
    "........OvvvvvvO........",
    "........OjjOOjjO........",
    ".......OjjO...OjjO......",
    ".......OjjO...OjjO......",
    ".......OjjO...OjjO......",
    ".......OWWO...OWWO......",
    ".......OOOO...OOOO......",
    "........................",
  ],
  // DONALD DUMP — the biggest resident: the gold swoop, the tan, the navy
  // suit, and a red tie that ends somewhere around the knees.
  donald_dump_0: [
    "........................",
    "........................",
    ".........OOOOOOO........",
    "........OyyyyyyyO.......",
    ".......OyyyyyyyyyO......",
    ".......OyttttttyyO......",
    ".......OttKttKttO.......",
    ".......OttttttttO.......",
    "........OttttttO........",
    "......OOOOOOOOOOOO......",
    ".....OJJJWWCCWWJJJO.....",
    "....OJJJJWCCCCWJJJJO....",
    "....OJpOJWWCCWWJOpJO....",
    "....OJpOJJWCCWJJOpJO....",
    "....OJpOJJWCCWJJOpJO....",
    "....OppOJJWCCWJJOppO....",
    ".....OOOJJJCCJJJOOO.....",
    "......OJJJJJJJJJJO......",
    "......OJJJOOOOJJJO......",
    "......OJJO....OJJO......",
    "......OJJO....OJJO......",
    "......OKKO....OKKO......",
    "......OOOO....OOOO......",
    "........................",
  ],
  donald_dump_1: [
    "........................",
    "........................",
    ".........OOOOOOO........",
    "........OyyyyyyyO.......",
    ".......OyyyyyyyyyO......",
    ".......OyttttttyyO......",
    ".......OttKttKttO.......",
    ".......OttttttttO.......",
    "........OttttttO........",
    "......OOOOOOOOOOOO......",
    ".....OJJJWWCCWWJJJO.....",
    "....OJJJJWCCCCWJJJJO....",
    "....OJpOJWWCCWWJOpJO....",
    "....OJpOJJWCCWJJOpJO....",
    "....OJpOJJWCCWJJOpJO....",
    "....OppOJJWCCWJJOppO....",
    ".....OOOJJJCCJJJOOO.....",
    "......OJJJJJJJJJJO......",
    "......OJJJOOOOJJJO......",
    ".....OJJO......OJJO.....",
    ".....OJJO......OJJO.....",
    ".....OKKO......OKKO.....",
    ".....OOOO......OOOO.....",
    "........................",
  ],
};

// VLADIMIR PUTAIN (the clone) — the Eastworld drawing in a fresh white
// bathrobe (never a redraw): the suit denim swaps to robe white, everything
// else — judo posture, near-black shoes, the red tie now reading as the
// robe's piping — carries over.
for (const frame of ["0", "1"]) {
  SPRITES[`putain_clone_${frame}`] = swapPalette(
    eastworld.sprites[`vladimir_putain_${frame}`],
    { C: "W" },
  );
}

// The six liveries: the shared bodyguard body re-accented per resident
// (tie + pin chars) — the GROK-controller precedent, never a redraw.
const LIVERIES = {
  guard_kremlin: "C", // KREMLIN SHADOW keeps the power red
  guard_meta: "Q", // META SENTINEL scans in cyan
  guard_oracle: "I", // ORACLE ENFORCER in brass
  guard_prime: "y", // PRIME GUARDIAN in delivery gold
  guard_alignment: "U", // ALIGNMENT OFFICER in aligned green
  guard_loyalty: "o", // LOYALTY ENFORCER in solid bullion
};
for (const [id, accent] of Object.entries(LIVERIES)) {
  for (const frame of ["0", "1"]) {
    SPRITES[`${id}_${frame}`] = swapPalette(SPRITES[`bodyguard_${frame}`], {
      C: accent,
    });
  }
}

export default {
  name: "bunker",
  /** Ground tile behind this family's contact sheet. */
  ground: "bunker_0",
  palette: PALETTE,
  sprites: SPRITES,
  // The vault floor and carpet read as terrain, not subjects.
  contrastExempt: ["bunker_0", "bunker_1", "carpet_0", "carpet_1"],
  animations: {
    cia_agent_walk: { frames: ["cia_agent_0", "cia_agent_1"], delayMs: 320 },
    fbi_agent_walk: { frames: ["fbi_agent_0", "fbi_agent_1"], delayMs: 300 },
    ice_agent_walk: { frames: ["ice_agent_0", "ice_agent_1"], delayMs: 280 },
    soldier_walk: { frames: ["soldier_0", "soldier_1"], delayMs: 320 },
    vacuum_bot_roll: { frames: ["vacuum_bot_0", "vacuum_bot_1"], delayMs: 240 },
    bodyguard_walk: { frames: ["bodyguard_0", "bodyguard_1"], delayMs: 340 },
    donald_dump_walk: {
      frames: ["donald_dump_0", "donald_dump_1"],
      delayMs: 380,
    },
  },
};
