// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The icons family (see the `pixel-assets` skill): every 12×12 inventory
// icon — weapons, gear, abilities, story items. Drawn in UI panels, never
// on the ground. One string per pixel row, one character per pixel; `.` is
// transparent and every other char must exist in CORE_PALETTE
// (sprite-data/core.mjs) or this family's local palette.

import { swapPalette } from "../asset-tools/palette.mjs";

// Icons that spawn palette variants live as consts: the trophy/elite
// versions are swapPalette calls, never redraws.
// Base cuts that spawn palette variants: the ball cap (mission tan on the
// moon) and the trouser cut (thermal / carbon / mail legs are recolors).
const CAP_ICON = [
  "............",
  "............",
  "....OOOO....",
  "...OjjjjO...",
  "..OjWWjjjO..",
  "..OjWWjjjO..",
  ".OjjjjjjjO..",
  ".OjjjjjjOOO.",
  "..OOOOOjjjO.",
  ".......OOO..",
  "............",
  "............",
];

const JEANS_ICON = [
  "............",
  "............",
  "..OOOOOOOO..",
  "..OjjjjjjO..",
  "..OjjjjjjO..",
  "..OjjOOjjO..",
  "..OjjO.OjjO.",
  "..OjjO.OjjO.",
  "..OjjO.OjjO.",
  "..OjjO.OjjO.",
  "..OOO...OOO.",
  "............",
];

const TASER_ICON = [
  "............",
  "...aa..aa...",
  "...Oa..aO...",
  "..OOOOOOO...",
  "..OhhhhhO...",
  "..OhHhhhO...",
  "..OhhhhhO...",
  "...OhhhO....",
  "...OhhhO....",
  "...OOOOO....",
  "............",
  "............",
];

const LASER_ICON = [
  "............",
  ".rr.........",
  ".rr.........",
  "....OO......",
  "...ObbO.....",
  "....ObbO....",
  ".....ObbO...",
  "......ObbO..",
  ".......ObO..",
  "........O...",
  "............",
  "............",
];

const PISTOL_ICON = [
  "............",
  "............",
  "..OOOOOO....",
  "..OaaaaAO...",
  "..OOOaaO....",
  "....OaAO....",
  "....OaAO....",
  "....OOO.....",
  "............",
  "............",
  "............",
  "............",
];

// The keycards and the paper trail: one card, one document, recolored per
// plot thread.
const KEYCARD_ICON = [
  "............",
  "............",
  ".OOOOOOOOOO.",
  ".OWWWWWWWWO.",
  ".OjjjjjjjjO.",
  ".OWWWWWWWWO.",
  ".OWyyOWWwWO.",
  ".OWyyOWwwWO.",
  ".OWWWWWWWWO.",
  ".OOOOOOOOOO.",
  "............",
  "............",
];

const MANIFEST_ICON = [
  "............",
  ".OOOOOOOOO..",
  ".OWWWWWWWO..",
  ".OWbbbbWWO..",
  ".OWWWWWWWO..",
  ".OWbbbbbWO..",
  ".OWWWWWWWO..",
  ".OWrrrbWWO..",
  ".OWWWWWWWO..",
  ".OOOOOOOOO..",
  "............",
  "............",
];

// The GOLDEN STAPLER icon is the stapler re-skinned in trophy gold — a
// swapPalette call, never a redraw.
const STAPLER_ICON = [
  "............",
  "..OOOOOO....",
  ".OrrrrrrO...",
  ".OrrrrrrOO..",
  "..OOOOOrrO..",
  ".OaaaaaaaO..",
  ".OAAAAAAAO..",
  "..OOOOOOO...",
  "............",
  "............",
  "............",
  "............",
];

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  // Electric blue + charged white-blue core for the storm bolt.
  e: [90, 180, 255],
  s: [214, 240, 255],
  // PETER SEAL's teal — grip of the contrarian dagger.
  C: [82, 158, 168],
  // Billionaire black (matches the mars family): grips and gun bodies.
  N: [48, 52, 68],
  // Level-up stat glyphs: a darker flesh shade for the strength arm and a
  // pink brain ramp for intellect. Skin base `p`, greens `G`/`g`/`l`, red
  // `r`/`i`, gold `y`/`Y` and the electric blue above are reused from the core.
  d: [176, 120, 92], // strength: skin shadow
  // Mars plasma: the blade's magenta edge and its hot tint.
  z: [236, 82, 190],
  Z: [252, 168, 226],
  u: [232, 150, 172], // intellect: brain pink
  U: [196, 104, 132], // intellect: brain fold shadow
  // Aged parchment for the HUD's treasure map: sun-bleached tan + shadow.
  t: [222, 192, 138],
  D: [178, 142, 92],
  // Item-card weapon-class glyphs, tinted to WEAPON_CLASS_COLORS (the app's
  // tiers.ts) so the glyph reads as the class line it replaces.
  K: [232, 185, 62], // melee gold
  Q: [224, 96, 58], // ranged ember
  X: [180, 93, 240], // magic violet
};

const SPRITES = {
  // The item card's weapon-class glyphs (ItemCard.tsx), sitting left of the
  // item name at 1× (12 CSS px) — bold single-subject silhouettes, no fine
  // detail: a sword for melee, a crosshair for ranged, a spark for magic.
  icon_class_melee: [
    ".....OO.....",
    "....OKKO....",
    "....OKKO....",
    "....OKKO....",
    "....OKKO....",
    "....OKKO....",
    "..OOOKKOOO..",
    "..OKKKKKKO..",
    "..OOOKKOOO..",
    "....OKKO....",
    "....OOOO....",
    "............",
  ],
  icon_class_ranged: [
    ".....QQ.....",
    ".....QQ.....",
    "...QQQQQQ...",
    "..Q......Q..",
    "..Q..QQ..Q..",
    "QQQ.QQQQ.QQQ",
    "QQQ.QQQQ.QQQ",
    "..Q..QQ..Q..",
    "..Q......Q..",
    "...QQQQQQ...",
    ".....QQ.....",
    ".....QQ.....",
  ],
  icon_class_magic: [
    "............",
    ".....XX..XX.",
    "....XXXX.XX.",
    "...XXXXXX...",
    ".XXXXWWXXXX.",
    ".XXXXWWXXXX.",
    "...XXXXXX...",
    "....XXXX....",
    ".....XX.....",
    "............",
    "............",
    "............",
  ],
  // ARMSTRONG's Apollo survival-kit machete: broad steel blade, wood grip.
  icon_machete: [
    "............",
    ".......OOO..",
    "......OaaO..",
    ".....OaaAO..",
    "....OaaAO...",
    "...OaaAO....",
    "..OaaAO.....",
    ".OaaAO......",
    ".OaAO.......",
    "OkkO........",
    "OkkO........",
    ".OO.........",
  ],
  // The MOON'S BLADE trophy: a pale spectral blade, ghost-lit.
  icon_moons_blade: [
    "............",
    ".......OOO..",
    "......OxxO..",
    ".....OxxcO..",
    "....OxxcO...",
    "...OxxcO....",
    "..OxxcO.....",
    ".OxxcO......",
    ".OxcO.......",
    "OkkO........",
    "OkkO........",
    ".OO.........",
  ],
  // ---- The wall arsenal: one starting weapon per difficulty (the piece the
  // prelude hangs on the hero's living-room wall — see prelude.mjs for the
  // mounted versions). EASY's HAIRY POTTER'S WAND: a licensed-adjacent wand,
  // gold glow at the tip, fur bristling off the grip end.
  icon_hairy_wand: [
    "............",
    "........OO..",
    ".......OyYO.",
    "......OyYYO.",
    "......OyyO..",
    ".....OkkO...",
    "....OkkO....",
    "...OkkO.....",
    "..OkkO......",
    ".BOkOB......",
    ".BBOBB......",
    "............",
  ],
  // MEDIUM's MEDIEVAL SWORD: a proper knight's blade — bright steel, a wide
  // gold crossguard, wrapped grip, gold pommel.
  icon_medieval_sword: [
    "............",
    ".......OOO..",
    "......OVvO..",
    ".....OVvvO..",
    "....OVvvO...",
    "...OVvvO....",
    "..OVvvO.....",
    ".OoqOvOqoO..",
    "..OkkO......",
    ".OyOkO......",
    "..OOO.......",
    "............",
  ],
  // HARD's COMBAT KNIFE: a short tactical blade over a dark bar guard and a
  // billionaire-black grip.
  icon_combat_knife: [
    "............",
    "............",
    ".......OO...",
    "......OVvO..",
    ".....OVvO...",
    "....OVvO....",
    "...OVvO.....",
    "..OaaaO.....",
    "..ONNO......",
    ".ONNO.......",
    "..OO........",
    "............",
  ],
  // NIGHTMARE's BRASS KNUCKLES: four finger slots in a gold duster, the palm
  // bar shaded below.
  icon_knuckles: [
    "............",
    ".OOOOOOOOOO.",
    "OYYyyyyyyyyO",
    "OyOyOyOyOyyO",
    "OyOyOyOyOyyO",
    "OyyyyyyyyyyO",
    ".OOqqqqqqOO.",
    "..OqqqqqqO..",
    "...OOOOOO...",
    "............",
    "............",
    "............",
  ],
  // JESUS CHRIST!'s STICK: a stick. Crooked, knotted, bark-shaded. A stick.
  icon_stick: [
    "............",
    ".........O..",
    "........OBO.",
    ".......OBO..",
    "......OBO...",
    ".....OBEO...",
    "....OBEO....",
    "...OBEO.....",
    "..OBEO......",
    "..OBO.......",
    "...O........",
    "............",
  ],
  // Inventory icons, 12×12.
  icon_blaster: [
    "............",
    "............",
    ".OOOOOOOOO..",
    ".OAAAAAAAyO.",
    ".OAAAAAAAyO.",
    ".OOOOAAOOO..",
    "....OAAO....",
    "....OAAO....",
    "....OOOO....",
    "............",
    "............",
    "............",
  ],
  // The lander's chunky chrome service wrench (moon base pool).
  icon_lunar_wrench: [
    "............",
    ".OO....OO...",
    ".OAO..OAO...",
    ".OAAOOAAO...",
    "..OAAAAO....",
    "...OAAO.....",
    "....OAAO....",
    ".....OAAO...",
    "......OAAO..",
    ".......OAO..",
    "........O...",
    "............",
  ],
  icon_suit: [
    "............",
    "..OOOOOOOO..",
    ".OaaaaaaaaO.",
    ".OaaOrrOaaO.",
    ".OaaaaaaaaO.",
    ".OAaaaaaaAO.",
    ".OAaaaaaaAO.",
    "..OaaaaaaO..",
    "..OAAAAAAO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  icon_charm: [
    "............",
    "....OOOO....",
    "...OFFFFO...",
    "..OFFOOOO...",
    "..OFO.......",
    "..OFO.......",
    "..OFO.......",
    "..OFFOOOO...",
    "...OFFFFO...",
    "....OOOO....",
    "............",
    "............",
  ],
  // The merchant's COIN: gold with a square mint-hole, lit top-left. The
  // shop UI's currency mark and the HUD's purse badge.
  icon_coin: [
    "............",
    "...OOOOOO...",
    "..OyyooooO..",
    ".OyyoooooqO.",
    ".OyooooooqO.",
    ".OyooOOooqO.",
    ".OyooOOooqO.",
    ".OoooooooqO.",
    ".OooooooqqO.",
    "..OooooqqO..",
    "...OOOOOO...",
    "............",
  ],
  // A little STACK of three coins: the shop's "sell everything" mark, three
  // gold discs overlapping (two behind, one in front) — the same gold ramp as
  // the single coin, no mint-hole at this size.
  icon_coins: [
    ".OOOO..OOOO.",
    "OyyooOOyyooO",
    "OyoooOOyoooO",
    "OoooqOOoooqO",
    "OooqqOOooqqO",
    ".OO.OOOO.OO.",
    "...OyyooO...",
    "...OyoooO...",
    "...OoooqO...",
    "...OooqqO...",
    "....OOOO....",
    "............",
  ],
  // The starter BAG: a leather satchel — a top carry handle over a rounded
  // body, a brass clasp down the middle, right and bottom edges shaded.
  icon_bag: [
    "....OOOO....",
    "...OB..BO...",
    "..OB....BO..",
    ".OOOOOOOOOO.",
    ".OBBBooBBEO.",
    ".OBBBooBBEO.",
    ".OBBBBBBBEO.",
    ".OBBBBBBBEO.",
    ".OBBBBBBBEO.",
    ".OBEEEEEEEO.",
    ".OOOOOOOOOO.",
    "............",
  ],
  // ---- The base weapon roster (Diablo-style bases, 5 per level) -----------
  // SPACEZ HQ: a shipping desk's yellow snap-blade knife.
  icon_box_cutter: [
    "............",
    "........OO..",
    ".......OaaO.",
    "......OaAO..",
    ".....OaAO...",
    "....OaAO....",
    "...OhhO.....",
    "..OhHhO.....",
    ".OhhHO......",
    ".OhhO.......",
    "..OO........",
    "............",
  ],
  // The drawer 9MM: the pistol silhouette in black polymer.
  icon_nine_mm: swapPalette(PISTOL_ICON, { a: "N", A: "b" }),
  // The lab bench laser rig (the overclocked elite variant swaps it gold).
  icon_prototype_laser: LASER_ICON,
  // The armory's pump gun: steel barrel over a walnut pump and stock.
  icon_pump_shotgun: [
    "............",
    ".........OO.",
    "........OaaO",
    ".......OaAO.",
    "......OaAO..",
    ".....OBBO...",
    "....OBBO....",
    "...OaAO.....",
    "..OBBO......",
    ".OBBO.......",
    "..OO........",
    "............",
  ],
  // THE MOON: the survival kit's .38 — chrome with a wooden grip.
  icon_service_revolver: [
    "............",
    "............",
    ".OOOOOOOOO..",
    ".OaaaaaaaAO.",
    ".OOOAAAOaO..",
    "...OAAAOaO..",
    "....OOOBBO..",
    "......OBBO..",
    ".......OO...",
    "............",
    "............",
    "............",
  ],
  // The geologist's pick hammer: flat face one side, spike the other.
  icon_geology_hammer: [
    "............",
    "..OOOOOO....",
    ".OaaaaaAOO..",
    ".OaaaaaAAO..",
    ".OAAAOAAO...",
    "..OOBO.O....",
    "....OBO.....",
    "....OBO.....",
    "....OBO.....",
    "....OBO.....",
    ".....O......",
    "............",
  ],
  // Military surplus that hitched a ride: long barrel, wooden stock.
  icon_surplus_carbine: [
    "............",
    ".........OO.",
    "........OaO.",
    ".......OaO..",
    "......OaO...",
    ".....OaO....",
    "....OaO.....",
    "...OkkO.....",
    "..OkkO......",
    "..OkO.......",
    "...O........",
    "............",
  ],
  // The atomic-age RETRO RAYGUN: chrome fins, blue charge ring.
  icon_retro_raygun: [
    "............",
    "............",
    "......OOO...",
    ".OOOOOaaaOO.",
    ".OeeaaaaaaO.",
    ".OOOOaaaAO..",
    ".....OaaAO..",
    ".....OaAO...",
    ".....OBBO...",
    "....OBBO....",
    ".....OO.....",
    "............",
  ],
  // MARS: the SMART PISTOL — white ceramic, no trigger, one cyan eye.
  icon_smart_pistol: [
    "............",
    "............",
    "..OOOOOOO...",
    "..OWWeWWwO..",
    "..OOOWWwO...",
    "....OWwO....",
    "....OWwO....",
    "....OwwO....",
    ".....OO.....",
    "............",
    "............",
    "............",
  ],
  // The PLASMA BLADE: a humming magenta edge (machete cut, plasma ramp).
  icon_plasma_blade: [
    "............",
    ".......OOO..",
    "......OZzO..",
    ".....OZzO...",
    "....OZzO....",
    "...OZzO.....",
    "..OZzO......",
    ".OZzO.......",
    ".OzO........",
    "ONNO........",
    "ONNO........",
    ".OO.........",
  ],
  // The RAILGUN: twin dark rails, capacitor glow dots.
  icon_railgun: [
    "............",
    ".........OO.",
    "........OeO.",
    ".......ONNO.",
    "......ONNO..",
    ".....OeNO...",
    "....ONNO....",
    "...ONeO.....",
    "..ONNO......",
    "..ONO.......",
    "...O........",
    "............",
  ],
  // The ARC PROJECTOR: a steel fork spitting blue-white current.
  icon_arc_projector: [
    "............",
    "..Os.sO.....",
    "..OeOeO.....",
    "..OvOvO.....",
    "...OvO......",
    "...OvVO.....",
    "....OvO.....",
    "....OkO.....",
    "....OkO.....",
    ".....O......",
    "............",
    "............",
  ],
  // The GRAVITY MAUL: a black cube that bends light, on a plain haft.
  icon_gravity_maul: [
    "............",
    "..OOOOO.....",
    ".ObNNNPO....",
    ".ONNNNNO....",
    ".ONPNNNO....",
    ".ONNNNbO....",
    "..OOOOO.....",
    "....OBO.....",
    "....OBO.....",
    "....OBO.....",
    ".....O......",
    "............",
  ],
  // THE RIFT: a legionary's GLADIUS — broad blade, gold guard.
  icon_gladius: [
    "............",
    ".....OO.....",
    "....OaAO....",
    "....OaAO....",
    "....OaAO....",
    "....OaAO....",
    "....OaAO....",
    "..OOyyOO....",
    "....OkO.....",
    "....OkO.....",
    ".....O......",
    "............",
  ],
  // The English LONGBOW: yew stave, taut string.
  icon_longbow: [
    "............",
    "....OO......",
    "...OBOw.....",
    "..OBO.w.....",
    ".OBO..w.....",
    ".OBO..w.....",
    ".OBO..w.....",
    ".OBO..w.....",
    "..OBO.w.....",
    "...OBOw.....",
    "....OO......",
    "............",
  ],
  // The BLUNDERBUSS: flared brass muzzle, powder-age stock.
  icon_blunderbuss: [
    "............",
    ".......OOOO.",
    "......OooqO.",
    ".......OoqO.",
    "......OoqO..",
    ".....OoqO...",
    "....OoqO....",
    "...OBBO.....",
    "..OBBO......",
    ".OBBO.......",
    "..OO........",
    "............",
  ],
  // The EXECUTIONER'S AXE: a broad steel crescent on a long haft.
  icon_executioners_axe: [
    "............",
    ".......OO...",
    "..OOOO.OBO..",
    ".OaaaAOOBO..",
    ".OaaaaAOBO..",
    ".OaaaaAOBO..",
    ".OaaaAOOBO..",
    "..OAAO.OBO..",
    "...OO..OBO..",
    ".......OBO..",
    "........O...",
    "............",
  ],
  // The SORCERER'S STAFF: a gnarled stave crowned with a violet crystal.
  icon_sorcerers_staff: [
    "............",
    ".....OO.....",
    "....OLPO....",
    "....OPLO....",
    ".....OO.....",
    "....OBO.....",
    ".....OBO....",
    "....OBO.....",
    ".....OBO....",
    "....OBO.....",
    ".....O......",
    "............",
  ],
  // ---- Rift fantasy gear ---------------------------------------------------
  // The LUCKY CLOVER: four leaves, pressed flat by something enormous.
  icon_clover: [
    "............",
    "...OO.OO....",
    "..OGlOGlO...",
    "..OGGOGGO...",
    "...OOOOO....",
    "..OGlOGlO...",
    "..OGGOGGO...",
    "...OO.OO....",
    "......Og....",
    ".....Og.....",
    "............",
    "............",
  ],
  // The CRYSTAL ORB: it shows you the blow before it lands.
  icon_crystal_orb: [
    "............",
    "....OOOO....",
    "...OsWseO...",
    "..OsWsseeO..",
    "..OssseeeO..",
    "..OseeeeeO..",
    "...OeeeeO...",
    "....OOOO....",
    "...OqooqO...",
    "....OOOO....",
    "............",
    "............",
  ],
  // The GRIMOIRE: a book that reads YOU. Violet leather, gold clasp.
  icon_grimoire: [
    "............",
    ".OOOOOOOOO..",
    ".OPPPPPPPO..",
    ".OPLLLLLPO..",
    ".OPLPPPLPO..",
    ".OPLLLLLPO..",
    ".OPPPPPPPO..",
    ".OPPPoPPPO..",
    ".OOOOOOOOO..",
    "............",
    "............",
    "............",
  ],
  // The ENCHANTED RING: one ring, one cold blue stone.
  icon_enchanted_ring: [
    "............",
    ".....OO.....",
    "....OeeO....",
    "....OeeO....",
    "...OOooOO...",
    "..Oo....oO..",
    "..Oq....qO..",
    "..Oq....qO..",
    "...OqooqO...",
    "....OOOO....",
    "............",
    "............",
  ],
  // The DRAGONSCALE CLOAK: shed, not taken. Green scales, gold clasp.
  icon_dragonscale_cloak: [
    "............",
    "..OOOOOOOO..",
    ".OGGGyyGGGO.",
    ".OGlGlGlGGO.",
    ".OGGlGlGGGO.",
    ".OGlGlGlGGO.",
    ".OgGlGlGGgO.",
    "..OGGGGGGO..",
    "..OggggggO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // A wand bearing a violet void orb.
  icon_void_wand: [
    "............",
    ".....OO.....",
    "....OmmO....",
    "....OmMO....",
    ".....OO.....",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    "..O.........",
    "............",
  ],
  // ---- Second-magic bases, one per level pool (INT-scaled energy weapons):
  // the wand ladder that brings the caster's climb up to the melee/ranged
  // density. Each shares a projectile sprite with an existing shot.
  //
  // SPACEZ HQ: the MICROWAVE EMITTER — a repurposed break-room magnetron in a
  // steel body, spitting a blue lattice from the muzzle dish.
  icon_microwave_emitter: [
    "............",
    "............",
    "..OOOOOOO...",
    ".OVvvvvvsO..",
    ".OVvvvveesO.",
    ".OVvvvvvsO..",
    ".OOOOVvOOO..",
    "....OVvO....",
    "....OVvO....",
    "....OOOO....",
    "............",
    "............",
  ],
  // THE MOON: the PULSAR ROD — a dark survey rod capped by a pulsing
  // white-blue star, ticking out a beat the 70s mistook for aliens.
  icon_pulsar_rod: [
    "............",
    "....OOO.....",
    "...OsWsO....",
    "...OWWsO....",
    "...OsseO....",
    "....OeO.....",
    "....ObO.....",
    "....ObO.....",
    "....ObO.....",
    "....ObO.....",
    "....OO......",
    "............",
  ],
  // MARS: the GRAVITON MAW — a printed black housing cupping a magenta well
  // of bent space, heavy in the hand.
  icon_graviton_maw: [
    "............",
    "...OOOOO....",
    "..ONNNNNO...",
    "..ONzZzNO...",
    "..ONZzZNO...",
    "..ONzZzNO...",
    "...ONNNO....",
    "....ONO.....",
    "....ONO.....",
    "....ONO.....",
    "....OO......",
    "............",
  ],
  // THE RIFT: the EMBER WAND — a knotted wand crowned with a live flame,
  // gold at the heart, red at the crown.
  icon_ember_wand: [
    "............",
    ".......OO...",
    "......OrO...",
    ".....OriO...",
    ".....OyrO...",
    "......OyO...",
    ".....OBO....",
    "....OBO.....",
    "...OBEO.....",
    "..OBEO......",
    "..OEO.......",
    "...O........",
  ],
  // Ability pickups: time-limited powers.
  // FIRE ORBS: three fireballs mid-orbit.
  icon_fire_orbs: [
    "............",
    "....OO......",
    "...OrYO.....",
    "....OO......",
    "............",
    ".OO.....OO..",
    "OrYO...OrYO.",
    ".OO.....OO..",
    "............",
    "............",
    "............",
    "............",
  ],
  // STORM CELL: the classic thunderbolt silhouette in electric blue — a broad
  // top flag slanting down-left, the signature notch kicking right, then a
  // lower stroke tapering to a point at the bottom-left. Clean outline.
  icon_storm: [
    ".....OOOO...",
    "....OOseO...",
    "...OOeeOO...",
    "..OOeeOOOO..",
    "..OeesseeO..",
    "..OOOOeseO..",
    "...OOeeeOO..",
    "..OOeeeOO...",
    ".OOeseOO....",
    ".OeeeOO.....",
    ".OOOOO......",
    "............",
  ],
  // STASIS FIELD: a pale ring holding still around a speck of astronaut.
  icon_stasis: [
    "............",
    "....xxxx....",
    "..xx....xx..",
    ".x........x.",
    ".x........x.",
    "x....aa....x",
    "x....aa....x",
    ".x........x.",
    ".x........x.",
    "..xx....xx..",
    "....xxxx....",
    "............",
  ],
  // SCREEN NUKE: a squat bomb, fuse lit.
  icon_nuke: [
    "........yy..",
    "....OO..y...",
    "...OkkOy....",
    "..OOkkOO....",
    ".OaaAAAAO...",
    "OaaAAAAAAO..",
    "OaAAAAAAAO..",
    "OaAAAAAAAO..",
    "OAAAAAAAAO..",
    ".OAAAAAAO...",
    "..OOOOOO....",
    "............",
  ],
  // ITEM MAGNET: the classic red horseshoe, poles down.
  icon_magnet: [
    "............",
    "...rrrrrr...",
    "..rrrrrrrr..",
    ".rrr....rrr.",
    ".rr......rr.",
    ".rr......rr.",
    ".rr......rr.",
    ".rr......rr.",
    ".WW......WW.",
    ".WW......WW.",
    "............",
    "............",
  ],
  // ---- SpaceZ HQ trophy & elite icons (12×12) -------------------------------
  // The CEO's desk ornament: the old stapler drawing survives only as the
  // trophy's gold re-skin.
  icon_golden_stapler: swapPalette(STAPLER_ICON, { r: "y", a: "o", A: "q" }),
  // The guard's baton: dark shaft, wooden grip.
  icon_baton: [
    "............",
    ".........OO.",
    "........ObO.",
    ".......ObO..",
    "......ObO...",
    ".....ObO....",
    "....ObO.....",
    "...OkO......",
    "..OkO.......",
    "..OO........",
    "............",
    "............",
  ],
  // Cleanroom tooling rated for rocket hulls — MUSKRAT's toothpick.
  icon_plasma_cutter: [
    "..........cc",
    ".........cWc",
    "........cWWc",
    ".......cWWc.",
    ".....OvvWc..",
    "....OvvO....",
    "...OvvO.....",
    "..OkkO......",
    ".OkkO.......",
    ".OO.........",
    "............",
    "............",
  ],
  // White coat over a blue shirt — the LAB COAT suit gear.
  icon_lab_coat: [
    "............",
    "..OOOOOOOO..",
    ".OWWWOOWWWO.",
    ".OWWOjjOWWO.",
    ".OWWWWWWWWO.",
    ".OwWWWWWWwO.",
    ".OwWWWWWWwO.",
    "..OWWWWWWO..",
    "..OwwwwwwO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // THE ARCHITECT's PASSAGE CHIP: a microprocessor die, gold contact pins on
  // every side, a glowing cyan core — the implant he cut into his own skull.
  icon_passage_chip: [
    "............",
    "...y.yy.y...",
    "..OOOOOOOO..",
    "..OvvvvvvO..",
    "..OvOccOvO..",
    "y.OvcxxcvO.y",
    "y.OvcxxcvO.y",
    "..OvOccOvO..",
    "..OvvvvvvO..",
    "..OOOOOOOO..",
    "...y.yy.y...",
    "............",
  ],
  // The ID BADGE charm: photo, smudged name, gold clip.
  icon_badge: [
    "............",
    "....OyO.....",
    "..OOOOOOOO..",
    ".OWWWWWWWWO.",
    ".OWppOwwwWO.",
    ".OWppOwwwWO.",
    ".OWWWWWWWWO.",
    ".OWwwwwWWWO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
    "............",
  ],
  // The ACHIEVEMENT star: a gold four-point shine (map_elite's cut in visor
  // gold) with a white-hot core — the HUD badge button and the unlock toast.
  icon_star: [
    "............",
    ".....OO.....",
    "....OYYO....",
    "...OYYyyO...",
    "...OYyyyO...",
    "OYYyyWWyyyqO",
    "OyyyyWWyyqqO",
    "...OyyyqO...",
    "...OyyqqO...",
    "....OyqO....",
    ".....OO.....",
    "............",
  ],
  // ---- Achievement badge icons (12x12) ---------------------------------------
  // Drawn for the achievements browser and unlock toast; gold ramp from the
  // core (visor gold y/Y, lander-gold shadow q) so the shelf reads as one set.
  // The TROPHY cup: rim, handles, stem, flared foot — the difficulty ladder.
  icon_trophy: [
    "............",
    ".OOOOOOOOOO.",
    ".OYYYYyyyyO.",
    "OOYYYYyyyyOO",
    "OyOYYYyyyOyO",
    "OyOYYyyyyOyO",
    ".OOYyyyyOO..",
    "...OyyyyO...",
    "....OyyO....",
    "....OyqO....",
    "..OOyyyyOO..",
    "..OOOOOOOO..",
  ],
  // The SKULL: bone white, dark sockets, toothy jaw — the kill ladders.
  icon_skull: [
    "............",
    "...OOOOOO...",
    "..OWWWWWWO..",
    ".OWWWWWWWWO.",
    ".OWWWWWWWWO.",
    ".OWOOWWOOWO.",
    ".OWOOWWOOWO.",
    "..OWWOOWWO..",
    "..OWWWWWWO..",
    "..OWOWOWO...",
    "...OOOOO....",
    "............",
  ],
  // The CROWN: three points over a jeweled band — boss trophies. One solid
  // gold silhouette (interior seams at this size swallow the metal).
  icon_crown: [
    "............",
    "............",
    "............",
    "..OO.OO.OO..",
    ".OYYOYYOYYO.",
    ".OYYYYYYYYO.",
    ".OYyyyyyyyO.",
    ".OyWWyyyyqO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
    "............",
  ],
  // The MEDAL: flag-blue ribbon over a gold disc — the hero's level climb.
  icon_medal: [
    "............",
    "..OOO..OOO..",
    "..OjjO.OjjO.",
    "...OjjOjjO..",
    "....OjjjO...",
    "...OyYYyO...",
    "..OyYYYyyO..",
    "..OyYWWYyO..",
    "..OyYYyyqO..",
    "...OyyyqO...",
    "....OOO.....",
    "............",
  ],
  // The STOPWATCH: steel case, white face, dark hands — the speed clear.
  icon_stopwatch: [
    "............",
    ".....OO.....",
    "....OvvO....",
    "...OOOOOO...",
    "..OWWWWWWO..",
    ".OWWWOWWWWO.",
    ".OWWWOOWWWO.",
    ".OWWWWWWWWO.",
    "..OWWWWWWO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // ---- Elite signature weapon icons (12x12) ----------------------------------
  // The NIGHT MANAGER's back-nine special.
  icon_putter: [
    "............",
    ".........OO.",
    "........OkO.",
    ".......OkO..",
    "......OkO...",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OvvvO......",
    ".OvvvvO.....",
    "..OOOO......",
  ],
  // The CHIEF's taser with the export firmware - navy issue.
  icon_riot_taser: swapPalette(TASER_ICON, { h: "J", H: "j" }),
  // DR. NOVA's pointer, three safety screws short of legal.
  icon_overclocked_laser: swapPalette(LASER_ICON, { b: "y" }),
  // THE JANITOR's halberd.
  icon_floor_sign: [
    "............",
    ".....OO.....",
    "....OhhO....",
    "....OhhO....",
    "...OhrrhO...",
    "...OhrrhO...",
    "..OhhrrhhO..",
    "..OhhhhhhO..",
    ".OhhO..OhhO.",
    ".OOO....OOO.",
    "............",
    "............",
  ],
  // The MISSION SPECIALIST's survival kit piece.
  icon_flare_gun: swapPalette(PISTOL_ICON, { a: "r", A: "q" }),
  // The PROSPECTOR's tunneler.
  icon_core_drill: [
    "............",
    "........OO..",
    ".......OyO..",
    "......OyYO..",
    ".....OvvO...",
    "....OvVvO...",
    "...OvvvO....",
    "..OvvvO.....",
    "..ObvO......",
    "..ObbO......",
    "...OO.......",
    "............",
  ],
  // The MEDIC's screening probe, clicking past the safe band.
  icon_geiger_wand: [
    "............",
    "....OOO.....",
    "...OhHhO....",
    "...OhrhO....",
    "....OOO.....",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    "..O.........",
    "............",
  ],
  // THE CARTOGRAPHER's stake hammer.
  icon_surveyors_pick: [
    "............",
    "..OvvvvvvO..",
    ".OvvOOOOvvO.",
    ".OvO.Ok.OvO.",
    ".OO..OkO.OO.",
    ".....OkO....",
    "....OkO.....",
    "....OkO.....",
    "...OkO......",
    "...OkO......",
    "....O.......",
    "............",
  ],
  // ---- Story item icons (12x12) ----------------------------------------------
  // Keycards: supply bay white, cleanroom-vault red, AI-core electric blue.
  icon_keycard: KEYCARD_ICON,
  icon_keycard_red: swapPalette(KEYCARD_ICON, { W: "r", j: "W" }),
  icon_keycard_blue: swapPalette(KEYCARD_ICON, { W: "e", j: "s" }),
  // The paper trail: manifest, redacted Apollo log, blueprints — and the AI
  // CORE's own terminal readout, electric-blue glyphs on a dark screen.
  icon_manifest: MANIFEST_ICON,
  icon_log: swapPalette(MANIFEST_ICON, { b: "O", r: "b" }),
  icon_blueprint: swapPalette(MANIFEST_ICON, { W: "j", b: "W", r: "W" }),
  icon_corelog: swapPalette(MANIFEST_ICON, { W: "b", b: "e", r: "s" }),
  // PROJECT SECOND MAN, in its manila folder.
  icon_dossier: [
    "............",
    "............",
    ".OOOO.......",
    ".OooOOOOOO..",
    ".OooooooooO.",
    ".OoWWWWWWoO.",
    ".OoWrrrrWoO.",
    ".OoWWWWWWoO.",
    ".OooooooooO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
  ],
  // ---- Level-up stat glyphs (12x12) ------------------------------------------
  // Drawn on the gold LEVEL UP! buttons — the dark navy outline carries them
  // against the yellow, so each keeps a bold silhouette and 2–3 fill colors.
  // STAMINA (SPRINT + HP): a red heart with a top-left shine.
  icon_stat_stamina: [
    "............",
    "..OO..OO....",
    ".OrrOOrrO...",
    "OrrrrrrrrO..",
    "OrWrrrrrrO..",
    ".OrrrrrrO...",
    "..OrrrrO....",
    "...OrrO.....",
    "....OO......",
    "............",
    "............",
    "............",
  ],
  // STRENGTH (DAMAGE + BAG): a flexed arm — fist up on a vertical forearm,
  // the bicep bulging up from the horizontal upper arm below.
  icon_stat_strength: [
    "............",
    "......OOO...",
    ".....OpppO..",
    ".OO..OpppO..",
    "OppO.OpppO..",
    "OppOOOpppO..",
    "OpppppppO...",
    "OppddddpO...",
    ".OOOOOOO....",
    "............",
    "............",
    "............",
  ],
  // DEXTERITY (SPEED + CRIT): a crosshair reticle over a red bullseye.
  icon_stat_dexterity: [
    "............",
    "....OOO.....",
    "..OO...OO...",
    ".O..OOO..O..",
    ".O.OrrrO.O..",
    "OO.OrrrO.OO.",
    ".O.OrrrO.O..",
    ".O..OOO..O..",
    "..OO...OO...",
    "....OOO.....",
    "............",
    "............",
  ],
  // INTELLECT (MAGIC + AOE): a wizard's hat — a bent purple cone with a gold
  // hatband, widening to a broad brim.
  icon_stat_intelligence: [
    "............",
    "......OO....",
    ".....OmO....",
    ".....OMO....",
    "....OmmO....",
    "....OMyO....",
    "...OmmmO....",
    "...OMmmMO...",
    "..OmmmmmO...",
    "..OMmmmMO...",
    ".OOOOOOOOO..",
    "............",
  ],
  // SPEED (MOVE SPEED): an electric-blue lightning bolt.
  icon_stat_speed: [
    "............",
    ".......OO...",
    "......OsO...",
    ".....OsO....",
    "....OseO....",
    "...OeeeeO...",
    "...OOOeeO...",
    ".....OeO....",
    "....OeO.....",
    "...OeO......",
    "...OO.......",
    "............",
  ],
  // LUCK (CRIT + LOOT): a four-leaf clover on a short stem.
  icon_stat_luck: [
    "............",
    "..OO..OO....",
    ".OlGOOGlO...",
    ".OGGGGGGO...",
    "..OGGGGO....",
    ".OGGGGGGO...",
    ".OlGOOGlO...",
    "..OO..OO....",
    "....Og......",
    "....Og......",
    "....OO......",
    "............",
  ],
  // UI action — DROP ALL: a steel waste bin with an overhanging lid, a top
  // handle, and three vertical ribs. The inventory's "trash the junk" button.
  icon_trash: [
    "............",
    "....OOOO....",
    "..OOOOOOOO..",
    "..OVVVVVVO..",
    ".OOOOOOOOOO.",
    "..OvbvbvbO..",
    "..OvbvbvbO..",
    "..OvbvbvbO..",
    "..OvbvbvbO..",
    "..OOOOOOOO..",
    "............",
    "............",
  ],
  // UI action — AUTO-EQUIP: two steel blades crossed in an X, gold guards and
  // pommels at the hilts. The inventory's "optimize my gear" button.
  icon_swords: [
    "............",
    "..VV....VV..",
    "...VV..VV...",
    "....VVVV....",
    ".....VV.....",
    "....VVVV....",
    "...VV..VV...",
    "..VV....VV..",
    ".oooo..oooo.",
    ".qq......qq.",
    ".OO......OO.",
    "............",
  ],
  // The anti-grav unit: a ring of not-metal, hovering over its own glow.
  icon_antigrav: [
    "............",
    "............",
    "....OOOO....",
    "..OOyyyyOO..",
    ".OyyOOOOyyO.",
    ".OyO....OyO.",
    ".OyyOOOOyyO.",
    "..OOyyyyOO..",
    "....OOOO....",
    "..cc....cc..",
    "....cccc....",
    "............",
  ],
  // ---- Mars (level 3) --------------------------------------------------------
  // The CYBER KATANA: angular chrome blade, allegedly shatterproof.
  icon_cyber_katana: [
    "............",
    ".......OOO..",
    "......OVxO..",
    ".....OVxxO..",
    "....OVxxO...",
    "...OVxxO....",
    "..OVxxO.....",
    ".OVxxO......",
    ".OVxO.......",
    "ONNO........",
    "ONNO........",
    ".OO.........",
  ],
  // LARRY WEBPAGE's crawler pole: a literal search bar.
  icon_search_bar: [
    "............",
    ".........OO.",
    "........OyO.",
    ".......OrO..",
    "......OjO...",
    ".....OrO....",
    "....OjO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    "..O.........",
    "............",
  ],
  // BUILD GATES's tablet: it crashes whatever it's pointed at.
  icon_blue_screen: [
    "............",
    ".OOOOOOOOO..",
    ".OeeeeeeeO..",
    ".OesssseeO..",
    ".OeeeeeeeO..",
    ".OessseeeO..",
    ".OeeeeeeeO..",
    ".OesseeeeO..",
    ".OeeeeeeeO..",
    ".OOOOOOOOO..",
    "............",
    "............",
  ],
  // PETER SEAL's letter opener: short, fast, contrarian.
  icon_contrarian_dagger: [
    "............",
    "......OO....",
    ".....OVvO...",
    "....OVvO....",
    "...OVvO.....",
    "..OVvO......",
    ".OOvOO......",
    ".OCCO.......",
    "OCCO........",
    ".OO.........",
    "............",
    "............",
  ],
  // MOSQUE's parting gift. Legally, not a flamethrower.
  icon_not_a_flamethrower: [
    "............",
    ".........y..",
    ".......yry..",
    "..OOOOOOry..",
    "..ONNNNNOy..",
    "..OOONNO....",
    "....ONNO....",
    "....ONNO....",
    "....OOO.....",
    "............",
    "............",
    "............",
  ],
  // OPTIMUSK PRIME's sidearm: a syringe that injects prompts. Steel barrel,
  // cyan payload window, needle down-right like the other diagonal arms.
  icon_prompt_injector: [
    "............",
    ".OvO........",
    "OvOvO.......",
    ".OvOvvO.....",
    "..OOvccvO...",
    "....OccvvO..",
    ".....OvvvO..",
    "......OvObO.",
    ".......ObO..",
    "........b...",
    "............",
    "............",
  ],
  // ---- Mars story items -------------------------------------------------------
  // The shrine pass: green glass, warm to the touch.
  icon_keycard_green: swapPalette(KEYCARD_ICON, { W: "G", j: "W" }),
  // The ORG CHART: one cyan box on top, every report a robot-white box.
  icon_orgchart: [
    "............",
    "....OOOO....",
    "....OccO....",
    "....OOOO....",
    "......v.....",
    "...vvvvvv...",
    "...v....v...",
    ".OOOO..OOOO.",
    ".OWWO..OWWO.",
    ".OOOO..OOOO.",
    "............",
    "............",
  ],
  // The passenger ledger: leather-bound, net-worth column included.
  icon_ledger: [
    "............",
    "............",
    ".OOOOOOOOO..",
    ".OEEEEEEEO..",
    ".OEWWWWWEO..",
    ".OEWbbWWEO..",
    ".OEWWWWWEO..",
    ".OEWbyWWEO..",
    ".OEWWWWWEO..",
    ".OOOOOOOOO..",
    "............",
    "............",
  ],
  // The MOON POST-MORTEM: a crash report, appropriately blue.
  icon_postmortem: swapPalette(MANIFEST_ICON, { W: "e", b: "W", r: "W" }),
  // The ENGAGEMENT REPORT: a dashboard still live, one row blinking red.
  icon_report: [
    "............",
    ".OOOOOOOOO..",
    ".ObbbbbbbO..",
    ".ObGGGbbbO..",
    ".ObbbbbbbO..",
    ".ObGGGGbbO..",
    ".ObbbbbbbO..",
    ".ObrrbbbbO..",
    ".ObbbbbbbO..",
    ".OOOOOOOOO..",
    "............",
    "............",
  ],
  // ---- Armor: HEAD ----------------------------------------------------------
  // The company softball cap: blue crown, white front panel, front brim.
  icon_baseball_cap: CAP_ICON,
  // The shipping floor's hard hat: gold dome, wide brim, ridge highlight.
  icon_hard_hat: [
    "............",
    "............",
    "....OOOO....",
    "...OyYYyO...",
    "..OyYYYyyO..",
    "..OyyYYyyO..",
    "..OyyyyyyO..",
    ".OOOOOOOOOO.",
    ".OyyyyyyyyO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
  ],
  // The fab shop's welding mask: dark shell, one cyan glass slot.
  icon_welding_mask: [
    "............",
    "...OOOOOO...",
    "..ObvvvvbO..",
    "..ObbbbbbO..",
    "..OesssebO..",
    "..OeeeeebO..",
    "..ObbbbbbO..",
    "..ObbbbbbO..",
    "...ObbbbO...",
    "....OOOO....",
    "............",
    "............",
  ],
  // The armory's riot helmet: navy shell, clear face shield.
  icon_riot_helmet: [
    "............",
    "....OOOO....",
    "...OJJJJO...",
    "..OJJJJJJO..",
    "..OJJJJJJO..",
    "..OsssssJO..",
    "..OsseesJO..",
    "..OsssssJO..",
    "..OJOOOJJO..",
    "...OO..OO...",
    "............",
    "............",
  ],
  // The gold-mirrored Apollo bubble: white shell, sun in the visor.
  icon_apollo_visor: [
    "............",
    "....OOOO....",
    "...OaaaaO...",
    "..OaaaaaaO..",
    "..OaOOOOaO..",
    ".OaOYYyyOaO.",
    ".OaOYyyyOaO.",
    ".OaOyyyyOaO.",
    "..OaOOOOaO..",
    "...OaaaaO...",
    "....OOOO....",
    "............",
  ],
  // The smart pistol's other half: a black targeting monocle, live lens.
  icon_monocle: [
    "............",
    "............",
    "...OOOOO....",
    "..ONNNNNO...",
    ".ONOssONNO..",
    ".ONseesNNOO.",
    ".ONseesNNyO.",
    ".ONOssONNOO.",
    "..ONNNNNO...",
    "...OOOOO....",
    "............",
    "............",
  ],
  // The neural visor: white band, magenta read-out strip.
  icon_neural_visor: [
    "............",
    "............",
    "....OOOOO...",
    "...OaaaaaO..",
    "..OaaaaaaaO.",
    "..OzZzzzzaO.",
    "..OzzzzZzaO.",
    "..OaaaaaaaO.",
    "...OOOOOOO..",
    "............",
    "............",
    "............",
  ],
  // The printed helm: one seamless ceramic piece, a single printed seam.
  icon_printed_helm: [
    "............",
    "....OOOO....",
    "...OWWWWO...",
    "..OWWWWWwO..",
    "..OWWWWWwO..",
    "..OWwwwwWO..",
    "..OWWWWWwO..",
    "..OWWWWWwO..",
    "..OWwWWwWO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // The viking helm: steel dome, nose guard, NO horns. Never horns.
  icon_viking_helm: [
    "............",
    "............",
    "....OOOO....",
    "...OvVVvO...",
    "..OvVVVvvO..",
    "..OvvVVvvO..",
    "..OvvOOvvO..",
    "..OvO..OvO..",
    "....OvvO....",
    "....OOOO....",
    "............",
    "............",
  ],
  // The knight's helm: full steel, one dark eye slit, crest ridge.
  icon_knights_helm: [
    "............",
    "....OOOO....",
    "...OvVVvO...",
    "..OvVVVvvO..",
    "..OvvvvvvO..",
    "..OOOOOOOO..",
    "..OvvvvvvO..",
    "..OvvOOvvO..",
    "..OvvvvvvO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // The great helm: the executioner era's flat-topped bucket, cross slit.
  icon_great_helm: [
    "............",
    "...OOOOOO...",
    "..OvVVVVvO..",
    "..OvvvvvvO..",
    "..OOOOOOOO..",
    "..OvvOOvvO..",
    "..OvvvvvvO..",
    "..OvvOOvvO..",
    "..OvvvvvvO..",
    "..OvvvvvvO..",
    "...OOOOOO...",
    "............",
  ],
  // ---- Armor: CHEST ---------------------------------------------------------
  // The hero's own T-SHIRT: plain white cotton.
  icon_tshirt: [
    "............",
    "............",
    ".OOO.OO.OOO.",
    "OWWWOWWOWWWO",
    "OWOWWWWWWOWO",
    "OOOWWwWWWOOO",
    "...OWWWWO...",
    "...OWwWWO...",
    "...OWWWWO...",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // Maintenance coveralls: hazmat-yellow bib and straps.
  icon_coveralls: [
    "............",
    "............",
    ".OO......OO.",
    ".OhO.OO.OhO.",
    ".OhOOhhOOhO.",
    ".OhhhHhhhhO.",
    ".OOhhhhhOO..",
    "..OhHhhhO...",
    "..OhhhhHO...",
    "..OhhhhhO...",
    "..OOOOOOO...",
    "............",
  ],
  // The security desk's kevlar vest: navy panels, strapped sides.
  icon_kevlar_vest: [
    "............",
    "............",
    ".OOO....OOO.",
    ".OJOOOOOOJO.",
    ".OJJJJJJJJO.",
    ".OJJOJJOJJO.",
    ".OJJJJJJJJO.",
    "..OJJJJJJO..",
    "..OJOJJOJO..",
    "..OJJJJJJO..",
    "..OOOOOOOO..",
    "............",
  ],
  // The crew survival kit's flight jacket: tan leather, wool collar.
  icon_flight_jacket: [
    "............",
    "............",
    ".OO.OOOO.OO.",
    ".ODOWWWWODO.",
    ".ODDOWWODDO.",
    ".ODDDttDDDO.",
    ".OODtttttOO.",
    "..ODttttDO..",
    "..ODtttttO..",
    "..ODDDDDDO..",
    "..OOOOOOOO..",
    "............",
  ],
  // The micrometeoroid vest: quilted whipple layers, lander-white.
  icon_micro_vest: [
    "............",
    "............",
    ".OOO....OOO.",
    ".OaOOOOOOaO.",
    ".OaaaaaaaaO.",
    ".OAAAAAAAAO.",
    ".OaaaaaaaaO.",
    "..OAAAAAAO..",
    "..OaaaaaaO..",
    "..OAAAAAAO..",
    "..OOOOOOOO..",
    "............",
  ],
  // The colony printer's polymer shell: smooth white, black trim.
  icon_polymer_shell: [
    "............",
    "............",
    ".OOO....OOO.",
    ".ONOOOOOONO.",
    ".ONWWWWWWNO.",
    ".OWWwWWWWWO.",
    ".OWWWWwWWWO.",
    "..OWwWWWWO..",
    "..OWWWWwWO..",
    "..ONNNNNNO..",
    "..OOOOOOOO..",
    "............",
  ],
  // Nanoweave plate: a lattice woven at a scale nobody audits.
  icon_nanoweave: [
    "............",
    "............",
    ".OOO....OOO.",
    ".ONOOOOOONO.",
    ".ONNzNNzNNO.",
    ".ONzNNzNNNO.",
    ".ONNzNNzNNO.",
    "..ONNzNNzO..",
    "..OzNNzNNO..",
    "..ONNNNNNO..",
    "..OOOOOOOO..",
    "............",
  ],
  // The AEGIS exoplate: white shell braced around a gold core.
  icon_aegis_plate: [
    "............",
    "............",
    ".OOO....OOO.",
    ".OaOOOOOOaO.",
    ".OaaaaaaaaO.",
    ".OaaAyyAaaO.",
    ".OaaAyYAaaO.",
    "..OaAyyAaO..",
    "..OaaAAaaO..",
    "..OaaaaaaO..",
    "..OOOOOOOO..",
    "............",
  ],
  // The centurion's cuirass: legion bronze, muscled front.
  icon_cuirass: [
    "............",
    "............",
    ".OOO....OOO.",
    ".OoOOOOOOoO.",
    ".OooooooooO.",
    ".OoqooooqoO.",
    ".OooqooqooO.",
    "..OoooooqO..",
    "..OoqqqqoO..",
    "..OooooooO..",
    "..OOOOOOOO..",
    "............",
  ],
  // The chainmail hauberk: patient steel rings, row on row.
  icon_chainmail: [
    "............",
    "............",
    ".OOO....OOO.",
    ".OvOOOOOOvO.",
    ".OvVvVvVvVO.",
    ".OVvVvVvVvO.",
    ".OvVvVvVvVO.",
    "..OvVvVvVO..",
    "..OVvVvVvO..",
    "..OvVvVvVO..",
    "..OOOOOOOO..",
    "............",
  ],
  // ---- Armor: LEGS ----------------------------------------------------------
  // The hero's own JEANS: honest denim.
  icon_jeans: JEANS_ICON,
  // Warehouse cargo pants: green, thigh pockets.
  icon_cargo_pants: [
    "............",
    "............",
    "..OOOOOOOO..",
    "..OggggggO..",
    "..OgGGgGGO..",
    "..OggOOggO..",
    "..OggO.OggO.",
    "..OGgO.OgGO.",
    "..OggO.OggO.",
    "..OggO.OggO.",
    "..OOO...OOO.",
    "............",
  ],
  // Padded work pants: tan canvas, sewn-in knee pads.
  icon_work_pants: [
    "............",
    "............",
    "..OOOOOOOO..",
    "..OttttttO..",
    "..OttttttO..",
    "..OttOOttO..",
    "..OttO.OttO.",
    "..ODDO.ODDO.",
    "..ODDO.ODDO.",
    "..OttO.OttO.",
    "..OOO...OOO.",
    "............",
  ],
  // Pressure trousers: the lower half of a suit, gold ring seals.
  icon_pressure_trousers: [
    "............",
    "............",
    "..OOOOOOOO..",
    "..OyyyyyyO..",
    "..OaaaaaaO..",
    "..OaaOOaaO..",
    "..OaaO.OaaO.",
    "..OaAO.OAaO.",
    "..OaaO.OaaO.",
    "..OyyO.OyyO.",
    "..OOO...OOO.",
    "............",
  ],
  // Servo greaves: printed steel, powered joints.
  icon_servo_greaves: [
    "............",
    "............",
    "..OOOOOOOO..",
    "..OvvvvvvO..",
    "..OvVvvVvO..",
    "..OvvOOvvO..",
    "..OveO.OevO.",
    "..OvvO.OvvO.",
    "..OveO.OevO.",
    "..OvvO.OvvO.",
    "..OOO...OOO.",
    "............",
  ],
  // Plate greaves: full steel legs, knee cops.
  icon_plate_greaves: [
    "............",
    "............",
    "..OOOOOOOO..",
    "..OvVVVvvO..",
    "..OvvvvvvO..",
    "..OVvOOvVO..",
    "..OvvO.OvvO.",
    "..OVVO.OVVO.",
    "..OvvO.OvvO.",
    "..OvvO.OvvO.",
    "..OOO...OOO.",
    "............",
  ],
  // ---- Armor: FEET ----------------------------------------------------------
  // The hero's own LEATHER BOOTS: broken in years ago.
  icon_leather_boots: [
    "............",
    "............",
    "............",
    "..OOO..OOO..",
    "..OkO..OkO..",
    "..OkO..OkO..",
    "..OkkO.OkkO.",
    "..OkkO.OkkO.",
    ".OkkkOOkkkO.",
    ".OkkkkOkkkkO",
    ".OOOOO.OOOO.",
    "............",
  ],
  // Office sneakers: white uppers, red flash.
  icon_sneakers: [
    "............",
    "............",
    "............",
    "..OOO..OOO..",
    "..OWO..OWO..",
    "..OWO..OWO..",
    "..OWrO.OWrO.",
    "..OWWO.OWWO.",
    ".OWWWOOWWWO.",
    ".OwwwwOwwwwO",
    ".OOOOO.OOOO.",
    "............",
  ],
  // Steel-toe boots: warehouse leather, bright caps.
  icon_steel_boots: [
    "............",
    "............",
    "............",
    "..OOO..OOO..",
    "..OkO..OkO..",
    "..OkO..OkO..",
    "..OkkO.OkkO.",
    "..OkkO.OkkO.",
    ".OkkvOOkkvO.",
    ".OkkvvOkkvvO",
    ".OOOOO.OOOO.",
    "............",
  ],
  // Lunar overshoes: galoshes rated for the Sea of Tranquility.
  icon_lunar_overshoes: [
    "............",
    "............",
    "............",
    "..OOO..OOO..",
    "..OfO..OfO..",
    "..OfO..OfO..",
    "..OffO.OffO.",
    "..OFfO.OFfO.",
    ".OfffOOfffO.",
    ".OffffOffffO",
    ".OOOOO.OOOO.",
    "............",
  ],
  // MOON BOOTS: the classic print-leaving kind. Big soles, bigger history.
  icon_moon_boots: [
    "............",
    "............",
    "............",
    "..OOO..OOO..",
    "..OaO..OaO..",
    "..OaO..OaO..",
    "..OaaO.OaaO.",
    "..OaAO.OaAO.",
    ".OaaaOOaaaO.",
    ".OAAAAOAAAAO",
    ".OOOOO.OOOO.",
    "............",
  ],
  // Gecko soles: printed shoes that grip like the lizard they audit.
  icon_gecko_soles: [
    "............",
    "............",
    "............",
    "..OOO..OOO..",
    "..ONO..ONO..",
    "..ONO..ONO..",
    "..ONNO.ONNO.",
    "..ONNO.ONNO.",
    ".ONNNOONNNO.",
    ".OlGlGOlGlGO",
    ".OOOOO.OOOO.",
    "............",
  ],
  // Mag boots: printed steel, live magnet coils.
  icon_mag_boots: [
    "............",
    "............",
    "............",
    "..OOO..OOO..",
    "..OvO..OvO..",
    "..OvO..OvO..",
    "..OvvO.OvvO.",
    "..OveO.OveO.",
    ".OvvvOOvvvO.",
    ".OeeeeOeeeeO",
    ".OOOOO.OOOO.",
    "............",
  ],
  // Legionary sandals: caligae, two thousand years broken-in.
  icon_sandals: [
    "............",
    "............",
    "............",
    "............",
    "..OOO..OOO..",
    "..ODO..ODO..",
    "..O.DO.O.DO.",
    "..OD.O.OD.O.",
    ".ODDDOODDDO.",
    ".ODDDDODDDDO",
    ".OOOOO.OOOO.",
    "............",
  ],
  // Sabatons: segmented steel feet, the last word in footwear.
  icon_sabatons: [
    "............",
    "............",
    "............",
    "..OOO..OOO..",
    "..OvO..OvO..",
    "..OVO..OVO..",
    "..OvvO.OvvO.",
    "..OVVO.OVVO.",
    ".OvvvOOvvvO.",
    ".OvVvVOvVvVO",
    ".OOOOO.OOOO.",
    "............",
  ],
  // The moon ground crew's MISSION CAP: the softball cap in mission tan.
  icon_mission_cap: swapPalette(CAP_ICON, { j: "t", W: "D" }),
  // THERMAL LEGGINGS: the jeans cut in insulation white.
  icon_thermal_leggings: swapPalette(JEANS_ICON, { j: "w" }),
  // CARBON LEGGINGS: the same cut printed in matte black weave.
  icon_carbon_leggings: swapPalette(JEANS_ICON, { j: "N" }),
  // CHAUSSES: mail for the legs — the jeans cut rendered in rings.
  icon_chausses: swapPalette(JEANS_ICON, { j: "v" }),
  // ---- HUD widgets -----------------------------------------------------------
  // The TREASURE MAP: the HUD's map button, drawn like a pirate chart —
  // torn parchment (20×14, wider than the inventory icons so it fills the
  // clock-width button), a bold red X, a dashed ink trail walking up from
  // the corner, a compass cross top-left, and a blue wave under the X.
  icon_treasure_map: [
    "....................",
    "..OOOOOOOOOOOOOOOO..",
    ".OttttttttttttttttO.",
    ".OtkttttttttrtttrtO.",
    "OtkkkttttttttrtrttO.",
    "OttkttttttttttrtttO.",
    ".OtttttttttttrtrtDO.",
    ".OttttttttttrtttrDO.",
    "OttttttttkkttttttDO.",
    "OtttttkktttttjjjtDO.",
    ".OtkktttttttttttDDO.",
    ".OtttttttttttDDDDO..",
    "..OOOOOOOOOOOOOOO...",
    "....................",
  ],
  // The TRIBUTE SCHEDULE: a Gantt chart chiseled in stone, one milestone lit.
  icon_tablet: [
    "............",
    "..OOOOOOO...",
    ".OvvvvvvvO..",
    ".OvbbbvvvO..",
    ".OvvvvvvvO..",
    ".OvbbbbvvO..",
    ".OvvvvvvvO..",
    ".OvGGvvvvO..",
    ".OvvvvvvvO..",
    ".OOOOOOOOO..",
    "............",
    "............",
  ],
  // ---- EASTWORLD (level 5): the park's hybrid frontier arsenal ---------------
  // The MONO-WIRE LARIAT: a coiled rope with a wire glint.
  icon_lariat: [
    "............",
    "...OOOOO....",
    "..OBBBBBO...",
    ".OBBOOOBBO..",
    ".OBO...OBO..",
    ".OBO...OBO..",
    ".OBO...OBVO.",
    ".OBBOOOBBOVO",
    "..OBBBBBO.O.",
    "...OOOOOVO..",
    "........O...",
    "............",
  ],
  // The PLASMA PEACEMAKER: a six-shooter with a glowing cylinder — grip
  // lower-left, muzzle upper-right (the paper-doll hand convention).
  icon_peacemaker: [
    "............",
    "............",
    "..OOOOOOOOO.",
    ".OvvvvvvvvvO",
    ".OOeeOOOOOO.",
    "..OeeOO.....",
    "..OvveO.....",
    "..OBBOO.....",
    ".OBBO.......",
    ".OBO........",
    "..O.........",
    "............",
  ],
  // The PLASMA BRANDING IRON: a rod ending in a white-hot brand.
  icon_branding_iron: [
    "............",
    ".........OO.",
    "........OBO.",
    ".......OBO..",
    "......OBO...",
    ".....OBO....",
    "..OOOBO.....",
    ".OyYOO......",
    ".OYyO.......",
    ".OyyO.......",
    "..OO........",
    "............",
  ],
  // The MAGLEV REPEATER: a lever rifle on a rail.
  icon_repeater: [
    "............",
    "............",
    "........OO..",
    "..OOOOOOvvO.",
    ".OeeeeeevvO.",
    "..OOOOOBBO..",
    "......OBBO..",
    ".....OBBO...",
    "....OBOO....",
    "....OO......",
    "............",
    "............",
  ],
  // The SNAKE-OIL SPRAYER: a bottle of the good stuff, trust the label.
  icon_snake_oil: [
    "............",
    "....OOO.....",
    "....OkO.....",
    "...OGGGO....",
    "..OGllGGO...",
    "..OGGGGGO...",
    "..OWWWWWO...",
    "..OWrrWWO...",
    "..OGGGGGO...",
    "..OgGGGgO...",
    "...OOOOO....",
    "............",
  ],
  // HIGH NOON: the sun, holstered.
  icon_high_noon: [
    "............",
    ".....OO.....",
    "...OyYyO....",
    "..OyYYYyO...",
    ".OOYYyYYOO..",
    ".OOYyyyYOO..",
    ".OOYYyYYOO..",
    "..OyYYYyO...",
    "...OyYyO....",
    ".....OO.....",
    "....ONNO....",
    ".....OO.....",
  ],
  // The TRASH estate: a cardboard sword, sad and damp.
  icon_cardboard_sword: [
    "............",
    ".....OO.....",
    "....OBEO....",
    "....OBEO....",
    "....OEBO....",
    "...OBEO.....",
    "...OEBO.....",
    "..OOBBOO....",
    "....OEO.....",
    "....OEO.....",
    ".....O......",
    "............",
  ],
  // NOT-A-FLAMETHROWER (EMPTY): a canister and a cold nozzle.
  icon_busted_flamethrower: [
    "............",
    "............",
    "..OOOO......",
    ".OvvvvO.OO..",
    ".OvvvvOONNO.",
    ".OvbbvvvNNO.",
    ".OvvvvOONNO.",
    ".OvvvvO.OO..",
    "..OOOO......",
    ".....E......",
    "............",
    "............",
  ],
  // The CYBERVAN WIPER BLADE: a very flat, very stainless strip.
  icon_cybervan_wiper: [
    "............",
    "............",
    "........OO..",
    ".......OvO..",
    "......OvO...",
    ".....OvO....",
    "....OvO.....",
    "...OvO......",
    "..ONO.......",
    "..OO........",
    "............",
    "............",
  ],
  // The SERVO STETSON: a ten-gallon hat with a one-gallon gyro.
  icon_stetson: [
    "............",
    "............",
    "....OOOO....",
    "...OBBBBO...",
    "...OBBBBO...",
    "..OBEEEEBO..",
    ".OBBBBBBBBO.",
    "OBBBBBBBBBBO",
    ".OOOOOOOOOO.",
    "............",
    "............",
    "............",
  ],
  // The MIRRORSHADE VISOR: an eye-band that shows you only yourself.
  icon_mirrorshade: [
    "............",
    "............",
    "............",
    ".OOOOOOOOOO.",
    "ONNNNNNNNNNO",
    "ONcNNNNNcNNO",
    ".OOOOOOOOOO.",
    "............",
    "............",
    "............",
    "............",
    "............",
  ],
  // The EXO-DUSTER: a trail coat over a printed frame.
  icon_duster: [
    "............",
    "...OOOOOO...",
    "..OBBBBBBO..",
    ".OBBOBBOBBO.",
    ".OBBOBBOBBO.",
    ".OEBOBBOBEO.",
    ".OBBOBBOBBO.",
    ".OBBOBBOBBO.",
    ".OEBOBBOBEO.",
    ".OBBOBBOBBO.",
    "..OOOOOOOO..",
    "............",
  ],
  // The TIN STAR CUIRASS: the star IS the armor.
  icon_tin_star: [
    "............",
    "..OOOOOOOO..",
    ".OvvvvvvvvO.",
    ".OvvvaavvvO.",
    ".OvvaaaavvO.",
    ".OvaaaaaavO.",
    ".OvvaaaavvO.",
    ".OvvvaavvvO.",
    ".OvvvvvvvvO.",
    "..OOOOOOOO..",
    "............",
    "............",
  ],
  // The RATTLESNAKE CHAPS: they still rattle. Ignore it.
  icon_chaps: [
    "............",
    "............",
    "..OOOOOOOO..",
    "..ODDDDDDO..",
    "..ODDDDDDO..",
    "..ODDOODDO..",
    "..ODDO.ODDO.",
    "..OBDO.ODBO.",
    "..ODDO.ODDO.",
    "..OBDO.ODBO.",
    "..OOO...OOO.",
    "............",
  ],
  // The SPUR-JET BOOTS: the rowels are turbines.
  icon_spur_boots: [
    "............",
    "............",
    "...OOO......",
    "...ODDO.....",
    "...ODDO.....",
    "...ODDO.....",
    "...ODDOOO...",
    "...ODDDDDO..",
    "..aODDDDDO..",
    ".OaOOOOOOO..",
    "..a.........",
    "............",
  ],
  // The SHERIFF'S BADGE: authority is mostly posture.
  icon_sheriff_badge: [
    "............",
    "............",
    ".....OO.....",
    "....OaaO....",
    "..OOOaaOOO..",
    ".OaaaaaaaaO.",
    "..OOaaaaOO..",
    "....OaaO....",
    "...OaOOaO...",
    "...OO..OO...",
    "............",
    "............",
  ],
  // SEAGULL'S PONYTAIL: it remembers seven kinds of ju-jutsu.
  icon_ponytail: [
    "............",
    "....OOO.....",
    "...OkkkO....",
    "...OkkkO....",
    "....OkkO....",
    "....OkkO....",
    "...OkkO.....",
    "...OkkO.....",
    "....OkkO....",
    "....OkkO....",
    ".....OO.....",
    "............",
  ],
  // The BOTTOMLESS CARAFE: it refills itself, and so do you.
  icon_carafe: [
    "............",
    "....OOO.....",
    "....OWO.....",
    "...OWWWO....",
    "..OWrrrWO...",
    ".OWrrrrrWO..",
    ".OWrirrrWO..",
    ".OWrrrrrWO..",
    "..OWrrrWO...",
    "...OOOOO....",
    "............",
    "............",
  ],
  // PUTAIN's brand watches: gold base, silver and rose-gold recolors below.
  icon_watch_gold: [
    "............",
    "....OOOO....",
    "....OqqO....",
    "...OOOOOO...",
    "..OoWWWooO..",
    "..OoWyWooO..",
    "..OoWWyooO..",
    "..OooooooO..",
    "...OOOOOO...",
    "....OqqO....",
    "....OOOO....",
    "............",
  ],
  // The EASTWORLD BROCHURE: the fine print waives your organs.
  icon_brochure: [
    "............",
    "..OOOOOOO...",
    ".OWWWWWWWO..",
    ".OWyyWWWWO..",
    ".OWyyWWwWO..",
    ".OWWWWwWWO..",
    ".OWrWWWwWO..",
    ".OWWWwWWWO..",
    ".OWwWWWwWO..",
    ".OOOOOOOO...",
    "............",
    "............",
  ],
  // SEAGULL's ALL-ACCESS PASS: laminated, autographed, to himself.
  icon_pass: [
    "............",
    ".....OO.....",
    "....ONNO....",
    "..OOOOOOOO..",
    ".OWWWWWWWWO.",
    ".OWyyyyyyWO.",
    ".OWWWWWWWWO.",
    ".OWwwwWWWWO.",
    ".OWWWWWwwWO.",
    "..OOOOOOOO..",
    "............",
    "............",
  ],
  // THE SNOW ARCHIVE: a hard drive in a faraday sleeve — the training set
  // the SUPERCORE was raised on. Label up top, activity light still blinking.
  icon_snow_archive: [
    "............",
    "..OOOOOOOO..",
    ".ONNNNNNNNO.",
    ".ONWWWWwNNO.",
    ".ONWwwwwNNO.",
    ".ONNNNNNNNO.",
    ".ONeeeeeeNO.",
    ".ONNNNNNNNO.",
    ".ONNONNONNO.",
    "..OOOOOOOO..",
    "............",
    "............",
  ],
  // SNOW's DEAD MAN'S SWITCH: a key fob with a red publish button and one
  // blue heartbeat LED. If it stops checking in, everything goes out.
  icon_dead_switch: [
    "............",
    ".....OO.....",
    "....OOOO....",
    ".....OO.....",
    "...OOOOOO...",
    "..ONNNNNNO..",
    "..ONrrrNNO..",
    "..ONrrrNNO..",
    "..ONNNNNNO..",
    "..ONeeNNNO..",
    "..OOOOOOOO..",
    "............",
  ],
  // THE ANNEXATION MAP: every building renamed after a city he couldn't take.
  icon_annex_map: [
    "............",
    "..OOOOOOOO..",
    ".OttttttttO.",
    ".OtDtttrttO.",
    ".OttttrrttO.",
    ".OttrrrttDO.",
    ".OtrrttttDO.",
    ".OttttDDttO.",
    ".OttttttttO.",
    "..OOOOOOOO..",
    "............",
    "............",
  ],
};

// The other two watches on PUTAIN's wrist: silver and rose-gold recolors of
// the gold face — never redraws.
SPRITES.icon_watch_silver = swapPalette(SPRITES.icon_watch_gold, {
  o: "a",
  q: "A",
  y: "A",
});
SPRITES.icon_watch_rose = swapPalette(SPRITES.icon_watch_gold, {
  o: "u",
  q: "U",
  y: "U",
});
// The PRAIRIE IRON: the stage-prop revolver, blued steel over the plasma cut.
SPRITES.icon_prairie_iron = swapPalette(SPRITES.icon_peacemaker, {
  v: "N",
  e: "y",
});

export default {
  name: "icons",
  /** Ground tile behind this family's contact sheet. */
  ground: "lab_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {},
  contrastExempt: [],
};
