// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The icons family (see the `pixel-assets` skill): every 12×12 inventory
// icon — weapons, gear, abilities, story items. Drawn in UI panels, never
// on the ground. One string per pixel row, one character per pixel; `.` is
// transparent and every other char must exist in CORE_PALETTE
// (sprite-data/core.mjs) or this family's local palette.

import { swapPalette } from "../asset-tools/palette.mjs";

// Icons that spawn palette variants live as consts: the trophy/elite
// versions are swapPalette calls, never redraws.
const TASER_ICON = [
  "............",
  "...aa..aa...",
  "...Oa..aO...",
  "..OOOOOOO...",
  "..OhhhhhO...",
  "..OhHhhhO...",
  "..OhhhhhO...",
  "...OhhhO....",
  "...OhhhO....",
  "...OOOOO....",
  "............",
  "............",
];

const LASER_ICON = [
  "............",
  ".rr.........",
  ".rr.........",
  "....OO......",
  "...ObbO.....",
  "....ObbO....",
  ".....ObbO...",
  "......ObbO..",
  ".......ObO..",
  "........O...",
  "............",
  "............",
];

const PISTOL_ICON = [
  "............",
  "............",
  "..OOOOOO....",
  "..OaaaaAO...",
  "..OOOaaO....",
  "....OaAO....",
  "....OaAO....",
  "....OOO.....",
  "............",
  "............",
  "............",
  "............",
];

// The keycards and the paper trail: one card, one document, recolored per
// plot thread.
const KEYCARD_ICON = [
  "............",
  "............",
  ".OOOOOOOOOO.",
  ".OWWWWWWWWO.",
  ".OjjjjjjjjO.",
  ".OWWWWWWWWO.",
  ".OWyyOWWwWO.",
  ".OWyyOWwwWO.",
  ".OWWWWWWWWO.",
  ".OOOOOOOOOO.",
  "............",
  "............",
];

const MANIFEST_ICON = [
  "............",
  ".OOOOOOOOO..",
  ".OWWWWWWWO..",
  ".OWbbbbWWO..",
  ".OWWWWWWWO..",
  ".OWbbbbbWO..",
  ".OWWWWWWWO..",
  ".OWrrrbWWO..",
  ".OWWWWWWWO..",
  ".OOOOOOOOO..",
  "............",
  "............",
];

// The GOLDEN STAPLER icon is the stapler re-skinned in trophy gold — a
// swapPalette call, never a redraw.
const STAPLER_ICON = [
  "............",
  "..OOOOOO....",
  ".OrrrrrrO...",
  ".OrrrrrrOO..",
  "..OOOOOrrO..",
  ".OaaaaaaaO..",
  ".OAAAAAAAO..",
  "..OOOOOOO...",
  "............",
  "............",
  "............",
  "............",
];

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  // Electric blue + charged white-blue core for the storm bolt.
  e: [90, 180, 255],
  s: [214, 240, 255],
  // PETER SEAL's teal — grip of the contrarian dagger.
  C: [82, 158, 168],
  // Billionaire black (matches the mars family): grips and gun bodies.
  N: [48, 52, 68],
  // Level-up stat glyphs: a darker flesh shade for the strength arm and a
  // pink brain ramp for intellect. Skin base `p`, greens `G`/`g`/`l`, red
  // `r`/`i`, gold `y`/`Y` and the electric blue above are reused from the core.
  d: [176, 120, 92], // strength: skin shadow
  u: [232, 150, 172], // intellect: brain pink
  U: [196, 104, 132], // intellect: brain fold shadow
};

const SPRITES = {
  // ARMSTRONG's Apollo survival-kit machete: broad steel blade, wood grip.
  icon_machete: [
    "............",
    ".......OOO..",
    "......OaaO..",
    ".....OaaAO..",
    "....OaaAO...",
    "...OaaAO....",
    "..OaaAO.....",
    ".OaaAO......",
    ".OaAO.......",
    "OkkO........",
    "OkkO........",
    ".OO.........",
  ],
  // The MOON'S BLADE trophy: a pale spectral blade, ghost-lit.
  icon_moons_blade: [
    "............",
    ".......OOO..",
    "......OxxO..",
    ".....OxxcO..",
    "....OxxcO...",
    "...OxxcO....",
    "..OxxcO.....",
    ".OxxcO......",
    ".OxcO.......",
    "OkkO........",
    "OkkO........",
    ".OO.........",
  ],
  // The CRUDE SWORD: the hero's own blade off the wall, the default starting
  // weapon. Dull steel, a gold crossguard, a wrapped grip — rough but his.
  icon_crude_sword: [
    "............",
    ".......OOO..",
    "......OVvO..",
    ".....OVvvO..",
    "....OVvvO...",
    "...OVvvO....",
    "..OVvvO.....",
    ".OqOvOqO....",
    "..OkkO......",
    "..OkkO......",
    "...OO.......",
    "............",
  ],
  // Inventory icons, 12×12.
  icon_blaster: [
    "............",
    "............",
    ".OOOOOOOOO..",
    ".OAAAAAAAyO.",
    ".OAAAAAAAyO.",
    ".OOOOAAOOO..",
    "....OAAO....",
    "....OAAO....",
    "....OOOO....",
    "............",
    "............",
    "............",
  ],
  icon_wand: [
    "............",
    "........OO..",
    ".......OLLO.",
    "......OLPPO.",
    "......OPPO..",
    ".....OkkO...",
    "....OkkO....",
    "...OkkO.....",
    "..OkkO......",
    "..OkO.......",
    "...O........",
    "............",
  ],
  icon_wrench: [
    "............",
    ".OO....OO...",
    ".OAO..OAO...",
    ".OAAOOAAO...",
    "..OAAAAO....",
    "...OAAO.....",
    "....OAAO....",
    ".....OAAO...",
    "......OAAO..",
    ".......OAO..",
    "........O...",
    "............",
  ],
  icon_suit: [
    "............",
    "..OOOOOOOO..",
    ".OaaaaaaaaO.",
    ".OaaOrrOaaO.",
    ".OaaaaaaaaO.",
    ".OAaaaaaaAO.",
    ".OAaaaaaaAO.",
    "..OaaaaaaO..",
    "..OAAAAAAO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  icon_charm: [
    "............",
    "....OOOO....",
    "...OFFFFO...",
    "..OFFOOOO...",
    "..OFO.......",
    "..OFO.......",
    "..OFO.......",
    "..OFFOOOO...",
    "...OFFFFO...",
    "....OOOO....",
    "............",
    "............",
  ],
  // The simple base-type weapons (Diablo-style unnamed drops).
  // A length of scavenged conduit: dull steel, flanged ends.
  icon_pipe: [
    "............",
    "........OO..",
    ".......OaaO.",
    "......OaaAO.",
    ".....OaaAO..",
    "....OaaAO...",
    "...OaaAO....",
    "..OaaAO.....",
    ".OaaAO......",
    ".OaAO.......",
    "..OO........",
    "............",
  ],
  // A geologist's sledge: heavy steel head, wooden haft.
  icon_hammer: [
    "............",
    "..OOOOOOO...",
    ".OaaaaaaAO..",
    ".OaaaaaaAO..",
    ".OAAAAAAAO..",
    "..OOOkOOO...",
    ".....OkO....",
    ".....OkO....",
    ".....OkO....",
    ".....OkO....",
    "......O.....",
    "............",
  ],
  // A compact sidearm: shorter and duller than the hero's blaster.
  icon_pistol: PISTOL_ICON,
  // A long-barreled rifle with a wooden stock.
  icon_rifle: [
    "............",
    ".........OO.",
    "........OaO.",
    ".......OaO..",
    "......OaO...",
    ".....OaO....",
    "....OaO.....",
    "...OkkO.....",
    "..OkkO......",
    "..OkO.......",
    "...O........",
    "............",
  ],
  // A wand crowned with a golden star.
  icon_star_wand: [
    "............",
    ".....OyO....",
    "....OyYyO...",
    ".....OyO....",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    ".OO.........",
    "............",
    "............",
  ],
  // A wand bearing a violet void orb.
  icon_void_wand: [
    "............",
    ".....OO.....",
    "....OmmO....",
    "....OmMO....",
    ".....OO.....",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    "..O.........",
    "............",
  ],
  // Ability pickups: time-limited powers.
  // FIRE ORBS: three fireballs mid-orbit.
  icon_fire_orbs: [
    "............",
    "....OO......",
    "...OrYO.....",
    "....OO......",
    "............",
    ".OO.....OO..",
    "OrYO...OrYO.",
    ".OO.....OO..",
    "............",
    "............",
    "............",
    "............",
  ],
  // STORM CELL: the classic thunderbolt silhouette in electric blue — a broad
  // top flag slanting down-left, the signature notch kicking right, then a
  // lower stroke tapering to a point at the bottom-left. Clean outline.
  icon_storm: [
    ".....OOOO...",
    "....OOseO...",
    "...OOeeOO...",
    "..OOeeOOOO..",
    "..OeesseeO..",
    "..OOOOeseO..",
    "...OOeeeOO..",
    "..OOeeeOO...",
    ".OOeseOO....",
    ".OeeeOO.....",
    ".OOOOO......",
    "............",
  ],
  // STASIS FIELD: a pale ring holding still around a speck of astronaut.
  icon_stasis: [
    "............",
    "....xxxx....",
    "..xx....xx..",
    ".x........x.",
    ".x........x.",
    "x....aa....x",
    "x....aa....x",
    ".x........x.",
    ".x........x.",
    "..xx....xx..",
    "....xxxx....",
    "............",
  ],
  // SCREEN NUKE: a squat bomb, fuse lit.
  icon_nuke: [
    "........yy..",
    "....OO..y...",
    "...OkkOy....",
    "..OOkkOO....",
    ".OaaAAAAO...",
    "OaaAAAAAAO..",
    "OaAAAAAAAO..",
    "OaAAAAAAAO..",
    "OAAAAAAAAO..",
    ".OAAAAAAO...",
    "..OOOOOO....",
    "............",
  ],
  // ITEM MAGNET: the classic red horseshoe, poles down.
  icon_magnet: [
    "............",
    "...rrrrrr...",
    "..rrrrrrrr..",
    ".rrr....rrr.",
    ".rr......rr.",
    ".rr......rr.",
    ".rr......rr.",
    ".rr......rr.",
    ".WW......WW.",
    ".WW......WW.",
    "............",
    "............",
  ],
  // ---- SpaceZ HQ weapons & gear icons (12×12) -------------------------------
  icon_stapler: STAPLER_ICON,
  icon_golden_stapler: swapPalette(STAPLER_ICON, { r: "y", a: "o", A: "q" }),
  // A gray slab of keys — the IT department's last stand.
  icon_keyboard: [
    "............",
    "............",
    "............",
    ".OOOOOOOOOO.",
    ".OvvvvvvvvO.",
    ".OvTvTvTvvO.",
    ".OvTvTvTvvO.",
    ".OvvTTTTvvO.",
    ".ObbbbbbbbO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
  ],
  // The janitor's mop: long handle, stringy head.
  icon_mop: [
    "............",
    ".........OO.",
    "........OkO.",
    ".......OkO..",
    "......OkO...",
    ".....OkO....",
    "....OkO.....",
    "..OOkOO.....",
    ".OWWWWWO....",
    ".OWwWwWO....",
    ".OWOWOWO....",
    "............",
  ],
  // Red cylinder, white label, hose nozzle up top.
  icon_extinguisher: [
    "............",
    "....OaO.....",
    "...OOOOO....",
    "..OrrrrrO...",
    "..OrWWrrO...",
    "..OrWWrrO...",
    "..OrrrrrO...",
    "..OrrrrrO...",
    "..OrrrrqO...",
    "...OOOO.....",
    "............",
    "............",
  ],
  // Security-issue taser: yellow body, twin prongs.
  icon_taser: TASER_ICON,
  // A pen light with a hot red dot on the far wall.
  icon_laser_pointer: LASER_ICON,
  // Something unlabeled from the lab shelf, glowing faintly green.
  icon_beaker: [
    "............",
    "...OxxO.....",
    "....xx......",
    "....xx......",
    "...OxxO.....",
    "..OxxxxO....",
    ".OxnnnnxO...",
    ".OnnnnnnO...",
    ".OnnnnnnO...",
    "..OOOOOO....",
    "............",
    "............",
  ],
  // The guard's baton: dark shaft, wooden grip.
  icon_baton: [
    "............",
    ".........OO.",
    "........ObO.",
    ".......ObO..",
    "......ObO...",
    ".....ObO....",
    "....ObO.....",
    "...OkO......",
    "..OkO.......",
    "..OO........",
    "............",
    "............",
  ],
  // Cleanroom tooling rated for rocket hulls — MUSKRAT's toothpick.
  icon_plasma_cutter: [
    "..........cc",
    ".........cWc",
    "........cWWc",
    ".......cWWc.",
    ".....OvvWc..",
    "....OvvO....",
    "...OvvO.....",
    "..OkkO......",
    ".OkkO.......",
    ".OO.........",
    "............",
    "............",
  ],
  // White coat over a blue shirt — the LAB COAT suit gear.
  icon_lab_coat: [
    "............",
    "..OOOOOOOO..",
    ".OWWWOOWWWO.",
    ".OWWOjjOWWO.",
    ".OWWWWWWWWO.",
    ".OwWWWWWWwO.",
    ".OwWWWWWWwO.",
    "..OWWWWWWO..",
    "..OwwwwwwO..",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // THE ARCHITECT's PASSAGE CHIP: a microprocessor die, gold contact pins on
  // every side, a glowing cyan core — the implant he cut into his own skull.
  icon_passage_chip: [
    "............",
    "...y.yy.y...",
    "..OOOOOOOO..",
    "..OvvvvvvO..",
    "..OvOccOvO..",
    "y.OvcxxcvO.y",
    "y.OvcxxcvO.y",
    "..OvOccOvO..",
    "..OvvvvvvO..",
    "..OOOOOOOO..",
    "...y.yy.y...",
    "............",
  ],
  // The ID BADGE charm: photo, smudged name, gold clip.
  icon_badge: [
    "............",
    "....OyO.....",
    "..OOOOOOOO..",
    ".OWWWWWWWWO.",
    ".OWppOwwwWO.",
    ".OWppOwwwWO.",
    ".OWWWWWWWWO.",
    ".OWwwwwWWWO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
    "............",
  ],
  // ---- Elite signature weapon icons (12x12) ----------------------------------
  // The NIGHT MANAGER's back-nine special.
  icon_putter: [
    "............",
    ".........OO.",
    "........OkO.",
    ".......OkO..",
    "......OkO...",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OvvvO......",
    ".OvvvvO.....",
    "..OOOO......",
  ],
  // The CHIEF's taser with the export firmware - navy issue.
  icon_riot_taser: swapPalette(TASER_ICON, { h: "J", H: "j" }),
  // DR. NOVA's pointer, three safety screws short of legal.
  icon_overclocked_laser: swapPalette(LASER_ICON, { b: "y" }),
  // THE JANITOR's halberd.
  icon_floor_sign: [
    "............",
    ".....OO.....",
    "....OhhO....",
    "....OhhO....",
    "...OhrrhO...",
    "...OhrrhO...",
    "..OhhrrhhO..",
    "..OhhhhhhO..",
    ".OhhO..OhhO.",
    ".OOO....OOO.",
    "............",
    "............",
  ],
  // The MISSION SPECIALIST's survival kit piece.
  icon_flare_gun: swapPalette(PISTOL_ICON, { a: "r", A: "q" }),
  // The PROSPECTOR's tunneler.
  icon_core_drill: [
    "............",
    "........OO..",
    ".......OyO..",
    "......OyYO..",
    ".....OvvO...",
    "....OvVvO...",
    "...OvvvO....",
    "..OvvvO.....",
    "..ObvO......",
    "..ObbO......",
    "...OO.......",
    "............",
  ],
  // The MEDIC's screening probe, clicking past the safe band.
  icon_geiger_wand: [
    "............",
    "....OOO.....",
    "...OhHhO....",
    "...OhrhO....",
    "....OOO.....",
    ".....OkO....",
    "....OkO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    "..O.........",
    "............",
  ],
  // THE CARTOGRAPHER's stake hammer.
  icon_surveyors_pick: [
    "............",
    "..OvvvvvvO..",
    ".OvvOOOOvvO.",
    ".OvO.Ok.OvO.",
    ".OO..OkO.OO.",
    ".....OkO....",
    "....OkO.....",
    "....OkO.....",
    "...OkO......",
    "...OkO......",
    "....O.......",
    "............",
  ],
  // ---- Story item icons (12x12) ----------------------------------------------
  // Keycards: supply bay white, cleanroom-vault red, AI-core electric blue.
  icon_keycard: KEYCARD_ICON,
  icon_keycard_red: swapPalette(KEYCARD_ICON, { W: "r", j: "W" }),
  icon_keycard_blue: swapPalette(KEYCARD_ICON, { W: "e", j: "s" }),
  // The paper trail: manifest, redacted Apollo log, blueprints — and the AI
  // CORE's own terminal readout, electric-blue glyphs on a dark screen.
  icon_manifest: MANIFEST_ICON,
  icon_log: swapPalette(MANIFEST_ICON, { b: "O", r: "b" }),
  icon_blueprint: swapPalette(MANIFEST_ICON, { W: "j", b: "W", r: "W" }),
  icon_corelog: swapPalette(MANIFEST_ICON, { W: "b", b: "e", r: "s" }),
  // PROJECT SECOND MAN, in its manila folder.
  icon_dossier: [
    "............",
    "............",
    ".OOOO.......",
    ".OooOOOOOO..",
    ".OooooooooO.",
    ".OoWWWWWWoO.",
    ".OoWrrrrWoO.",
    ".OoWWWWWWoO.",
    ".OooooooooO.",
    ".OOOOOOOOOO.",
    "............",
    "............",
  ],
  // ---- Level-up stat glyphs (12x12) ------------------------------------------
  // Drawn on the gold LEVEL UP! buttons — the dark navy outline carries them
  // against the yellow, so each keeps a bold silhouette and 2–3 fill colors.
  // STAMINA (SPRINT + HP): a red heart with a top-left shine.
  icon_stat_stamina: [
    "............",
    "..OO..OO....",
    ".OrrOOrrO...",
    "OrrrrrrrrO..",
    "OrWrrrrrrO..",
    ".OrrrrrrO...",
    "..OrrrrO....",
    "...OrrO.....",
    "....OO......",
    "............",
    "............",
    "............",
  ],
  // STRENGTH (DAMAGE + BAG): a flexed arm — fist up on a vertical forearm,
  // the bicep bulging up from the horizontal upper arm below.
  icon_stat_strength: [
    "............",
    "......OOO...",
    ".....OpppO..",
    ".OO..OpppO..",
    "OppO.OpppO..",
    "OppOOOpppO..",
    "OpppppppO...",
    "OppddddpO...",
    ".OOOOOOO....",
    "............",
    "............",
    "............",
  ],
  // DEXTERITY (SPEED + CRIT): a crosshair reticle over a red bullseye.
  icon_stat_dexterity: [
    "............",
    "....OOO.....",
    "..OO...OO...",
    ".O..OOO..O..",
    ".O.OrrrO.O..",
    "OO.OrrrO.OO.",
    ".O.OrrrO.O..",
    ".O..OOO..O..",
    "..OO...OO...",
    "....OOO.....",
    "............",
    "............",
  ],
  // INTELLECT (MAGIC + AOE): a wizard's hat — a bent purple cone with a gold
  // hatband, widening to a broad brim.
  icon_stat_intelligence: [
    "............",
    "......OO....",
    ".....OmO....",
    ".....OMO....",
    "....OmmO....",
    "....OMyO....",
    "...OmmmO....",
    "...OMmmMO...",
    "..OmmmmmO...",
    "..OMmmmMO...",
    ".OOOOOOOOO..",
    "............",
  ],
  // SPEED (MOVE SPEED): an electric-blue lightning bolt.
  icon_stat_speed: [
    "............",
    ".......OO...",
    "......OsO...",
    ".....OsO....",
    "....OseO....",
    "...OeeeeO...",
    "...OOOeeO...",
    ".....OeO....",
    "....OeO.....",
    "...OeO......",
    "...OO.......",
    "............",
  ],
  // LUCK (CRIT + LOOT): a four-leaf clover on a short stem.
  icon_stat_luck: [
    "............",
    "..OO..OO....",
    ".OlGOOGlO...",
    ".OGGGGGGO...",
    "..OGGGGO....",
    ".OGGGGGGO...",
    ".OlGOOGlO...",
    "..OO..OO....",
    "....Og......",
    "....Og......",
    "....OO......",
    "............",
  ],
  // The anti-grav unit: a ring of not-metal, hovering over its own glow.
  icon_antigrav: [
    "............",
    "............",
    "....OOOO....",
    "..OOyyyyOO..",
    ".OyyOOOOyyO.",
    ".OyO....OyO.",
    ".OyyOOOOyyO.",
    "..OOyyyyOO..",
    "....OOOO....",
    "..cc....cc..",
    "....cccc....",
    "............",
  ],
  // ---- Mars (level 3) --------------------------------------------------------
  // The CYBER KATANA: angular chrome blade, allegedly shatterproof.
  icon_cyber_katana: [
    "............",
    ".......OOO..",
    "......OVxO..",
    ".....OVxxO..",
    "....OVxxO...",
    "...OVxxO....",
    "..OVxxO.....",
    ".OVxxO......",
    ".OVxO.......",
    "ONNO........",
    "ONNO........",
    ".OO.........",
  ],
  // LARRY WEBPAGE's crawler pole: a literal search bar.
  icon_search_bar: [
    "............",
    ".........OO.",
    "........OyO.",
    ".......OrO..",
    "......OjO...",
    ".....OrO....",
    "....OjO.....",
    "...OkO......",
    "..OkO.......",
    ".OkO........",
    "..O.........",
    "............",
  ],
  // BUILD GATES's tablet: it crashes whatever it's pointed at.
  icon_blue_screen: [
    "............",
    ".OOOOOOOOO..",
    ".OeeeeeeeO..",
    ".OesssseeO..",
    ".OeeeeeeeO..",
    ".OessseeeO..",
    ".OeeeeeeeO..",
    ".OesseeeeO..",
    ".OeeeeeeeO..",
    ".OOOOOOOOO..",
    "............",
    "............",
  ],
  // PETER SEAL's letter opener: short, fast, contrarian.
  icon_contrarian_dagger: [
    "............",
    "......OO....",
    ".....OVvO...",
    "....OVvO....",
    "...OVvO.....",
    "..OVvO......",
    ".OOvOO......",
    ".OCCO.......",
    "OCCO........",
    ".OO.........",
    "............",
    "............",
  ],
  // MOSQUE's parting gift. Legally, not a flamethrower.
  icon_not_a_flamethrower: [
    "............",
    ".........y..",
    ".......yry..",
    "..OOOOOOry..",
    "..ONNNNNOy..",
    "..OOONNO....",
    "....ONNO....",
    "....ONNO....",
    "....OOO.....",
    "............",
    "............",
    "............",
  ],
  // ---- Mars story items -------------------------------------------------------
  // The shrine pass: green glass, warm to the touch.
  icon_keycard_green: swapPalette(KEYCARD_ICON, { W: "G", j: "W" }),
  // The passenger ledger: leather-bound, net-worth column included.
  icon_ledger: [
    "............",
    "............",
    ".OOOOOOOOO..",
    ".OEEEEEEEO..",
    ".OEWWWWWEO..",
    ".OEWbbWWEO..",
    ".OEWWWWWEO..",
    ".OEWbyWWEO..",
    ".OEWWWWWEO..",
    ".OOOOOOOOO..",
    "............",
    "............",
  ],
  // The MOON POST-MORTEM: a crash report, appropriately blue.
  icon_postmortem: swapPalette(MANIFEST_ICON, { W: "e", b: "W", r: "W" }),
  // The ENGAGEMENT REPORT: a dashboard still live, one row blinking red.
  icon_report: [
    "............",
    ".OOOOOOOOO..",
    ".ObbbbbbbO..",
    ".ObGGGbbbO..",
    ".ObbbbbbbO..",
    ".ObGGGGbbO..",
    ".ObbbbbbbO..",
    ".ObrrbbbbO..",
    ".ObbbbbbbO..",
    ".OOOOOOOOO..",
    "............",
    "............",
  ],
  // The TRIBUTE SCHEDULE: a Gantt chart chiseled in stone, one milestone lit.
  icon_tablet: [
    "............",
    "..OOOOOOO...",
    ".OvvvvvvvO..",
    ".OvbbbvvvO..",
    ".OvvvvvvvO..",
    ".OvbbbbvvO..",
    ".OvvvvvvvO..",
    ".OvGGvvvvO..",
    ".OvvvvvvvO..",
    ".OOOOOOOOO..",
    "............",
    "............",
  ],
};

export default {
  name: "icons",
  /** Ground tile behind this family's contact sheet. */
  ground: "lab_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {},
  contrastExempt: [],
};
