// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The Mars family (see the `pixel-assets` skill): the secret colony of
// level 3 — rovers and red regolith outside, deck plating, servo robots and
// fembots inside, the billionaire elites, ELON MOSQUE, and the rift he flees
// through. One string per pixel row, one character per pixel; `.` is
// transparent and every other char must exist in CORE_PALETTE
// (sprite-data/core.mjs) or this family's local palette.

import { ramp, shade, swapPalette } from "../asset-tools/palette.mjs";

import moon from "./moon.mjs";

/** The Mars biome floor — retheme the whole desert from this base. */
const MARS = ramp([178, 100, 62], { shadeBy: 0.28, tintBy: 0.22 });
const MARS_PIT = shade(MARS.base, 0.45); // crater floors, deep cracks

/** The colony base's deck plating — a shade under the HQ lab whites. */
const DECK = ramp([128, 134, 152], { shadeBy: 0.3, tintBy: 0.24 });

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  t: MARS.base,
  d: MARS.dark,
  u: MARS.light,
  e: MARS_PIT,
  D: DECK.base,
  s: DECK.dark,
  N: [48, 52, 68], // billionaire black: coats, MOSQUE's jacket
  C: [82, 158, 168], // teal: PETER SEAL, the shrine's glass
  Q: [232, 120, 168], // fembot pink trim
  Z: [246, 182, 205], // fembot gown highlight
};

const SPRITES = {
  // ---- The colony's machines (16×16 minions) --------------------------------
  // SCOUT ROVER — the dust's fodder rank: a camera on wheels, fresh paint on a
  // worn chassis. A boxy camera head with a cyan lens rides a short mast over a
  // steel deck on three round wheels. Frames spin the wheel spokes and blink
  // the status lamp — a cheap thing that evaporates on contact.
  scout_rover_0: [
    "................",
    ".....OOOOOo.....",
    ".....ObcxbO.....",
    ".....OVxcVO.....",
    ".....OOOOOO.....",
    "........b.......",
    "........b.......",
    ".OOOoOOOOOOHOOO.",
    ".OVVVVVVVVVVVVO.",
    ".OvvvvvvvvvvvvO.",
    ".OvvvvvvvvvvvvO.",
    ".OOOOOOOOOOOOOO.",
    "..OaO.OaO..OaO..",
    "..OVO.OVO..OVO..",
    "..OOO.OOO..OOO..",
    "................",
  ],
  scout_rover_1: [
    "................",
    ".....OOOOOH.....",
    ".....ObcxbO.....",
    ".....OVxcVO.....",
    ".....OOOOOO.....",
    "........b.......",
    "........b.......",
    ".OOOHOOOOOOoOOO.",
    ".OVVVVVVVVVVVVO.",
    ".OvvvvvvvvvvvvO.",
    ".OvvvvvvvvvvvvO.",
    ".OOOOOOOOOOOOOO.",
    "..OaO.OaO..OaO..",
    "..OVO.OVO..OVO..",
    "..OOO.OOO..OOO..",
    "................",
  ],
  // MINING ROVER — the outdoor heavy: a tracked drill rig that looms over the
  // rover fields (20×20, a head bigger than the 16px fodder — size IS the
  // hierarchy tell for a 210hp wrecking-ball). Steel body with a cyan sensor
  // visor and a gold/black hazard band, twin tank treads, and a big central
  // grinding auger tipped with a bright tooth. Frames shift the tread links and
  // spin the auger flutes; the wound generator tears its plating in pale x.
  mining_rover_0: [
    "....................",
    "....................",
    "....................",
    "....OOOOOOOOOOOO....",
    "....OVVVVVVVVVVO....",
    "....OvbccccccbvO....",
    "....OvbbbxxbbbvO....",
    "....OkyykyykyykO....",
    "....OhkhhkhhkhkO....",
    "....ObbbbbbbbbbO....",
    "OOOOOOOOOOOOOOOOOOOO",
    "VkkkV..OOOOOO..VkkkV",
    "OkkkO.OhohohoO.OkkkO",
    "VkkkV.OohohohO.VkkkV",
    "OkvkO..OohohO..OkvkO",
    "VkkkV..OhohoO..VkkkV",
    "OkkkO...OhoO...OkkkO",
    "VkkkV....yy....VkkkV",
    "OOOOO....W.....OOOOO",
    "....................",
  ],
  mining_rover_1: [
    "....................",
    "....................",
    "....................",
    "....OOOOOOOOOOOO....",
    "....OVVVVVVVVVVO....",
    "....OvbccccccbvO....",
    "....OvbbbxxbbbvO....",
    "....OkyykyykyykO....",
    "....OhkhhkhhkhkO....",
    "....ObbbbbbbbbbO....",
    "OOOOOOOOOOOOOOOOOOOO",
    "OkkkO..OOOOOO..OkkkO",
    "VkkkV.OohohohO.VkkkV",
    "OkkkO.OhohohoO.OkkkO",
    "VkvkV..OhohoO..VkvkV",
    "OkkkO..OohohO..OkkkO",
    "VkkkV...OohO...VkkkV",
    "OkkkO....yy....OkkkO",
    "OOOOO....W.....OOOOO",
    "....................",
  ],
  // SERVO UNIT — the base's staff robot (the colony runs on these instead of
  // workers): a boxy deck-gray head with one wide cyan visor-eye and a tip
  // antenna, a chest readout between two panels, thin service arms, and a
  // tread base whose cleats roll frame to frame.
  servo_bot_0: [
    "........O.......",
    "........Vc......",
    "....OOOOOOOO....",
    "....OFFFFFFO....",
    "....OOxcccOO....",
    "....OVvVVvVO....",
    "....OOOOOOOO....",
    "..OOOOOOOOOOOO..",
    "..OFFFOOOOFFFO..",
    "..OvVVOccOVVvO..",
    "..OvVVOOOOVVvO..",
    "..OvOOOOOOOOvO..",
    "....OOOOOOOO....",
    "....DsDsDsDO....",
    "....OOOOOOOO....",
    "................",
  ],
  servo_bot_1: [
    "........O.......",
    "........Vc......",
    "....OOOOOOOO....",
    "....OFFFFFFO....",
    "....OOxcccOO....",
    "....OVvVVvVO....",
    "....OOOOOOOO....",
    "..OOOOOOOOOOOO..",
    "..OFFFOOOOFFFO..",
    "..OvVVOccOVVvO..",
    "..OvVVOOOOVVvO..",
    "..OvOOOOOOOOvO..",
    "....OOOOOOOO....",
    "....ODsDsDsD....",
    "....OOOOOOOO....",
    "................",
  ],
  // FEMBOT — the companion line: an uncanny android in a white babydoll gown
  // with pink trim, big blonde hair and a porcelain doll face with cyan
  // camera-eyes. It blows a pink-heart kiss (upper right) and — frame to frame
  // — winks its eyes shut. Smiles. Listens. Uploads everything. Hits hard.
  fembot_0: [
    "..............Q.",
    "...OOOOOOOO..QZQ",
    "..OhyyyyyyhO.QQ.",
    "..OyYyyyyYyO..Q.",
    "..OywwwwwwyO....",
    "..OywcwwcwyO....",
    "..OywwrrwwyO....",
    "...OZWWWWZO.....",
    "..OWWWQQWWWO....",
    "..OWWWWWWWWO....",
    "..OZWWWWWWZO....",
    "..OZZWWWWZZO....",
    "...OppO.OppO....",
    "...OQQO.OQQO....",
    "....OO...OO.....",
    "................",
  ],
  fembot_1: [
    "..............Q.",
    "...OOOOOOOO..QZQ",
    "..OhyyyyyyhO.QQ.",
    "..OyYyyyyYyO..Q.",
    "..OywwwwwwyO....",
    "..OywbwwbwyO....",
    "..OywwrrwwyO....",
    "...OZWWWWZO.....",
    "..OWWWQQWWWO....",
    "..OWWWWWWWWO....",
    "..OZWWWWWWZO....",
    "..OZZWWWWZZO....",
    "..OppO...OppO...",
    "..OQQO...OQQO...",
    "...OO.....OO....",
    "................",
  ],
  // SPARKS gore recolor lives in spacez.mjs (shared with OPTIMUSK).
  // ---- The billionaires (24×24 elites) ---------------------------------------
  // LARRY WEBPAGE — indexed the planet before breakfast: white shirt with
  // the four-color logo stripe, dark hair, khaki-gray slacks.
  larry_webpage_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OWWWWWWWWWWO......",
    ".....OWWWjryjWWWWWO.....",
    "....OWWWWjryjWWWWWWO....",
    "....OWwWWjryjWWWwWWO....",
    "....OWpOWWWWWWWOpWO.....",
    ".....OWwWWWWWWWwWO......",
    ".....OWWWWWWWWWWWO......",
    "......OWWWWOOWWWWO......",
    "......OvvvO..OvvvO......",
    "......OvvvO..OvvvO......",
    "......OvvvO..OvvvO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  larry_webpage_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OWWWWWWWWWWO......",
    ".....OWWWjryjWWWWWO.....",
    "....OWWWWjryjWWWWWWO....",
    "....OWwWWjryjWWWwWWO....",
    "....OWpOWWWWWWWOpWO.....",
    ".....OWwWWWWWWWwWO......",
    ".....OWWWWWWWWWWWO......",
    "......OWWWWOOWWWWO......",
    ".....OvvvO....OvvvO.....",
    ".....OvvvO....OvvvO.....",
    ".....OvvvO....OvvvO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // BUILD GATES — the colony OS: pale-blue sweater over a white collar,
  // glasses, side-parted gray hair.
  build_gates_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOwwwwwwOO.......",
    ".......OwwwwwwwwO.......",
    ".......OwppppppwO.......",
    ".......OOpOppOpOO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OxxxWWWWxxxO......",
    ".....OxxxxWWWWxxxxO.....",
    "....OxxxxxxWWxxxxxxO....",
    "....OxxcxxxxxxxxcxxO....",
    "....OxpOxxxxxxxOpxO.....",
    ".....OxcxxxxxxxcxO......",
    ".....OxxxxxxxxxxxO......",
    "......OxxxxOOxxxxO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  build_gates_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOwwwwwwOO.......",
    ".......OwwwwwwwwO.......",
    ".......OwppppppwO.......",
    ".......OOpOppOpOO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OxxxWWWWxxxO......",
    ".....OxxxxWWWWxxxxO.....",
    "....OxxxxxxWWxxxxxxO....",
    "....OxxcxxxxxxxxcxxO....",
    "....OxpOxxxxxxxOpxO.....",
    ".....OxcxxxxxxxcxO......",
    ".....OxxxxxxxxxxxO......",
    "......OxxxxOOxxxxO......",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // PETER SEAL — the tithe-keeper of the lizard gods: pale and unblinking,
  // slicked hair with a widow's peak, a bloodless blue-gray face with wide
  // cold-staring eyes, and a teal shrine-glass cravat that flows into a
  // keeper's stole down the black coat.
  peter_seal_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkkakkakkO.......",
    ".......OakcaackaO.......",
    ".......OaOaaaaOaO.......",
    "........OaaaaaaO........",
    "......ONNNCCCCNNNO......",
    ".....ONNNNCccCNNNNO.....",
    "....ONNNNNCCCCNNNNNO....",
    "....ONNNNNCWWCNNNNNO....",
    "....ONaONNCCCCNNOaNO....",
    ".....ONNNNcNNcNNNNO.....",
    ".....ONCNNNNNNNNCNO.....",
    "......ONNNNOONNNNO......",
    "......ONNNO..ONNNO......",
    "......ONNNO..ONNNO......",
    "......ONNNO..ONNNO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  peter_seal_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkkakkakkO.......",
    ".......OakcaackaO.......",
    ".......OaOaaaaOaO.......",
    "........OaaaaaaO........",
    "......ONNNCCCCNNNO......",
    ".....ONNNNCccCNNNNO.....",
    "....ONNNNNCCCCNNNNNO....",
    "....ONNNNNCWWCNNNNNO....",
    "....ONaONNCCCCNNOaNO....",
    ".....ONNNNcNNcNNNNO.....",
    ".....ONCNNNNNNNNCNO.....",
    "......ONNNNOONNNNO......",
    ".....ONNNO....ONNNO.....",
    ".....ONNNO....ONNNO.....",
    ".....ONNNO....ONNNO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // OPTIMUSK PRIME — the robot foreman (elite): the OPTIMUSK silhouette
  // scaled to the 24px elite frame so the family resemblance reads at a
  // glance — same white armor panels (W/w) over steel joints (v/V/b), same
  // black-cyan visor band (x) and chest core (c) — plus what the line units
  // lack: a gold command crest on the helmet and gold epaulettes (y), the
  // middle-management markings. Frames alternate the leg stride; the torso
  // holds still like the rank and file.
  optimusk_prime_0: [
    "........................",
    "..........OyyO..........",
    ".........OWWWWO.........",
    "........OWWWWWWO........",
    "........OOxxxxOO........",
    "........OwWWWWwO........",
    ".........OWWWWO.........",
    "......OOwWWWWWWwOO......",
    "....OyvWWWWWWWWWWvyO....",
    "...OvvvWWWWWWWWWwvvvO...",
    "...OvVvWWWccccWWwvVvO...",
    "...OvVvWWWccccWWwvVvO...",
    "...OvOvWWWWWWWWWwvOvO...",
    "...OvbvWWWWWWWWWwvbvO...",
    "...ObbOwWWWWWWWWwObbO...",
    "......OwWWWWWWWWwO......",
    "......OvvvO..OvvvO......",
    "......OvvvO..OvvvO......",
    "......ObbbO..ObbbO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  optimusk_prime_1: [
    "........................",
    "..........OyyO..........",
    ".........OWWWWO.........",
    "........OWWWWWWO........",
    "........OOxxxxOO........",
    "........OwWWWWwO........",
    ".........OWWWWO.........",
    "......OOwWWWWWWwOO......",
    "....OyvWWWWWWWWWWvyO....",
    "...OvvvWWWWWWWWWwvvvO...",
    "...OvVvWWWccccWWwvVvO...",
    "...OvVvWWWccccWWwvVvO...",
    "...OvOvWWWWWWWWWwvOvO...",
    "...OvbvWWWWWWWWWwvbvO...",
    "...ObbOwWWWWWWWWwObbO...",
    "......OwWWWWWWWWwO......",
    ".....OvvvO....OvvvO.....",
    ".....OvvvO....OvvvO.....",
    ".....ObbbO....ObbbO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // ELON MOSQUE — the boss: the man who owns the planet. A giant smug head
  // in aviator shades over a black bomber jacket with a bold gold DOLLAR
  // SIGN (the girl was the down payment; he always closes) and white
  // sneakers. 48x48; frames alternate the stance and lift the smirk into a
  // raised-chin sneer.
  elon_mosque_0: [
    "................................................",
    "................................................",
    "..................OOOOOOOOOO....................",
    "................OOkkkkkkkkkkOO..................",
    "...............OkkkkkkkkkkkkkkO.................",
    "..............OkkkkkkkkkkkkkkkkO................",
    ".............OkkppppppppppppkkkO................",
    ".............OkpppppppppppppppkO................",
    ".............OpkkkkppppppkkkkpO.................",
    ".............OpOcOOOOOOOOOcOOpO.................",
    ".............OpOOOOOOOOOOOOOOpO.................",
    ".............OppppppppppppppppO.................",
    ".............OppppppOOppppppppO.................",
    ".............OppppppppkppppppO..................",
    "..............OpppkkkkppppppO...................",
    "..............OppppppppppppO....................",
    "...............OppppppppppO.....................",
    "................OOppppppOO......................",
    ".............OOOOONNNNNNOOOOO...................",
    "..........OONNNNNNNNNNNNNNNNNNOO................",
    ".........ONNNNNNNNNNNNNNNNNNNNNNO...............",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    "......ONNNNNNNNNNNNNyNNNNNNNNNNNNNNO............",
    ".....ONNNNNNNNNNNNNyyyyNNNNNNNNNNNNNO...........",
    ".....ONNpNNNNNNNNNyyYNNyNNNNNNNpNNNNO...........",
    ".....ONppONNNNNNNNyyyNNNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNNyYyNNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNNNyyyNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNyNNYNyyNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNyyyyNNNNNNNOppNNNNO...........",
    ".....ONpppONNNNNNNNNyNNNNNNOpppNNNNO............",
    "......ONppONNNNNNNNNNNNNNNNOppNNNNO.............",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNO...........",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNO...........",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    "........ONNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    "........ONNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    ".........ONNNNNNNNNNNNNNNNNNNNNNNO..............",
    ".........OONNNNNNNOOOOOONNNNNNNOOO..............",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........OWWWWWO......OWWWWWO.................",
    "...........OWwWWWO......OWwWWWO.................",
    "............OOOOO........OOOOO..................",
  ],
  elon_mosque_1: [
    "................................................",
    "................................................",
    "..................OOOOOOOOOO....................",
    "................OOkkkkkkkkkkOO..................",
    "...............OkkkkkkkkkkkkkkO.................",
    "..............OkkkkkkkkkkkkkkkkO................",
    ".............OkkppppppppppppkkkO................",
    ".............OkpppppppppppppppkO................",
    ".............OpkkkkppppppkkkkpO.................",
    ".............OpOcOOOOOOOOOcOOpO.................",
    ".............OpOOOOOOOOOOOOOOpO.................",
    ".............OppppppppppppppppO.................",
    ".............OppppppOOkpppppppO.................",
    ".............OppppkkkkpppppppO..................",
    "..............OpppppppppppppO...................",
    "..............OppppppppppppO....................",
    "...............OppppppppppO.....................",
    "................OOppppppOO......................",
    ".............OOOOONNNNNNOOOOO...................",
    "..........OONNNNNNNNNNNNNNNNNNOO................",
    ".........ONNNNNNNNNNNNNNNNNNNNNNO...............",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    "......ONNNNNNNNNNNNNyNNNNNNNNNNNNNNO............",
    ".....ONNNNNNNNNNNNNyyyyNNNNNNNNNNNNNO...........",
    ".....ONNpNNNNNNNNNyyYNNyNNNNNNNpNNNNO...........",
    ".....ONppONNNNNNNNyyyNNNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNNyYyNNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNNNyyyNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNyNNYNyyNNNNNOppNNNNO...........",
    ".....ONpppONNNNNNNyyyyNNNNNNOpppNNNNO...........",
    ".....ONppONNNNNNNNNNyNNNNNNNOppNNNNNO...........",
    "......ONNNONNNNNNNNNNNNNNNNNONNNNNNO............",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNO...........",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNO...........",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    "........ONNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    "........ONNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    ".........ONNNNNNNNNNNNNNNNNNNNNNNO..............",
    ".........OONNNNNNNOOOOOONNNNNNNOOO..............",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........OWWWWWO......OWWWWWO.................",
    "...........OWwWWWO......OWwWWWO.................",
    "............OOOOO........OOOOO..................",
  ],
  // ---- The rift ---------------------------------------------------------------
  // The tear MOSQUE flees through — left on the board by the engine when he
  // escapes (EnemyDef.flees), and the doorway the story follows next.
  rift: [
    "............MM..................",
    "...........MmmM.................",
    "..........MmPPmM................",
    ".........MmPLLPmM...............",
    ".........MmPLWLPmM..............",
    "........MmPLWWLPmM..............",
    "........MmPLWWWLPmM.............",
    ".......MmPLWWWWLPmM.............",
    ".......MmPLWWWWWLPmM............",
    "......MmPLWWWWWWLPmM............",
    "......MmPLWWWWWWLPmM............",
    ".....MmPLWWWWWWWWLPmM...........",
    ".....MmPLWWWWWWWWLPmM...........",
    ".....MmPLWWWWWWWWLPmM...........",
    "....MmPLWWWWWWWWWWLPmM..........",
    "....MmPLWWWWWWWWWWLPmM..........",
    "....MmPLWWWWWWWWWWLPmM..........",
    "....MmPLWWWWWWWWWWLPmM..........",
    "....MmPLWWWWWWWWWWLPmM..........",
    ".....MmPLWWWWWWWWLPmM...........",
    ".....MmPLWWWWWWWWLPmM...........",
    ".....MmPLWWWWWWWWLPmM...........",
    "......MmPLWWWWWWLPmM............",
    "......MmPLWWWWWWLPmM............",
    ".......MmPLWWWWWLPmM............",
    ".......MmPLWWWWLPmM.............",
    "........MmPLWWWLPmM.............",
    "........MmPLWWLPmM..............",
    ".........MmPLWLPmM..............",
    ".........MmPLLPmM...............",
    "..........MmPPmM................",
    "...........MmmM.................",
    "............MM..................",
    "................................",
    "................................",
    "................................",
  ],
  // ---- Landmarks --------------------------------------------------------------
  // The hero's ship, parked at the western edge — chrome, fins, still warm.
  starship: [
    "........................",
    "...........OO...........",
    "..........OaaO..........",
    ".........OaaaaO.........",
    ".........OaaaAO.........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    "........OaOOOaAO........",
    "........OaOxxOAO........",
    "........OaOxxOAO........",
    "........OaOOOaAO........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    "........OaOOOaAO........",
    "........OaOxxOAO........",
    "........OaOxxOAO........",
    "........OaOOOaAO........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    ".......OAaaaaaAAO.......",
    "......OAAaaaaaAAAO......",
    ".....OAAOaaaaaAOAAO.....",
    "....OAAO.OAAAAO.OAAO....",
    "....OOO..ObbObO..OOO....",
    "........ObbO.ObO........",
    ".......OOOO...OOO.......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // The colony's welcome, out in the middle of nowhere: MARS in red on a
  // white panel. Invitation only.
  billboard: [
    "................................",
    "..OOOOOOOOOOOOOOOOOOOOOOOOOOOO..",
    ".OWWWWWWWWWWWWWWWWWWWWWWWWWWWWO.",
    ".OWWrWWWrWWrrrWWrrrrWWWrrrrWWWO.",
    ".OWWrrWrrWrWWWrWrWWWrWrWWWWWWWO.",
    ".OWWrWrWrWrrrrrWrrrrWWWrrrWWWWO.",
    ".OWWrWWWrWrWWWrWrWrWWWWWWWrWWWO.",
    ".OWWrWWWrWrWWWrWrWWrWWrrrrWWWWO.",
    ".OWWWWWWWWWWWWWWWWWWWWWWWWWWWWO.",
    ".OWWjjWWWWWWWWWWWWWWWWWWWjjWWWO.",
    ".OWWWWWWWWWWWWWWWWWWWWWWWWWWWWO.",
    "..OOOOOOOOOOOOOOOOOOOOOOOOOOOO..",
    "......OkkO............OkkO......",
    "......OkkO............OkkO......",
    "......OkkO............OkkO......",
    "......OkkO............OkkO......",
    "......OkkO............OkkO......",
    ".....OOkkOO..........OOkkOO.....",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  // The lizard shrine inside the TERRARIUM: a carved lizard-god idol enshrined
  // in a stone arch — jade stone with a gilded frill crest, cold slit eyes and
  // a snout — with the tithe piled in gold at its feet. The colony's owners.
  shrine: [
    "........................",
    ".........OOOOOO.........",
    ".......OOddddddOO.......",
    "......OddddddddddO......",
    "......OdyGllllGydO......",
    "......OdGlGGGGlGdO......",
    "......OdGllGGllGdO......",
    "......OdGyOGGOyGdO......",
    "......OdGGGnnGGGdO......",
    "......OdgGGGGGGgdO......",
    "......OdkgGOOGgkdO......",
    "......OdkgGGGGgkdO......",
    "......OdkkgGGgkkdO......",
    "......OdkkkggkkkdO......",
    "......OdoyhyhyoydO......",
    "......OdyoqooqoydO......",
    "......OddddddddddO......",
    "......OOOOOOOOOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // ---- Ground tiles (16×16) ---------------------------------------------------
  // Red regolith. Keep edges featureless so they tile without seams;
  // mars_1 carries a small pock, rust_* are the oxide-gravel patches.
  mars_0: [
    "tttttttttttttttt",
    "ttttttttttttttdt",
    "ttuttttttttttttt",
    "ttttttttttttdttt",
    "tttttttttttttttt",
    "ttttttttttuttttt",
    "tttttttttttttttt",
    "tttttttttttttttt",
    "tttttdtttttttttt",
    "tttttttttttttttt",
    "tttttttttttddttt",
    "ttttttttttdttttt",
    "tttutttttttttttt",
    "ttttttttttttttdt",
    "tttttttttttttttt",
    "tttttttttttttttt",
  ],
  mars_1: [
    "tttttttttttttttt",
    "tduttttttttttttt",
    "ttttttttttttdttt",
    "tttttttutttttttt",
    "tttttttttttttttt",
    "tttttttttttttttt",
    "tttttttddttttttt",
    "ttttttdeedtttttt",
    "ttttttdeedtttttd",
    "tttttttddttttttt",
    "ttttuttttttttttt",
    "tttdtttttttttttt",
    "tttttttttttttttt",
    "ttttttttdttttttt",
    "tttttttttttttttt",
    "tttttttttttttttt",
  ],
  rust_0: [
    "tttttttttttttttt",
    "ttttttttuttttttt",
    "tttttutttttttttt",
    "tttttddutttttttt",
    "tttttdutdttttttt",
    "ttuttttddttttttt",
    "ttddtttttttttttt",
    "ttddtttttttttttt",
    "ttttttttttedtett",
    "tttttttttttttedd",
    "ttttttuttttttutt",
    "ttedttddttuttttt",
    "ttddttdttttttttt",
    "tttttedtddtutttt",
    "tuttttttdttttttt",
    "tttttttttttttttt",
  ],
  rust_1: [
    "tttttttttttttttt",
    "tttttttttttttttt",
    "tttttttttttttttt",
    "ttttttutttttuttt",
    "ttttttddtttedttt",
    "tttttttuttudtttt",
    "ttttttttttteettt",
    "ttttttttttuddttt",
    "tttttttttutddttt",
    "tttttttttttteddt",
    "ttttttttttutddtt",
    "ttttttttttttuttt",
    "ttttttuttttttutt",
    "tttttttdttttttdt",
    "ttttttddttttttdt",
    "tttttttttttttttt",
  ],
  // The base's deck plating: a seam along the top/left edge like the HQ
  // lab tiles, so the panel grid stays continuous when tiled.
  deck_0: [
    "ssssssssssssssss",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDVDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDVDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDsDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDVDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDVDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDsDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
  ],
  deck_1: [
    "ssssssssssssssss",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDVDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDssDDDDDDDDD",
    "sDDDssDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDssDDD",
    "sDDDDDDDDDssDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDVDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDVDDDD",
    "sDDDDDDDDDDDDDDD",
  ],
  // ---- Obstacles & decor ------------------------------------------------------
  // MARSROCK — the moon slabs' oxidized cousins: same grids, red palette.
  marsrock_1x1: swapPalette(moon.sprites.moonrock_1x1, { f: "t", F: "u" }),
  marsrock_1x2: swapPalette(moon.sprites.moonrock_1x2, { f: "t", F: "u" }),
  marsrock_2x2: swapPalette(moon.sprites.moonrock_2x2, { f: "t", F: "u" }),
  // Craters and strewn rocks, re-oxidized the same way.
  crater_red_big: swapPalette(moon.sprites.crater_big, { F: "u" }),
  crater_red_small: swapPalette(moon.sprites.crater_small, { F: "u" }),
  red_rocks: moon.sprites.rocks,
  // Tire tracks — the dust has been worked for years (no collision).
  tracks: [
    "................",
    ".dd..dd..dd..dd.",
    ".ee..ee..ee..ee.",
    "................",
    "................",
    "....dd..dd..dd..",
    "....ee..ee..ee..",
    "................",
  ],
  // ---- Projectiles ------------------------------------------------------------
  // The BLUE SCREEN's glitch bolt: a jagged blue square of bad data.
  glitch: [
    "........",
    "..jxj...",
    ".jxWxj..",
    "jxWjWxj.",
    ".jxWxjx.",
    "..jxjx..",
    "...jx...",
    "........",
  ],
};

// ---- RARE & UNIQUE mobs (palette variants — the Diablo recolor idiom) ------
// The special machines wear the colony's own body plans in finishes the
// printers never issue, so a find reads at a glance (the engine adds the
// aura + name).
for (const frame of [0, 1]) {
  // MISPRINTED FEMBOT — the companion line in glitch green: gown misprinted
  // grass-green, hair fused to bare steel, the pink trim corrupted dark.
  SPRITES[`misprinted_fembot_${frame}`] = swapPalette(
    SPRITES[`fembot_${frame}`],
    { W: "G", Z: "l", Q: "g", y: "v", Y: "V" },
  );
  // DERELICT ROVER — the scout rusted to the axles, camera eye burnt to a
  // dead red, hazard stripe faded into the pit-dark.
  SPRITES[`derelict_rover_${frame}`] = swapPalette(
    SPRITES[`scout_rover_${frame}`],
    { v: "B", V: "S", b: "E", c: "R", x: "r", a: "E", H: "d" },
  );
  // UNIT ZERO — the servo chassis in original antique brass, running its
  // first firmware behind pale-gold eyes.
  SPRITES[`unit_zero_${frame}`] = swapPalette(SPRITES[`servo_bot_${frame}`], {
    F: "o",
    v: "q",
    c: "y",
    x: "Y",
  });
}

export default {
  name: "mars",
  /** Ground tile behind this family's contact sheet. */
  ground: "mars_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {
    scout_rover_roll: {
      frames: ["scout_rover_0", "scout_rover_1"],
      delayMs: 240,
    },
    mining_rover_grind: {
      frames: ["mining_rover_0", "mining_rover_1"],
      delayMs: 340,
    },
    servo_bot_walk: { frames: ["servo_bot_0", "servo_bot_1"], delayMs: 300 },
    fembot_walk: { frames: ["fembot_0", "fembot_1"], delayMs: 260 },
    misprinted_fembot_walk: {
      frames: ["misprinted_fembot_0", "misprinted_fembot_1"],
      delayMs: 260,
    },
    derelict_rover_roll: {
      frames: ["derelict_rover_0", "derelict_rover_1"],
      delayMs: 300,
    },
    unit_zero_walk: { frames: ["unit_zero_0", "unit_zero_1"], delayMs: 320 },
    larry_webpage_walk: {
      frames: ["larry_webpage_0", "larry_webpage_1"],
      delayMs: 280,
    },
    build_gates_walk: {
      frames: ["build_gates_0", "build_gates_1"],
      delayMs: 300,
    },
    optimusk_prime_walk: {
      frames: ["optimusk_prime_0", "optimusk_prime_1"],
      delayMs: 340,
    },
    peter_seal_walk: {
      frames: ["peter_seal_0", "peter_seal_1"],
      delayMs: 300,
    },
    elon_mosque_strut: {
      frames: ["elon_mosque_0", "elon_mosque_1"],
      delayMs: 380,
    },
  },
  /**
   * Wound-style overrides — mobs whose gore-derived default doesn't read on
   * their body colors. The machines default to gold sparks (`y`), which
   * vanishes on the FEMBOT's gold hair and gown trim — she wounds in the
   * deck-gray of torn plating instead. PETER SEAL's black coat swallows
   * dried-blood cores, so his stay bright red.
   */
  wounds: {
    fembot: { splat: "v", core: "b" },
    // The misprint wounds like its sister: torn deck-gray plating on the
    // green gown (gold sparks sink into the glitch print).
    misprinted_fembot: { splat: "v", core: "b" },
    // Gold sparks vanish on UNIT ZERO's antique brass — pale torn plating
    // reads instead (the mining rover's rule).
    unit_zero: { splat: "x", core: "b" },
    // Bright gold spark + dark-gold core so the electrical hit reads across the
    // little scout's steel deck (its default core matched the body too closely).
    scout_rover: { splat: "y", core: "H" },
    // Gold sparks + a dark-gold scuff so the electrical hit reads on the
    // servo's deck-gray shell (its default spark barely moved 4 px).
    servo_bot: { splat: "y", core: "Y", scuff: "H" },
    // Gold sparks vanish on the gold hazard cab — torn pale plating reads.
    mining_rover: { splat: "x", core: "b" },
    peter_seal: { splat: "r", core: "r" },
    elon_mosque: { splat: "r", core: "r" },
  },
  /** Ground tiles and flat desert decor the contrast lint skips. */
  contrastExempt: [
    "mars_0",
    "mars_1",
    "rust_0",
    "rust_1",
    "deck_0",
    "deck_1",
    "crater_red_big",
    "crater_red_small",
    "red_rocks",
    "tracks",
  ],
};
