// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The Mars family (see the `pixel-assets` skill): the secret colony of
// level 3 — rovers and red regolith outside, deck plating, servo robots and
// fembots inside, the billionaire elites, ELON MOSQUE, and the rift he flees
// through. One string per pixel row, one character per pixel; `.` is
// transparent and every other char must exist in CORE_PALETTE
// (sprite-data/core.mjs) or this family's local palette.

import { ramp, shade, swapPalette } from "../asset-tools/palette.mjs";

import moon from "./moon.mjs";

/** The Mars biome floor — retheme the whole desert from this base. */
const MARS = ramp([178, 100, 62], { shadeBy: 0.28, tintBy: 0.22 });
const MARS_PIT = shade(MARS.base, 0.45); // crater floors, deep cracks

/** The colony base's deck plating — a shade under the HQ lab whites. */
const DECK = ramp([128, 134, 152], { shadeBy: 0.3, tintBy: 0.24 });

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  t: MARS.base,
  d: MARS.dark,
  u: MARS.light,
  e: MARS_PIT,
  D: DECK.base,
  s: DECK.dark,
  N: [48, 52, 68], // billionaire black: coats, MOSQUE's jacket
  C: [82, 158, 168], // teal: PETER SEAL, the shrine's glass
  Q: [232, 120, 168], // fembot pink trim
  Z: [246, 182, 205], // fembot gown highlight
};

const SPRITES = {
  // ---- The colony's machines (16×16 minions) --------------------------------
  // SCOUT ROVER — a camera on six wheels, the dust's fodder rank. Frames
  // alternate the wheel base like a stride.
  scout_rover_0: [
    "................",
    ".....OOO........",
    "....OxccO.......",
    ".....OOO........",
    "......OvO.......",
    "....OOOvOOOO....",
    "...OvooooooVO...",
    "..OvvoqoqoqvvO..",
    "..OvvvvvvvvvvO..",
    "..OObOObbOObOO..",
    "..ObbO.ObbO.ObO.",
    "...OO...OO...O..",
    "................",
    "................",
    "................",
    "................",
  ],
  scout_rover_1: [
    "................",
    ".....OOO........",
    "....OxccO.......",
    ".....OOO........",
    "......OvO.......",
    "....OOOvOOOO....",
    "...OvooooooVO...",
    "..OvvqoqoqovvO..",
    "..OvvvvvvvvvvO..",
    "..OObbOObOObbO..",
    "..OObbO.ObbOOO..",
    "....OO...OO.....",
    "................",
    "................",
    "................",
    "................",
  ],
  // MINING ROVER — the outdoor heavy: a tracked drill rig that looms over the
  // rover fields (20×20, a head bigger than the 16px fodder — size IS the
  // hierarchy tell for a 210hp wrecking-ball). Steel body with a cyan sensor
  // visor and a gold/black hazard band, twin tank treads, and a big central
  // grinding auger tipped with a bright tooth. Frames shift the tread links and
  // spin the auger flutes; the wound generator tears its plating in pale x.
  mining_rover_0: [
    "....................",
    "....................",
    "....................",
    "....OOOOOOOOOOOO....",
    "....OVVVVVVVVVVO....",
    "....OvbccccccbvO....",
    "....OvbbbxxbbbvO....",
    "....OkyykyykyykO....",
    "....OhkhhkhhkhkO....",
    "....ObbbbbbbbbbO....",
    "OOOOOOOOOOOOOOOOOOOO",
    "VkkkV..OOOOOO..VkkkV",
    "OkkkO.OhohohoO.OkkkO",
    "VkkkV.OohohohO.VkkkV",
    "OkvkO..OohohO..OkvkO",
    "VkkkV..OhohoO..VkkkV",
    "OkkkO...OhoO...OkkkO",
    "VkkkV....yy....VkkkV",
    "OOOOO....W.....OOOOO",
    "....................",
  ],
  mining_rover_1: [
    "....................",
    "....................",
    "....................",
    "....OOOOOOOOOOOO....",
    "....OVVVVVVVVVVO....",
    "....OvbccccccbvO....",
    "....OvbbbxxbbbvO....",
    "....OkyykyykyykO....",
    "....OhkhhkhhkhkO....",
    "....ObbbbbbbbbbO....",
    "OOOOOOOOOOOOOOOOOOOO",
    "OkkkO..OOOOOO..OkkkO",
    "VkkkV.OohohohO.VkkkV",
    "OkkkO.OhohohoO.OkkkO",
    "VkvkV..OhohoO..VkvkV",
    "OkkkO..OohohO..OkkkO",
    "VkkkV...OohO...VkkkV",
    "OkkkO....yy....OkkkO",
    "OOOOO....W.....OOOOO",
    "....................",
  ],
  // SERVO UNIT — the base's staff robot: one wide cyan eye, deck-gray
  // shell, thin service arms. Same 12px figure as the HQ crowd.
  servo_bot_0: [
    "................",
    ".....OvvvvO.....",
    "....OvVVVVvO....",
    "....OOxxxxOO....",
    "....OvvvvvvO....",
    "...ObvWWWWvbO...",
    "..ObvvWccWvvbO..",
    "..ObvvWWWWvvbO..",
    "..OvOvWWWWvOvO..",
    "...OvvWWWWvvO...",
    "...OvvO..OvvO...",
    "...ObbO..ObbO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  servo_bot_1: [
    "................",
    ".....OvvvvO.....",
    "....OvVVVVvO....",
    "....OOxxxxOO....",
    "....OvvvvvvO....",
    "...ObvWWWWvbO...",
    "..ObvvWccWvvbO..",
    "..ObvvWWWWvvbO..",
    "..OvOvWWWWvOvO..",
    "...OvvWWWWvvO...",
    "..OvvO....OvvO..",
    "..ObbO....ObbO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // FEMBOT — the companion line: big blonde hair, white babydoll with pink
  // trim. Smiles. Uploads everything. Hits hard.
  fembot_0: [
    "................",
    "....OyyyyyyO....",
    "...OyYyyyyYyO...",
    "...OyppppppyO...",
    "...OypOppOpyO...",
    "....OppQQppO....",
    "...OZZZZZZZZO...",
    "..OZWWWWWWWWZO..",
    "..OQWWZWWZWWQO..",
    "..OpOZWWWWZOpO..",
    "...OQZZZZZZQO...",
    "...OppO..OppO...",
    "...OQQO..OQQO...",
    "...OOOO..OOOO...",
    "................",
    "................",
  ],
  fembot_1: [
    "................",
    "....OyyyyyyO....",
    "...OyYyyyyYyO...",
    "...OyppppppyO...",
    "...OypOppOpyO...",
    "....OppQQppO....",
    "...OZZZZZZZZO...",
    "..OZWWWWWWWWZO..",
    "..OQWWZWWZWWQO..",
    "..OpOZWWWWZOpO..",
    "...OQZZZZZZQO...",
    "..OppO....OppO..",
    "..OQQO....OQQO..",
    "..OOOO....OOOO..",
    "................",
    "................",
  ],
  // SPARKS gore recolor lives in spacez.mjs (shared with OPTIMUSK).
  // ---- The billionaires (24×24 elites) ---------------------------------------
  // LARRY WEBPAGE — indexed the planet before breakfast: white shirt with
  // the four-color logo stripe, dark hair, khaki-gray slacks.
  larry_webpage_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OWWWWWWWWWWO......",
    ".....OWWWjryjWWWWWO.....",
    "....OWWWWjryjWWWWWWO....",
    "....OWwWWjryjWWWwWWO....",
    "....OWpOWWWWWWWOpWO.....",
    ".....OWwWWWWWWWwWO......",
    ".....OWWWWWWWWWWWO......",
    "......OWWWWOOWWWWO......",
    "......OvvvO..OvvvO......",
    "......OvvvO..OvvvO......",
    "......OvvvO..OvvvO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  larry_webpage_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OWWWWWWWWWWO......",
    ".....OWWWjryjWWWWWO.....",
    "....OWWWWjryjWWWWWWO....",
    "....OWwWWjryjWWWwWWO....",
    "....OWpOWWWWWWWOpWO.....",
    ".....OWwWWWWWWWwWO......",
    ".....OWWWWWWWWWWWO......",
    "......OWWWWOOWWWWO......",
    ".....OvvvO....OvvvO.....",
    ".....OvvvO....OvvvO.....",
    ".....OvvvO....OvvvO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // BUILD GATES — the colony OS: pale-blue sweater over a white collar,
  // glasses, side-parted gray hair.
  build_gates_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOwwwwwwOO.......",
    ".......OwwwwwwwwO.......",
    ".......OwppppppwO.......",
    ".......OOpOppOpOO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OxxxWWWWxxxO......",
    ".....OxxxxWWWWxxxxO.....",
    "....OxxxxxxWWxxxxxxO....",
    "....OxxcxxxxxxxxcxxO....",
    "....OxpOxxxxxxxOpxO.....",
    ".....OxcxxxxxxxcxO......",
    ".....OxxxxxxxxxxxO......",
    "......OxxxxOOxxxxO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  build_gates_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOwwwwwwOO.......",
    ".......OwwwwwwwwO.......",
    ".......OwppppppwO.......",
    ".......OOpOppOpOO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OxxxWWWWxxxO......",
    ".....OxxxxWWWWxxxxO.....",
    "....OxxxxxxWWxxxxxxO....",
    "....OxxcxxxxxxxxcxxO....",
    "....OxpOxxxxxxxOpxO.....",
    ".....OxcxxxxxxxcxO......",
    ".....OxxxxxxxxxxxO......",
    "......OxxxxOOxxxxO......",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // PETER SEAL — the tithe-keeper: slicked hair, black coat with a teal
  // collar, pale and unblinking.
  peter_seal_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......ONNNCCCCNNNO......",
    ".....ONNNNCWWCNNNNO.....",
    "....ONNNNNCWWCNNNNNO....",
    "....ONNNNNCWWCNNNNNO....",
    "....ONpONNCCCCNNOpNO....",
    ".....ONNNNNNNNNNNNO.....",
    ".....ONCNNNNNNNNCNO.....",
    "......ONNNNOONNNNO......",
    "......ONNNO..ONNNO......",
    "......ONNNO..ONNNO......",
    "......ONNNO..ONNNO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  peter_seal_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......ONNNCCCCNNNO......",
    ".....ONNNNCWWCNNNNO.....",
    "....ONNNNNCWWCNNNNNO....",
    "....ONNNNNCWWCNNNNNO....",
    "....ONpONNCCCCNNOpNO....",
    ".....ONNNNNNNNNNNNO.....",
    ".....ONCNNNNNNNNCNO.....",
    "......ONNNNOONNNNO......",
    ".....ONNNO....ONNNO.....",
    ".....ONNNO....ONNNO.....",
    ".....ONNNO....ONNNO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // OPTIMUSK PRIME — the robot foreman (elite): the OPTIMUSK silhouette
  // scaled to the 24px elite frame so the family resemblance reads at a
  // glance — same white armor panels (W/w) over steel joints (v/V/b), same
  // black-cyan visor band (x) and chest core (c) — plus what the line units
  // lack: a gold command crest on the helmet and gold epaulettes (y), the
  // middle-management markings. Frames alternate the leg stride; the torso
  // holds still like the rank and file.
  optimusk_prime_0: [
    "........................",
    "..........OyyO..........",
    ".........OWWWWO.........",
    "........OWWWWWWO........",
    "........OOxxxxOO........",
    "........OwWWWWwO........",
    ".........OWWWWO.........",
    "......OOwWWWWWWwOO......",
    "....OyvWWWWWWWWWWvyO....",
    "...OvvvWWWWWWWWWwvvvO...",
    "...OvVvWWWccccWWwvVvO...",
    "...OvVvWWWccccWWwvVvO...",
    "...OvOvWWWWWWWWWwvOvO...",
    "...OvbvWWWWWWWWWwvbvO...",
    "...ObbOwWWWWWWWWwObbO...",
    "......OwWWWWWWWWwO......",
    "......OvvvO..OvvvO......",
    "......OvvvO..OvvvO......",
    "......ObbbO..ObbbO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  optimusk_prime_1: [
    "........................",
    "..........OyyO..........",
    ".........OWWWWO.........",
    "........OWWWWWWO........",
    "........OOxxxxOO........",
    "........OwWWWWwO........",
    ".........OWWWWO.........",
    "......OOwWWWWWWwOO......",
    "....OyvWWWWWWWWWWvyO....",
    "...OvvvWWWWWWWWWwvvvO...",
    "...OvVvWWWccccWWwvVvO...",
    "...OvVvWWWccccWWwvVvO...",
    "...OvOvWWWWWWWWWwvOvO...",
    "...OvbvWWWWWWWWWwvbvO...",
    "...ObbOwWWWWWWWWwObbO...",
    "......OwWWWWWWWWwO......",
    ".....OvvvO....OvvvO.....",
    ".....OvvvO....OvvvO.....",
    ".....ObbbO....ObbbO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // ELON MOSQUE — the boss: the man who owns the planet. A giant smug head
  // over a black bomber jacket with a gold Z, white sneakers. 48×48;
  // frames alternate the stance and the raised chin.
  elon_mosque_0: [
    "................................................",
    "................................................",
    "..................OOOOOOOOOO....................",
    "................OOkkkkkkkkkkOO..................",
    "...............OkkkkkkkkkkkkkkO.................",
    "..............OkkkkkkkkkkkkkkkkO................",
    ".............OkkppppppppppppkkkO................",
    ".............OkpppppppppppppppkO................",
    ".............OppppppppppppppppO.................",
    ".............OppOOppppppppOOppO.................",
    ".............OppOOppppppppOOppO.................",
    ".............OppppppppppppppppO.................",
    ".............OppppppOOppppppppO.................",
    ".............OpppppppppppppppO..................",
    "..............OppprrrrrrppppO...................",
    "..............OppppppppppppO....................",
    "...............OppppppppppO.....................",
    "................OOppppppOO......................",
    ".............OOOOONNNNNNOOOOO...................",
    "..........OONNNNNNNNNNNNNNNNNNOO................",
    ".........ONNNNNNNNNNNNNNNNNNNNNNO...............",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    "......ONNNNNNNNNNyyNNNNNNNNNNNNNNNNO............",
    ".....ONNNNNNNNNNyyNNNNNNNNNNNNNNNNNNO...........",
    ".....ONNpNNNNNNyyyyNNNNNNNNNNNNpNNNNO...........",
    ".....ONppONNNNNyyNyyNNNNNNNNNOppNNNNO...........",
    ".....ONppONNNNyyNNNyyNNNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNNNNNNNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNNNNNNNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNNNNNNNNNNNNOppNNNNO...........",
    ".....ONpppONNNNNNNNNNNNNNNNOpppNNNNO............",
    "......ONppONNNNNNNNNNNNNNNNOppNNNNO.............",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNO...........",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNO...........",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    "........ONNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    "........ONNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    ".........ONNNNNNNNNNNNNNNNNNNNNNNO..............",
    ".........OONNNNNNNOOOOOONNNNNNNOOO..............",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........OWWWWWO......OWWWWWO.................",
    "...........OWwWWWO......OWwWWWO.................",
    "............OOOOO........OOOOO..................",
  ],
  elon_mosque_1: [
    "................................................",
    "................................................",
    "..................OOOOOOOOOO....................",
    "................OOkkkkkkkkkkOO..................",
    "...............OkkkkkkkkkkkkkkO.................",
    "..............OkkkkkkkkkkkkkkkkO................",
    ".............OkkppppppppppppkkkO................",
    ".............OkpppppppppppppppkO................",
    ".............OppppppppppppppppO.................",
    ".............OppOOppppppppOOppO.................",
    ".............OppOOppppppppOOppO.................",
    ".............OppppppppppppppppO.................",
    ".............OppppppOOppppppppO.................",
    ".............OpppppppppppppppO..................",
    "..............OpppprrrrrrpppO...................",
    "..............OppppppppppppO....................",
    "...............OppppppppppO.....................",
    "................OOppppppOO......................",
    ".............OOOOONNNNNNOOOOO...................",
    "..........OONNNNNNNNNNNNNNNNNNOO................",
    ".........ONNNNNNNNNNNNNNNNNNNNNNO...............",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    "......ONNNNNNNNNNyyNNNNNNNNNNNNNNNNO............",
    ".....ONNNNNNNNNNyyNNNNNNNNNNNNNNNNNNO...........",
    ".....ONNpNNNNNNyyyyNNNNNNNNNNNNpNNNNO...........",
    ".....ONppONNNNNyyNyyNNNNNNNNNOppNNNNO...........",
    ".....ONppONNNNyyNNNyyNNNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNNNNNNNNNNNNOppNNNNO...........",
    ".....ONppONNNNNNNNNNNNNNNNNNNOppNNNNO...........",
    ".....ONpppONNNNNNNNNNNNNNNNNOpppNNNNO...........",
    ".....ONppONNNNNNNNNNNNNNNNNNOppNNNNNO...........",
    "......ONNNONNNNNNNNNNNNNNNNNONNNNNNO............",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNO...........",
    "......ONNNNNNNNNNNNNNNNNNNNNNNNNNNNNO...........",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    ".......ONNNNNNNNNNNNNNNNNNNNNNNNNNNO............",
    "........ONNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    "........ONNNNNNNNNNNNNNNNNNNNNNNNNO.............",
    ".........ONNNNNNNNNNNNNNNNNNNNNNNO..............",
    ".........OONNNNNNNOOOOOONNNNNNNOOO..............",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........ONNNNNO......ONNNNNO.................",
    "...........OWWWWWO......OWWWWWO.................",
    "...........OWwWWWO......OWwWWWO.................",
    "............OOOOO........OOOOO..................",
  ],
  // ---- The rift ---------------------------------------------------------------
  // The tear MOSQUE flees through — left on the board by the engine when he
  // escapes (EnemyDef.flees), and the doorway the story follows next.
  rift: [
    "............MM..................",
    "...........MmmM.................",
    "..........MmPPmM................",
    ".........MmPLLPmM...............",
    ".........MmPLWLPmM..............",
    "........MmPLWWLPmM..............",
    "........MmPLWWWLPmM.............",
    ".......MmPLWWWWLPmM.............",
    ".......MmPLWWWWWLPmM............",
    "......MmPLWWWWWWLPmM............",
    "......MmPLWWWWWWLPmM............",
    ".....MmPLWWWWWWWWLPmM...........",
    ".....MmPLWWWWWWWWLPmM...........",
    ".....MmPLWWWWWWWWLPmM...........",
    "....MmPLWWWWWWWWWWLPmM..........",
    "....MmPLWWWWWWWWWWLPmM..........",
    "....MmPLWWWWWWWWWWLPmM..........",
    "....MmPLWWWWWWWWWWLPmM..........",
    "....MmPLWWWWWWWWWWLPmM..........",
    ".....MmPLWWWWWWWWLPmM...........",
    ".....MmPLWWWWWWWWLPmM...........",
    ".....MmPLWWWWWWWWLPmM...........",
    "......MmPLWWWWWWLPmM............",
    "......MmPLWWWWWWLPmM............",
    ".......MmPLWWWWWLPmM............",
    ".......MmPLWWWWLPmM.............",
    "........MmPLWWWLPmM.............",
    "........MmPLWWLPmM..............",
    ".........MmPLWLPmM..............",
    ".........MmPLLPmM...............",
    "..........MmPPmM................",
    "...........MmmM.................",
    "............MM..................",
    "................................",
    "................................",
    "................................",
  ],
  // ---- Landmarks --------------------------------------------------------------
  // The hero's ship, parked at the western edge — chrome, fins, still warm.
  starship: [
    "........................",
    "...........OO...........",
    "..........OaaO..........",
    ".........OaaaaO.........",
    ".........OaaaAO.........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    "........OaOOOaAO........",
    "........OaOxxOAO........",
    "........OaOxxOAO........",
    "........OaOOOaAO........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    "........OaOOOaAO........",
    "........OaOxxOAO........",
    "........OaOxxOAO........",
    "........OaOOOaAO........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    "........OaaaaaAO........",
    ".......OAaaaaaAAO.......",
    "......OAAaaaaaAAAO......",
    ".....OAAOaaaaaAOAAO.....",
    "....OAAO.OAAAAO.OAAO....",
    "....OOO..ObbObO..OOO....",
    "........ObbO.ObO........",
    ".......OOOO...OOO.......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // The colony's welcome, out in the middle of nowhere: MARS in red on a
  // white panel. Invitation only.
  billboard: [
    "................................",
    "..OOOOOOOOOOOOOOOOOOOOOOOOOOOO..",
    ".OWWWWWWWWWWWWWWWWWWWWWWWWWWWWO.",
    ".OWWrWWWrWWrrrWWrrrrWWWrrrrWWWO.",
    ".OWWrrWrrWrWWWrWrWWWrWrWWWWWWWO.",
    ".OWWrWrWrWrrrrrWrrrrWWWrrrWWWWO.",
    ".OWWrWWWrWrWWWrWrWrWWWWWWWrWWWO.",
    ".OWWrWWWrWrWWWrWrWWrWWrrrrWWWWO.",
    ".OWWWWWWWWWWWWWWWWWWWWWWWWWWWWO.",
    ".OWWjjWWWWWWWWWWWWWWWWWWWjjWWWO.",
    ".OWWWWWWWWWWWWWWWWWWWWWWWWWWWWO.",
    "..OOOOOOOOOOOOOOOOOOOOOOOOOOOO..",
    "......OkkO............OkkO......",
    "......OkkO............OkkO......",
    "......OkkO............OkkO......",
    "......OkkO............OkkO......",
    "......OkkO............OkkO......",
    ".....OOkkOO..........OOkkOO.....",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  // The lizard shrine inside the TERRARIUM: a stone arch, a green idol,
  // and the tithe piled in gold at its feet.
  shrine: [
    "........................",
    ".........OOOOO..........",
    ".......OOeeeeeOO........",
    "......OeeeeeeeeeO.......",
    ".....OeedOOOOOeeeO......",
    ".....OedO.....OeeO......",
    ".....OedO.GG..OeeO......",
    ".....OedOGllGOOeeO......",
    ".....OedOGlGgOOeeO......",
    ".....OedOOGGgOOeeO......",
    ".....OedOGGGggOeeO......",
    ".....OedOGgGgGOeeO......",
    ".....OedOgGGgOOeeO......",
    ".....OedO.GgO.OeeO......",
    ".....OedO.GgO.OeeO......",
    ".....OedOOOOOOOeeO......",
    ".....OeddeeeeeeeeeO.....",
    "....OeoyooOOOooyooO.....",
    "....Ooyooyoooyooyoo.....",
    "....OOOOOOOOOOOOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // ---- Ground tiles (16×16) ---------------------------------------------------
  // Red regolith. Keep edges featureless so they tile without seams;
  // mars_1 carries a small pock, rust_* are the oxide-gravel patches.
  mars_0: [
    "tttttttttttttttt",
    "ttttttttttttttdt",
    "ttuttttttttttttt",
    "ttttttttttttdttt",
    "tttttttttttttttt",
    "ttttttttttuttttt",
    "tttttttttttttttt",
    "tttttttttttttttt",
    "tttttdtttttttttt",
    "tttttttttttttttt",
    "tttttttttttddttt",
    "ttttttttttdttttt",
    "tttutttttttttttt",
    "ttttttttttttttdt",
    "tttttttttttttttt",
    "tttttttttttttttt",
  ],
  mars_1: [
    "tttttttttttttttt",
    "tduttttttttttttt",
    "ttttttttttttdttt",
    "tttttttutttttttt",
    "tttttttttttttttt",
    "tttttttttttttttt",
    "tttttttddttttttt",
    "ttttttdeedtttttt",
    "ttttttdeedtttttd",
    "tttttttddttttttt",
    "ttttuttttttttttt",
    "tttdtttttttttttt",
    "tttttttttttttttt",
    "ttttttttdttttttt",
    "tttttttttttttttt",
    "tttttttttttttttt",
  ],
  rust_0: [
    "tttttttttttttttt",
    "ttttttttuttttttt",
    "tttttutttttttttt",
    "tttttddutttttttt",
    "tttttdutdttttttt",
    "ttuttttddttttttt",
    "ttddtttttttttttt",
    "ttddtttttttttttt",
    "ttttttttttedtett",
    "tttttttttttttedd",
    "ttttttuttttttutt",
    "ttedttddttuttttt",
    "ttddttdttttttttt",
    "tttttedtddtutttt",
    "tuttttttdttttttt",
    "tttttttttttttttt",
  ],
  rust_1: [
    "tttttttttttttttt",
    "tttttttttttttttt",
    "tttttttttttttttt",
    "ttttttutttttuttt",
    "ttttttddtttedttt",
    "tttttttuttudtttt",
    "ttttttttttteettt",
    "ttttttttttuddttt",
    "tttttttttutddttt",
    "tttttttttttteddt",
    "ttttttttttutddtt",
    "ttttttttttttuttt",
    "ttttttuttttttutt",
    "tttttttdttttttdt",
    "ttttttddttttttdt",
    "tttttttttttttttt",
  ],
  // The base's deck plating: a seam along the top/left edge like the HQ
  // lab tiles, so the panel grid stays continuous when tiled.
  deck_0: [
    "ssssssssssssssss",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDVDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDVDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDsDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDVDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDVDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDsDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
  ],
  deck_1: [
    "ssssssssssssssss",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDVDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDssDDDDDDDDD",
    "sDDDssDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDssDDD",
    "sDDDDDDDDDssDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDVDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDDDDDD",
    "sDDDDDDDDDDVDDDD",
    "sDDDDDDDDDDDDDDD",
  ],
  // ---- Obstacles & decor ------------------------------------------------------
  // MARSROCK — the moon slabs' oxidized cousins: same grids, red palette.
  marsrock_1x1: swapPalette(moon.sprites.moonrock_1x1, { f: "t", F: "u" }),
  marsrock_1x2: swapPalette(moon.sprites.moonrock_1x2, { f: "t", F: "u" }),
  marsrock_2x2: swapPalette(moon.sprites.moonrock_2x2, { f: "t", F: "u" }),
  // Craters and strewn rocks, re-oxidized the same way.
  crater_red_big: swapPalette(moon.sprites.crater_big, { F: "u" }),
  crater_red_small: swapPalette(moon.sprites.crater_small, { F: "u" }),
  red_rocks: moon.sprites.rocks,
  // Tire tracks — the dust has been worked for years (no collision).
  tracks: [
    "................",
    ".dd..dd..dd..dd.",
    ".ee..ee..ee..ee.",
    "................",
    "................",
    "....dd..dd..dd..",
    "....ee..ee..ee..",
    "................",
  ],
  // ---- Projectiles ------------------------------------------------------------
  // The BLUE SCREEN's glitch bolt: a jagged blue square of bad data.
  glitch: [
    "........",
    "..jxj...",
    ".jxWxj..",
    "jxWjWxj.",
    ".jxWxjx.",
    "..jxjx..",
    "...jx...",
    "........",
  ],
};

export default {
  name: "mars",
  /** Ground tile behind this family's contact sheet. */
  ground: "mars_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {
    scout_rover_roll: {
      frames: ["scout_rover_0", "scout_rover_1"],
      delayMs: 240,
    },
    mining_rover_grind: {
      frames: ["mining_rover_0", "mining_rover_1"],
      delayMs: 340,
    },
    servo_bot_walk: { frames: ["servo_bot_0", "servo_bot_1"], delayMs: 300 },
    fembot_walk: { frames: ["fembot_0", "fembot_1"], delayMs: 260 },
    larry_webpage_walk: {
      frames: ["larry_webpage_0", "larry_webpage_1"],
      delayMs: 280,
    },
    build_gates_walk: {
      frames: ["build_gates_0", "build_gates_1"],
      delayMs: 300,
    },
    optimusk_prime_walk: {
      frames: ["optimusk_prime_0", "optimusk_prime_1"],
      delayMs: 340,
    },
    peter_seal_walk: {
      frames: ["peter_seal_0", "peter_seal_1"],
      delayMs: 300,
    },
    elon_mosque_strut: {
      frames: ["elon_mosque_0", "elon_mosque_1"],
      delayMs: 380,
    },
  },
  /**
   * Wound-style overrides — mobs whose gore-derived default doesn't read on
   * their body colors. The machines default to gold sparks (`y`), which
   * vanishes on the FEMBOT's gold hair and gown trim — she wounds in the
   * deck-gray of torn plating instead. PETER SEAL's black coat swallows
   * dried-blood cores, so his stay bright red.
   */
  wounds: {
    fembot: { splat: "v", core: "b" },
    // Gold sparks vanish on the gold hazard cab — torn pale plating reads.
    mining_rover: { splat: "x", core: "b" },
    peter_seal: { splat: "r", core: "r" },
    elon_mosque: { splat: "r", core: "r" },
  },
  /** Ground tiles and flat desert decor the contrast lint skips. */
  contrastExempt: [
    "mars_0",
    "mars_1",
    "rust_0",
    "rust_1",
    "deck_0",
    "deck_1",
    "crater_red_big",
    "crater_red_small",
    "red_rocks",
    "tracks",
  ],
};
