// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The moon family (see the `pixel-assets` skill): the haunting, the
// landmarks and the regolith of level 2. One string per pixel row, one
// character per pixel; `.` is transparent and every other char must exist
// in CORE_PALETTE (sprite-data/core.mjs) or this family's local palette.

import { shade, swapPalette } from "../asset-tools/palette.mjs";

import { BOSS, GHOST, MOON } from "./core.mjs";
import { BLOOD_0, BLOOD_1 } from "./effects.mjs";

/** The faintest haunting tier — translucency baked into the alpha channel. */
const WISP = { base: [205, 232, 240, 185], dark: [148, 188, 199, 185] };

const MOON_PIT = shade(MOON.base, 0.43); // crater floors

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  u: WISP.base,
  U: WISP.dark,
  C: GHOST.dark,
  N: BOSS.dark,
  d: MOON.dark,
  e: MOON_PIT,
};

const SPRITES = {
  // WISP — the faintest haunting, found near the landing site.
  wisp_0: [
    "................",
    "................",
    "......OOOO......",
    ".....OuuuuO.....",
    "....OuuuuuuO....",
    "....OuOuuOuO....",
    "....OuuuuuuO....",
    "....OUuuuuUO....",
    ".....OuuuUO.....",
    "......OuUO......",
    ".......OO.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  wisp_1: [
    "................",
    "................",
    "................",
    "......OOOO......",
    ".....OuuuuO.....",
    "....OuOuuOuO....",
    "....OuuuuuuO....",
    "....OUuuuuUO....",
    ".....OUuuuO.....",
    "......OUuO......",
    ".......OO.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  // MOON GHOST — the classic sheet, mid-difficulty band.
  ghost_0: [
    "................",
    ".....OOOOOO.....",
    "....OxxccccO....",
    "...OxcccccccO...",
    "...OcOccccOcO...",
    "...OccccccccO...",
    "..OccccOOccccO..",
    "..OccccccccccO..",
    "..OccccccccccO..",
    "..OCccccccccCO..",
    "..OCcOccccOcCO..",
    "...OCO.OO.OCO...",
    "................",
    "................",
    "................",
    "................",
  ],
  ghost_1: [
    "................",
    "................",
    ".....OOOOOO.....",
    "....OxxccccO....",
    "...OxcccccccO...",
    "...OcOccccOcO...",
    "...OccccccccO...",
    "..OccccOOccccO..",
    "..OccccccccccO..",
    "..OccccccccccO..",
    "..OCccccccccCO..",
    "..OCcOccccOcCO..",
    "...OCO.OO.OCO...",
    "................",
    "................",
    "................",
  ],
  // WRAITH — fast, hooded, red-eyed; prowls the far side.
  wraith_0: [
    "......OOOO......",
    ".....OmmmmO.....",
    "....OmmmmmmO....",
    "....OmRmmRmO....",
    "....OmmmmmmO....",
    "...OmmmMMmmmO...",
    "...OmmmmmmmmO...",
    "..OmmMmmmmMmmO..",
    "..OmmmmmmmmmmO..",
    "..OMmmmmmmmmMO..",
    "..OMmMmmmmMmMO..",
    "...OMOMmmMOMO...",
    "....O.OMMO.O....",
    ".......OO.......",
    "................",
    "................",
  ],
  wraith_1: [
    "......OOOO......",
    ".....OmmmmO.....",
    "....OmmmmmmO....",
    "....OmRmmRmO....",
    "....OmmmmmmO....",
    "...OmmMMmmmmO...",
    "...OmmmmmmmmO...",
    "..OmmMmmmmMmmO..",
    "..OmmmmmmmmmmO..",
    "..OMmmmmmmmmMO..",
    "..OMmMmmmmMmMO..",
    "...OMOMmmMOMO...",
    "....O..OMMO.O...",
    "........OO......",
    "................",
    "................",
  ],
  // ARMSTRONG — the boss: a giant astronaut ghost with ENORMOUS arms,
  // haunting the flag he planted. 48×48, generated-then-tuned by hand.
  armstrong_0: [
    "................................................",
    "................................................",
    "....................OOOOOOOO....................",
    "..................OOnnnnnnnnOO..................",
    ".................OWWWWnnnnnnnnO.................",
    "................OnnnnnnOOnnnnnnO................",
    "...............OnnnOOOOOOOOOOnnnO...............",
    "..............OnnnOOOOOOOOOOOOnnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "...............OnnOOOOOOOOOOOOnnO...............",
    "................OnnOOOOOOOOOOnnO................",
    "...........OOOOOnnnnnnnOOnnnnnnnOOOOO...........",
    "........OOOnnnnnnnnnnnnnnnnnnnnnnnnnnOOO........",
    "......OOnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnOO......",
    ".....OnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnO.....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnNnnnnnnnnnnnnnnnnnnNnnNnnnnnnnO...",
    "...OnnnnnnnNOnNnnnnnnnnnnnnnnnnnnNnONnnnnnnnO...",
    "...OnnnnnnnO.ONNnnnnnnnnnnnnnnnnNNO.OnnnnnnnO...",
    "...OnnnnnnnO.ONNNnnnnnnnnnnnnnnNNNO.OnnnnnnnO...",
    "...OnnnnnnnO..ONNNnnnnnnnnnnnnNNNO..OnnnnnnnO...",
    "..OnnnnnnnnnO.OnnnnnnnnnnnnnnnnnnO.OnnnnnnnnnO..",
    "..OnnnnnnnnnO..OnnnnnnnnnnnnnnnnO..OnnnnnnnnnO..",
    ".OnnnnnnnnnnnO..OnnnnnnnnnnnnnnO..OnnnnnnnnnnnO.",
    "..OnnnnnnnnnO...OnnnnnnnnnnnnnnO...OnnnnnnnnnO..",
    "..OnNNNNNNnnO..OnnnnnnnnnnnnnnnnO..OnNNNNNNnnO..",
    "...OnnnnnnnO....OnnnnnnnnnnnnnnO....OnnnnnnnO...",
    "...OOnnnnnOO....OnnnnnnnnnnnnnnO....OOnnnnnOO...",
    ".....OOOOO.......OnnnnnnnnnnnnO.......OOOOO.....",
    "...............OOnnnnnnnnnnnnnnOO...............",
    "..............OnnnnOOOnnnOOOOnnnnO..............",
    "..............OnnnO...OnO....OnnnO..............",
    "..............OnnnO..OnnnO...OnnnO..............",
    "...............OOO...OnnnO....OOO...............",
    ".....................OnnnO......................",
    "......................OOO.......................",
  ],
  armstrong_1: [
    "................................................",
    "................................................",
    "....................OOOOOOOO....................",
    "..................OOnnnnnnnnOO..................",
    ".................OWWWWnnnnnnnnO.................",
    "................OnnnnnnOOnnnnnnO................",
    "...............OnnnOOOOOOOOOOnnnO...............",
    "..............OnnnOOOOOOOOOOOOnnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOWWOOOOOOWWOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "..............OnnOOOOOOOOOOOOOOnnO..............",
    "...............OnnOOOOOOOOOOOOnnO...............",
    "................OnnOOOOOOOOOOnnO................",
    "...........OOOOOnnnnnnnOOnnnnnnnOOOOO...........",
    "......OOOOOnnnnnnnnnnnnnnnnnnnnnnnnnnOOOOO......",
    ".....OnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnO.....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "....OnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnO....",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoyyoorronnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnoooooooonnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnnnnnnnnnnnnnnnnnnnnnnnNnnnnnnnO...",
    "...OnnnnnnnNnnNnnnnnnnnnnnnnnnnnnNnnNnnnnnnnO...",
    "...OnnnnnnnNOnNnnnnnnnnnnnnnnnnnnNnONnnnnnnnO...",
    "...OnnnnnnnO.ONNnnnnnnnnnnnnnnnnNNO.OnnnnnnnO...",
    "..OnnnnnnnnnOONNNnnnnnnnnnnnnnnNNNOOnnnnnnnnnO..",
    "..OnnnnnnnnnO.ONNNnnnnnnnnnnnnNNNO.OnnnnnnnnnO..",
    ".OnnnnnnnnnnnOOnnnnnnnnnnnnnnnnnnOOnnnnnnnnnnnO.",
    "..OnnnnnnnnnO..OnnnnnnnnnnnnnnnnO..OnnnnnnnnnO..",
    "..OnNNNNNNnnO...OnnnnnnnnnnnnnnO...OnNNNNNNnnO..",
    "...OnnnnnnnO....OnnnnnnnnnnnnnnO....OnnnnnnnO...",
    "...OOnnnnnOO...OnnnnnnnnnnnnnnnnO...OOnnnnnOO...",
    ".....OOOOO......OnnnnnnnnnnnnnnO......OOOOO.....",
    "................OnnnnnnnnnnnnnnO................",
    ".................OnnnnnnnnnnnnO.................",
    "...............OOnnnnnnnnnnnnnnOO...............",
    "..............OnnnnOOOOnnnOOOnnnnO..............",
    "..............OnnnO....OnO...OnnnO..............",
    "..............OnnnO...OnnnO..OnnnO..............",
    "...............OOO....OnnnO...OOO...............",
    "......................OnnnO.....................",
    ".......................OOO......................",
  ],
  // Landmarks: the ship at the landing site and the old flag.
  lander: [
    "................................",
    "..................AA............",
    "..................A.............",
    "............OOOOOOOO............",
    "............OaaaaaaO............",
    "............OaaaaaaO............",
    "..........OOaaaaaaaaOO..........",
    "..........OaaOOOaaaaAO..........",
    "..........OaaOOOaAAAAO..........",
    "..........OaaOOOaAAAAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    ".......OOOooooooooooooOOO.......",
    ".......OooooooooooooooqqO.......",
    ".......OqooqooqooqooqoqqO.......",
    ".......OooooooooooooooqqO.......",
    ".......OoqooqooqooqooqqqO.......",
    ".......OooooooooooooooqqO.......",
    ".......OooooooooooooooqqO.......",
    ".......OqqqqqqqqqqqqqqqqO.......",
    ".......OOOOOOOqqqqOOOOOOO.......",
    "......OO......OAAO......OO......",
    ".....OO.......OAAO.......OO.....",
    "....OO.......OOOOOO.......OO....",
    "...OO......................OO...",
    ".OOOOO....................OOOOO.",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  flag: [
    "................",
    "...OO...........",
    "...OAOOOOOOOOOO.",
    "...OAOjjjjjrrrO.",
    "...OAOjWjjjrrrO.",
    "...OAOjjjjjWWWO.",
    "...OAOjjjjjWWWO.",
    "...OAOrrrrrrrrO.",
    "...OAOWWWWWWWWO.",
    "...OAOrrrrrrrrO.",
    "...OAOOOOOOOOOO.",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "...OAO..........",
    "..OOAOO.........",
    "................",
  ],
  // Moonscape decor: craters and strewn rocks (no collision).
  crater_big: [
    "................................",
    "................................",
    "................................",
    "................................",
    "..............dddd..............",
    "..........FFdddddddddd..........",
    ".......FFFFdddddddddddddd.......",
    "......FFFFd.eeeeeeee.ddddd......",
    ".....FFFFeeeeeeeeeeeeeedddd.....",
    "....FFF.eeeeee....eeeeee.ddd....",
    "...FFFeeeee..........eeeeeddd...",
    "..FFFFeee..............eeedddd..",
    "..FFFeeee..............eeeeddd..",
    ".FFFeeee................eeeeddd.",
    ".FFdeee..................eeeddd.",
    ".Fddeee..................eeeddd.",
    ".dddeee..................eeeddd.",
    ".dddeee..................eeeddd.",
    ".dddeeee................eeeeddd.",
    "..dddeeee..............eeeeddd..",
    "..ddddeee..............eeedddd..",
    "...dddeeeee..........eeeeeddd...",
    "....ddd.eeeeee....eeeeee.ddd....",
    ".....ddddeeeeeeeeeeeeeedddd.....",
    "......ddddd.eeeeeeee.ddddd......",
    ".......dddddddddddddddddd.......",
    "..........dddddddddddd..........",
    "..............dddd..............",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  crater_small: [
    "................",
    "................",
    "......Fddd......",
    "...FFFddddddd...",
    "..FFF.eeee.ddd..",
    ".FF.eeeeeeee.dd.",
    ".FFee......eedd.",
    ".F.ee......ee.d.",
    ".d.ee......ee.d.",
    ".ddee......eedd.",
    ".dd.eeeeeeee.dd.",
    "..ddd.eeee.ddd..",
    "...dddddddddd...",
    "......dddd......",
    "................",
    "................",
  ],
  rocks: [
    "................",
    "................",
    "................",
    "...eeee.........",
    "..edddde........",
    "...eeee.........",
    "..........eeee..",
    "..........edde..",
    "..........eeee..",
    "................",
    "................",
    ".....eee........",
    ".....eee........",
    "................",
    "................",
    "................",
  ],
  // Solid obstacles (collision in the engine): the tall boulder blocks
  // everything; the low rock can be jumped over (never by monsters).
  boulder: [
    "............OOOOO...........",
    "..........OOFFFFOOO.........",
    ".........OFFFFFFFFFOO.......",
    "........OFFFFFFFffffOO......",
    ".......OFFFFFdFFffffffO.....",
    "......OFFFFFdffffffffffO....",
    ".....OFFFFFdfffffffffffO....",
    "....OFFFFFdffffffffffffdO...",
    "...OFFFFFdffffffffffffddO...",
    "..OFFFFFdfffffffdfffffddO...",
    "..OFFFFdffffffffdffffdddO...",
    ".OFFFFdfffffffffdfffddddO...",
    ".OFFFdffffffffffdffdddddO...",
    ".OFFfffffffffffdddddddddO...",
    ".OFffffffffffffdeeddddddOO..",
    "OFffffffffffffdeeedddddddO..",
    "OffffffffffffdeeeddddddddO..",
    "OfffffffdddddeeedddddddeeO..",
    "OffffdddddddeeeddddddeeeeO..",
    ".OdddddddddeeedddddeeeeeO...",
    ".OOddddddddeedddddeeeeeOO...",
    "...OOOOOOOOOOOOOOOOOOOO.....",
  ],
  rock: [
    "..................",
    ".....OOOOOOOO.....",
    "...OOFFFfffffOO...",
    "..OFFFFffffffffO..",
    ".OFFFfddffffffddO.",
    ".OFFfffffffffdddO.",
    ".OfffffffffdddddO.",
    ".OfffdfffdddeddeO.",
    "..OfffffddddddeO..",
    "...OOfddddddeOO...",
    ".....OOOOOOOO.....",
    "..................",
  ],
  // MOONROCK — solid slabs in 1×1, 1×2 and 2×2 footprints (16 px per cell),
  // sized to match the engine's rectangular collision box. Tall, chiselled
  // stone: sight, shots and blasts all stop at them. Lit top-left, shadowed
  // bottom-right, like the boulder.
  moonrock_1x1: [
    "................",
    "...OOOOOO.......",
    ".OOFFFFffOOO....",
    ".OFFFFffffffOO..",
    "OFFFFffffffffdO.",
    "OFFFffffffffddO.",
    "OFFffffffefddddO",
    "OffffffffeOddddO",
    "OfffffffddeOddO.",
    "OffffffdddeOddO.",
    "OfffffdddddeddO.",
    ".OfffddddddddO..",
    ".OffddddddddeO..",
    "..OOdddddddOO...",
    "....OOOOOOO.....",
    "................",
  ],
  moonrock_1x2: [
    "................",
    ".....OOOOO......",
    "...OOFFFffOO....",
    "..OFFFFFffffOO..",
    "..OFFFFffffffO..",
    ".OFFFFffffffffO.",
    ".OFFFFffffffffO.",
    ".OFFFffffefffdO.",
    "OFFFFffffeOffdO.",
    "OFFFffffffeOdddO",
    "OFFfffffffeOddO.",
    "OFFffffffffeddO.",
    ".OffffffffedddO.",
    ".OfffffffdeddO..",
    ".OfffffffdddddO.",
    ".OffffffddddddO.",
    "OfffffffddddddO.",
    "OffffffdddddddO.",
    "OfffffddddddddO.",
    ".OffffdddddddddO",
    ".OfffdddddddddO.",
    ".OffdedddddddeO.",
    ".OffddeOdddddeO.",
    ".OfdddeOddddeO..",
    ".OfddddeddddeO..",
    "..OddddedddeeeO.",
    ".OddddddddeeeeO.",
    "..OdddddddeeeO..",
    "..OddddddeeeeO..",
    "...OOddddeeOO...",
    ".....OOOOOO.....",
    "................",
  ],
  moonrock_2x2: [
    "................................",
    "................................",
    "........OOOOOOOOOOOOOOO.........",
    ".....OOOFFFFffffeffffffOOOO.....",
    "...OOFFFFFFfffffeffffffffddOO...",
    "..OFFFFFFFfffffffeffffffdddddO..",
    "..OFFFFFFffffffffefffffdddddddO.",
    ".OFFFFFFffffffffffffffddddddddO.",
    ".OFFFFFffffffffffffffdddddddddO.",
    ".OFFFFffffffffffffffddddddddddO.",
    ".OFFffffffffffffffddddddddddddO.",
    ".OFffffffffffffffddddddddddddOO.",
    ".OffffffffffffffddddddddddddO...",
    ".OfffffffffffffddddddddddddO....",
    ".OffffffffffffddddddddddddddOO..",
    ".OfffffffffffddddddddddddddeeeO.",
    ".OffffffffffddddddddddddddeeeeO.",
    ".OOffffffffddddddddddddddeeeeeO.",
    "...OffffffddddddddddddddeeeeeeO.",
    "..OffffffddddddddddddddeeeeeeeO.",
    ".OfffffddddddOeddddddeeeeeeeeeO.",
    ".OffffdddddddOedddddeeeeeeeeeeO.",
    ".OfffdddddddddOedddeeeeeeeeeeeO.",
    ".OffddddddddddOedOeeeeeeeeeeeeO.",
    ".OfddddddddddOeddeOeeeeeeeeeeeO.",
    ".OddddddddddddOeeeeOeeeeeeeeeO..",
    "..OdddddddddddOeeeeeOeeeeeeeO...",
    "..OdddddddddddeOeeeeeeeeeeeO....",
    "...OOddddddddeeeeeeeeeeeeOO.....",
    ".....OOOddddeeeeeeeeeOOOO.......",
    "........OOOOOOOOOOOOO...........",
    "................................",
  ],
  // Ground tiles. Keep edges featureless so they tile without seams;
  // moon_1 carries a small pock, gravel_* are the scree patches.
  moon_0: [
    "ffffffffffffffff",
    "fffffffffffffdff",
    "ffFfffffffffFfff",
    "fffffffffffdffff",
    "ffffffffffffffff",
    "ffffffffffFfffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
    "fffffdffffffffff",
    "ffffffffffffffff",
    "fffffffffffddfff",
    "ffffffffffdfffff",
    "fffFffffffffffff",
    "fffffffffffffdff",
    "ffffffffffffffff",
    "ffffffffffffffff",
  ],
  moon_1: [
    "ffffffffffffffff",
    "fdFfffffffffffff",
    "ffffffffffffdfff",
    "fffffffFffffffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
    "fffffffddfffffff",
    "ffffffdeedffffff",
    "ffffffdeedffffdf",
    "fffffffddfffffff",
    "ffffFfffffffffff",
    "fffdffffffffffff",
    "ffffffffffffffff",
    "ffffffffdfffffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
  ],
  gravel_0: [
    "ffffffffffffffff",
    "ffffffffFfffffff",
    "fffffFffffffffff",
    "fffffddFffffffff",
    "fffffdFfdfffffff",
    "ffFffffddfffffff",
    "ffddffffffffffff",
    "ffddffffffffffff",
    "ffffffffffedfeff",
    "fffffffffffffddf",
    "ffffffFffffffFff",
    "ffedffddffFfffff",
    "ffddffdfffffffff",
    "fffffedfddfFffff",
    "fFffffffdfffffff",
    "ffffffffffffffff",
  ],
  gravel_1: [
    "ffffffffffffffff",
    "ffffffffffffffff",
    "ffffffffffffffff",
    "ffffffFffffFffff",
    "ffffffddfffedfff",
    "fffffffFffFdffff",
    "ffffffffffeeffff",
    "ffffffffffFddfff",
    "fffffffffFfddfff",
    "ffffffffffffedff",
    "ffffffffffFfddff",
    "ffffffffffffFfff",
    "ffffffFffffffFff",
    "fffffffdffffffdf",
    "ffffffddffffffdf",
    "ffffffffffffffff",
  ],
  // ECTO — the ghost-tier recolor of the blood-splash droplets; the base
  // frames live with the other gore in sprite-data/effects.mjs.
  ecto_0: swapPalette(BLOOD_0, { r: "c" }),
  ecto_1: swapPalette(BLOOD_1, { r: "x" }),
  // MISSION SPECIALIST - an Apollo suit gone spectral below the waist.
  apollo_ghost_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOaaaaaaOO.......",
    "......OaaaaaaaaaaO......",
    "......OaaOYyyyOaaO......",
    "......OaaOyyyyOaaO......",
    "......OaaOyyyyOaaO......",
    ".......OaaaaaaaaO.......",
    "......OaaaaaaaaaaO......",
    ".....OaaAaaaaaaAaaO.....",
    "....OaaaAaarraaAaaaO....",
    "....OaaaAaaaaaaAaaaO....",
    "....OaaOAaaaaaaAOaaO....",
    ".....OcaaaaaaaaaacO.....",
    ".....OccaaaaaaaaccO.....",
    "......OcccccccccO.......",
    ".......OCcccccCO........",
    "......OCcO.OccO.........",
    ".......OO...OCO.........",
    ".............O..........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  apollo_ghost_1: [
    "........................",
    "........................",
    ".........OOOOOO.........",
    ".......OOaaaaaaOO.......",
    "......OaaaaaaaaaaO......",
    "......OaaOYyyyOaaO......",
    "......OaaOyyyyOaaO......",
    "......OaaOyyyyOaaO......",
    ".......OaaaaaaaaO.......",
    "......OaaaaaaaaaaO......",
    ".....OaaAaaaaaaAaaO.....",
    "....OaaaAaarraaAaaaO....",
    "....OaaaAaaaaaaAaaaO....",
    "....OaaOAaaaaaaAOaaO....",
    ".....OcaaaaaaaaaacO.....",
    ".....OccaaaaaaaaccO.....",
    "......OcccccccccO.......",
    ".......OCcccccCO........",
    ".........OcO.OcCO.......",
    ".........OO...OO........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // THE PROSPECTOR - a dead lunar miner: gold hard hat with a lit headlamp,
  // carrying a pickaxe over the shoulder.
  prospector_0: [
    ".........OyyyO..........",
    "........OYyyyyO.........",
    "......OoooYYoooO........",
    ".......HHHWWHHHuO.......",
    ".......OuuYYuuuuO..O....",
    ".......OuOuuuuOuO.AT....",
    ".......OuuuuuuuuO.AAO...",
    "........OuuuuuuOTAA.....",
    "......OuuuuuuuuAAkd.....",
    ".....OuuUuuuuuOdkuO.....",
    "....OuuuUuuuuEkUuuuO....",
    "....OuuuUuuuEkuUuuuO....",
    "....OuuOUuEkkuuUOuuO....",
    ".....OuuuEkuuuuuuuO.....",
    ".....OUEkkuuuuuuuUO.....",
    "......ukuuuuuuuuUO......",
    ".......OUuuOOuuUO.......",
    "......OUuO...OuUO.......",
    ".......OO.....OO........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  prospector_1: [
    ".........OyyyO..........",
    "........OYyyyyO.........",
    "......OoooYYoooO........",
    ".......HHHWWHHHO........",
    ".......OuuYYuuuuO..O....",
    ".......OuuuuuuuuO.AT....",
    ".......OuOuuuuOuO.AAO...",
    ".......OuuuuuuuuTAA.....",
    "........OuuuuuuAAkd.....",
    "......OuuuuuuuOdkO......",
    ".....OuuUuuuuEkUuuO.....",
    "....OuuuUuuuEkuUuuuO....",
    "....OuuuUuEkkuuUuuuO....",
    "....OuuOUEkuuuuUOuuO....",
    ".....OUEkkuuuuuuuuO.....",
    ".....OukuuuuuuuuuUO.....",
    "......OUuuuuuuuuUO......",
    ".......OUuuOOuuUO.......",
    "........OuO...OuO.......",
    ".........O.....O........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // QUARANTINE MEDIC - a ghost in whites, red cross still on duty.
  quarantine_medic_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOccccccOO.......",
    "......OccccccccccO......",
    "......OccOccccOccO......",
    "......OccccccccccO......",
    ".......OccccccccO.......",
    "......OWWWWWWWWWWO......",
    ".....OWWWWWrrWWWWWO.....",
    "....OWWWWrrrrrrWWWWO....",
    "....OWWWWrrrrrrWWWWO....",
    "....OWWWWWWrrWWWWWWO....",
    "....OccOWWWWWWWWOccO....",
    ".....OWwWWWWWWWWwWO.....",
    ".....OcWWWWWWWWWWcO.....",
    "......OccWWWWWWccO......",
    ".......OCccccccCO.......",
    "......OCcO..OccO........",
    ".......OO....OCO........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  quarantine_medic_1: [
    "........................",
    "........................",
    ".........OOOOOO.........",
    ".......OOccccccOO.......",
    "......OccccccccccO......",
    "......OccOccccOccO......",
    "......OccccccccccO......",
    ".......OccccccccO.......",
    "......OWWWWWWWWWWO......",
    ".....OWWWWWrrWWWWWO.....",
    "....OWWWWrrrrrrWWWWO....",
    "....OWWWWrrrrrrWWWWO....",
    "....OWWWWWWrrWWWWWWO....",
    "....OccOWWWWWWWWOccO....",
    ".....OWwWWWWWWWWwWO.....",
    ".....OcWWWWWWWWWWcO.....",
    "......OccWWWWWWccO......",
    ".......OCccccccCO.......",
    "........OcO..OcCO.......",
    ".........O....OO........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // THE CARTOGRAPHER - a red-eyed wraith poring over a gold chart.
  cartographer_0: [
    "........................",
    ".........OOOOOO.........",
    "........OmmmmmmO........",
    ".......OmmmmmmmmO.......",
    ".......OmRmmmmRmO.......",
    ".......OmmmmmmmmO.......",
    "........OmmMMmmO........",
    "......OmmmmmmmmmmO......",
    ".....OmmMmmmmmmMmmO.....",
    "....OmmmMmmmmmmMmmmO....",
    "....OmmOooooooooOmmO....",
    "....OmmOoqoqqoqoOmmO....",
    "....OmmOooooooooOmmO....",
    ".....OmmmmmmmmmmmmO.....",
    ".....OMmmmmmmmmmmMO.....",
    "......OMmmmmmmmmMO......",
    ".......OMmmOOmmMO.......",
    "......OMmO...OmMO.......",
    ".......OO.....OO........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  cartographer_1: [
    "........................",
    "........................",
    ".........OOOOOO.........",
    "........OmmmmmmO........",
    ".......OmmmmmmmmO.......",
    ".......OmRmmmmRmO.......",
    ".......OmmmmmmmmO.......",
    "........OmmMMmmO........",
    "......OmmmmmmmmmmO......",
    ".....OmmMmmmmmmMmmO.....",
    "....OmmmMmmmmmmMmmmO....",
    "....OmmOooooooooOmmO....",
    "....OmmOoqoqqoqoOmmO....",
    "....OmmOooooooooOmmO....",
    ".....OmmmmmmmmmmmmO.....",
    ".....OMmmmmmmmmmmMO.....",
    "......OMmmmmmmmmMO......",
    ".......OMmOOOmmMO.......",
    "........OmO...OMO.......",
    ".........O.....O........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
};

export default {
  name: "moon",
  /** Ground tile behind this family's contact sheet. */
  ground: "moon_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {
    wisp_float: { frames: ["wisp_0", "wisp_1"], delayMs: 340 },
    ghost_float: { frames: ["ghost_0", "ghost_1"], delayMs: 300 },
    wraith_float: { frames: ["wraith_0", "wraith_1"], delayMs: 240 },
    armstrong_loom: { frames: ["armstrong_0", "armstrong_1"], delayMs: 420 },
    apollo_ghost_float: {
      frames: ["apollo_ghost_0", "apollo_ghost_1"],
      delayMs: 340,
    },
    prospector_float: {
      frames: ["prospector_0", "prospector_1"],
      delayMs: 320,
    },
    quarantine_medic_float: {
      frames: ["quarantine_medic_0", "quarantine_medic_1"],
      delayMs: 340,
    },
    cartographer_float: {
      frames: ["cartographer_0", "cartographer_1"],
      delayMs: 280,
    },
  },
  /**
   * Wound-style overrides — mobs whose gore-derived default (index.mjs)
   * doesn't read on their body colors. Pale-bodied tiers darken in the
   * ghost-dark; the violet wraith and the shrouded elites keep the pale
   * ecto default — dark-on-dark wounds don't read. ARMSTRONG smears in his
   * own tier's darker green.
   */
  wounds: {
    wisp: { splat: "C" },
    ghost: { splat: "C" },
    prospector: { splat: "U", core: "C" },
    armstrong: { splat: "N" },
  },
  /** Ground tiles and flat regolith decor the contrast lint skips. */
  contrastExempt: [
    "moon_0",
    "moon_1",
    "gravel_0",
    "gravel_1",
    "crater_big",
    "crater_small",
    "rocks",
  ],
};
