// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The prelude family (see the `pixel-assets` skill): the living-room props
// and cast of the opening cutscene. One string per pixel row, one character
// per pixel; `.` is transparent and every other char must exist in
// CORE_PALETTE (sprite-data/core.mjs) or this family's local palette.

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {};

const SPRITES = {
  // ---- The prelude: living-room props ---------------------------------------
  // The couch our hero holds down for the whole scene.
  couch: [
    "....................................",
    ".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..",
    ".OBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBO..",
    ".OBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBO..",
    ".OBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBO..",
    ".OBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBO..",
    ".OBBSSSSSSSSSSSSSSSSSSSSSSSSSSBBBO..",
    ".OBBOOOOOOOOOOOOOOOOOOOOOOOOOOBBBO..",
    ".OBBOSSSSSSSSSOSSSSSSSSOSSSSSOBBBO..",
    ".OBBOSSSSSSSSSOSSSSSSSSOSSSSSOBBBO..",
    ".OBBOSSSSSSSSSOSSSSSSSSOSSSSSOBBBO..",
    ".OBBOEEEEEEEEEOEEEEEEEEOEEEEEOBBBO..",
    ".OBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBO..",
    ".OEBBBBBBBBBBBBBBBBBBBBBBBBBBBBEEO..",
    ".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...",
    "..OkkO..........................OkkO",
    "..OkkO..........................OkkO",
    "....................................",
    "....................................",
    "....................................",
  ],
  // The TV, mid-movie, lighting the room.
  tv: [
    "........................",
    "..OOOOOOOOOOOOOOOOOOOO..",
    ".ObbbbbbbbbbbbbbbbbbbbO.",
    ".ObOOOOOOOOOOOOOOOOOObO.",
    ".ObOxxxxxxxxxxxxxxxxObO.",
    ".ObOxxxxxxccccxxxxxxObO.",
    ".ObOxxxcccccccccxxxxObO.",
    ".ObOxxxxxcccxxxxxxxxObO.",
    ".ObOxxxxxxxxxxxxxxxxObO.",
    ".ObOOOOOOOOOOOOOOOOOObO.",
    ".ObbbbbbbbbbbbbbbbbbbbO.",
    "..OOOOOOOOOOOOOOOOOOOO..",
    "........ObbbbO..........",
    "......ObbbbbbbbO........",
    "......OOOOOOOOOO........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // The coffee table. Conspicuously chipless. Sodaless too.
  table: [
    "....................",
    "..OOOOOOOOOOOOOOOO..",
    ".OBBBBBBBBBBBBBBBBO.",
    ".OEEEEEEEEEEEEEEEEO.",
    "..OEEO........OEEO..",
    "..OEEO........OEEO..",
    "..OOOO........OOOO..",
    "....................",
    "....................",
    "....................",
  ],
  // A floor lamp doing its best.
  lamp: [
    "..........",
    "...OOOO...",
    "..OyyyyO..",
    ".OyyYyyyO.",
    ".OyyyyyyO.",
    ".OOOOOOOO.",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "...OObO...",
    "..ObbbbO..",
    "..OOOOOO..",
    "..........",
    "..........",
  ],
  // The front door. Last seen closing.
  door: [
    "..................",
    ".OOOOOOOOOOOOOOOO.",
    ".OVVVVVVVVVVVVVVO.",
    ".OVOOOOOOOOOOOOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEBBBByBEBOVO.",
    ".OVOBEBBBByBEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOOOOOOOOOOOOVO.",
    ".OVVVVVVVVVVVVVVO.",
    ".OOOOOOOOOOOOOOOO.",
    "..................",
    "..................",
  ],
  // The window: night outside, and — wait for it — the moon.
  window: [
    "....................",
    ".OOOOOOOOOOOOOOOOOO.",
    ".OVVVVVVVVVVVVVVVVO.",
    ".OVOOOOOOOOOOOOOOVO.",
    ".OVOJJJJJJJJJffJOVO.",
    ".OVOJJJWJJJJffffOVO.",
    ".OVOJJJJJJJJffffOVO.",
    ".OVOJWJJJJJJJffJOVO.",
    ".OVOJJJJJWJJJJJJOVO.",
    ".OVOJJJJJJJJJJJJOVO.",
    ".OVOJJJJJJJJWJJJOVO.",
    ".OVOJJJJJJJJJJJJOVO.",
    ".OVOOOOOOOOOOOOOOVO.",
    ".OVVVVVVVVVVVVVVVVO.",
    ".OOOOOOOOOOOOOOOOOO.",
    "....................",
  ],
  // The crude sword on the wall: dull steel blade (point up), a plain
  // crossguard and a wrapped grip, resting on two small mount pegs. The one
  // thing the hero takes with him — his default weapon on the moon.
  wall_sword: [
    "....OO....",
    "...OVvO...",
    "...OVvO...",
    "...OVvO...",
    "...OVvO...",
    "..OOVvOO..",
    "..ObVvbO..",
    "...OVvO...",
    "...OVvO...",
    "...OVvO...",
    "...OVvO...",
    "..OVVvvO..",
    ".OOOOOOOO.",
    ".OqqqqqqO.",
    ".OOOOOOOO.",
    "...OkkO...",
    "...OkkO...",
    "...OkkO...",
    "...OOOO...",
    "...OaaO...",
    "...OOOO...",
    "..........",
  ],
  // ---- The prelude: the cast ------------------------------------------------
  // ADA — red jacket (the one with the beacon in it), off to the store.
  ada_0: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OkppppkO....",
    "...OrrrrrrrrO...",
    "..OrrrWWrrrrrO..",
    "..OrrrWWrrrrrO..",
    "..OpOrrrrrrOpO..",
    "...OrrrrrrrrO...",
    "...OjjO..OjjO...",
    "...OjjO..OjjO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  ada_1: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OkppppkO....",
    "...OrrrrrrrrO...",
    "..OrrrWWrrrrrO..",
    "..OrrrWWrrrrrO..",
    "..OpOrrrrrrOpO..",
    "...OrrrrrrrrO...",
    "..OjjO....OjjO..",
    "..OjjO....OjjO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // Our hero, couch mode: white tee, knees up, movie face. Frame 1 blinks
  // with the TV light.
  hero_couch_0: [
    "................",
    "................",
    "......OOOOO.....",
    ".....OkkkkkO....",
    ".....OpOpppO....",
    ".....OppppkO....",
    ".....OWWWWWO....",
    "....OWWWWWWWO...",
    "....OWWWWWWWO...",
    "...OjjjjOWWWO...",
    "..OjjjjjjWWWO...",
    "..OjjOOjjOOO....",
    "..OOO..OOO......",
    "................",
    "................",
    "................",
  ],
  hero_couch_1: [
    "................",
    "................",
    "......OOOOO.....",
    ".....OkkkkkO....",
    ".....OpppppO....",
    ".....OppppkO....",
    ".....OWWWWWO....",
    "....OWWWWWWWO...",
    "....OWWWWWWWO...",
    "...OjjjjOWWWO...",
    "..OjjjjjjWWWO...",
    "..OjjOOjjOOO....",
    "..OOO..OOO......",
    "................",
    "................",
    "................",
  ],
};

export default {
  name: "prelude",
  /** Ground tile behind this family's contact sheet. */
  ground: "lab_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {
    ada_walk: { frames: ["ada_0", "ada_1"], delayMs: 220 },
    hero_couch_idle: { frames: ["hero_couch_0", "hero_couch_1"], delayMs: 600 },
  },
  contrastExempt: [],
};
