// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The prelude family (see the `pixel-assets` skill): the living-room props
// and cast of the opening cutscene. One string per pixel row, one character
// per pixel; `.` is transparent and every other char must exist in
// CORE_PALETTE (sprite-data/core.mjs) or this family's local palette.

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  // Billionaire black (same value as the icons family's local N): the
  // combat knife's tactical grip on the wall mount.
  N: [48, 52, 68],
};

const SPRITES = {
  // ---- The prelude: living-room props ---------------------------------------
  // The couch our hero holds down for the whole scene.
  couch: [
    "....................................",
    ".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..",
    ".OBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBO..",
    ".OBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBO..",
    ".OBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBO..",
    ".OBSSSSSSSSSSSSSSSSSSSSSSSSSSSSSBO..",
    ".OBBSSSSSSSSSSSSSSSSSSSSSSSSSSBBBO..",
    ".OBBOOOOOOOOOOOOOOOOOOOOOOOOOOBBBO..",
    ".OBBOSSSSSSSSSOSSSSSSSSOSSSSSOBBBO..",
    ".OBBOSSSSSSSSSOSSSSSSSSOSSSSSOBBBO..",
    ".OBBOSSSSSSSSSOSSSSSSSSOSSSSSOBBBO..",
    ".OBBOEEEEEEEEEOEEEEEEEEOEEEEEOBBBO..",
    ".OBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBO..",
    ".OEBBBBBBBBBBBBBBBBBBBBBBBBBBBBEEO..",
    ".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...",
    "..OkkO..........................OkkO",
    "..OkkO..........................OkkO",
    "....................................",
    "....................................",
    "....................................",
  ],
  // The TV, mid-movie, lighting the room.
  tv: [
    "........................",
    "..OOOOOOOOOOOOOOOOOOOO..",
    ".ObbbbbbbbbbbbbbbbbbbbO.",
    ".ObOOOOOOOOOOOOOOOOOObO.",
    ".ObOxxxxxxxxxxxxxxxxObO.",
    ".ObOxxxxxxccccxxxxxxObO.",
    ".ObOxxxcccccccccxxxxObO.",
    ".ObOxxxxxcccxxxxxxxxObO.",
    ".ObOxxxxxxxxxxxxxxxxObO.",
    ".ObOOOOOOOOOOOOOOOOOObO.",
    ".ObbbbbbbbbbbbbbbbbbbbO.",
    "..OOOOOOOOOOOOOOOOOOOO..",
    "........ObbbbO..........",
    "......ObbbbbbbbO........",
    "......OOOOOOOOOO........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // The coffee table. Conspicuously chipless. Sodaless too.
  table: [
    "....................",
    "..OOOOOOOOOOOOOOOO..",
    ".OBBBBBBBBBBBBBBBBO.",
    ".OEEEEEEEEEEEEEEEEO.",
    "..OEEO........OEEO..",
    "..OEEO........OEEO..",
    "..OOOO........OOOO..",
    "....................",
    "....................",
    "....................",
  ],
  // A floor lamp doing its best.
  lamp: [
    "..........",
    "...OOOO...",
    "..OyyyyO..",
    ".OyyYyyyO.",
    ".OyyyyyyO.",
    ".OOOOOOOO.",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "....Ob....",
    "...OObO...",
    "..ObbbbO..",
    "..OOOOOO..",
    "..........",
    "..........",
  ],
  // The front door. Last seen closing.
  door: [
    "..................",
    ".OOOOOOOOOOOOOOOO.",
    ".OVVVVVVVVVVVVVVO.",
    ".OVOOOOOOOOOOOOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEBBBByBEBOVO.",
    ".OVOBEBBBByBEBOVO.",
    ".OVOBEBBBBBBEBOVO.",
    ".OVOBEEEEEEEEBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOBBBBBBBBBBOVO.",
    ".OVOOOOOOOOOOOOVO.",
    ".OVVVVVVVVVVVVVVO.",
    ".OOOOOOOOOOOOOOOO.",
    "..................",
    "..................",
  ],
  // The window: night outside, and — wait for it — the moon.
  window: [
    "....................",
    ".OOOOOOOOOOOOOOOOOO.",
    ".OVVVVVVVVVVVVVVVVO.",
    ".OVOOOOOOOOOOOOOOVO.",
    ".OVOJJJJJJJJJffJOVO.",
    ".OVOJJJWJJJJffffOVO.",
    ".OVOJJJJJJJJffffOVO.",
    ".OVOJWJJJJJJJffJOVO.",
    ".OVOJJJJJWJJJJJJOVO.",
    ".OVOJJJJJJJJJJJJOVO.",
    ".OVOJJJJJJJJWJJJOVO.",
    ".OVOJJJJJJJJJJJJOVO.",
    ".OVOOOOOOOOOOOOOOVO.",
    ".OVVVVVVVVVVVVVVVVO.",
    ".OOOOOOOOOOOOOOOOOO.",
    "....................",
  ],
  // ---- The wall arsenal: ONE of these hangs on the back wall, picked by the
  // difficulty (the prelude scene has a per-difficulty variant — see
  // defs/cutscenes.ts WALL_ARMS). All rest on the same small mount pegs so
  // the wall reads the same however the run is armed.
  // MEDIUM: the medieval sword — dull steel blade (point up), a plain
  // crossguard and a wrapped grip.
  wall_medieval_sword: [
    "....OO....",
    "...OVvO...",
    "...OVvO...",
    "...OVvO...",
    "...OVvO...",
    "..OOVvOO..",
    "..ObVvbO..",
    "...OVvO...",
    "...OVvO...",
    "...OVvO...",
    "...OVvO...",
    "..OVVvvO..",
    ".OOOOOOOO.",
    ".OqqqqqqO.",
    ".OOOOOOOO.",
    "...OkkO...",
    "...OkkO...",
    "...OkkO...",
    "...OOOO...",
    "...OaaO...",
    "...OOOO...",
    "..........",
  ],
  // EASY: HAIRY POTTER'S WAND — a gold-glow tip on a slim shaft, the grip end
  // bristling with fur. Mount pegs mid-shaft.
  wall_hairy_wand: [
    "..........",
    "...OOOO...",
    "..OYyyYO..",
    "..OyyyyO..",
    "...OyyO...",
    "...OkkO...",
    "...OkkO...",
    "..ObkkbO..",
    "...OkkO...",
    "...OkkO...",
    "...OkkO...",
    "...OkkO...",
    "...OkkO...",
    "..OBkkBO..",
    "..OBBBBO..",
    "..OBBBBO..",
    "...OBBO...",
    "....OO....",
    "..........",
    "..........",
    "..........",
    "..........",
  ],
  // HARD: the COMBAT KNIFE — a short bright blade over a dark bar guard and
  // a black grip, on the same pegs.
  wall_combat_knife: [
    "..........",
    "..........",
    "....OO....",
    "...OVvO...",
    "...OVvO...",
    "...OVvO...",
    "..OOVvOO..",
    "..ObVvbO..",
    "...OVvO...",
    "...OVvO...",
    "..OVVvvO..",
    "..OOOOOO..",
    "..OaaaaO..",
    "..OOOOOO..",
    "...ONNO...",
    "...ONNO...",
    "...ONNO...",
    "....OO....",
    "..........",
    "..........",
    "..........",
    "..........",
  ],
  // NIGHTMARE: the BRASS KNUCKLES — a gold duster hung flat, palm bar down,
  // resting on one peg.
  wall_brass_knuckles: [
    "............",
    "............",
    "............",
    "............",
    "............",
    ".OOOOOOOOOO.",
    "OYYyyyyyyyyO",
    "OyOyOyOyOyyO",
    "OyOyOyOyOyyO",
    "OyyyyyyyyyyO",
    ".OOqqqqqqOO.",
    "..OqqqqqqO..",
    "...OOOOOO...",
    "....ObbO....",
    "....ObbO....",
    "....OOOO....",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
  ],
  // JESUS CHRIST!: A STICK — crooked, knotted, proudly mounted like an
  // heirloom. Pegs and all.
  wall_stick: [
    "..........",
    "....OO....",
    "...OBBO...",
    "...OBBO...",
    "...OBEO...",
    "...OBBO...",
    "..ObBBbO..",
    "...OBEO...",
    "...OBBO...",
    "..OBBO....",
    "..OBEO....",
    "..OBBO....",
    "..OBBO....",
    "...OBEO...",
    "...OBBO...",
    "...OBBO...",
    "....OO....",
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
  ],
  // ---- The prelude: the cast ------------------------------------------------
  // ADA — red jacket (the one with the beacon in it), off to the store.
  ada_0: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OkppppkO....",
    "...OrrrrrrrrO...",
    "..OrrrWWrrrrrO..",
    "..OrrrWWrrrrrO..",
    "..OpOrrrrrrOpO..",
    "...OrrrrrrrrO...",
    "...OjjO..OjjO...",
    "...OjjO..OjjO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  ada_1: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OkppppkO....",
    "...OrrrrrrrrO...",
    "..OrrrWWrrrrrO..",
    "..OrrrWWrrrrrO..",
    "..OpOrrrrrrOpO..",
    "...OrrrrrrrrO...",
    "..OjjO....OjjO..",
    "..OjjO....OjjO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // ADA, couch mode: same seated silhouette as the hero, red jacket (the one
  // with the beacon) instead of the white tee, so the two read as a matched
  // pair on the sofa. A `pose` beat swaps her to the standing `ada` sprite
  // when she gets up for the store. Frame 1 blinks with the TV light.
  ada_couch_0: [
    "................",
    "................",
    "......OOOOO.....",
    ".....OkkkkkO....",
    ".....OpOpppO....",
    ".....OppppkO....",
    ".....OrrrrrO....",
    "....OrrWWrrrO...",
    "....OrrWWrrrO...",
    "...OjjjjOrrrO...",
    "..OjjjjjjrrrO...",
    "..OjjOOjjOOO....",
    "..OOO..OOO......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  ada_couch_1: [
    "................",
    "................",
    "......OOOOO.....",
    ".....OkkkkkO....",
    ".....OpppppO....",
    ".....OppppkO....",
    ".....OrrrrrO....",
    "....OrrWWrrrO...",
    "....OrrWWrrrO...",
    "...OjjjjOrrrO...",
    "..OjjjjjjrrrO...",
    "..OjjOOjjOOO....",
    "..OOO..OOO......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  // Our hero, couch mode: white tee, knees up, movie face. Frame 1 blinks
  // with the TV light.
  hero_couch_0: [
    "................",
    "................",
    "......OOOOO.....",
    ".....OkkkkkO....",
    ".....OpOpppO....",
    ".....OppppkO....",
    ".....OWWWWWO....",
    "....OWWWWWWWO...",
    "....OWWWWWWWO...",
    "...OjjjjOWWWO...",
    "..OjjjjjjWWWO...",
    "..OjjOOjjOOO....",
    "..OOO..OOO......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  hero_couch_1: [
    "................",
    "................",
    "......OOOOO.....",
    ".....OkkkkkO....",
    ".....OpppppO....",
    ".....OppppkO....",
    ".....OWWWWWO....",
    "....OWWWWWWWO...",
    "....OWWWWWWWO...",
    "...OjjjjOWWWO...",
    "..OjjjjjjWWWO...",
    "..OjjOOjjOOO....",
    "..OOO..OOO......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
};

export default {
  name: "prelude",
  /** Ground tile behind this family's contact sheet. */
  ground: "lab_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {
    ada_walk: { frames: ["ada_0", "ada_1"], delayMs: 220 },
    ada_couch_idle: { frames: ["ada_couch_0", "ada_couch_1"], delayMs: 600 },
    hero_couch_idle: { frames: ["hero_couch_0", "hero_couch_1"], delayMs: 600 },
  },
  contrastExempt: [],
};
