// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The Rift family (see the `pixel-assets` skill): level 4 — the
// hallucinatory space between universes. Void ground with star specks,
// nebula patches, black holes and asteroids, alien fauna (voidlings, star
// jellies, unravelers, gravitons), history's missing (TESLA, EARHART,
// RASPUTIN, and the apparitions HOUDINI and THE KING), and GROK OMEGA —
// ZAI's secret superintelligence, a floating monolith with one huge eye.
// One string per pixel row, one character per pixel; `.` is transparent and
// every other char must exist in CORE_PALETTE (sprite-data/core.mjs) or
// this family's local palette.

import { GHOST } from "./core.mjs";

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  // The ecto wound core the damage generator paints on this family's pale
  // fauna (same char the moon's haunting uses; scoped per family).
  C: GHOST.dark,
  // The void floor sits at a deep indigo rather than true black: every
  // sprite here wears the standard dark outline, and on a near-black ground
  // silhouettes dissolve (the contrast lint calls it at <60). The letterbox
  // beyond the level bounds stays near-black, so the play field still reads
  // as a lit island of unreality floating in nothing.
  z: [66, 60, 104], // void floor base
  Z: [46, 42, 76], // void deep
  u: [140, 140, 182], // dim star speck
  e: [108, 70, 150], // nebula wisp
  d: [80, 50, 112], // nebula core
  K: [10, 9, 16], // absolute black: hole cores, the King's pompadour
  N: [42, 46, 70], // entity shell: lost TV, dark suits
  Q: [96, 240, 208], // AI glow cyan
  X: [236, 82, 190], // glitch magenta
};

const SPRITES = {
  // ---- The rift's fauna (16×16 minions) --------------------------------------
  // VOIDLING — a ragged scrap of hungry dark with three pale eyes. Frames
  // squish the blob and flick the tendrils.
  voidling_0: [
    "................",
    "................",
    "......OOOO......",
    "....OOPPPPO.....",
    "...OPPPPPPPO....",
    "..OPPxPPPxPPO...",
    "..OPPxPPPxPPO...",
    ".OPPPPPPPPPPPO..",
    ".OPPPPPxPPPPPO..",
    ".OMPPPPPPPPMPO..",
    ".OMMPPMMPPMMPO..",
    "..OMMMMMMMMMO...",
    "...OMMO..OMO....",
    "....OO....O.....",
    "................",
    "................",
  ],
  voidling_1: [
    "................",
    "................",
    "................",
    "......OOOO......",
    "...OOOPPPPOO....",
    "..OPPPxPPPxPO...",
    "..OPPPxPPPxPO...",
    ".OPPPPPPPPPPPO..",
    ".OPPPPPxPPPPPO..",
    ".OMPPPPPPPPMPO..",
    ".OMMPPMMPPMMPO..",
    "..OMMMMMMMMMO...",
    "....OMO..OMMO...",
    ".....O....OO....",
    "................",
    "................",
  ],
  // STAR JELLY — a translucent drifter: pale dome, faint organs, trailing
  // strands. It phases through everything; the frames sway the strands.
  star_jelly_0: [
    "................",
    "................",
    ".....OOOOOO.....",
    "....OxxxcccO....",
    "...OxxccccccO...",
    "..OxcccccccccO..",
    "..OcccPccPcccO..",
    "..OccccccccccO..",
    "...OOOOOOOOOO...",
    "...OcO.OcO.OcO..",
    "...OcO.OcO.OcO..",
    "....OmO.OmO.O...",
    "....OmO..OmO....",
    ".....O....O.....",
    "................",
    "................",
  ],
  star_jelly_1: [
    "................",
    "................",
    ".....OOOOOO.....",
    "....OxxxcccO....",
    "...OxxccccccO...",
    "..OxcccccccccO..",
    "..OccPccPccccO..",
    "..OccccccccccO..",
    "...OOOOOOOOOO...",
    "..OcO.OcO.OcO...",
    "..OcO.OcO.OcO...",
    "...O.OmO.OmO....",
    "....OmO..OmO....",
    ".....O....O.....",
    "................",
    "................",
  ],
  // UNRAVELER — a person-shaped glitch in the local reality: violet body,
  // magenta slabs tearing out of it, a cyan scanline. The frames teleport
  // the tears to the other side.
  unraveler_0: [
    "................",
    ".....OOOO.......",
    "....OmmmmO......",
    "....OmQQmO......",
    "....OmmmmO......",
    "..XXOmmmmO......",
    "..XXOmmmmmO.....",
    "...OmmXXmmO.....",
    "...OmmXXmmO.....",
    "...OmmmmmmO.....",
    "..QQQmmmmmO.....",
    "...OmmmmmmO.....",
    "...OmO..OmO.....",
    "...OmO..OmO.....",
    "...OO....OO.....",
    "................",
  ],
  unraveler_1: [
    "................",
    ".....OOOO.......",
    "....OmmmmO......",
    "....OQQmmO......",
    "....OmmmmO......",
    "....OmmmmOXX....",
    "...OmmmmmOXX....",
    "...OmmXXmmO.....",
    "...OmmXXmmO.....",
    "...OmmmmmmO.....",
    "...OmmmmmQQQ....",
    "...OmmmmmmO.....",
    "...OmO..OmO.....",
    "...OmO..OmO.....",
    "...OO....OO.....",
    "................",
  ],
  // GRAVITON — a fist-sized collapsed star: a void-black heart in a hot
  // gold ring, dragging a purple halo. The frames orbit the outer sparks.
  graviton_0: [
    "................",
    "................",
    "....yy..........",
    ".....OOOOO......",
    "....OPyyyPO.....",
    "...OPyKKKyPO....",
    "...OyKKKKKyO....",
    "...OyKKKKKyO....",
    "...OPyKKKyPO....",
    "....OPyyyPO.....",
    ".....OOOOO......",
    "..........yy....",
    "................",
    "................",
    "................",
    "................",
  ],
  graviton_1: [
    "................",
    "................",
    "..........yy....",
    ".....OOOOO......",
    "....OPyyyPO.....",
    "...OPyKKKyPO....",
    "...OyKKKKKyO....",
    "...OyKKKKKyO....",
    "...OPyKKKyPO....",
    "....OPyyyPO.....",
    ".....OOOOO......",
    "....yy..........",
    "................",
    "................",
    "................",
    "................",
  ],
  // ---- History's missing (24×24 elites) --------------------------------------
  // NIKOLA TESLA — the sharp black suit, the middle-parted hair, the
  // mustache, and stray current crackling off his cuffs.
  nikola_tesla_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppkkkkppO.......",
    "........OppppppO........",
    "......ONNNWWWWNNNO......",
    ".....ONNNNWWWWNNNNO.....",
    "....ONNNNNNWWNNNNNNO....",
    "....ONNNNNNNNNNNNNNO....",
    "....ONpONNNNNNNOpNO.....",
    ".....OyNNNNNNNNNyO......",
    ".....ONNNNNNNNNNNO......",
    "......ONNNNOONNNNO......",
    "......ONNNO..ONNNO......",
    "......ONNNO..ONNNO......",
    "......ONNNO..ONNNO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  nikola_tesla_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppkkkkppO.......",
    "........OppppppO........",
    "......ONNNWWWWNNNO......",
    ".....ONNNNWWWWNNNNO.....",
    "....ONNNNNNWWNNNNNNO....",
    "....ONNNNNNNNNNNNNNO....",
    "....ONpONNNNNNNOpNO.....",
    ".....ONyNNNNNNNyNO......",
    ".....ONNNNNNNNNNNO......",
    "......ONNNNOONNNNO......",
    ".....ONNNO....ONNNO.....",
    ".....ONNNO....ONNNO.....",
    ".....ONNNO....ONNNO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // AMELIA EARHART — leather flight cap with the goggles pushed up, white
  // scarf, bomber jacket, ninety years of circling.
  amelia_earhart_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOBBBBBBOO.......",
    ".......OBByyyyBBO.......",
    ".......OBppppppBO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OBBWWWWWBBBO......",
    ".....OBBBWWWWWBBBBO.....",
    "....OBBBBBWWBBBBBBBO....",
    "....OBSBBBBWWBBBSBBO....",
    "....OBpOBBBWWBBOpBO.....",
    ".....OBSBBBBBBBSBO......",
    ".....OBBBBBBBBBBBO......",
    "......OBBBBOOBBBBO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  amelia_earhart_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOBBBBBBOO.......",
    ".......OBByyyyBBO.......",
    ".......OBppppppBO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OBBWWWWWBBBO......",
    ".....OBBBWWWWWBBBBO.....",
    "....OBBBBBWWBBBBBBBO....",
    "....OBSBBBBWWBBBSBBO....",
    "....OBpOBBBWWBBOpBO.....",
    ".....OBSBBBBBBBSBO......",
    ".....OBBBBBBBBBBBO......",
    "......OBBBBOOBBBBO......",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // GRIGORI RASPUTIN — the unkillable mystic: floor-length black robe, a
  // beard past his chest, a gold cross, and eyes that glow wrong.
  grigori_rasputin_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    "......OkkkkkkkkkkO......",
    "......OkkppppppkkO......",
    "......OkpRppppRpkO......",
    "......OkkppppppkkO......",
    ".......OkkkkkkkkO.......",
    "......ONNkkkkkkNNO......",
    ".....ONNNkkkkkkNNNO.....",
    "....ONNNNkkkkkkNNNNO....",
    "....ONNNNNkkkkNNNNNO....",
    "....ONpONNykyNNOpNO.....",
    ".....ONNNNyyyNNNNNO.....",
    ".....ONNNNNyNNNNNO......",
    ".....ONNNNNNNNNNNO......",
    ".....ONNNNNNNNNNNO......",
    ".....ONNNNNNNNNNNO......",
    ".....ONNNNNNNNNNNO......",
    ".....OOOOOOOOOOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  grigori_rasputin_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    "......OkkkkkkkkkkO......",
    "......OkkppppppkkO......",
    "......OkpRppppRpkO......",
    "......OkkppppppkkO......",
    ".......OkkkkkkkkO.......",
    "......ONNkkkkkkNNO......",
    ".....ONNNkkkkkkNNNO.....",
    "....ONNNNkkkkkkNNNNO....",
    "....ONNNNNkkkkNNNNNO....",
    "....ONpONNykyNNOpNO.....",
    ".....ONNNNyyyNNNNNO.....",
    ".....ONNNNNyNNNNNO......",
    ".....ONNNNNNNNNNNO......",
    "....ONNNNNNNNNNNNNO.....",
    "....ONNNNNNNNNNNNNO.....",
    "....ONNNNNNNNNNNNNO.....",
    "....OOOOOOOOOOOOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // HARRY HOUDINI — the apparition of the escape artist: spectral pale,
  // strapped into a ghost of a straitjacket, chains and a gold padlock —
  // none of which are holding him. He trails off instead of standing.
  harry_houdini_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOmmmmmmOO.......",
    ".......OmmmmmmmmO.......",
    ".......OmccccccmO.......",
    ".......OcOccccOcO.......",
    ".......OccccccccO.......",
    "........OccccccO........",
    "......OxxxxxxxxxxO......",
    ".....OxxvvvvvvvxxxO.....",
    "....OxcccccccccccxO.....",
    "....OxxvvvvvvvvxxxO.....",
    "....OxxxxxyyxxxxxxO.....",
    ".....OxxxxyyxxxxxO......",
    ".....OxxxxxxxxxxxO......",
    "......OcccccccccO.......",
    "......OcccOOcccO........",
    ".......OccO.OcO.........",
    "........OcO..OcO........",
    ".........O....O.........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  harry_houdini_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOmmmmmmOO.......",
    ".......OmmmmmmmmO.......",
    ".......OmccccccmO.......",
    ".......OcOccccOcO.......",
    ".......OccccccccO.......",
    "........OccccccO........",
    "......OxxxxxxxxxxO......",
    ".....OxxvvvvvvvxxxO.....",
    "....OxcccccccccccxO.....",
    "....OxxvvvvvvvvxxxO.....",
    "....OxxxxxyyxxxxxxO.....",
    ".....OxxxxyyxxxxxO......",
    ".....OxxxxxxxxxxxO......",
    "......OcccccccccO.......",
    "......OcccOOcccO........",
    ".......OcO..OccO........",
    "......OcO....OcO........",
    ".......O......O.........",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // THE KING — the apparition in the white jumpsuit: black pompadour and
  // sideburns, gold shades, rhinestone trim, flared legs. Uh-huh.
  the_king_0: [
    "........................",
    "........OOOOOOO.........",
    "......OOKKKKKKKOO.......",
    "......OKKKKKKKKKO.......",
    ".......OKppppppKO.......",
    ".......OpyOppOypO.......",
    "......OKKppppppKKO......",
    "........OppppppO........",
    "......OWWWWyyWWWWO......",
    ".....OWWWWWyyWWWWWO.....",
    "....OWwWWWWyyWWWwWWO....",
    "....OWWWWWWyyWWWWWWO....",
    "....OWpOWWWyyWWOpWO.....",
    ".....OWwWWWWWWWwWO......",
    ".....OWWWWWWWWWWWO......",
    "......OWWWWOOWWWWO......",
    "......OWWWO..OWWWO......",
    "......OWWWO..OWWWO......",
    ".....OWWWWO..OWWWWO.....",
    ".....OOOOOO..OOOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  the_king_1: [
    "........................",
    "........OOOOOOO.........",
    "......OOKKKKKKKOO.......",
    "......OKKKKKKKKKO.......",
    ".......OKppppppKO.......",
    ".......OpyOppOypO.......",
    "......OKKppppppKKO......",
    "........OppppppO........",
    "......OWWWWyyWWWWO......",
    ".....OWWWWWyyWWWWWO.....",
    "....OWwWWWWyyWWWwWWO....",
    "....OWWWWWWyyWWWWWWO....",
    "....OWpOWWWyyWWOpWO.....",
    ".....OWwWWWWWWWwWO......",
    ".....OWWWWWWWWWWWO......",
    "......OWWWWOOWWWWO......",
    ".....OWWWO....OWWWO.....",
    ".....OWWWO....OWWWO.....",
    "....OWWWWO....OWWWWO....",
    "....OOOOOO....OOOOOO....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // ---- GROK OMEGA (48×48 boss) ------------------------------------------------
  // ZAI's latest superintelligence, manifested as a hovering steel monolith
  // with one enormous eye, a crown of drifting crystals, circuit traces for
  // veins, and glitch slabs tearing off its edges. No legs — it floats on a
  // shimmer of anti-grav purple. Frames bob the crown, wander the pupil,
  // and relocate the glitch.
  grok_omega_0: [
    "............PP.........PP........PP.............",
    "............LP.........LP........LP.............",
    "................................................",
    "......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO......",
    "......OVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvQQQQQQQQQQQQQQQQQQQQQQQQQQQQvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvOOOOOOOOOOOOOOOOOOOOOOOOOOOOOObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKxxxxxxxxKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKxxxxxxxxxxxxxxKKKKKKKObbO......",
    "......OVvOKKKKKxxxxxxxxxxxxxxxxxxKKKKKObbO......",
    "......OVvOKKKKxxxxxxxxQQQQxxxxxxxxKKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbO......",
    "......OVvOKKxxxxxxxQQQQKKQQQQxxxxxxxKKObbO......",
    "......OVvOKKKxxxxxxxQQQKKQQQxxxxxxxKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbO......",
    "......OVvOKKKKxxxxxxxxQQQQxxxxxxxxKKKKObbO......",
    "......OVvOKKKKKxxxxxxxxxxxxxxxxxxKKKKKObbO......",
    "......OVvOKKKKKKKxxxxxxxxxxxxxxKKKKKKKObbO......",
    "....XXOVvOKKKKKKKKKKxxxxxxxxKKKKKKKKKKObbO......",
    "....XXOVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOOOOOOOOOOOOOOOOOOOOOOOOOOOOOObbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvQQQQQQQQQQQvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvQvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvQQQQQQQQQQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvQQQQQQQQQQQQvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbO......",
    "......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO......",
    "................................................",
    "..............PP.......PP.......PP..............",
    "..............P........P........P...............",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
  ],
  grok_omega_1: [
    "................................................",
    "............PP.........PP........PP.............",
    "............LP.........LP........LP.............",
    "......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO......",
    "......OVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvQQQQQQQQQQQQQQQQQQQQQQQQQQQQvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvOOOOOOOOOOOOOOOOOOOOOOOOOOOOOObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKxxxxxxxxKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKxxxxxxxxxxxxxxKKKKKKKObbO......",
    "......OVvOKKKKKxxxxxxxxxxxxxxxxxxKKKKKObbO......",
    "......OVvOKKKKxxxxxxxxQQQQxxxxxxxxKKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbOXX....",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbOXX....",
    "......OVvOKKxxxxxxxQQQQQQKKQQxxxxxxxKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQKKQxxxxxxxKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbO......",
    "......OVvOKKKKxxxxxxxxQQQQxxxxxxxxKKKKObbO......",
    "......OVvOKKKKKxxxxxxxxxxxxxxxxxxKKKKKObbO......",
    "......OVvOKKKKKKKxxxxxxxxxxxxxxKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKxxxxxxxxKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOOOOOOOOOOOOOOOOOOOOOOOOOOOOOObbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvQQQQQQQQQQQvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvQvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvQQQQQQQQQQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvQQQQQQQQQQQQvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbO......",
    "......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO......",
    "................................................",
    "................................................",
    "..............PP.......PP.......PP..............",
    "..............P........P........P...............",
    "................................................",
    "................................................",
    "................................................",
  ],
  // ---- Hazards ----------------------------------------------------------------
  // BLACK HOLE — the well's core visual: an absolute-black heart, a hot
  // gold inner ring, and purple accretion arms. Frames rotate the arms.
  blackhole_0: [
    "................................",
    "................................",
    "..............LL................",
    ".............LPP................",
    "............LP..................",
    "...........LP.......PP..........",
    "..........LP.......PLLP.........",
    "................................",
    "..........MPPP..................",
    ".........MP..yyyyyy.............",
    ".........MP.yyKKKKyy............",
    "........MP.yKKKKKKKKy...........",
    "........MP.yKKKKKKKKy...........",
    "........MP.yKKKKKKKKy...........",
    "...PP......yKKKKKKKKy...........",
    "..PLLP.....yKKKKKKKKy...........",
    "...PP.......yyKKKKyy.PM.........",
    "..............yyyyyy..PM........",
    "..................PP..PM........",
    "..................PPPM..........",
    "................................",
    ".........PLP....................",
    "..........PL....................",
    "...........PL...................",
    "............PL..................",
    ".............PLL................",
    "..............PP................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  blackhole_1: [
    "................................",
    "................................",
    "................................",
    "................PP..............",
    "...............PLLP.............",
    "................PP..............",
    "......PP........................",
    ".......PLL......................",
    ".........PL.....................",
    "..........PPyyyyyy..............",
    "............yyKKKKyy............",
    "...........yKKKKKKKKy...........",
    "...........yKKKKKKKKy...........",
    "...........yKKKKKKKKy...........",
    "...........yKKKKKKKKy...........",
    "...........yKKKKKKKKy...........",
    "............yyKKKKyy............",
    "..............yyyyyyPP..........",
    "....................PLL.........",
    "......................PL........",
    ".......................PM.......",
    "........................PM......",
    "................................",
    "......MP........................",
    ".....MP.........................",
    "....MP..........PP..............",
    "...............PLLP.............",
    "................PP..............",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  // ASTEROID — a tumbling rock: moon-gray hide, cratered. Frames rotate
  // the crater pattern a quarter turn.
  asteroid_0: [
    "................",
    ".....OOOOO......",
    "...OOfFFffOO....",
    "..OfFFFFfffbO...",
    "..OFFfffffbbO...",
    ".OfFfffEEffbbO..",
    ".OFffffEEfffbO..",
    ".OFfffffffffbO..",
    ".OffEEffffbbbO..",
    ".OffEEfffbbbbO..",
    "..OfffffbbbbO...",
    "..OffbbbbbbO....",
    "...OObbbbOO.....",
    ".....OOOO.......",
    "................",
    "................",
  ],
  asteroid_1: [
    "................",
    ".....OOOOO......",
    "...OOfFFffOO....",
    "..OfFFFFfffbO...",
    "..OFFffEEffbO...",
    ".OfFfffEEffbbO..",
    ".OFffffffffbbO..",
    ".OFffffffEEfbO..",
    ".OfffffffEEbbO..",
    ".OfffffffbbbbO..",
    "..OfffffbbbbO...",
    "..OffbbbbbbO....",
    "...OObbbbOO.....",
    ".....OOOO.......",
    "................",
    "................",
  ],
  // ---- Obstacles & decor ------------------------------------------------------
  // RIFT SHARD — a crystallized moment: solid amethyst spears. Blocks
  // sight, shots and feet.
  rift_shard: [
    "................",
    "......OO........",
    ".....OLPO..OO...",
    ".....OLPO.OLPO..",
    "....OLPPPOOLPO..",
    "....OLPPPOLPPO..",
    "...OLPPMPPPPMO..",
    "...OLPPMPPPPMO..",
    "...OLPPPMPPMMO..",
    "..OLPPPPMPPMMO..",
    "..OLPPPPPMPMMO..",
    "..OLPPMPPPPMMO..",
    "..OPPPMMPPMMMO..",
    "...OOOOOOOOOO...",
    "................",
    "................",
  ],
  // SPACE JUNK — a drifting pile of somebody's cargo: hoppable cover.
  space_junk: [
    "................",
    "................",
    "....OOOOOO......",
    "...OVvvvvbO.....",
    "...OvvoovbO.....",
    "..OOOOOOOOOOO...",
    "..OVVvvvvvvbO...",
    "..OvvvqqvvvbO...",
    "..OvvvqqvvbbO...",
    "..OvvvvvvbbbO...",
    "..OOOOOOOOOOO...",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  // STARDUST — a loose sparkle of ground-up somewhere else (no collision).
  stardust: [
    "................",
    "................",
    "....xx..........",
    "....xx..........",
    "................",
    "..........uu....",
    "..........uu....",
    "................",
    "................",
    "......xx........",
    "......xx........",
    "................",
    "............uu..",
    "............uu..",
    "................",
    "................",
  ],
  // FLOATING ROCK — a chunk of ground that forgot which way is down,
  // hovering on a shimmer of anti-grav purple.
  floating_rock: [
    "................",
    "................",
    "....OOOOOO......",
    "...OfFFfffO.....",
    "..OfFFffffbO....",
    "..OffffffbbO....",
    "...OffffbbO.....",
    "....OOOOOO......",
    "................",
    ".....PP.PP......",
    "......P.P.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  // LOST TV — somebody's television, still tuned to WEBFLIX static.
  lost_tv: [
    "................",
    "....vv.....vv...",
    ".....vv...vv....",
    "......v...v.....",
    "....OOOOOOOOO...",
    "...ONNNNNNNNNO..",
    "...ONOOOOOOONO..",
    "...ONOxxQxxONO..",
    "...ONOxQxxxONO..",
    "...ONOxxxQxONO..",
    "...ONOOOOOOONO..",
    "...ONNNNNNNNNO..",
    "...OOOOOOOOOOO..",
    "....ON.....NO...",
    "................",
    "................",
  ],
  // ---- Ground tiles (16×16) ---------------------------------------------------
  // The void floor: near-black indigo with dim star specks. Edges stay
  // featureless so the nothing tiles without seams; void_1 carries one
  // brighter star.
  void_0: [
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzuzzzzzzzzzzzzz",
    "zzzzzzzzzzZZzzzz",
    "zzzzzzzzzzZZzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzuzz",
    "zzzZZzzzzzzzzzzz",
    "zzzZZzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzuzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzZZzz",
    "zuzzzzzzzzzzZZzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
  ],
  void_1: [
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzuzzzzz",
    "zzZZzzzzzzzzzzzz",
    "zzZZzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzxxzzzzzzzz",
    "zzzzzxxxxzzzzzzz",
    "zzzzzxxxxzzzzzzz",
    "zzzzzzxxzzzzzzzz",
    "zzzzzzzzzzzzZZzz",
    "zzuzzzzzzzzzZZzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzuzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
  ],
  // Nebula patches: violet wisps pooling in the dark.
  nebula_0: [
    "zzzzzzzzzzzzzzzz",
    "zzzzeezzzzzzzzzz",
    "zzzeddeezzzzzzzz",
    "zzeddddeezzzzzzz",
    "zzzeddeezzzuzzzz",
    "zzzzeezzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzeeezzzzz",
    "zzzzzzzeddeezzzz",
    "zzzzzzzeddeezzzz",
    "zzzzzzzzeeezzzzz",
    "zzuzzzzzzzzzzzzz",
    "zzzzzzzzzzzzeezz",
    "zzzzzzzzzzzeddez",
    "zzzzzzzzzzzzeezz",
    "zzzzzzzzzzzzzzzz",
  ],
  nebula_1: [
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzeezzzz",
    "zzzzzzzzzeddeezz",
    "zzzzzzzzeddddeez",
    "zzzzzzzzzeddeezz",
    "zzzzzzzzzzeezzzz",
    "zzuzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzeeezzzzzzzzzzz",
    "zeddeezzzzzzzzzz",
    "zeddeezzzzuzzzzz",
    "zzeeezzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzeezzzzzzz",
    "zzzzzzeddezzzzzz",
    "zzzzzzzeezzzzzzz",
  ],
  // ---- Projectiles ------------------------------------------------------------
  // The SINGULARITY CANNON's shot: a very small, very rude black hole.
  singularity: [
    "........",
    "..PPP...",
    ".PKKKL..",
    ".PKKKKL.",
    ".PKKKKL.",
    "..LKKL..",
    "...LLL..",
    "........",
  ],
  // ---- Icons (12×12) ----------------------------------------------------------
  // TESLA COIL — the tower, the torus, the spark.
  icon_tesla_coil: [
    "............",
    ".....yy.....",
    "....yYYy....",
    "....yYYy....",
    ".....yy.....",
    "....OvvO....",
    "....OvvO....",
    "...OvvvvO...",
    "....OvvO....",
    "...OkkkkO...",
    "..OkkkkkkO..",
    "............",
  ],
  // SINGULARITY CANNON — a fat barrel wrapped around a black core.
  icon_singularity_cannon: [
    "............",
    "............",
    "...OOOOOO...",
    "..OvVVVvvO..",
    ".OvPPPPvvbO.",
    ".OvPKKPvvbO.",
    ".OvPKKPvvbO.",
    ".OvPPPPvvbO.",
    "..OvvvvbbO..",
    "...OOOOOO...",
    "......ObO...",
    "............",
  ],
  // AVIATOR GOGGLES — two gold lenses on a leather strap.
  icon_goggles: [
    "............",
    "............",
    "............",
    ".OBBBBBBBBO.",
    "OBOOOBBOOOBO",
    "OByyOBBOyyBO",
    "OByyOBBOyyBO",
    "OBOOOBBOOOBO",
    ".OBBBBBBBBO.",
    "............",
    "............",
    "............",
  ],
  // RASPUTIN'S BEARD — the beard. It survived everything.
  icon_beard: [
    "............",
    "...OO..OO...",
    "..OkkOOkkO..",
    "..OkkkkkkO..",
    "..OkkkkkkO..",
    "..OkkkkkkO..",
    "...OkkkkO...",
    "...OkkkkO...",
    "....OkkO....",
    "....OkkO....",
    ".....OO.....",
    "............",
  ],
  // GOLDEN PARACHUTE — deploys automatically upon career failure.
  icon_parachute: [
    "............",
    "....yyyy....",
    "..yyYYYYyy..",
    ".OyYYYYYYyO.",
    ".OyOyOyOyO..",
    "..O.O.O.O...",
    "..O..O..O...",
    "...OOOOO....",
    "....OOO.....",
    "....OWO.....",
    ".....O......",
    "............",
  ],
  // WARDENCLYFFE NOTES — free energy, underlined twice.
  icon_notes: [
    "............",
    "..OOOOOOOO..",
    ".OWWWWWWWWO.",
    ".OWkkkkkWWO.",
    ".OWWWWWWWWO.",
    ".OWkkkkkkWO.",
    ".OWWWyyWWWO.",
    ".OWWyyWWWWO.",
    ".OWyyyyWWWO.",
    ".OWWWWWWWWO.",
    "..OOOOOOOO..",
    "............",
  ],
  // ZAI PROBE — burnt, still logging, still telling exactly one recipient.
  icon_probe: [
    "............",
    ".....yy.....",
    "....Oyy.....",
    "....OvvO....",
    "...OvVVvO...",
    "..OvVvvvvO..",
    "..OvvXXvvO..",
    "..OvvXXvvO..",
    "...OvvvbO...",
    "....OObO....",
    "...ObO.ObO..",
    "............",
  ],
};

export default {
  name: "rift",
  /** Ground tile behind this family's contact sheet. */
  ground: "void_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {
    voidling_squish: { frames: ["voidling_0", "voidling_1"], delayMs: 320 },
    star_jelly_drift: {
      frames: ["star_jelly_0", "star_jelly_1"],
      delayMs: 360,
    },
    unraveler_glitch: { frames: ["unraveler_0", "unraveler_1"], delayMs: 200 },
    graviton_orbit: { frames: ["graviton_0", "graviton_1"], delayMs: 260 },
    grok_omega_hum: { frames: ["grok_omega_0", "grok_omega_1"], delayMs: 380 },
    blackhole_spin: { frames: ["blackhole_0", "blackhole_1"], delayMs: 240 },
    asteroid_tumble: { frames: ["asteroid_0", "asteroid_1"], delayMs: 220 },
  },
  /**
   * Wound-overlay overrides where the defaults vanish on the local body
   * colors: the STAR JELLY is itself ecto-pale (cyan splats disappear), so
   * it bruises in slime purple instead.
   */
  wounds: {
    star_jelly: { splat: "P", core: "M" },
    // The graviton is a gold ring around a black heart — spark-gold wounds
    // vanish on it, so it cracks in glitch magenta instead.
    graviton: { splat: "X", core: "P" },
  },
  /** Ground tiles and flat sparkle decor the contrast lint skips. */
  contrastExempt: ["void_0", "void_1", "nebula_0", "nebula_1", "stardust"],
};
