// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The Rift family (see the `pixel-assets` skill): level 4 — the
// hallucinatory space between universes. Void ground with star specks,
// nebula patches, black holes and asteroids, alien fauna (voidlings, star
// jellies, unravelers, gravitons), history's missing (TESLA, EARHART,
// RASPUTIN, and the apparitions HOUDINI and THE KING), and GROK OMEGA —
// ZAI's secret superintelligence, a floating monolith with one huge eye.
// One string per pixel row, one character per pixel; `.` is transparent and
// every other char must exist in CORE_PALETTE (sprite-data/core.mjs) or
// this family's local palette.

import { swapPalette } from "../asset-tools/palette.mjs";
import { GHOST } from "./core.mjs";

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  // The ecto wound core the damage generator paints on this family's pale
  // fauna (same char the moon's haunting uses; scoped per family).
  C: GHOST.dark,
  // The void floor sits at a deep indigo rather than true black: every
  // sprite here wears the standard dark outline, and on a near-black ground
  // silhouettes dissolve (the contrast lint calls it at <60). The letterbox
  // beyond the level bounds stays near-black, so the play field still reads
  // as a lit island of unreality floating in nothing.
  z: [66, 60, 104], // void floor base
  Z: [46, 42, 76], // void deep
  u: [140, 140, 182], // dim star speck
  e: [108, 70, 150], // nebula wisp
  d: [80, 50, 112], // nebula core
  K: [10, 9, 16], // absolute black: hole cores, the King's pompadour
  N: [42, 46, 70], // entity shell: lost TV, dark suits
  Q: [96, 240, 208], // AI glow cyan
  X: [236, 82, 190], // glitch magenta
  t: [204, 112, 40], // LUCKY's ginger beard
};

const SPRITES = {
  // ---- The rift's fauna (16×16 minions) --------------------------------------
  // VOIDLING — a scrap of hungry dark: a near-black ragged blob studded with
  // too many pale eyes (a big central eye anchoring a swarm of smaller ones).
  // The dark body reads as a hole full of eyes against the indigo void floor.
  // Frame 1 squishes flatter and re-aims the eyes — a scanning, blinking pulse.
  voidling_0: [
    "................",
    "....O..OO.O.....",
    "...OKOOKKOKOO...",
    "..OKKxKKKKxKKO..",
    "..OKKKKxKKKKcO..",
    ".OKcKKxKxKKKKO..",
    ".OKKKKKxKKKKKO..",
    "..OKcKKKKKKKcO..",
    "..OKKKKKKKKKO...",
    "...OKKxKKxKKO...",
    "...OOKKKKKOO....",
    "..OO.OKKKO.OO...",
    "..O...OKO...O...",
    ".......O........",
    "................",
    "................",
  ],
  voidling_1: [
    "................",
    "................",
    "...O.OO..OO.O...",
    "..OKOKKOOKKOKO..",
    ".OKKKxKxKKxKKKO.",
    ".OKKKKxKxKKKcKO.",
    ".OKcKKKxKKKKKKO.",
    "..OKKKcKKKcKKO..",
    "..OKKKKKKKKKO...",
    "...OOKxKKxOO....",
    "..OO.OKKKO.OO...",
    "..O...OOO..OO...",
    "..O.........O...",
    "................",
    "................",
    "................",
  ],
  // STAR JELLY — a translucent space-drifter that phases through everything.
  // A rounded glassy bell with a bright top highlight and a glowing teal STAR
  // core at its heart (the name made literal), a frilly rim, and long wispy
  // tentacles fading cyan -> lavender -> purple. The tentacles sway and pulse
  // between frames.
  star_jelly_0: [
    "................",
    "................",
    "......OOOO......",
    ".....OxnnnO.....",
    "....OWncccxO....",
    "...OxccnccccO...",
    "...OcccWQcccO...",
    "...OcccQncccO...",
    "...OcOcccOccO...",
    "....c.c..c.c....",
    "....c.c..c.c....",
    "....m.m..m.m....",
    "....m.m..m.m....",
    "....M.M..M.M....",
    "................",
  ],
  star_jelly_1: [
    "................",
    "................",
    "......OOOO......",
    ".....OxnnnO.....",
    "....OWncccxO....",
    "...OxccnccccO...",
    "...OcccWQcccO...",
    "...OcccQncccO...",
    "...OcOcccOccO...",
    "....c.c..c.c....",
    "....c.c..c.c....",
    "....m.m..m.m....",
    "....M.M..M.M....",
    "................",
    "................",
    "................",
  ],
  // UNRAVELER — a person-shaped glitch in the local reality: a violet humanoid
  // ringed by chromatic aberration (cyan Q down the left edge, magenta X down
  // the right), a single datamosh slice sheared off it, and threads unravelling
  // from its feet. The tear TELEPORTS between frames — head-shear to torso-shear
  // — so it flickers and reads as hard to pin.
  unraveler_0: [
    "......OOOO......",
    ".....QmmmmX.....",
    "....Q.QmMMMMmX..",
    "....X.QmMMMMmX..",
    "....QmMMMMmX....",
    ".....QmmmmX.....",
    "....QmMMMMmX....",
    "...QmMMMMMMmX...",
    "..QmMMMMMMMMmX..",
    ".QQmMMMMMMMMmX..",
    "..QmMMMMMMMMmX..",
    "...QmMMMMMMmX...",
    "...QmmmOmmmX....",
    "...QmmX.QmmX....",
    "....XO...XO.....",
    "....Q...........",
  ],
  unraveler_1: [
    "......OOOO......",
    ".....QmmmmX.....",
    "....QmMMMMmX....",
    "....QmMMMMmX....",
    "....QmMMMMmX....",
    ".....QmmmmX.....",
    "....QmMMMMmX....",
    "...QmMMMMMMmX...",
    "QmMMMMMMMMmX....",
    "QmMMMMMMMMmX....",
    "..QmMMMMMMMMmX..",
    "...QmMMMMMMmX...",
    "...QmmmOmmmX....",
    "...QmmX.QmmX....",
    "....OX...OX.....",
    "..........Q.....",
  ],
  // GRAVITON — a fist-sized collapsed star that weighs a battleship: a dense
  // void-black heart ringed by a hot gold accretion disk (lit top-left),
  // dragging a purple gravity halo, with matter caught falling in on curved
  // arcs. Drawn on a 20×20 canvas so it looms heavy over the 16px fauna — the
  // tankiest minion on the field should read as the heaviest. Frames orbit
  // the infalling arcs a quarter turn and wander the singularity glint.
  graviton_0: [
    "....................",
    "....................",
    "...LL..MeMeMe.......",
    "...L.eMeMeMeMeM.....",
    "....eMeOOYYOOMeM....",
    "...eMOOYYYYYYOOeM...",
    "...MeOYooKKooyOMe...",
    "..MeOYoKKKKKKoyOMe..",
    "..eMOYoKKKKKKooOeM..",
    "..MeYYKKKWKKKKooMe..",
    "..eMYYKKKKYKKKooeM..",
    "..MeOYoKKKKKKooOMe..",
    "..eMOYoKKKKKKooOeM..",
    "...eMOyooKKoooOeM...",
    "...MeOOyoooooOOMe...",
    "....MeMOOooOOeMe....",
    ".....MeMeMeMeMe.L...",
    ".......eMeMeM..LL...",
    "....................",
    "....................",
  ],
  graviton_1: [
    "....................",
    "....................",
    ".......MeMeMe..LL...",
    ".....eMeMeMeMeM.L...",
    "....eMeOOYYOOMeM....",
    "...eMOOYYYYYYOOeM...",
    "...MeOYooKKooyOMe...",
    "..MeOYoKKKKKKoyOMe..",
    "..eMOYoKKKKKKooOeM..",
    "..MeYYKKKKWKKKooMe..",
    "..eMYYKKKYKKKKooeM..",
    "..MeOYoKKKKKKooOMe..",
    "..eMOYoKKKKKKooOeM..",
    "...eMOyooKKoooOeM...",
    "...MeOOyoooooOOMe...",
    "....MeMOOooOOeMe....",
    "...L.MeMeMeMeMe.....",
    "...LL..eMeMeM.......",
    "....................",
    "....................",
  ],
  // ---- History's missing (24×24 elites) --------------------------------------
  // NIKOLA TESLA — the sharp black suit, middle-parted hair and mustache, but
  // now wreathed in pure current: bold white/cyan lightning bolts crackle down
  // both flanks, his eyes glow charged, his hair stands on end. Frames re-jag
  // the bolts (a live flicker) and stride the legs.
  nikola_tesla_0: [
    ".........QOcOQO.........",
    ".......OckkkkkkcO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpQppppQpO.......",
    "..QW...OppkkkkppO..QW...",
    "..WQ....OppppppO.....WQ.",
    "..QW..ONNNWWWWNNNO.QW...",
    ".QWQ.ONNNNWTWNNNNNO..WQ.",
    ".cQWONNNNNNWWNNNNNNQW.c.",
    "..WQONNNNNNNNNNNNNNO.WQ.",
    "..QWONNNNNNNNNNNNNNQW...",
    "..WQONNNNNNNNNNNNNNO.WQ.",
    "..QW.ONNNNNNNNNNNNOQW...",
    "..WQ.ONNNNNNNNNNNO...WQ.",
    "......ONNNNOONNNNO......",
    "......ONNNO..ONNNO......",
    "......ONNNO..ONNNO......",
    "......ONNNO..ONNNO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  nikola_tesla_1: [
    ".........OcOQOc.........",
    ".......OOQkkkkcOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpQppppQpO.......",
    ".QW....OppkkkkppO...QW..",
    "...WQ...OppppppO....WQ..",
    ".QW...ONNNWWWWNNNO..QW..",
    "...WQONNNNWTWNNNNNO.WQ..",
    ".QW.ONNNNNNWWNNNNNNOQW..",
    ".c.WQNNNNNNNNNNNNNNOWQc.",
    ".QW.ONNNNNNNNNNNNNNOQWQ.",
    "...WQNNNNNNNNNNNNNNOWQ..",
    ".QW..ONNNNNNNNNNNNO.QW..",
    "...WQONNNNNNNNNNNO..WQ..",
    "......ONNNNOONNNNO......",
    ".....ONNNO....ONNNO.....",
    ".....ONNNO....ONNNO.....",
    ".....ONNNO....ONNNO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // AMELIA EARHART — the aviator's apparition, ninety years circling: a dark
  // leather flight cap with two brass-rimmed goggle lenses pushed up on the
  // brow (dark glass, a hard glint), a pale sheepskin fleece collar, a bomber
  // jacket with a gold zipper, gloved hands, and a white silk scarf streaming
  // off the right shoulder. The scarf sways and the feet spread into a hover
  // between frames.
  amelia_earhart_0: [
    "........................",
    "........OOOOOOO.........",
    ".......OEEEEEEEO........",
    "......OEEEEEEEEEO.......",
    "......OEyTyEyTyEO.......",
    "......OEybyEybyEO.......",
    "......OEpppppppEO.......",
    ".......OEpppppEO........",
    "........OpSSpO..........",
    ".....TwwOppppOwwT.......",
    "....OTwwBBBBBBwwTOW.....",
    "....OBBBEyBBBEBBBOWWW...",
    "....OBEBBByqBBBEBO.WWW..",
    ".....OpOBByqBBOpO.......",
    ".....OBEBBBBBBEBO.......",
    ".....OBBBBBBBBBBO.......",
    "......OBBBBBBBBO........",
    ".......ObbO..ObbO.......",
    ".......ObbO..ObbO.......",
    ".......ObbO..ObbO.......",
    ".......OkkO..OkkO.......",
    ".......OOOO..OOOO.......",
    "........................",
    "........................",
  ],
  amelia_earhart_1: [
    "........................",
    "........OOOOOOO.........",
    ".......OEEEEEEEO........",
    "......OEEEEEEEEEO.......",
    "......OEyTyEyTyEO.......",
    "......OEybyEybyEO.......",
    "......OEpppppppEO.......",
    ".......OEpppppEO........",
    "........OpSSpO..........",
    ".....TwwOppppOwwT.......",
    "....OTwwBBBBBBwwTOWW....",
    "....OBBBEyBBBEBBBOWWWW..",
    "....OBEBBByqBBBEBO.W....",
    ".....OpOBByqBBOpO.......",
    ".....OBEBBBBBBEBO.......",
    ".....OBBBBBBBBBBO.......",
    "......OBBBBBBBBO........",
    ".......ObbO..ObbO.......",
    ".......ObbO..ObbO.......",
    "......ObbO....ObbO......",
    "......OkkO....OkkO......",
    "......OOOO....OOOO......",
    "........................",
    "........................",
  ],
  // GRIGORI RASPUTIN — the unkillable mad monk, doorman of the tribute road.
  // The tankiest elite, so he reads HEAVY and menacing: a deep charcoal hood
  // (near-black, not the old void-blue that camouflaged) over a gaunt pale
  // face with burning wrong-glowing eyes, a huge grey beard spilling past his
  // chest, a big gold three-bar Orthodox cross, and a broad cassock flaring to
  // a ragged floor-length hem. The hem sways between frames.
  grigori_rasputin_0: [
    "........................",
    ".......OOOOOOOOOO.......",
    "......OkkkkkkkkkkO......",
    "......OkOSSSSSSOkO......",
    "......OkORSSRO..kO......",
    "......OkOSSSSSO.kO......",
    ".......OOSSSSO.O........",
    "......OvOfffffOvO.......",
    ".....OvkffAAAAfkvO......",
    "....OvkkfAAAAAAfkvO.....",
    "....OkvkkfAAAAfkkvO.....",
    "....OkkkkfAffAfkkkkO....",
    "....OvkkkkfAAfkkkkvO....",
    "....OkkkkkkyfkkkkkkO....",
    "....OvkkkyyyyykkkkvO....",
    "....OkkkkkkykkkkkkkO....",
    "....OvkkyyyyyyykkkvO....",
    "....OkkkkkkhkkkkkkkO....",
    "...OkkkkkkkykkkkkkkkO...",
    "...OkkkkkhyyyhkkkkkkO...",
    "...OOkkkkkkkkkkkkkkOO...",
    "....OO.OO.OO.OO.OO.O....",
    "........................",
    "........................",
  ],
  grigori_rasputin_1: [
    "........................",
    ".......OOOOOOOOOO.......",
    "......OkkkkkkkkkkO......",
    "......OkOSSSSSSOkO......",
    "......OkORSSRO..kO......",
    "......OkOSSSSSO.kO......",
    ".......OOSSSSO.O........",
    "......OvOfffffOvO.......",
    ".....OvkffAAAAfkvO......",
    "....OvkkfAAAAAAfkvO.....",
    "....OkvkkfAAAAfkkvO.....",
    "....OkkkkfAffAfkkkkO....",
    "....OvkkkkfAAfkkkkvO....",
    "....OkkkkkkyfkkkkkkO....",
    "....OvkkkyyyyykkkkvO....",
    "....OkkkkkkykkkkkkkO....",
    "....OvkkyyyyyyykkkvO....",
    "....OkkkkkkhkkkkkkkO....",
    "...OkkkkkkkykkkkkkkkO...",
    "...OkkkkkhyyyhkkkkkkO...",
    "...OOkkkkkkkkkkkkkkOO...",
    "....O.OO.OO.OO.OO.OO....",
    "........................",
    "........................",
  ],
  // LUCKY — folklore's missing: the little man with the pot of gold. Green
  // top hat with a gold band buckle, ginger beard past his chest, emerald
  // coat, gold belt buckle. Deliberately small for an elite — a head and a
  // half shorter than history's missing, same foot anchor. Frame 1 spreads
  // the jig.
  lucky_0: [
    "........................",
    "........................",
    "........................",
    ".........OOOOOO.........",
    ".........OGGGGO.........",
    ".........OGGGGO.........",
    ".........OgyyGO.........",
    ".......OGGGGGGGGO.......",
    "........OppppppO........",
    "........OpOppOpO........",
    ".......OttppppttO.......",
    ".......OttttttttO.......",
    "......OGGttttttGGO......",
    "......OGGGttttGGGO......",
    "......OGpOGttGOpGO......",
    "......OGGGGyyGGGGO......",
    ".......OGGGGGGGGO.......",
    ".......OggO..OggO.......",
    ".......OggO..OggO.......",
    ".......OOOO..OOOO.......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  lucky_1: [
    "........................",
    "........................",
    "........................",
    ".........OOOOOO.........",
    ".........OGGGGO.........",
    ".........OGGGGO.........",
    ".........OgyyGO.........",
    ".......OGGGGGGGGO.......",
    "........OppppppO........",
    "........OpOppOpO........",
    ".......OttppppttO.......",
    ".......OttttttttO.......",
    "......OGGttttttGGO......",
    "......OGGGttttGGGO......",
    "......OGpOGttGOpGO......",
    "......OGGGGyyGGGGO......",
    ".......OGGGGGGGGO.......",
    "......OggO....OggO......",
    "......OggO....OggO......",
    "......OOOO....OOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // HARRY HOUDINI — the apparition of the escape artist: a spectral showman in
  // a top hat, a chain draped across the chest with a gold padlock hanging at
  // the sternum — none of it holding him. He trails off into wisps instead of
  // standing. Frame 1 re-wisps the dissolve for a floating shimmer.
  harry_houdini_0: [
    ".......OkkkkkkkkO.......",
    ".......OkkkkkkkkO.......",
    ".....OkkkkkkkkkkkkO.....",
    "........OccccccO........",
    ".......OccccccccO.......",
    ".......OcckcckccO.......",
    ".......OccccccccO.......",
    "........OcCCCCcO........",
    ".....OOOccccccccOOO.....",
    "....OVwccccccccccVwO....",
    "...OccwVcccoocccwVccO...",
    "...OcccVwcoccocVwcccO...",
    "...OccccwVyyyywVccccO...",
    "...OcccccVykkywcccccO...",
    "....OcccccoooocccccO....",
    "....OccccccVwccccccO....",
    ".....OcccOOOOcccccO.....",
    ".....OccO....OOccO......",
    "......OcO......OcO......",
    ".......OO.......OO......",
    "........O........O......",
    "........................",
    "........................",
    "........................",
  ],
  harry_houdini_1: [
    ".......OkkkkkkkkO.......",
    ".......OkkkkkkkkO.......",
    ".....OkkkkkkkkkkkkO.....",
    "........OccccccO........",
    ".......OccccccccO.......",
    ".......OcckcckccO.......",
    ".......OccccccccO.......",
    "........OcCCCCcO........",
    ".....OOOccccccccOOO.....",
    "....OVwccccccccccVwO....",
    "...OccwVcccoocccwVccO...",
    "...OcccVwcoccocVwcccO...",
    "...OccccwVyyyywVccccO...",
    "...OcccccVykkywcccccO...",
    "....OcccccoooocccccO....",
    "....OccccccVwccccccO....",
    ".....OcccccOOOOcccO.....",
    "......OccOO....OccO.....",
    "......OcO......OcO......",
    ".......OO......OO.......",
    "........O......O........",
    "........................",
    "........................",
    "........................",
  ],
  // THE KING — the apparition in the white jumpsuit: black pompadour and
  // sideburns, gold shades, rhinestone trim, flared legs. Uh-huh.
  the_king_0: [
    "........................",
    "........OOOOOOO.........",
    "......OOKKKKKKKOO.......",
    "......OKKKKKKKKKO.......",
    ".......OKppppppKO.......",
    ".......OpyOppOypO.......",
    "......OKKppppppKKO......",
    "........OppppppO........",
    "......OWWWWyyWWWWO......",
    ".....OWWWWWyyWWWWWO.....",
    "....OWwWWWWyyWWWwWWO....",
    "....OWWWWWWyyWWWWWWO....",
    "....OWpOWWWyyWWOpWO.....",
    ".....OWwWWWWWWWwWO......",
    ".....OWWWWWWWWWWWO......",
    "......OWWWWOOWWWWO......",
    "......OWWWO..OWWWO......",
    "......OWWWO..OWWWO......",
    ".....OWWWWO..OWWWWO.....",
    ".....OOOOOO..OOOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  the_king_1: [
    "........................",
    "........OOOOOOO.........",
    "......OOKKKKKKKOO.......",
    "......OKKKKKKKKKO.......",
    ".......OKppppppKO.......",
    ".......OpyOppOypO.......",
    "......OKKppppppKKO......",
    "........OppppppO........",
    "......OWWWWyyWWWWO......",
    ".....OWWWWWyyWWWWWO.....",
    "....OWwWWWWyyWWWwWWO....",
    "....OWWWWWWyyWWWWWWO....",
    "....OWpOWWWyyWWOpWO.....",
    ".....OWwWWWWWWWwWO......",
    ".....OWWWWWWWWWWWO......",
    "......OWWWWOOWWWWO......",
    ".....OWWWO....OWWWO.....",
    ".....OWWWO....OWWWO.....",
    "....OWWWWO....OWWWWO....",
    "....OOOOOO....OOOOOO....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // ---- GROK OMEGA (48×48 boss) ------------------------------------------------
  // ZAI's latest superintelligence, manifested as a hovering steel monolith
  // with one enormous eye, a crown of drifting crystals, circuit traces for
  // veins, and glitch slabs tearing off its edges. No legs — it floats on a
  // shimmer of anti-grav purple. Frames bob the crown, wander the pupil,
  // and relocate the glitch.
  grok_omega_0: [
    "............PP.........PP........PP.............",
    "............LP.........LP........LP.............",
    "................................................",
    "......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO......",
    "......OVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvQQQQQQQQQQQQQQQQQQQQQQQQQQQQvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvOOOOOOOOOOOOOOOOOOOOOOOOOOOOOObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKxxxxxxxxKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKxxxxxxxxxxxxxxKKKKKKKObbO......",
    "......OVvOKKKKKxxxxxxxxxxxxxxxxxxKKKKKObbO......",
    "......OVvOKKKKxxxxxxxxQQQQxxxxxxxxKKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbO......",
    "......OVvOKKxxxxxxxQQQQKKQQQQxxxxxxxKKObbO......",
    "......OVvOKKKxxxxxxxQQQKKQQQxxxxxxxKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbO......",
    "......OVvOKKKKxxxxxxxxQQQQxxxxxxxxKKKKObbO......",
    "......OVvOKKKKKxxxxxxxxxxxxxxxxxxKKKKKObbO......",
    "......OVvOKKKKKKKxxxxxxxxxxxxxxKKKKKKKObbO......",
    "....XXOVvOKKKKKKKKKKxxxxxxxxKKKKKKKKKKObbO......",
    "....XXOVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOOOOOOOOOOOOOOOOOOOOOOOOOOOOOObbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvQQQQQQQQQQQvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvQvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvQQQQQQQQQQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvQQQQQQQQQQQQvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbO......",
    "......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO......",
    "................................................",
    "..............PP.......PP.......PP..............",
    "..............P........P........P...............",
    "................................................",
    "................................................",
    "................................................",
    "................................................",
  ],
  grok_omega_1: [
    "................................................",
    "............PP.........PP........PP.............",
    "............LP.........LP........LP.............",
    "......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO......",
    "......OVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvQQQQQQQQQQQQQQQQQQQQQQQQQQQQvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvOOOOOOOOOOOOOOOOOOOOOOOOOOOOOObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKxxxxxxxxKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKxxxxxxxxxxxxxxKKKKKKKObbO......",
    "......OVvOKKKKKxxxxxxxxxxxxxxxxxxKKKKKObbO......",
    "......OVvOKKKKxxxxxxxxQQQQxxxxxxxxKKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbOXX....",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbOXX....",
    "......OVvOKKxxxxxxxQQQQQQKKQQxxxxxxxKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQKKQxxxxxxxKKKObbO......",
    "......OVvOKKKxxxxxxxQQQQQQQQxxxxxxxKKKObbO......",
    "......OVvOKKKKxxxxxxxxQQQQxxxxxxxxKKKKObbO......",
    "......OVvOKKKKKxxxxxxxxxxxxxxxxxxKKKKKObbO......",
    "......OVvOKKKKKKKxxxxxxxxxxxxxxKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKxxxxxxxxKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOKKKKKKKKKKKKKKKKKKKKKKKKKKKKObbO......",
    "......OVvOOOOOOOOOOOOOOOOOOOOOOOOOOOOOObbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvQQQQQQQQQQQvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvQvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvQQQQQQQQQQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvQvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvQQQQQQQQQQQQvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbbO......",
    "......OVbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbO......",
    "......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO......",
    "................................................",
    "................................................",
    "..............PP.......PP.......PP..............",
    "..............P........P........P...............",
    "................................................",
    "................................................",
    "................................................",
  ],
  // ---- Hazards ----------------------------------------------------------------
  // BLACK HOLE — the well's core visual: an absolute-black heart, a hot
  // gold inner ring, and purple accretion arms. Frames rotate the arms.
  blackhole_0: [
    "................................",
    "................................",
    "..............LL................",
    ".............LPP................",
    "............LP..................",
    "...........LP.......PP..........",
    "..........LP.......PLLP.........",
    "................................",
    "..........MPPP..................",
    ".........MP..yyyyyy.............",
    ".........MP.yyKKKKyy............",
    "........MP.yKKKKKKKKy...........",
    "........MP.yKKKKKKKKy...........",
    "........MP.yKKKKKKKKy...........",
    "...PP......yKKKKKKKKy...........",
    "..PLLP.....yKKKKKKKKy...........",
    "...PP.......yyKKKKyy.PM.........",
    "..............yyyyyy..PM........",
    "..................PP..PM........",
    "..................PPPM..........",
    "................................",
    ".........PLP....................",
    "..........PL....................",
    "...........PL...................",
    "............PL..................",
    ".............PLL................",
    "..............PP................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  blackhole_1: [
    "................................",
    "................................",
    "................................",
    "................PP..............",
    "...............PLLP.............",
    "................PP..............",
    "......PP........................",
    ".......PLL......................",
    ".........PL.....................",
    "..........PPyyyyyy..............",
    "............yyKKKKyy............",
    "...........yKKKKKKKKy...........",
    "...........yKKKKKKKKy...........",
    "...........yKKKKKKKKy...........",
    "...........yKKKKKKKKy...........",
    "...........yKKKKKKKKy...........",
    "............yyKKKKyy............",
    "..............yyyyyyPP..........",
    "....................PLL.........",
    "......................PL........",
    ".......................PM.......",
    "........................PM......",
    "................................",
    "......MP........................",
    ".....MP.........................",
    "....MP..........PP..............",
    "...............PLLP.............",
    "................PP..............",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  // ASTEROID — a tumbling rock: moon-gray hide, cratered. Frames rotate
  // the crater pattern a quarter turn.
  asteroid_0: [
    "................",
    ".....OOOOO......",
    "...OOfFFffOO....",
    "..OfFFFFfffbO...",
    "..OFFfffffbbO...",
    ".OfFfffEEffbbO..",
    ".OFffffEEfffbO..",
    ".OFfffffffffbO..",
    ".OffEEffffbbbO..",
    ".OffEEfffbbbbO..",
    "..OfffffbbbbO...",
    "..OffbbbbbbO....",
    "...OObbbbOO.....",
    ".....OOOO.......",
    "................",
    "................",
  ],
  asteroid_1: [
    "................",
    ".....OOOOO......",
    "...OOfFFffOO....",
    "..OfFFFFfffbO...",
    "..OFFffEEffbO...",
    ".OfFfffEEffbbO..",
    ".OFffffffffbbO..",
    ".OFffffffEEfbO..",
    ".OfffffffEEbbO..",
    ".OfffffffbbbbO..",
    "..OfffffbbbbO...",
    "..OffbbbbbbO....",
    "...OObbbbOO.....",
    ".....OOOO.......",
    "................",
    "................",
  ],
  // ---- Obstacles & decor ------------------------------------------------------
  // RIFT SHARD — a crystallized moment: solid amethyst spears. Blocks
  // sight, shots and feet.
  rift_shard: [
    "................",
    "......OO........",
    ".....OLPO..OO...",
    ".....OLPO.OLPO..",
    "....OLPPPOOLPO..",
    "....OLPPPOLPPO..",
    "...OLPPMPPPPMO..",
    "...OLPPMPPPPMO..",
    "...OLPPPMPPMMO..",
    "..OLPPPPMPPMMO..",
    "..OLPPPPPMPMMO..",
    "..OLPPMPPPPMMO..",
    "..OPPPMMPPMMMO..",
    "...OOOOOOOOOO...",
    "................",
    "................",
  ],
  // SPACE JUNK — a drifting pile of somebody's cargo: hoppable cover.
  space_junk: [
    "................",
    "................",
    "....OOOOOO......",
    "...OVvvvvbO.....",
    "...OvvoovbO.....",
    "..OOOOOOOOOOO...",
    "..OVVvvvvvvbO...",
    "..OvvvqqvvvbO...",
    "..OvvvqqvvbbO...",
    "..OvvvvvvbbbO...",
    "..OOOOOOOOOOO...",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  // STARDUST — a loose sparkle of ground-up somewhere else (no collision).
  stardust: [
    "................",
    "................",
    "....xx..........",
    "....xx..........",
    "................",
    "..........uu....",
    "..........uu....",
    "................",
    "................",
    "......xx........",
    "......xx........",
    "................",
    "............uu..",
    "............uu..",
    "................",
    "................",
  ],
  // FLOATING ROCK — a chunk of ground that forgot which way is down,
  // hovering on a shimmer of anti-grav purple.
  floating_rock: [
    "................",
    "................",
    "....OOOOOO......",
    "...OfFFfffO.....",
    "..OfFFffffbO....",
    "..OffffffbbO....",
    "...OffffbbO.....",
    "....OOOOOO......",
    "................",
    ".....PP.PP......",
    "......P.P.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  // LOST TV — somebody's television, still tuned to WEBFLIX static.
  lost_tv: [
    "................",
    "....vv.....vv...",
    ".....vv...vv....",
    "......v...v.....",
    "....OOOOOOOOO...",
    "...ONNNNNNNNNO..",
    "...ONOOOOOOONO..",
    "...ONOxxQxxONO..",
    "...ONOxQxxxONO..",
    "...ONOxxxQxONO..",
    "...ONOOOOOOONO..",
    "...ONNNNNNNNNO..",
    "...OOOOOOOOOOO..",
    "....ON.....NO...",
    "................",
    "................",
  ],
  // ---- Ground tiles (16×16) ---------------------------------------------------
  // The void floor: near-black indigo with dim star specks. Edges stay
  // featureless so the nothing tiles without seams; void_1 carries one
  // brighter star.
  void_0: [
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzuzzzzzzzzzzzzz",
    "zzzzzzzzzzZZzzzz",
    "zzzzzzzzzzZZzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzuzz",
    "zzzZZzzzzzzzzzzz",
    "zzzZZzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzuzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzZZzz",
    "zuzzzzzzzzzzZZzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
  ],
  void_1: [
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzuzzzzz",
    "zzZZzzzzzzzzzzzz",
    "zzZZzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzxxzzzzzzzz",
    "zzzzzxxxxzzzzzzz",
    "zzzzzxxxxzzzzzzz",
    "zzzzzzxxzzzzzzzz",
    "zzzzzzzzzzzzZZzz",
    "zzuzzzzzzzzzZZzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzuzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
  ],
  // Nebula patches: violet wisps pooling in the dark.
  nebula_0: [
    "zzzzzzzzzzzzzzzz",
    "zzzzeezzzzzzzzzz",
    "zzzeddeezzzzzzzz",
    "zzeddddeezzzzzzz",
    "zzzeddeezzzuzzzz",
    "zzzzeezzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzeeezzzzz",
    "zzzzzzzeddeezzzz",
    "zzzzzzzeddeezzzz",
    "zzzzzzzzeeezzzzz",
    "zzuzzzzzzzzzzzzz",
    "zzzzzzzzzzzzeezz",
    "zzzzzzzzzzzeddez",
    "zzzzzzzzzzzzeezz",
    "zzzzzzzzzzzzzzzz",
  ],
  nebula_1: [
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzzzzeezzzz",
    "zzzzzzzzzeddeezz",
    "zzzzzzzzeddddeez",
    "zzzzzzzzzeddeezz",
    "zzzzzzzzzzeezzzz",
    "zzuzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzeeezzzzzzzzzzz",
    "zeddeezzzzzzzzzz",
    "zeddeezzzzuzzzzz",
    "zzeeezzzzzzzzzzz",
    "zzzzzzzzzzzzzzzz",
    "zzzzzzzeezzzzzzz",
    "zzzzzzeddezzzzzz",
    "zzzzzzzeezzzzzzz",
  ],
  // ---- Projectiles ------------------------------------------------------------
  // The SINGULARITY CANNON's shot: a very small, very rude black hole.
  singularity: [
    "........",
    "..PPP...",
    ".PKKKL..",
    ".PKKKKL.",
    ".PKKKKL.",
    "..LKKL..",
    "...LLL..",
    "........",
  ],
  // ---- Icons (12×12) ----------------------------------------------------------
  // TESLA COIL — the tower, the torus, the spark.
  icon_tesla_coil: [
    "............",
    ".....yy.....",
    "....yYYy....",
    "....yYYy....",
    ".....yy.....",
    "....OvvO....",
    "....OvvO....",
    "...OvvvvO...",
    "....OvvO....",
    "...OkkkkO...",
    "..OkkkkkkO..",
    "............",
  ],
  // SINGULARITY CANNON — a fat barrel wrapped around a black core.
  icon_singularity_cannon: [
    "............",
    "............",
    "...OOOOOO...",
    "..OvVVVvvO..",
    ".OvPPPPvvbO.",
    ".OvPKKPvvbO.",
    ".OvPKKPvvbO.",
    ".OvPPPPvvbO.",
    "..OvvvvbbO..",
    "...OOOOOO...",
    "......ObO...",
    "............",
  ],
  // AVIATOR GOGGLES — two gold lenses on a leather strap.
  icon_goggles: [
    "............",
    "............",
    "............",
    ".OBBBBBBBBO.",
    "OBOOOBBOOOBO",
    "OByyOBBOyyBO",
    "OByyOBBOyyBO",
    "OBOOOBBOOOBO",
    ".OBBBBBBBBO.",
    "............",
    "............",
    "............",
  ],
  // RASPUTIN'S BEARD — the beard. It survived everything.
  icon_beard: [
    "............",
    "...OO..OO...",
    "..OkkOOkkO..",
    "..OkkkkkkO..",
    "..OkkkkkkO..",
    "..OkkkkkkO..",
    "...OkkkkO...",
    "...OkkkkO...",
    "....OkkO....",
    "....OkkO....",
    ".....OO.....",
    "............",
  ],
  // GOLDEN PARACHUTE — deploys automatically upon career failure.
  icon_parachute: [
    "............",
    "....yyyy....",
    "..yyYYYYyy..",
    ".OyYYYYYYyO.",
    ".OyOyOyOyO..",
    "..O.O.O.O...",
    "..O..O..O...",
    "...OOOOO....",
    "....OOO.....",
    "....OWO.....",
    ".....O......",
    "............",
  ],
  // WARDENCLYFFE NOTES — free energy, underlined twice.
  icon_notes: [
    "............",
    "..OOOOOOOO..",
    ".OWWWWWWWWO.",
    ".OWkkkkkWWO.",
    ".OWWWWWWWWO.",
    ".OWkkkkkkWO.",
    ".OWWWyyWWWO.",
    ".OWWyyWWWWO.",
    ".OWyyyyWWWO.",
    ".OWWWWWWWWO.",
    "..OOOOOOOO..",
    "............",
  ],
  // ZAI PROBE — burnt, still logging, still telling exactly one recipient.
  icon_probe: [
    "............",
    ".....yy.....",
    "....Oyy.....",
    "....OvvO....",
    "...OvVVvO...",
    "..OvVvvvvO..",
    "..OvvXXvvO..",
    "..OvvXXvvO..",
    "...OvvvbO...",
    "....OObO....",
    "...ObO.ObO..",
    "............",
  ],
};

// ---- RARE & UNIQUE mobs (palette variants — the Diablo recolor idiom) ------
// The special fauna wears the void's own body plans in colors the rift never
// spawns, so a find reads at a glance (the engine adds the aura + name).
for (const frame of [0, 1]) {
  // STRAY COMET — a voidling inverted into pale ice, sparkles burnt white.
  SPRITES[`stray_comet_${frame}`] = swapPalette(SPRITES[`voidling_${frame}`], {
    K: "c",
    x: "W",
    c: "W",
  });
  // COLLAPSED STAR — a star jelly fallen all the way in: violet flesh around
  // an absolute-black heart, glinting glitch magenta.
  SPRITES[`collapsed_star_${frame}`] = swapPalette(
    SPRITES[`star_jelly_${frame}`],
    { c: "P", n: "K", W: "L", x: "L", Q: "X" },
  );
  // THE LAST PHOTON — a scrap of pure light where a voidling would be dark,
  // sparkling visor-gold.
  SPRITES[`the_last_photon_${frame}`] = swapPalette(
    SPRITES[`voidling_${frame}`],
    { K: "W", x: "y", c: "y" },
  );
}

export default {
  name: "rift",
  /** Ground tile behind this family's contact sheet. */
  ground: "void_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {
    voidling_squish: { frames: ["voidling_0", "voidling_1"], delayMs: 320 },
    star_jelly_drift: {
      frames: ["star_jelly_0", "star_jelly_1"],
      delayMs: 360,
    },
    stray_comet_squish: {
      frames: ["stray_comet_0", "stray_comet_1"],
      delayMs: 280,
    },
    collapsed_star_drift: {
      frames: ["collapsed_star_0", "collapsed_star_1"],
      delayMs: 400,
    },
    the_last_photon_squish: {
      frames: ["the_last_photon_0", "the_last_photon_1"],
      delayMs: 180,
    },
    unraveler_glitch: { frames: ["unraveler_0", "unraveler_1"], delayMs: 200 },
    graviton_orbit: { frames: ["graviton_0", "graviton_1"], delayMs: 260 },
    lucky_jig: { frames: ["lucky_0", "lucky_1"], delayMs: 280 },
    grok_omega_hum: { frames: ["grok_omega_0", "grok_omega_1"], delayMs: 380 },
    blackhole_spin: { frames: ["blackhole_0", "blackhole_1"], delayMs: 240 },
    asteroid_tumble: { frames: ["asteroid_0", "asteroid_1"], delayMs: 220 },
  },
  /**
   * Wound-overlay overrides where the defaults vanish on the local body
   * colors: the STAR JELLY is itself ecto-pale (cyan splats disappear), so
   * it bruises in slime purple instead.
   */
  wounds: {
    star_jelly: { splat: "P", core: "M" },
    // The comet and the photon are ecto-pale like the jelly — cyan splats
    // vanish, so they bruise in slime purple too.
    stray_comet: { splat: "P", core: "M" },
    the_last_photon: { splat: "P", core: "M" },
    // The collapsed star is itself violet-black — it cracks in the glitch
    // magenta the graviton uses.
    collapsed_star: { splat: "X", core: "Q" },
    // The graviton is a gold ring around a black heart — spark-gold wounds
    // vanish on it, so it cracks in glitch magenta instead.
    graviton: { splat: "X", core: "P" },
  },
  /** Ground tiles and flat sparkle decor the contrast lint skips. */
  contrastExempt: ["void_0", "void_1", "nebula_0", "nebula_1", "stardust"],
};
