// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The SpaceZ HQ family (see the `pixel-assets` skill): the night shift,
// MUSKRAT, and the lab floors, walls and furniture of level 1. One string
// per pixel row, one character per pixel; `.` is transparent and every
// other char must exist in CORE_PALETTE (sprite-data/core.mjs) or this
// family's local palette.

import { swapPalette } from "../asset-tools/palette.mjs";
import { LAB } from "./core.mjs";
import { BLOOD_0, BLOOD_1 } from "./effects.mjs";

/** Chars only this family draws with — merged with the core at build time. */
const PALETTE = {
  t: LAB.base,
  s: LAB.dark,
};

const SPRITES = {
  // ---- SpaceZ HQ (level 1) --------------------------------------------------
  // The night shift. All five staff share one 12px-wide figure (head rows
  // 1-4, torso 5-9, legs 10-12) so the crowd reads as coworkers; frames
  // alternate the leg stride exactly like the player's.
  // INTERN — gray hoodie, jeans, perpetually underslept.
  intern_0: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OvVvvvvvvO...",
    "..OvvVvvvvvvvO..",
    "..OvvVvvvvVvvO..",
    "..OpOvvvvvvOpO..",
    "...OvvvvvvvvO...",
    "...OjjO..OjjO...",
    "...OjjO..OjjO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  intern_1: [
    "................",
    ".....OOOOO......",
    "....OkkkkkkO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OvVvvvvvvO...",
    "..OvvVvvvvvvvO..",
    "..OvvVvvvvVvvO..",
    "..OpOvvvvvvOpO..",
    "...OvvvvvvvvO...",
    "..OjjO....OjjO..",
    "..OjjO....OjjO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // LAB SCIENTIST — white coat, gray hair, glasses.
  scientist_0: [
    "................",
    ".....OOOOO......",
    "....OWWWWWWO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OWWWjjWWWO...",
    "..OWWWWjjWWWWO..",
    "..OWWwWWWWwWWO..",
    "..OpOWWWWWWOpO..",
    "...OWwWWWWwWO...",
    "...ObbO..ObbO...",
    "...ObbO..ObbO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  scientist_1: [
    "................",
    ".....OOOOO......",
    "....OWWWWWWO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OWWWjjWWWO...",
    "..OWWWWjjWWWWO..",
    "..OWWwWWWWwWWO..",
    "..OpOWWWWWWOpO..",
    "...OWwWWWWwWO...",
    "..ObbO....ObbO..",
    "..ObbO....ObbO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // PROPULSION ENGINEER — gold hard hat, hi-vis vest over gray overalls.
  engineer_0: [
    "................",
    ".....OOOOO......",
    "....OyYyyyyO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OovvvvvvoO...",
    "..OoovvvvvvooO..",
    "..OoovqqqvvooO..",
    "..OpOvvvvvvOpO..",
    "...OvvvqqvvvO...",
    "...ObbO..ObbO...",
    "...ObbO..ObbO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  engineer_1: [
    "................",
    ".....OOOOO......",
    "....OyYyyyyO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OovvvvvvoO...",
    "..OoovvvvvvooO..",
    "..OoovqqqvvooO..",
    "..OpOvvvvvvOpO..",
    "...OvvvqqvvvO...",
    "..ObbO....ObbO..",
    "..ObbO....ObbO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // SECURITY GUARD — navy uniform, cap, gold badge. The fast one.
  guard_0: [
    "................",
    ".....OOOOO......",
    "....OJJJJJJO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OJJjjjjJJO...",
    "..OJJJjjjjJJJO..",
    "..OJJjjyjjjJJO..",
    "..OpOjjjjjjOpO..",
    "...OJJjjjjJJO...",
    "...OJJO..OJJO...",
    "...OJJO..OJJO...",
    "...OOOO..OOOO...",
    "................",
    "................",
    "................",
  ],
  guard_1: [
    "................",
    ".....OOOOO......",
    "....OJJJJJJO....",
    "....OpOppOpO....",
    "....OppppppO....",
    "...OJJjjjjJJO...",
    "..OJJJjjjjJJJO..",
    "..OJJjjyjjjJJO..",
    "..OpOjjjjjjOpO..",
    "...OJJjjjjJJO...",
    "..OJJO....OJJO..",
    "..OJJO....OJJO..",
    "..OOOO....OOOO..",
    "................",
    "................",
    "................",
  ],
  // HAZMAT TECH — the deep-lab tank in a sealed yellow suit. Drawn bulkier on
  // an 18px canvas so it looms over the 16px office staff it wades through: a
  // hooded helmet with a wide cyan visor, gloved arms set off from the torso by
  // outline seams, a respirator (b) under the visor, a chest gauge (W/x), a
  // hazard band (O dashes) across the belt, and heavy boots. Frames stride.
  hazmat_0: [
    "..................",
    ".....OOOOOO.......",
    "....OhhhhhhO......",
    "....OxccccxO......",
    "....OxccccxO......",
    "....OhhbbhhO......",
    "..OhhhhhhhhhhO....",
    ".OhOhhhhhhhhOhO...",
    ".OhOhhhWxhhhOhO...",
    ".OhOhhhhhhhhOhO...",
    ".OHOhOhOhOhOOHO...",
    "..OhhhhhhhhhhO....",
    "..OhhhhhhhhhhO....",
    "...OhhhOOhhhO.....",
    "...OHHO..OHHO.....",
    "...OOOO..OOOO.....",
    "..................",
    "..................",
  ],
  hazmat_1: [
    "..................",
    ".....OOOOOO.......",
    "....OhhhhhhO......",
    "....OxccccxO......",
    "....OxccccxO......",
    "....OhhbbhhO......",
    "..OhhhhhhhhhhO....",
    ".OhOhhhhhhhhOhO...",
    ".OhOhhhWxhhhOhO...",
    ".OhOhhhhhhhhOhO...",
    ".OHOhOhOhOhOOHO...",
    "..OhhhhhhhhhhO....",
    "..OhhhhhhhhhhO....",
    "...OhhhOOhhhO.....",
    "..OHHO....OHHO....",
    "..OOOO....OOOO....",
    "..................",
    "..................",
  ],
  // OPTIMUSK — SpaceZ's humanoid robot, the toughest thing on the floor short
  // of the elites. Drawn on a bigger 20×20 canvas than the 16px staff (the
  // renderer sizes every mob to its own grid, so size IS the hierarchy tell):
  // it looms a head over the crowd it marches with, wrecking-ball shoulders of
  // white armor panels (W) over steel joints (v/V/b), a wide black visor with a
  // cyan optic slit (x/c), and a round glowing reactor core (c/x) in the chest
  // — reads as a heavy machine, not a coworker. Frames alternate the leg
  // stride like the crowd; the wound generator sparks it in gold (gore).
  optimusk_0: [
    "....................",
    "....................",
    "......OOOOOOOO......",
    "......OWWWWWWO......",
    "......OWWWWWWO......",
    "......OxccccxO......",
    "......OWWWWWWO......",
    "...OvvWWWWWWWWvvO...",
    "..OvvWWWWWWWWWWvvO..",
    "..OvWWWWccccWWWWvO..",
    "..OvWWWccxxccWWWvO..",
    "..OvWWWccxxccWWWvO..",
    "..OvWWWWccccWWWWvO..",
    "...OvWWWWWWWWWWvO...",
    "...OvvWWWWWWWWvvO...",
    "....OvvvO..OvvvO....",
    "....OvvvO..OvvvO....",
    "....ObbbO..ObbbO....",
    "....OOOOO..OOOOO....",
    "....................",
  ],
  optimusk_1: [
    "....................",
    "....................",
    "......OOOOOOOO......",
    "......OWWWWWWO......",
    "......OWWWWWWO......",
    "......OxccccxO......",
    "......OWWWWWWO......",
    "...OvvWWWWWWWWvvO...",
    "..OvvWWWWWWWWWWvvO..",
    "..OvWWWWccccWWWWvO..",
    "..OvWWWccxxccWWWvO..",
    "..OvWWWccxxccWWWvO..",
    "..OvWWWWccccWWWWvO..",
    "...OvWWWWWWWWWWvO...",
    "...OvvWWWWWWWWvvO...",
    "...OvvvO....OvvvO...",
    "...OvvvO....OvvvO...",
    "...ObbbO....ObbbO...",
    "...OOOOO....OOOOO...",
    "....................",
  ],
  // SPARKS — the machine-tier hit splash (OPTIMUSK bleeds electricity, not
  // blood): the blood droplets recolored to hot gold, base frames shared with
  // the other gore in sprite-data/effects.mjs.
  sparks_0: swapPalette(BLOOD_0, { r: "y" }),
  sparks_1: swapPalette(BLOOD_1, { r: "Y" }),
  // ---- SpaceZ HQ floor tiles (16×16) ----------------------------------------
  // Polished lab tiles with a seam along the top/left edge — every tile
  // carries the same seam, so the grid pattern is continuous when tiled.
  lab_0: [
    "ssssssssssssssss",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttTtttttt",
    "sttttttttttttttt",
    "stttTttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttstt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "stttttTttttttttt",
    "sttttttttttttttt",
    "stttttttttttTttt",
    "sttttttttttttttt",
    "sttstttttttttttt",
    "sttttttttttttttt",
  ],
  lab_1: [
    "ssssssssssssssss",
    "sttttttttttttttt",
    "stttttttttttTttt",
    "sttttttttttttttt",
    "sttttssttttttttt",
    "stttsstttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttssttt",
    "stttttttttsstttt",
    "sttttttttttttttt",
    "stTttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttTtttt",
    "sttttttttttttttt",
  ],
  // The "gravel" analogs: a floor vent grate and a hazard-striped patch,
  // clustering on the coarse grid exactly like the moon's scree.
  vent_0: [
    "ssssssssssssssss",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "stttOOOOOOOOtttt",
    "stttObbbbbbOtttt",
    "stttOvvvvvvOtttt",
    "stttObbbbbbOtttt",
    "stttOvvvvvvOtttt",
    "stttObbbbbbOtttt",
    "stttOvvvvvvOtttt",
    "stttObbbbbbOtttt",
    "stttOOOOOOOOtttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
  ],
  // The second grate variant: same inset, slats running the other way, so
  // patch clusters read as one field of server-room floor grating.
  vent_1: [
    "ssssssssssssssss",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "stttOOOOOOOOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttObvbvbvOtttt",
    "stttOOOOOOOOtttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
    "sttttttttttttttt",
  ],
  // ---- SpaceZ HQ obstacles --------------------------------------------------
  // One wall block: chained every 16 px by the engine's wall segments. A
  // recessed steel lab panel — a light top/left bevel (V) and a dark
  // bottom/right bevel (b) around a mid-steel field (v), with four flush corner
  // bolts (f). The O border keeps chained blocks reading as a clean panel grid;
  // the bevel gives each panel depth without the noise that would tire the eye
  // down a long corridor. Quiet by hierarchy — solid, not loud.
  wall: [
    "OOOOOOOOOOOOOOOO",
    "OVVVVVVVVVVVVVvO",
    "OVvvvvvvvvvvvvbO",
    "OVvfvvvvvvvvfvbO",
    "OVvvvvvvvvvvvvbO",
    "OVvvvvvvvvvvvvbO",
    "OVvvvvvvvvvvvvbO",
    "OVvvvvvvvvvvvvbO",
    "OVvvvvvvvvvvvvbO",
    "OVvvvvvvvvvvvvbO",
    "OVvvvvvvvvvvvvbO",
    "OVvvvvvvvvvvvvbO",
    "OVvfvvvvvvvvfvbO",
    "OVvvvvvvvvvvvvbO",
    "OvbbbbbbbbbbbbbO",
    "OOOOOOOOOOOOOOOO",
  ],
  // A server rack, blinkenlights and all. Blocks outright.
  server: [
    "....OOOOOOOO....",
    "...ObbbbbbbbO...",
    "...ObvvvvvvbO...",
    "...ObcbbbbrbO...",
    "...ObvvvvvvbO...",
    "...ObbbbbbbbO...",
    "...ObvvvvvvbO...",
    "...ObrbbbbcbO...",
    "...ObvvvvvvbO...",
    "...ObbbbbbbbO...",
    "...ObvvvvvvbO...",
    "...ObcbbbbcbO...",
    "...ObvvvvvvbO...",
    "...ObbbbbbbbO...",
    "....OOOOOOOO....",
    "................",
  ],
  // The vending machine Ada never got to (she went out for chips and soda).
  // A tall red cabinet — the extra height reads as a real vending machine —
  // with a glass front of shelved products (gold chip bags o/q, red/blue soda
  // cans j/r on grey shelves V), a button + coin panel (V/y) down the right,
  // and a delivery tray (b) at the bottom. Blocks outright.
  vending: [
    "..OOOOOOOOOOOO..",
    "..OWOWOWWWWWWi..",
    "..OOOOOOOOOrri..",
    "..OOqoqoqxOVyi..",
    "..OOVVVVxVOrri..",
    "..OOjrjrjrOVyi..",
    "..OOVVVVVVOrri..",
    "..OOqoqoqoOVyi..",
    "..OOVVVVVVOrri..",
    "..OOjrjrjrOVyi..",
    "..OOVVVVVVOrri..",
    "..OObbbbbbObbi..",
    "..OOOOOOOOOrri..",
    "..Orrrrrrrrrri..",
    "..OrOvvvvvvOri..",
    "..OrObbbbbbOri..",
    "..OrOOOOOOOOri..",
    "..Orrrrrrrrrri..",
    "..Orrrrrrrrrri..",
    "..OiiiiiiiiiiO..",
  ],
  // An office desk, monitor still on: a glowing screen (x/c with a W glint) on
  // a stand, a keyboard, and a coffee mug someone left on the night shift, over
  // a desktop (T/s) with a drawer pedestal (v/b, seam + V handles) and a leg.
  // Low — hop it.
  desk: [
    "....OOOOOOO.........",
    "....OWxxxxO.........",
    "....OcccccO.........",
    "....OOOOOOO.......o.",
    ".......b...OvVvVvVW.",
    ".OOOOOOOOOOOOOOOOOO.",
    ".OTTTTTTTTTTTTTTTTO.",
    ".OssssssssssssssssO.",
    "..OOOVOOO......OOO..",
    "..ObbbbbO......ObO..",
    "..OvvVvvO......ObO..",
    "..OOOOOOO......OOO..",
  ],
  // A shipping crate of rocket parts. Low — hop it.
  crate: [
    "..............",
    ".OOOOOOOOOOOO.",
    ".OooooOOooooO.",
    ".OooooqqooooO.",
    ".OqqqqqqqqqqO.",
    ".OooooqqooooO.",
    ".OooooqqooooO.",
    ".OqqqqqqqqqqO.",
    ".OOOOOOOOOOOO.",
    "..............",
    "..............",
    "..............",
  ],
  // ---- SpaceZ HQ landmarks --------------------------------------------------
  // The lobby's glass double door — where the run begins.
  entrance: [
    "................................",
    "....OOOOOOOOOOOOOOOOOOOOOOOO....",
    "...OVVVVVVVVVVVVVVVVVVVVVVVVO...",
    "...OVrrrrVVVVVVVVVVVVrrrrrVVO...",
    "...OVVVVVVVVVVVVVVVVVVVVVVVVO...",
    "...OVOOOOOOOOOOOOOOOOOOOOOOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxOxxOOxxOxxxxxxOVO...",
    "...OVOxxxxxxOxxOOxxOxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVOxxxxxxxxxOOxxxxxxxxxOVO...",
    "...OVObbbbbbbbbOObbbbbbbbbOVO...",
    "...OVOOOOOOOOOOOOOOOOOOOOOOVO...",
    "...OVVVVVVVVVVVVVVVVVVVVVVVVO...",
    "....OOOOOOOOOOOOOOOOOOOOOOOO....",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  // The prototype rocket MUSKRAT nests under — the reason we're here.
  rocket: [
    "................................",
    "..............OOOO..............",
    ".............OrrrrO.............",
    "............OrrrrrrO............",
    "...........OrrrrrrrrO...........",
    "...........OaaaaaaaaO...........",
    "..........OaaaaaaaaaaO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaOOOOaaAO..........",
    "..........OaaOxxxxOaAO..........",
    "..........OaaOxxxxOaAO..........",
    "..........OaaaOOOOaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaOOOOaaAO..........",
    "..........OaaOxxxxOaAO..........",
    "..........OaaOxxxxOaAO..........",
    "..........OaaaOOOOaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    "..........OaaaaaaaaaAO..........",
    ".........OraaaaaaaaaArO.........",
    "........OrraaaaaaaaaArrO........",
    ".......OrrraaaaaaaaaArrrO.......",
    "......OrrrraaaaaaaaaArrrrO......",
    "......OrrraaaaaaaaaaArrrO.......",
    "......OrrOaaaaaaaaaaAOrrO.......",
    "......OOO.OAAAAAAAAAO.OOO.......",
    "...........ObbObbO..............",
    "..........ObbO.ObbO.............",
    ".........ObbO...ObbO............",
    "........OOOOO...OOOOO...........",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
  ],
  // ---- SpaceZ HQ decor (no collision) ---------------------------------------
  // Scattered printouts nobody will ever file again.
  papers: [
    "............",
    "..WWW..W....",
    "..WwW.WWW...",
    "..WWW.WwW...",
    "......WWW...",
    ".WW.........",
    ".WWw........",
    "............",
  ],
  // A cable run taped to the floor.
  cable: [
    "..............",
    ".bb...bbb.....",
    "..bb.bb.bb.bb.",
    "...bbb...bbb..",
    "..............",
  ],
  // Something green leaked out of the lab. It moves if you stare.
  stain: [
    "............",
    "....nn......",
    "...nnnn.nn..",
    "..nnnnnnnn..",
    "...nnnnnn...",
    ".nn..nnn....",
    ".nn...nn....",
    "............",
  ],
  // The obligatory office plant, thriving on neglect.
  plant: [
    "............",
    "...G.GG.G...",
    "...GGllGG...",
    "..GGlGGlGG..",
    "..GgGGGGgG..",
    "...GgGGgG...",
    "....OkkO....",
    "....OkkO....",
    "...OkkkkO...",
    "...OOOOOO...",
    "............",
    "............",
  ],
  // MUSKRAT — the boss: a mutant rat the size of a golf cart, nesting
  // under the prototype rocket with the drive ingredient in his belly.
  // 48x48, generated from ellipse primitives then tuned by hand.
  muskrat_0: [
    "................................................",
    "................................................",
    "................................................",
    "...........OOOOO.................OOOOO..........",
    "..........OBBBBBO...............OBBBBBO.........",
    ".........OBBBBBBBO.............OBBBBBBBO........",
    "........OBBBBBBBBBO...........OBBBBBBBBBO.......",
    ".......OBBBBBpBBBBBO.O.......OBBBBBpBBBBBO......",
    ".......OBBBpppppBBBOOSOOOOOO.OBBBpppppBBBO......",
    ".......OBBBpppppBSSSSSSSSSBBOOBBBpppppBBBO......",
    ".......OBBpppppSSSSSSSSSSSSSBBBBpppppppBBO......",
    ".......OBBBpppSSSSSSSBBBBBBBSBBBBpppppBBBO......",
    "........OBBppSSSSSSBBBBBBBBBBBBBBpppppBBO.......",
    ".........OBBBSSSOOBBBBBBBBBBBBOOBBBpBBBO........",
    "..........OBBSSSBBOOBBBBBBBBOOBBBBBBBBO.........",
    "...........OSSSSBRRRRBBBBBBBRRRRBBBOOO..........",
    "............OSSBBRRRRBBBBBBBRRRRBBBBO...........",
    "............OSSBBRRRRBBBBBBBRRRRBBBBO...........",
    "............OSSBBBBBBBBBBBBBBBBBBBBBO...........",
    "............OBSBBBBBBBSSSSSBBBBBBBBBO...........",
    "............OBBBBBBBSSSpppSSSBBBBBBBO...........",
    "............OSSBBBBSSSpppppSSSBBBBBO............",
    "...........OSSSSBBBSSSSpppSSSSBBBBBO............",
    "..........OSSSSSBBBSSSSSSSSSSSBBBBO.......OOO...",
    ".........OSSSSSSSBBSSSSSSSSSSSBBBBBO.....OpppO..",
    "........OSSSSSSBBBBBSSWWOWWSSBBBBBBBO....OpppO..",
    "........OSSSSSBBBBBBBBWWOWWBBBBBBBBBBO...OppppO.",
    "........OSSSSBBBBBBBBBWWOWWBBBBBBBBBBBO...OpppO.",
    ".......OSSSSBBBBBBBBBBWWOWWBBBBBBBBBBBBO..OppppO",
    "........OSSSBBBBBBBBBBBBBBBBBBBBnnnBBBBO...OpppO",
    "........OSSBBBBBBBBBBBBBBBBBBBBnnnnnBBBBO..OpppO",
    "........OSSBBnnnBBBBBBBBBBBBBBBBnnnBBBBBO..OpppO",
    "........OBSBnnnnnBBBBBBBBBBBBBBBBBBBBBBBO.OppppO",
    "........OBBBnnnnnBBBBBBBBBBBBBBBBBBBBBBBO.OpppO.",
    "........OBBBnnnnnBBBBBBBBBEBBBBBBBBBBBBBOOppppO.",
    "........OBBBBnnnBBBEEEEEEEEEEEEEEEBBBBBBOOpppO..",
    "........OBBBBBBBBEEEEEEEEEEEEEEEEEEEBBBBpppppO..",
    ".........OBBBBBEEEEEEEEEEEEnnnEEEEEEEEpppppOO...",
    ".........OBBBBEEEEEEEEEEEEEnnnEEEEEEEEpppppO....",
    "..........OBBBEEEEEEEEEEEEEnnnEEEEEEEEpppOO.....",
    "...........OBEEEEEEEEEEEEEEEEEEEEEEEEEEEO.......",
    "............OBBBBBEEEEEEEEEEEEEBBBBBEEEO........",
    "...........OBBBBBBBEEEEEEEEEEEBBBBBBBEEO........",
    "..........OBBBBBBBBBEEEEEEEEEBBBBBBBBBO.........",
    "...........OBBBBBBBEEEEEEEEEEEBBBBBBBO..........",
    "............OpBpBpOEEEEEEEEEEEEpBpBpO...........",
    ".............OOOOO.OOOOOOOEOOOOOOOOO............",
    "..........................O.....................",
  ],
  muskrat_1: [
    "................................................",
    "................................................",
    "................................................",
    "................................................",
    "...........OOOOO.................OOOOO..........",
    "..........OBBBBBO...............OBBBBBO.........",
    ".........OBBBBBBBO.............OBBBBBBBO........",
    "........OBBBBBBBBBO..O........OBBBBBBBBBO.......",
    ".......OBBBBBpBBBBBOOSOOOOOO.OBBBBBpBBBBBO......",
    ".......OBBBpppppBSSSSSSSSSBBOOBBBpppppBBBO......",
    ".......OBBBppppSSSSSSSSSSSSSBBBBBpppppBBBO......",
    ".......OBBppppSSSSSSSBBBBBBBSBBBpppppppBBO......",
    ".......OBBBppSSSSSSBBBBBBBBBBBBBBpppppBBBO......",
    "........OBBppSSSOOBBBBBBBBBBBBOOBBppppBBO.......",
    ".........OBBBSSSBBOOBBBBBBBBOOBBBBBpBBBO........",
    "..........OBSSSSBRRRRBBBBBBBRRRRBBBBBBO.........",
    "...........OOSSBBRRRRBBBBBBBRRRRBBBBOO..........",
    "............OSSBBRRRRBBBBBBBRRRRBBBBO...........",
    "............OSSBBBBBBBBBBBBBBBBBBBBBO...........",
    "............OBSBBBBBBBSSSSSBBBBBBBBBO.....OOO...",
    "............OBBBBBBBSSSpppSSSBBBBBBBO....OpppO..",
    "............OSSBBBBSSSpppppSSSBBBBBO.....OpppOO.",
    "...........OSSSSBBBSSSSpppSSSSBBBBBO.....OpppppO",
    "..........OSSSSSBBBSSSSSSSSSSSBBBBO.......OOpppO",
    ".........OSSSSSSSBBSSSSSSSSSSSBBBBBO.......OpppO",
    "........OSSSSSSBBBBBSSWWOWWSSBBBBBBBO.......Oppp",
    "........OSSSSSBBBBBBBBWWOWWBBBBBBBBBBO......Oppp",
    "........OSSSSBBBBBBBBBWWOWWBBBBBBBBBBBO.....Oppp",
    ".......OSSSSBBBBBBBBBBWWOWWBBBBBBBBBBBBO....Oppp",
    "........OSSSBBBBBBBBBBBBBBBBBBBBnnnBBBBO....Oppp",
    "........OSSBBBBBBBBBBBBBBBBBBBBnnnnnBBBBO...Oppp",
    "........OSSBBnnnBBBBBBBBBBBBBBBBnnnBBBBBO..OpppO",
    "........OBSBnnnnnBBBBBBBBBBBBBBBBBBBBBBBO.OOpppO",
    "........OBBBnnnnnBBBBBBBBBBBBBBBBBBBBBBBOOpppppO",
    "........OBBBnnnnnBBBBBBBBBEBBBBBBBBBBBBBOOpppOO.",
    "........OBBBBnnnBBBEEEEEEEEEEEEEEEBBBBBBpppppO..",
    "........OBBBBBBBBEEEEEEEEEEEEEEEEEEEBBBBpppOO...",
    ".........OBBBBBEEEEEEEEEEEEnnnEEEEEEEEpppppO....",
    ".........OBBBBEEEEEEEEEEEEEnnnEEEEEEEEpppOO.....",
    "..........OBBBEEEEEEEEEEEEEnnnEEEEEEEEpppO......",
    "...........OBEEEEEEEEEEEEEEEEEEEEEEEEEEEO.......",
    "............OBBBBBEEEEEEEEEEEEEBBBBBEEEO........",
    "...........OBBBBBBBEEEEEEEEEEEBBBBBBBEEO........",
    "..........OBBBBBBBBBEEEEEEEEEBBBBBBBBBO.........",
    "...........OBBBBBBBEEEEEEEEEEEBBBBBBBO..........",
    "............OpBpBpOEEEEEEEEEEEEpBpBpO...........",
    ".............OOOOO.OOOOOOOEOOOOOOOOO............",
    "..........................O.....................",
  ],
  // ---- Elites (unique story mobs) -------------------------------------------
  // 24x24 - a head taller and wider than the 16px crowd, so a unique reads
  // as an event the moment it rushes into frame. Frames alternate the leg
  // stride (staff) or the tail sway (ghosts), reused as the idle bob while
  // they hold their dialogue.
  // THE NIGHT MANAGER - dark suit, red tie, knows the launch schedule.
  night_manager_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OJJJWWWWJJJO......",
    ".....OJJJJWrrWJJJJO.....",
    "....OJJJJJWrrWJJJJJO....",
    "....OJJJJJWrrWJJJJJO....",
    "....OJpOJJWWWWJJOpJO....",
    ".....OJJJJJJJJJJJJO.....",
    ".....OJJJJJJJJJJJJO.....",
    "......OJJJJOOJJJJO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  night_manager_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOkkkkkkOO.......",
    ".......OkkkkkkkkO.......",
    ".......OkppppppkO.......",
    ".......OpOppppOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OJJJWWWWJJJO......",
    ".....OJJJJWrrWJJJJO.....",
    "....OJJJJJWrrWJJJJJO....",
    "....OJJJJJWrrWJJJJJO....",
    "....OJpOJJWWWWJJOpJO....",
    ".....OJJJJJJJJJJJJO.....",
    ".....OJJJJJJJJJJJJO.....",
    "......OJJJJOOJJJJO......",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // CHIEF OF SECURITY - navy uniform, cap, shades, gold badge.
  security_chief_0: [
    "........................",
    ".........OOOOOO.........",
    "........OJJJJJJO........",
    ".......OJJJJJJJJO.......",
    ".......OppppppppO.......",
    ".......OOOOOOOOOO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OJJJJJJJJJJO......",
    ".....OJJJJJjjJJJJJO.....",
    "....OJJJyJJjjJJJJJJO....",
    "....OJJJJJJjjJJJJJJO....",
    "....OJpOJJJjjJJJOpJO....",
    ".....OJJJJJJJJJJJJO.....",
    ".....OJJJJJJJJJJJJO.....",
    "......OJJJJOOJJJJO......",
    "......OJJJO..OJJJO......",
    "......OJJJO..OJJJO......",
    "......OJJJO..OJJJO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  security_chief_1: [
    "........................",
    ".........OOOOOO.........",
    "........OJJJJJJO........",
    ".......OJJJJJJJJO.......",
    ".......OppppppppO.......",
    ".......OOOOOOOOOO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OJJJJJJJJJJO......",
    ".....OJJJJJjjJJJJJO.....",
    "....OJJJyJJjjJJJJJJO....",
    "....OJJJJJJjjJJJJJJO....",
    "....OJpOJJJjjJJJOpJO....",
    ".....OJJJJJJJJJJJJO.....",
    ".....OJJJJJJJJJJJJO.....",
    "......OJJJJOOJJJJO......",
    ".....OJJJO....OJJJO.....",
    ".....OJJJO....OJJJO.....",
    ".....OJJJO....OJJJO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // DR. NOVA - wild gray hair, goggles, lab whites over blue.
  head_scientist_0: [
    "........................",
    ".......OwwOOwwO.........",
    "......OwwwwwwwwwO.......",
    "......OwwwwwwwwwwO......",
    ".......OppppppppO.......",
    ".......OpOccccOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OWWWjjjjWWWO......",
    ".....OWWWWjjjjWWWWO.....",
    "....OWWWWWjjjjWWWWWO....",
    "....OWwWWWjjjjWWWwWO....",
    "....OWpOWWjjjjWWOpWO....",
    ".....OWwWWWWWWWWwWO.....",
    ".....OWwWWWWWWWWwWO.....",
    "......OWWWWOOWWWWO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  head_scientist_1: [
    "........................",
    ".........OwwOOwwO.......",
    ".......OwwwwwwwwwO......",
    "......OwwwwwwwwwwO......",
    ".......OppppppppO.......",
    ".......OpOccccOpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OWWWjjjjWWWO......",
    ".....OWWWWjjjjWWWWO.....",
    "....OWWWWWjjjjWWWWWO....",
    "....OWwWWWjjjjWWWwWO....",
    "....OWpOWWjjjjWWOpWO....",
    ".....OWwWWWWWWWWwWO.....",
    ".....OWwWWWWWWWWwWO.....",
    "......OWWWWOOWWWWO......",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // THE JANITOR - gray coveralls, brown cap, thirty years of secrets. Now he
  // reads the part: an upright cotton mop (tan strings o/q on a wood handle k)
  // held in his right hand, clear of the cap, and a yellow wringer bucket (h/H)
  // parked at his left foot, tucked far enough left to clear the leg stride.
  // The manuscript has him treat the fight as armed ("NOW DROP THE WEAPON") —
  // the mop IS his weapon.
  janitor_0: [
    "..................qoq...",
    ".........OOOOOO..qoqoq..",
    "........OBBBBBBO.oqoqo..",
    ".......OBBBBBBBBO.oqo...",
    ".......OppppppppO.k.....",
    ".......OpOppppOpO.k.....",
    ".......OppppppppO.k.....",
    "........OpwwwwpO..k.....",
    "......OvvvvvvvvvvOk.....",
    ".....OvvvVvvvvVvvvk.....",
    "....OvvvvVvvvvVvvvkO....",
    "....OvvvvVvvvvVvvvkO....",
    "....OvpOvvvvvvvvOpkO....",
    ".....OvvvvvvvvvvvvO.....",
    ".....OvvvvvvvvvvvvO.....",
    "OVVVO.OvvvvOOvvvvO......",
    "OhhhO.OvvvO..OvvvO......",
    "OhhhO.OvvvO..OvvvO......",
    "OHHHO.OvvvO..OvvvO......",
    "OOOOO.OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  janitor_1: [
    "..................qoq...",
    ".........OOOOOO..qoqoq..",
    "........OBBBBBBO.oqoqo..",
    ".......OBBBBBBBBO.oqo...",
    ".......OppppppppO.k.....",
    ".......OpOppppOpO.k.....",
    ".......OppppppppO.k.....",
    "........OpwwwwpO..k.....",
    "......OvvvvvvvvvvOk.....",
    ".....OvvvVvvvvVvvvk.....",
    "....OvvvvVvvvvVvvvkO....",
    "....OvvvvVvvvvVvvvkO....",
    "....OvpOvvvvvvvvOpkO....",
    ".....OvvvvvvvvvvvvO.....",
    ".....OvvvvvvvvvvvvO.....",
    "OVVVO.OvvvvOOvvvvO......",
    "OhhhOOvvvO....OvvvO.....",
    "OhhhOOvvvO....OvvvO.....",
    "OHHHOOvvvO....OvvvO.....",
    "OOOOOOOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // THE ARCHITECT - the hero's old bench partner, half-converted. The cyborg
  // cues are dialled up to read at gameplay scale: a riveted steel skullcap
  // implant (O rivets, V metal highlights) over a still-human face, bright
  // glowing cyan OPTIC EYES (x), and a bold glowing chest REACTOR (c ring
  // around an x core) echoing the OPTIMUSK machines he worships, with cyan
  // seams (c) marking the dark tech tunic apart from the night shift's plain
  // suits. Same 24px elite footprint and stride as the staff.
  architect_0: [
    "........................",
    ".........OOOOOO.........",
    ".......OOOvvvvOOO.......",
    ".......OVVvvvvVVO.......",
    ".......OvppcpcpcO.......",
    ".......OpxxppxxpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OvcvWWWWvcvO......",
    ".....OvvvvWccWvvvvO.....",
    "....OvvvvvcxxcvvvvvO....",
    "....OvvvvvcxxcvvvvvO....",
    "....OvpOvvWccWvvOpvO....",
    ".....OvvcvvvvvvcvvO.....",
    ".....OvvvvvvvvvvvvO.....",
    "......OvvvvOOvvvvO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......ObbbO..ObbbO......",
    "......OOOOO..OOOOO......",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  architect_1: [
    "........................",
    ".........OOOOOO.........",
    ".......OOOvvvvOOO.......",
    ".......OVVvvvvVVO.......",
    ".......OvppcpcpcO.......",
    ".......OpxxppxxpO.......",
    ".......OppppppppO.......",
    "........OppppppO........",
    "......OvcvWWWWvcvO......",
    ".....OvvvvWccWvvvvO.....",
    "....OvvvvvcxxcvvvvvO....",
    "....OvvvvvcxxcvvvvvO....",
    "....OvpOvvWccWvvOpvO....",
    ".....OvvcvvvvvvcvvO.....",
    ".....OvvvvvvvvvvvvO.....",
    "......OvvvvOOvvvvO......",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....ObbbO....ObbbO.....",
    ".....OOOOO....OOOOO.....",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // ---- Locked door (16x16, chained like wall blocks) -------------------------
  // A sealed steel blast door — two leaves meeting at a center seam (b|V) with
  // a bold red MAGLOCK (dark housing O, red bars r, bright bar R) straddling the
  // seam. Same steel family as the wall so it belongs on the corridor, but the
  // split and the red lock read it plainly as a door, plainly shut. Corner
  // bolts (f) echo the wall panel.
  door_locked: [
    "OOOOOOOOOOOOOOOO",
    "OVVVVVVbVVVVVVVO",
    "OVvvvvvbVvvvvvbO",
    "OVvfvvvbVvvvfvbO",
    "OVvvvvvbVvvvvvbO",
    "OVvvvvvbVvvvvvbO",
    "OVvvvOOOOOOvvvbO",
    "OVvvvOrrrrOvvvbO",
    "OVvvvORRRROvvvbO",
    "OVvvvOrrrrOvvvbO",
    "OVvvvOOOOOOvvvbO",
    "OVvvvvvbVvvvvvbO",
    "OVvfvvvbVvvvfvbO",
    "OVvvvvvbVvvvvvbO",
    "ObbbbbbbVbbbbbbO",
    "OOOOOOOOOOOOOOOO",
  ],
};

export default {
  name: "spacez",
  /** Ground tile behind this family's contact sheet. */
  ground: "lab_0",
  palette: PALETTE,
  sprites: SPRITES,
  animations: {
    intern_walk: { frames: ["intern_0", "intern_1"], delayMs: 300 },
    scientist_walk: { frames: ["scientist_0", "scientist_1"], delayMs: 300 },
    engineer_walk: { frames: ["engineer_0", "engineer_1"], delayMs: 280 },
    guard_walk: { frames: ["guard_0", "guard_1"], delayMs: 220 },
    hazmat_walk: { frames: ["hazmat_0", "hazmat_1"], delayMs: 380 },
    optimusk_walk: { frames: ["optimusk_0", "optimusk_1"], delayMs: 300 },
    muskrat_loom: { frames: ["muskrat_0", "muskrat_1"], delayMs: 400 },
    night_manager_walk: {
      frames: ["night_manager_0", "night_manager_1"],
      delayMs: 300,
    },
    security_chief_walk: {
      frames: ["security_chief_0", "security_chief_1"],
      delayMs: 240,
    },
    head_scientist_walk: {
      frames: ["head_scientist_0", "head_scientist_1"],
      delayMs: 300,
    },
    janitor_walk: { frames: ["janitor_0", "janitor_1"], delayMs: 340 },
    architect_walk: { frames: ["architect_0", "architect_1"], delayMs: 300 },
  },
  /** Ground tiles and flat floor decor the contrast lint skips. */
  contrastExempt: ["lab_0", "lab_1", "vent_0", "vent_1", "cable", "stain"],
};
